/* AL9 tests (7 Oct 2026) — the panel that explains itself: the chain's arithmetic (the number, the pies now and fully invested, what is
   proportional, the cap), room to play (target less held, the breakout band, the next two buy and trim levels with sizes), the number
   through the day and its smoothing, the stored history against DS1's own replay, the live sum taken from the chart API the way the page
   takes it, and the page itself headless at 1680 and 390. Nothing here writes: the page test runs with non-GET requests blocked and counted. */
import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path";
import { openPage, ROOT } from "./_harness.mjs";
import * as C from "../study/al9/chain.mjs";
import { explain, makeReadAt, pieSvg, chainPies, chartSvg, RANGES, TITLE } from "../study/al9/panel.mjs";
import { view, fetchDaily, fetchLive, baseline, loadAssumptions, ds1Shape, nyParts, STORE } from "../study/ds1/live.mjs";
const J = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, f), "utf8")), LV = J("study/ds1/data/ds1-live.json"), D = J("study/ds1/data/ds1.json"), H = J("study/al9/data/history.json"), near = (a, b, tol) => Math.abs(a - b) <= tol, sum = (a) => a.reduce((x, y) => x + y, 0);
const API = "https://scintilla-massive-chart-api.fly.dev", getApi = async (p) => { const r = await fetch(API + p, { headers: { Origin: "https://scintillahub.ai" }, signal: AbortSignal.timeout(60000) }); if (!r.ok) throw new Error(p.split("?")[0] + " " + r.status); return r.json(); };
const A0 = () => baseline(LV), BANNED = /\bevenings?\b|\brungs?\b|\bv1\b|\bv2\b|line vs reading/i;

test("1 · the number is the held part plus the tactical part times the market reading: 70 at a reading of 0, 79 at 30, 100 at 100 — and it never leaves 0 to 100", () => {
  const A = A0(); assert.equal(C.numberAt(0, A), 70); assert.ok(near(C.numberAt(30, A), 79, 1e-9)); assert.equal(C.numberAt(100, A), 100); assert.equal(C.numberAt(250, A), 100); assert.equal(C.numberAt(-5, A), 70);
  assert.equal(C.numberAt(50, { ...A, heldPct: 90, tacticalPct: 30 }), 100, "a held part and a tactical part that pass 100 between them stop at 100"); assert.ok(near(C.numberAt(50, { ...A, heldPct: 40, tacticalPct: 20 }), 50, 1e-9)); });

test("2 · the chain adds up at every market reading: the slices are the number, cash is the rest, each pie's slices are 100% of it, and every slice is its held part plus its tactical part", () => {
  const A = A0(); for (let r = 0; r <= 100; r += 5) { const c = C.chainAt(r, A); assert.ok(near(sum(c.slices.map((s) => s.pct)), c.number, 1e-9), "slices at " + r); assert.ok(near(c.number + c.cash, 100, 1e-9)); assert.ok(near(c.conviction + c.core, c.number, 1e-9)); assert.ok(near(c.held + c.tactical, c.number, 1e-9));
    for (const k of ["conviction", "core"]) assert.ok(near(sum(c.slices.filter((s) => s.kind === k).map((s) => s.ofAbove)), 100, 1e-6), k + " at " + r); for (const s of c.slices) assert.ok(near(s.heldPart + s.tacticalPart, s.pct, 1e-9) && s.pct >= 0);
    assert.ok(near(sum(Object.values(c.names).map((n) => n.pct)), c.number, 1e-9)); assert.ok(near(c.convOfInvested + c.coreOfInvested, 100, 1e-9)); } });

test("3 · how Micron comes to its size: its conviction part plus its memory share of the core — today's dials, and Alan's own sum of 7 Oct (6.45% plus 10.75% at 43% invested)", () => {
  const c = C.chainAt(30, A0()), mu = c.names.MU, conv = mu.parts.find((p) => p.kind === "conviction"), core = mu.parts.find((p) => p.kind === "core");
  assert.ok(near(c.number, 79, 1e-9) && near(c.convOfInvested, 26.5, 1e-9)); assert.ok(near(conv.pct, 79 * 0.265 * 0.8, 1e-9) && near(conv.ofAbove, 80, 1e-9)); assert.ok(near(core.pct, (79 * 0.735 * 2) / 17, 1e-9)); assert.ok(near(mu.pct, conv.pct + core.pct, 1e-12) && near(mu.pct, 23.58, 0.01));
  /* the sum he said aloud: conviction 1 dollar in 4 and all Micron's, Micron's memory share a fifth of the core, 43% invested */
  const his = C.chainAt(0, { ...A0(), heldPct: 43, tacticalPct: 0, convLift: 0, micronOfConv: 100, capMicron: 0, coreWeights: { NVDA: 1, AVGO: 1, TSM: 1, ORCL: 1, MU: 1 } }), m = his.names.MU;
  assert.ok(near(m.parts.find((p) => p.kind === "conviction").pct, 10.75, 1e-9), "10.75%"); assert.ok(near(m.parts.find((p) => p.kind === "core").pct, 6.45, 1e-9), "6.45%"); assert.ok(near(m.ofInvested, 40, 1e-9), "and that is how Micron comes to 40% of what is invested"); });

test("4 · is it always directly proportional? with no lift and no cap, exactly; with the baseline dials every name keeps its share of its own pie while conviction's share of what is invested rises 25 → 26.5 → 30", () => {
  const A = A0(), flat = C.proportional({ ...A, convLift: 0, capMicron: 0 }, 30); assert.equal(flat.exact, true); for (const r of flat.rows) assert.ok(near(r.at0, r.at100, 1e-9) && near(r.at0, r.now, 1e-9));
  const P = C.proportional(A, 30); assert.equal(P.exact, false); assert.deepEqual(P.conv.map((x) => +x.toFixed(4)), [25, 26.5, 30]); assert.deepEqual(P.capBinds, [false, false, true]);
  const a = C.chainAt(0, A), b = C.chainAt(60, A); for (const s of a.slices) assert.ok(near(s.ofAbove, b.slices.find((x) => x.key === s.key).ofAbove, 1e-9), s.key + " keeps its share of its pie");
  assert.ok(C.convShareAt(100, A) > C.convShareAt(0, A), "conviction's share rises with the market reading"); assert.equal(C.convShareAt(0, A), 25, "from Alan's 1 in 4"); });

test("5 · fully invested is each name's ceiling: the pie is 100% with no cash, Micron stops at its cap of 30% and what it gives up goes to the other core names, and no ceiling is under today's target", () => {
  const A = A0(), full = C.ceilingsOf(A), now = C.chainAt(30, A); assert.equal(full.number, 100); assert.ok(near(full.cash, 0, 1e-9)); assert.ok(near(full.names.MU.pct, 30, 1e-9)); assert.equal(full.names.MU.capped, true); assert.ok(near(full.capped[0].wouldBe, 24 + (70 * 2) / 17, 1e-9));
  const free = C.chainAt(100, { ...A, capMicron: 0 }); assert.ok(near(free.names.MU.pct, 24 + (70 * 2) / 17, 1e-9)); assert.ok(near(full.names.NVDA.pct - free.names.NVDA.pct, (full.capped[0].givenUp * 3) / 15, 1e-9), "Nvidia takes its 3 parts in 15 of what Micron gives up");
  assert.ok(near(sum(Object.values(full.names).map((n) => n.pct)), 100, 1e-9)); for (const s of C.ROWS) assert.ok(full.names[s].pct >= now.names[s].pct - 1e-9, s + " ceiling at or above its target"); assert.ok(near(full.names.NBIS.pct, 6, 1e-9)); });

test("6 · room to play: target less held for each name and for the account; the breakout band is for conviction names only, shared as conviction is, never over a ceiling, and open only while the name is breaking out", () => {
  const A = A0(), now = C.chainAt(30, A), full = C.ceilingsOf(A), acct = { nlv: 500000, positions: { MU: { shares: 50, price: 1000 }, NBIS: { shares: 100, price: 250 }, VST: { shares: 10, price: 100 } } };
  const R = C.roomToPlay(now, full, acct, A, { NBIS: true }), row = (s) => R.rows.find((x) => x.sym === s); assert.deepEqual(R.rows.map((x) => x.sym), C.ROWS);
  assert.ok(near(row("MU").held, 10, 1e-9) && near(row("MU").room, now.names.MU.pct - 10, 1e-9) && near(row("MU").roomUsd, ((now.names.MU.pct - 10) / 100) * 500000, 1e-6)); assert.ok(near(R.held, 10 + 5 + 0.2, 1e-9), "a holding outside the chain still counts as held"); assert.deepEqual(R.other.map((o) => o.sym), ["VST"]); assert.ok(near(R.room, 79 - 15.2, 1e-9));
  assert.ok(near(row("MU").band, 4, 1e-9) && near(row("NBIS").band, 1, 1e-9) && near(row("MU").band + row("NBIS").band, A.bandPts, 1e-9)); for (const s of C.ROWS.slice(2)) assert.equal(row(s).band, 0, s + " is core: no band");
  assert.equal(row("MU").bandOpen, false); assert.ok(near(row("MU").allowed, row("MU").target, 1e-12)); assert.equal(row("NBIS").bandOpen, true); assert.ok(near(row("NBIS").allowed, row("NBIS").target + 1, 1e-9)); assert.ok(near(row("NBIS").inBand, 5 - row("NBIS").target, 1e-9) && row("NBIS").over === 0, "inside its band: nothing to trim yet"); assert.ok(near(R.allowed, 79 + 1, 1e-9));
  const shut = C.roomToPlay(now, full, acct, A, {}); assert.ok(near(shut.rows.find((x) => x.sym === "NBIS").over, 5 - now.names.NBIS.pct, 1e-9), "the breakout over, what was inside the band is over the target and is trimmed");
  const tight = C.roomToPlay(C.chainAt(100, A), full, acct, A, { MU: true }); assert.equal(tight.rows.find((x) => x.sym === "MU").band, 0, "at its ceiling there is no band left"); });

test("7 · breaking out is a price above the highest close of the past 60 sessions — the day itself is not counted in that high", () => {
  const c = Array.from({ length: 80 }, (_, i) => 100 + (i % 7)); c[79] = 106.5; assert.equal(C.highOf(c, 79, 60), 106); assert.equal(C.breakingOut(c, 79, 60), true); c[79] = 106; assert.equal(C.breakingOut(c, 79, 60), false); assert.equal(C.breakingOut(c, 30, 60), false, "under 60 sessions of history: not a breakout"); assert.equal(C.breakingOut(null, 5, 60), false); });

test("8 · the next two buy levels and the next two trim levels, with sizes: the nearest two each side, two levels a hair apart shown as one, half the room at the first buy and the rest at the second, a trim only for what is over the allowed size at that price", () => {
  const L = C.nextLevels(100, [{ id: "21-day average", level: 96 }, { id: "3D P1", level: 96.1 }, { id: "50-day average", level: 92 }, { id: "200-day average", level: 80 }, { id: "1W B2", level: 104 }, { id: "its 60-session high", level: 110 }, { id: "2W C1", level: 120 }, { id: "bad", level: 0 }]);
  assert.deepEqual(L.buys.map((x) => x.id), ["3D P1 / 21-day average", "50-day average"]); assert.deepEqual(L.trims.map((x) => x.level), [104, 110]); assert.ok(L.buys[0].awayPct < 0 && L.trims[0].awayPct > 0);
  const A = A0(), row = { target: 10, allowed: 10, shares: 100 }, O = C.sizeOrders(row, L, A, 500000);   /* the target is $50,000; 100 shares are worth $9,610 at the first level */
  assert.equal(O.buys[0].shares, Math.floor((0.5 * (50000 - 100 * 96.1)) / 96.1)); assert.equal(O.buys[1].shares, Math.floor((50000 - (100 + O.buys[0].shares) * 92) / 92)); assert.ok((100 + O.buys[0].shares + O.buys[1].shares) * 92 <= 50000, "the two buys never pass the target");
  assert.deepEqual(O.trims.map((t) => [t.shares, t.why]), [[0, "under target"], [0, "under target"]]);
  const over = C.sizeOrders({ target: 10, allowed: 10, shares: 520 }, L, A, 500000); assert.equal(over.trims[0].shares, Math.ceil((520 * 104 - 50000) / 104)); assert.ok((520 - over.trims[0].shares) * 104 <= 50000); const full = C.sizeOrders({ target: 10, allowed: 10, shares: 600 }, L, A, 500000); assert.equal(full.buys[0].shares, 0); assert.equal(full.buys[0].why, "at target"); assert.equal(over.buys[0].why, "under one share", "520 shares are $28 short of the target at the first level: less than one share");
  assert.deepEqual(C.sizeOrders({ target: 10, allowed: 10, shares: 0 }, L, A, 500000).trims.map((t) => t.why), ["none held", "none held"]); });

test("9 · the number through the day: one point at the open and one at the end of every five minutes, a symbol with no bar yet keeps its last price, the number shown is the average of the last hour with the live point in it, and after the close it is the session's last hour", () => {
  const t0 = Date.UTC(2026, 9, 7, 13, 30), clock = (ms) => ({ date: "2026-10-07", minutes: 570 + Math.round((ms - t0) / 60000) }), bar = (i, c) => ({ t: t0 + i * 300000, o: c - 0.5, c });
  const bars5 = { SPY: Array.from({ length: 24 }, (_, i) => bar(i, 100 - i * 0.1)), QQQ: Array.from({ length: 24 }, (_, i) => bar(i, 200 - i * 0.2)), HYG: [bar(0, 77), bar(6, 76.9)], IEF: [] }, seen = [];
  const readAt = (p) => { seen.push({ ...p }); return 100 - p.SPY; }, A = A0(), pts = C.dayPath(bars5, "2026-10-07", clock, readAt, A, { IEF: 88.5, HYG: 77.2 });
  assert.equal(pts.length, 25); assert.equal(pts[0].hm, "09:30"); assert.equal(pts[1].hm, "09:35"); assert.equal(pts[24].hm, "11:30"); assert.equal(seen[0].SPY, 99.5, "the open is the first bar's own open"); assert.equal(seen[0].HYG, 76.5); assert.equal(seen[0].IEF, 88.5, "no bar today: yesterday's close"); assert.equal(seen[3].HYG, 77, "between its bars a symbol keeps its last price"); assert.equal(seen[8].HYG, 76.9);
  assert.ok(near(pts[5].number, C.numberAt(pts[5].reading, A), 1e-12)); const M = C.dayMarks(pts); assert.equal(M.open.hm, "09:30"); assert.equal(M.low.hm, "11:30", "the market's low is the moment SPY and QQQ together were lowest"); assert.ok(M.low.offOpenPct < 0); assert.ok(M.hi.number >= M.lo.number);
  const nowMs = pts[24].t + 60000, live = { number: 90, reading: 66.7 }, S = C.smoothed(pts, live, A, nowMs), inWin = pts.filter((p) => p.t > nowMs - 3600000); assert.equal(S.points, inWin.length + 1); assert.ok(near(S.number, (sum(inWin.map((p) => p.number)) + 90) / (inWin.length + 1), 1e-9)); assert.equal(S.minutes, 60); assert.equal(S.sessionOver, false);
  const late = C.smoothed(pts, live, A, pts[24].t + 3 * 3600000); assert.equal(late.sessionOver, true); assert.equal(late.points, 12, "the session's own last hour, the stale live point left out"); assert.equal(C.smoothed([], live, A, nowMs).number, 90, "before the open the live point is the number");
  assert.deepEqual(C.dayPath({ SPY: [], QQQ: [], HYG: [], IEF: [] }, "2026-10-07", clock, readAt, A), [], "no bars, no path — the panel still draws"); assert.equal(A.smoothMin, 60); assert.equal("lineEvenings" in A, false, "nothing is averaged over days"); });

test("10 · the stored history is DS1's own replay: every session from 2 Jan 2018, in order, each reading 0 to 100; it ends on DS1's stored close and equals DS1's last year day for day; the six days Alan named are there, each a low or a high by SPY's own closes", () => {
  assert.equal(H.from, "2018-01-02"); assert.equal(H.d.length, H.r.length); assert.equal(H.d.length, H.s.length); assert.ok(H.d.length > 2190); for (let i = 1; i < H.d.length; i++) assert.ok(H.d[i] > H.d[i - 1]); assert.ok(H.r.every((x) => x >= 0 && x <= 100) && H.s.every((x) => x > 100));
  assert.equal(H.to, D.tonight.date); assert.equal(H.r.at(-1), D.tonight.reading); assert.deepEqual(H.votes, D.kept); const at = Object.fromEntries(H.d.map((d, i) => [d, H.r[i]])); let n = 0; for (const [d, r] of D.series) { if (r == null) continue; assert.equal(at[d], r, "the same reading on " + d); n++; } assert.ok(n >= 250);
  for (const e of [...D.extremes.bottoms, ...D.extremes.tops]) if (e.date >= H.from && e.reading != null) assert.equal(at[e.date], e.reading, "DS1's reading at " + e.date);
  assert.deepEqual(H.marks.map((m) => [m.d, m.kind]), C.NAMED.map((m) => [m.d, m.kind])); assert.deepEqual(H.marks.map((m) => m.d), ["2025-04-08", "2026-03-30", "2026-07-29", "2026-08-13", "2026-09-16", "2026-10-06"]); for (const m of H.marks) { assert.equal(m.sessionsFromExtreme, 0, m.d + " is itself the lowest or highest SPY close of the 21 sessions around it"); assert.equal(m.reading, at[m.d]); }
  const hist = C.dailyHistory(H, { dates: [H.to, "2026-10-07"], reading: [50, 30], spy: [1, 777] }, A0()); assert.equal(hist.d.length, H.d.length + 1, "a day the file already has is not taken twice"); assert.equal(hist.d.at(-1), "2026-10-07"); assert.ok(near(hist.n.at(-1), 79, 1e-9)); assert.ok(near(hist.n[H.d.indexOf("2025-04-08")], 100, 1e-9), "at the April 2025 low the number would have been 100%"); });

test("11 · the pies are labelled on the drawing: every slice carries its name, its share of the whole account and its share of that pie; the big slice is turned to the bottom and holds its own label; no text is under 11px", () => {
  const ch = C.chainAt(30, A0()), pies = chainPies(ch); assert.deepEqual(pies.map((p) => p.id), ["account", "invested", "who", "conviction", "core"]);
  for (const p of pies) { const texts = [...p.svg.matchAll(/<text[^>]*font-size="([\d.]+)"[^>]*>([^<]*)<\/text>/g)].map((m) => ({ size: +m[1], t: m[2] })); assert.ok(texts.every((x) => x.size >= 11), p.id + " text size"); for (const s of p.slices) { assert.ok(texts.some((x) => x.t === s.name), p.id + ": " + s.name + " is on the drawing"); assert.ok(texts.some((x) => x.t === s.acct.toFixed(1) + "%"), p.id + ": " + s.name + "'s share of the account"); if (p.id !== "account") assert.ok(texts.some((x) => x.t === s.of), p.id + ": " + s.name + "'s share of the pie"); } assert.ok((p.svg.match(/<path d="M[\d. ]+L[\d. ]+A/g) || []).length + (p.svg.match(/<circle/g) || []).length >= p.slices.length); }
  assert.equal(pies[4].slices.length, 7); assert.ok(pies[4].slices.some((s) => s.name === "Micron memory")); assert.ok(pies[3].slices.map((s) => s.name).join() === "Micron,Nebius");
  const one = pieSvg([{ kind: "invested", name: "invested", acct: 100, frac: 100 }, { kind: "cash", name: "cash", acct: 0, frac: 0 }]); assert.ok(/<circle/.test(one) && !/cash/.test(one.replace(/aria-label="[^"]*"/, "")), "fully invested: one whole disc, and no label for a slice that is not there"); });

test("12 · the history chart: SPY above and the number below on one time axis, today every five minutes beside them, the named days marked — and each range starts where it says", () => {
  const A = A0(), hist = C.dailyHistory(H, null, A), named = H.marks.map((m) => { const i = hist.d.indexOf(m.d); return { d: m.d, kind: m.kind, i, reading: hist.r[i], number: hist.n[i], spy: hist.s[i] }; }), path0 = Array.from({ length: 40 }, (_, i) => ({ t: i, minutes: 570 + i * 5, hm: "", reading: 30, number: 79, spy: 777 + i * 0.01, qqq: 757 }));
  for (const [key] of RANGES) { const c = chartSvg({ W: 1060, hist, named, path: path0, range: key, A, live: { number: 79, reading: 30 }, narrow: false }); assert.ok(c.svg.includes(">SPY<") && c.svg.includes("THE NUMBER") && c.svg.includes(">TODAY<") && c.svg.includes("EVERY 5 MINUTES")); assert.equal(c.geo.n, hist.d.length);
    const first = hist.d[c.geo.a]; if (key === "all") assert.equal(first, "2018-01-02"); if (key === "low25") assert.ok(first >= "2025-03-03" && first <= "2025-03-07"); if (key === "3m") assert.equal(c.geo.m, 64);
    const marks = [...c.svg.matchAll(/data-mark="([\d-]+)" data-kind="(low|high)" data-number="([\d.]+)" data-labelled="(\d)"/g)]; assert.equal(marks.length, named.filter((k) => k.i >= c.geo.a).length); if (key === "low25") { assert.equal(marks.length, 6); assert.ok(marks.every((m) => m[4] === "1"), "on the default view every named day carries its date"); }
    assert.ok([...c.svg.matchAll(/font-size="([\d.]+)"/g)].every((m) => +m[1] >= 11)); }
  const noDay = chartSvg({ W: 300, hist, named, path: [], range: "3m", A, live: { number: 79, reading: 30 }, narrow: true }); assert.equal(noDay.geo.todayW, 0); assert.ok(!noDay.svg.includes(">TODAY<"), "before the open there is no strip for today, and the days still draw"); });

test("13 · the assumptions: every dial of the chain has its baseline, a saved value overrides it, a set saved under DS1's old key is not read, and DS1's own pie still adds to the same number", () => {
  const B = A0(); for (const [k, v] of Object.entries(C.DIALS)) assert.equal(B[k], v, k); for (const k of ["corePct", "micronPct", "nebiusPct", "lineEvenings"]) assert.equal(k in B, false, k + " is no longer a dial"); assert.equal(STORE, "al9.assumptions");
  const mem = new Map([[STORE, JSON.stringify({ heldPct: 60, convLift: 0 })], ["ds1.assumptions.v1", JSON.stringify({ tacticalPct: 5 })]]), store = { getItem: (k) => mem.get(k) ?? null, setItem: (k, v) => mem.set(k, v) }, A = loadAssumptions(LV, store); assert.equal(A.heldPct, 60); assert.equal(A.convLift, 0); assert.equal(A.tacticalPct, 30); assert.equal(A.convShare, 25);
  const S = ds1Shape(B); assert.ok(near(S.corePct + S.micronPct + S.nebiusPct, B.heldPct, 1e-9)); assert.ok(near(S.micronPct / S.nebiusPct, 4, 1e-9)); });

test("14 · the number taken from the chart API the way the page takes it: it is the held part plus tactical times the market reading, today's path is rebuilt from five-minute bars, the same sum at the live prices gives DS1's own live reading, and the days since the stored history join it", async () => {
  const A = A0(), candles = await fetchDaily(getApi), live = await fetchLive(getApi), st = { base: LV, A, history: H, bars5: live.bars5, view: view({ base: LV, candles, ...live, A }), now: nyParts(), ui: {} }, X = explain(st), v = st.view;
  assert.ok(near(X.live.number, C.numberAt(v.reading.reading, A), 1e-9)); assert.ok(X.sm.number >= 70 - 1e-9 && X.sm.number <= 100 + 1e-9); assert.ok(near(X.sm.number, C.numberAt(X.sm.reading, A), 0.05), "the average of the numbers is the number at the average reading (inside 0 to 100)"); assert.ok(near(X.today.number, X.sm.number, 0.05), "the pies are drawn at the number shown");
  const px = Object.fromEntries(C.VOTERS.map((s) => [s, v.S.bars[s].c[v.k]])), again = makeReadAt(v, LV)(px); assert.ok(near(again, v.reading.reading, 0.15), `the panel's own sum at the live prices ${again} against DS1's live reading ${v.reading.reading}`);
  assert.ok(live.bars5 && C.VOTERS.every((s) => Array.isArray(live.bars5[s])), "five-minute bars for the four symbols that are counted"); if (X.path.length) { assert.equal(X.path[0].hm, "09:30"); assert.ok(X.path.every((p) => p.number >= 70 - 1e-9 && p.number <= 100 + 1e-9 && p.minutes >= C.OPEN_MIN && p.minutes <= C.CLOSE_MIN)); assert.ok(X.marks.open && X.marks.low); for (let i = 1; i < X.path.length; i++) assert.ok(X.path[i].minutes > X.path[i - 1].minutes); }
  assert.ok(X.yest && X.yest.date < v.session || !v.live); assert.equal(X.hist.d.at(-1), v.tail.dates.at(-1)); assert.ok(X.hist.d.length >= H.d.length); assert.equal(X.named.length, 6);
  /* where the stored history and the page's own last year overlap, the two replays agree (different sources for HYG's payouts and the bars: a point or two) */
  const at = Object.fromEntries(H.d.map((d, i) => [d, H.r[i]])); let worst = 0, n = 0; v.tail.dates.forEach((d, i) => { if (at[d] != null && (i < v.tail.dates.length - 1 || !v.live)) { worst = Math.max(worst, Math.abs(at[d] - v.tail.reading[i])); n++; } }); assert.ok(n > 200); assert.ok(worst <= 6, "the stored history and the page's own replay of the same days differ by at most " + worst.toFixed(1) + " points of market reading");
  assert.equal(X.isToday, v.session === st.now.date); if (X.isToday) assert.equal(X.dayWord, "today"); const off = explain({ ...st, now: { ...st.now, date: "2099-01-01" } }); assert.equal(off.isToday, false); assert.match(off.dayWord, /^\d+ [A-Z][a-z]{2}$/, "on another day the session is named by its date, never called today");
  assert.deepEqual(X.room.rows.map((r) => r.sym), C.ROWS); assert.ok(near(X.room.room, X.today.number - X.room.held, 1e-9)); for (const s of C.ROWS) { const L = X.levels[s]; assert.ok(L && L.buys.length <= 2 && L.trims.length <= 2); for (const b of L.buys) assert.ok(b.level < L.price); for (const t of L.trims) assert.ok(t.level > L.price); }
  assert.equal(X.dips.length, 3); assert.ok(X.dips.every((d) => d.number >= X.live.number - 0.05), "a calm dip never lowers the number"); });

test("15 · the tool: the panel is the first thing on the page, live, at 1680 and 390 — the number, its day, its history, ten labelled pies, room to play — no error, no write, no sideways scroll, no text under 11px, none of the words Alan could not read; the chart's ranges, a day picked on it, a changed dial and a failed read each do what the page says", async () => {
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h }); try { const { page } = P;
    await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && document.getElementById("a9-root"), null, { timeout: 120000 }); await page.waitForFunction(() => window.DS1_LIVE.history, null, { timeout: 60000 }); await page.waitForTimeout(1200);
    const read = () => page.evaluate(() => { const root = document.getElementById("a9-root"), host = document.getElementById("ds1money-host"), st = window.DS1_LIVE, q = (s2) => [...host.querySelectorAll(s2)], leaves = q("*").filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg"));
      return { d: { ...root.dataset }, big: host.querySelector('[data-a9="number"]').textContent, kv: Object.fromEntries(q("[data-kv]").map((e) => [e.dataset.kv, e.textContent])), panel: { first: document.querySelector(".grid > .panel") === host.closest(".panel"), h2: host.closest(".panel").querySelector("h2").innerText, folded: host.closest(".panel").classList.contains("folded") }, error: st.error, panelError: st.panelError || null, reads: st.reads,
        rows: q(".a9-row").map((e) => ({ k: e.dataset.chain, number: +e.dataset.number, pies: [...e.querySelectorAll(".a9-pie")].map((x) => x.dataset.pie), label: e.querySelector(".a9-rl").innerText })), pieTexts: q(".a9-pie svg text").length, marks: q("#a9-chart [data-mark]").map((e) => [e.dataset.mark, e.dataset.kind, e.dataset.labelled]), range: root.dataset.range, ranges: q("[data-a9-range]").map((e) => e.dataset.a9Range), asOf: !!host.querySelector(".a9-asof"), room: q("[data-room]").map((e) => e.dataset.room), lv: q("[data-level]").length, say: host.querySelector('[data-a9="say"]').innerText, asm: { there: !!host.querySelector("details.asm"), open: (host.querySelector("details.asm") || {}).open, inputs: q("details.asm input[data-in]").map((e) => e.dataset.in) }, specs: q("details.sc-pagespecs").length, age: host.querySelector("[data-ds1-age]").textContent,
        note: [...document.querySelectorAll(".a9-note")].map((e) => ({ hidden: e.hidden, t: e.textContent, n: e.dataset.number })), text: host.innerText + "\n" + [...new Set(q("[data-l]").map((e) => e.dataset.l))].join("\n") /* on a narrow screen each cell of the table carries its own column's name */, step2: document.getElementById("ds1live").innerText, old: host.querySelectorAll("#ds1money, .pie, tr[data-slice]").length, scrollW: document.scrollingElement.scrollWidth, minFont: Math.min(...leaves.map((e) => parseFloat(getComputedStyle(e).fontSize))), svgFont: Math.min(...q("svg text").map((e) => parseFloat(e.getAttribute("font-size")))), svgWide: q("svg").filter((e) => e.getBoundingClientRect().right > innerWidth + 1).length }; });
    const r = await read(); assert.deepEqual(P.errors, []); assert.equal(r.error, null); assert.equal(r.panelError, null); assert.ok(r.panel.first && !r.panel.folded, "the panel is the first on the page, open as it loads"); assert.equal(r.panel.h2.replace(/\s*OPEN[\s\S]*$/, "").trim(), TITLE);
    const num = +r.d.number; assert.ok(num >= 70 && num <= 100); assert.equal(r.big, num.toFixed(0) + "%"); assert.ok(/^\d+\.\d%$/.test(r.kv.yest), "yesterday's close beside it: " + r.kv.yest); assert.ok(/^(\d+\.\d%|not open yet)$/.test(r.kv.open)); assert.ok(/^\d+\.\d%$/.test(r.kv.held) && /^\$[\d.]+K$/.test(r.kv.room));
    assert.deepEqual(r.rows.map((x) => x.k), ["now", "full"]); for (const row of r.rows) assert.deepEqual(row.pies, ["account", "invested", "who", "conviction", "core"]); assert.ok(Math.abs(r.rows[0].number - num) < 0.06, "the first row of pies is drawn at the number shown"); assert.equal(r.rows[1].number, 100); assert.match(r.rows[1].label, /FULLY INVESTED[\s\S]*each name's ceiling/); assert.ok(r.pieTexts >= 2 * (2 + 3 * 5 + 3 * 7 - 2), "every slice of both rows is labelled on the drawing: " + r.pieTexts);
    assert.equal(r.range, w >= 760 ? "low25" : "3m"); assert.deepEqual(r.ranges, ["3m", "low25", "all"]); if (w >= 760) { assert.deepEqual(r.marks.map((m) => m[0]), ["2025-04-08", "2026-03-30", "2026-07-29", "2026-08-13", "2026-09-16", "2026-10-06"]); assert.ok(r.marks.every((m) => m[2] === "1"), "all six named days carry their date"); } else assert.ok(r.marks.length >= 3);
    assert.deepEqual(r.room, [...Object.values({ a: "MU", b: "NBIS", c: "NVDA", d: "AVGO", e: "TSM", f: "ORCL", g: "AMZN", h: "GOOGL" }), "ALL"]); assert.ok(r.lv >= 20, "buy and trim levels on the table: " + r.lv); assert.ok(r.asm.there && r.asm.open === false, "DS1's assumptions panel is kept, one click away"); for (const k of ["heldPct", "tacticalPct", "convShare", "convLift", "micronOfConv", "capMicron", "bandPts", "smoothMin", "buyFirst", "cash", "shares.MU", "w.NVDA", "beta.MU"]) assert.ok(r.asm.inputs.includes(k), "a dial for " + k); assert.equal(r.specs, 1); assert.equal(r.old, 0, "DS1's own pie and slice table are not drawn as well");
    assert.match(r.text, /at today's market low|at the market low of \d+ [A-Z][a-z]{2}/, "the market's low, named for today or for the last session traded"); assert.match(r.text, /at yesterday's close|at the close before/);
    for (const s of ["THE NUMBER", "at the open", "room to play", "ITS HISTORY", "SINCE 2018", "1 · THE ACCOUNT", "2 · WHAT IS INVESTED", "3 · WHO GETS IT", "4 · INSIDE CONVICTION", "5 · INSIDE THE CORE", "FULLY INVESTED", "Micron sits in two pies", "Is it always directly proportional?", "What each dial moves", "ROOM TO PLAY", "NEXT BUY", "NEXT TRIM", "ASSUMPTIONS", "PAGE SPECS", "New York"]) assert.ok(r.text.includes(s), s);
    assert.ok(!BANNED.test(r.text), "the panel: " + (r.text.match(BANNED) || [])[0]); assert.ok(!BANNED.test(r.step2), "step 2: " + (r.step2.match(BANNED) || [])[0]); assert.ok(r.step2.includes("THE MARKET READING, LIVE") && r.step2.includes("any day"));
    assert.ok(r.scrollW <= w, "no sideways scroll: " + r.scrollW); assert.equal(r.svgWide, 0, "no drawing wider than the screen"); assert.ok(r.minFont >= 11, "no text under 11px: " + r.minFont); assert.ok(r.svgFont >= 11, "no drawn text under 11px: " + r.svgFont); assert.match(r.age, /^read \d\d:\d\d:\d\d New York · \d+ s old$/);
    assert.equal(r.note.length, 2); for (const n of r.note) if (!n.hidden) { assert.equal(n.n, num.toFixed(0)); assert.match(n.t, /The tool's answer to how much is the number at the top of the page: \d+% invested\./); assert.ok(!BANNED.test(n.t)); }
    /* the chart's ranges */
    await page.locator('#ds1money-host [data-a9-range="all"]').click(); await page.waitForTimeout(200); let c = await read(); assert.equal(c.range, "all"); assert.equal(c.marks.length, 6);
    await page.locator('#ds1money-host [data-a9-range="3m"]').click(); await page.waitForTimeout(200); c = await read(); assert.equal(c.range, "3m"); assert.ok(c.marks.length >= 3 && c.marks.length < 6);
    /* a day picked on the chart: the first row of pies shows that day, the second row and the room to play stay as they are; BACK TO NOW takes it back */
    const box = await page.locator("#a9-chart").boundingBox(); await page.mouse.move(box.x + 60, box.y + box.height / 2); await page.waitForTimeout(100); const words = await page.locator("#a9-read").innerText(); assert.match(words, /\d{4} · SPY [\d,.]+ · market reading \d+ · the number \d+\.\d%/);
    await page.mouse.click(box.x + 60, box.y + box.height / 2); await page.waitForTimeout(250); c = await read(); assert.equal(c.asOf, true); assert.match(c.text, /the number would have been \d+\.\d%/); assert.ok(!/^NOW/.test(c.rows[0].label)); assert.equal(c.rows[1].number, 100); assert.equal(c.d.number, r.d.number, "the number itself is still today's");
    await page.locator("#ds1money-host [data-a9-now]").click(); await page.waitForTimeout(250); c = await read(); assert.equal(c.asOf, false); assert.match(c.rows[0].label, /^NOW/);
    /* a dial: the held part 70 → 60 takes ten points off the number, and the opened fold stays open through the redraw; the baseline button takes it back */
    await page.locator("#ds1money-host details.asm > summary").click(); await page.waitForTimeout(150); const held = page.locator('#ds1money-host input[data-in="heldPct"]'); await held.fill("60"); await held.dispatchEvent("change"); await page.waitForTimeout(300); c = await read(); assert.ok(Math.abs(+c.d.number - (num - 10)) < 0.2, `held 70 → 60 took the number from ${num} to ${c.d.number}`); assert.equal(c.asm.open, true);
    await page.locator("#ds1money-host button[data-reset]").click(); await page.waitForTimeout(300); c = await read(); assert.ok(Math.abs(+c.d.number - num) < 0.2);
    /* the liveness rule: a read that fails leaves the panel as it was, with the cause; the age keeps ticking */
    await page.route("**/quotes*", (rt) => rt.abort()); await page.evaluate(() => window.DS1_LIVE.readNow()); await page.waitForTimeout(700); const f = await read(); assert.ok(f.error); assert.equal(f.reads, r.reads); assert.ok(Math.abs(+f.d.number - num) < 0.2, "the last number is still on screen"); assert.match(f.text, /last try failed/); assert.equal(f.rows.length, 2);
    await page.waitForTimeout(2100); assert.notEqual((await read()).age, f.age, "the age ticks while nothing new arrives"); await page.unroute("**/quotes*"); await page.evaluate(() => window.DS1_LIVE.readNow()); await page.waitForTimeout(600); const back = await read(); assert.equal(back.error, null); assert.equal(back.reads, r.reads + 1);
    assert.equal(P.nonGet.blocked + P.nonGet.allowed, 0, "no write of any kind");
  } finally { await P.close(); } } });

test("16 · index.html: the panel is wired in once, into the host DS1's module hands over; the note under THE BRIEF and step 2 is there; the words Alan could not read are not in what the page can show; no key is in any file of this study", () => {
  const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8"), code = html.replace(/<!--[\s\S]*?-->/g, "").replace(/\/\*[\s\S]*?\*\//g, "");
  assert.equal((code.match(/import \{ panel as a9Panel \} from "\.\/study\/al9\/panel\.mjs";/g) || []).length, 1); assert.match(code, /moneyPanel: a9Panel/); assert.equal((code.match(/startDeploymentSystem\(/g) || []).length, 1); assert.equal((code.match(/id="ds1money-host"/g) || []).length, 1); assert.equal((code.match(/id="a9-note-brief"/g) || []).length, 1); assert.equal((code.match(/id="a9-note-step2"/g) || []).length, 1);
  assert.ok(code.includes("<h2>" + TITLE + "</h2>"), "the panel's own title is in the page before any script runs"); assert.ok(code.indexOf('id="ds1money-host"') < code.indexOf('id="brief"'));
  /* what is left of those words is code, not text: class names, variables, the provider's URLs, storage keys, and the five-market bars' code that nothing draws any more */
  const seen = []; for (const l of code.split("\n")) { const l2 = l.includes("http") ? l : l.replace(/\/\/.*$/, ""); for (const m of l2.matchAll(/evening|\brungs?\b|\bv1\b|\bv2\b/gi)) { const ctx = l2.slice(Math.max(0, m.index - 46), m.index + m[0].length + 40); if (!/a7-rungs|a8-v2|\/v1|-v1'|engine-v2|const rungs|\$\{rungs\}|'\+rungs\+|rung:|rung=|rung,|L\.rung\?|\bv2=|\(v2&&|:v2\?|engine v2|three evenings|three-evening/.test(ctx)) seen.push(ctx.trim()); } } assert.deepEqual(seen, []);
  for (const f of ["study/al9/chain.mjs", "study/al9/panel.mjs", "study/al9/data/history.json", "scripts/al9-history.mjs", "scripts/al9-live-check.mjs", "scripts/al9-shots.mjs", "study/ds1/live.mjs"]) { const t = fs.readFileSync(path.join(ROOT, f), "utf8"); assert.ok(!/apikey=[A-Za-z0-9]{10,}/.test(t) && !/eyJ[A-Za-z0-9_-]{20,}\./.test(t) && !/Bearer\s+[A-Za-z0-9._-]{20,}/.test(t), "no key in " + f); assert.ok(!/\bfetch\([^)]*method:\s*["'](POST|PUT|PATCH|DELETE)/.test(t), "no write in " + f); }
  const pics = fs.readdirSync(path.join(ROOT, "study/al9/pictures")).filter((f) => /\.png$/.test(f)); assert.ok(pics.some((f) => /-1680\.png$/.test(f)) && pics.some((f) => /-390\.png$/.test(f)), "pictures at 1680 and at 390"); });

test("17 · the page written for Alan renders headless at 1680 and 390: its pictures load, no error, no write, no sideways scroll, no text under 11px, at most three decisions, none of the words he could not read — and its figures are the tool's own arithmetic", async () => {
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h, path: "study/al9/AL9.html" }); try {
    await P.page.waitForFunction(() => window.AL9_PAGE_READY === true && [...document.querySelectorAll("img")].every((i) => i.complete), null, { timeout: 60000 });
    const r = await P.page.evaluate(() => { const els = [...document.querySelectorAll("body *")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0), q = (s2) => document.querySelectorAll(s2).length;
      return { scrollW: document.scrollingElement.scrollWidth, minFont: Math.min(...els.map((e) => parseFloat(getComputedStyle(e).fontSize))), imgs: [...document.querySelectorAll("img")].map((i) => i.naturalWidth > 0), dec: q("#dec li"), wrong: q("#wrong li"), not: q("#notdone li"), named: [...document.querySelectorAll("#named tr")].slice(1).map((t) => [...t.children].map((c) => c.textContent)), specs: q("details.sc-pagespecs"), text: document.body.innerText }; });
    assert.deepEqual(P.errors, []); assert.equal(P.nonGet.blocked + P.nonGet.allowed, 0); assert.ok(r.scrollW <= w, "no sideways scroll: " + r.scrollW); assert.ok(r.minFont >= 11, "no text under 11px: " + r.minFont); assert.ok(r.imgs.length >= 8 && r.imgs.every(Boolean), "every picture loads"); assert.ok(r.dec >= 1 && r.dec <= 3, "at most three decisions"); assert.ok(r.wrong >= 5 && r.not >= 3); assert.equal(r.specs, 1); assert.ok(!BANNED.test(r.text), (r.text.match(BANNED) || [])[0]);
    /* the six days on the page are the stored history's, through the baseline dials */
    const A = A0(), MON = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"], at = Object.fromEntries(H.d.map((d, i) => [d, [H.r[i], H.s[i]]])); assert.equal(r.named.length, 6);
    H.marks.forEach((m, i) => { const row = r.named[i]; assert.equal(row[0], +m.d.slice(8) + " " + MON[+m.d.slice(5, 7) - 1] + " " + m.d.slice(0, 4)); assert.equal(row[1], "a " + m.kind); assert.equal(row[2], at[m.d][1].toFixed(2)); assert.equal(row[3], C.numberAt(at[m.d][0], A).toFixed(0) + "%"); });
    const c = C.chainAt(30, A), f = C.ceilingsOf(A); assert.ok(r.text.includes("24.0 + 6.0") && near(f.names.MU.parts.find((p) => p.kind === "conviction").pct, 24, 1e-9) && near(f.names.MU.pct, 30, 1e-9)); assert.ok(near(c.convOfInvested, 26.5, 1e-9));
  } finally { await P.close(); } } });
