/* DB1 tests (9 Oct 2026) — the first screen: the rebalancing dashboard, live on the tool's own reading.
   What they hold: the dashboard's arithmetic (the review page's, to the dollar); the money words; what the browser remembers and what it
   never keeps; the executive summary from a recorded state; the switches of version 3 in the dials and in the rules; the first screen's code
   carries no account word and no account figure, and everything the tool showed before sits inside THE LONG VERSION, closed; version 3 with
   both switches off is version 2 on live prices; the engine's check loads the rule files the page loads; and one headless page at a time at
   1680 and 390: the number on the first screen is the live reading through the dials, it moves with a chip, the balance and the size, Reset
   restores $500K and 25, nothing on the first screen is under 11px or reads the account, and the long version holds every old panel. */
import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
import { SIZE, START, STORE, money, pc, okSize, loadState, saveState, modelAt, numberOf, summaryLines, pies, dashboardHtml } from "../study/db1/dashboard.mjs";
import { view, fetchDaily, fetchLive, baseline, v2Rules, MOVES } from "../study/ds1/live.mjs"; import { DIALS, numberAt } from "../study/al9/chain.mjs"; import * as V3 from "../study/ds3/number.mjs";
import { openPage } from "./_harness.mjs"; import * as V2 from "../study/ds2/number.mjs";
const N_V2 = (vv) => V2.readingV2({ base: vv.v2.typical, rsiPoints: vv.reading.parts.find((p) => p.key === "rsi").points, creditPoints: vv.v2.creditFitted, rsi: vv.inputs.rsi, cash: vv.v2.cash }, vv.v2.rules);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), T = (f) => fs.readFileSync(path.join(ROOT, f), "utf8"), J = (f) => JSON.parse(T(f)), near = (a, b, tol) => Math.abs(a - b) <= tol;
const API = "https://scintilla-massive-chart-api.fly.dev", getApi = async (p) => { const r = await fetch(API + p, { headers: { Origin: "https://scintillahub.ai" }, signal: AbortSignal.timeout(60000) }); if (!r.ok) throw new Error(p.split("?")[0] + " " + r.status); return r.json(); };
const memStore = () => { const m = new Map(); return { getItem: (k) => (m.has(k) ? m.get(k) : null), setItem: (k, v) => m.set(k, String(v)), m }; };

test("1 · the arithmetic is the review page's: invested = number × size, cash the rest, conviction = balance × invested, core the rest; fully invested splits the size", () => {
  const M = modelAt({ number: 78.4, size: 500e3, bal: 25 }); assert.equal(M.invested, 392000); assert.equal(M.cash, 108000); assert.equal(M.conv, 98000); assert.equal(M.core, 294000); assert.equal(M.convFull, 125000); assert.equal(M.coreFull, 375000); assert.ok(near(M.convPct, 19.6, 1e-9) && near(M.corePct, 58.8, 1e-9) && near(M.cashPct, 21.6, 1e-9));
  const Z = modelAt({ number: 100, size: 1.5e6, bal: 0 }); assert.equal(Z.cash, 0); assert.equal(Z.conv, 0); assert.equal(Z.core, 1.5e6); const H = modelAt({ number: 120, size: 300e3, bal: 150 }); assert.equal(H.number, 100); assert.equal(H.bal, 100, "held to the ends");
  assert.equal(numberOf(28, DIALS), 78.4, "70% always in + 30% × 28 = 78.4"); assert.equal(numberOf(0, DIALS), 70); assert.equal(numberOf(100, DIALS), 100); assert.equal(numberOf(null, DIALS), null); });

test("2 · the money words and the size steps: $50K steps from $300K to $1.5M, $500K to start", () => {
  assert.equal(money(500e3), "$500K"); assert.equal(money(1.5e6), "$1.5M"); assert.equal(money(1.05e6), "$1.05M"); assert.equal(money(392000), "$392K"); assert.equal(money(94375), "$94.4K"); assert.equal(money(0), "$0"); assert.equal(money(null), "—"); assert.equal(pc(78.4), "78.4%");
  assert.deepEqual(SIZE, { min: 300e3, max: 1.5e6, step: 50e3, def: 500e3 }); assert.deepEqual(START, { size: 500e3, bal: 25 }); assert.ok(okSize(300e3) && okSize(1.5e6) && okSize(550e3)); assert.ok(!okSize(275e3) && !okSize(1.55e6) && !okSize(510e3) && !okSize("500000")); });

test("3 · what the browser remembers: the size, the balance and the last number — never an account; a broken or out-of-range value falls back to the start", () => {
  const s = memStore(); assert.deepEqual(loadState(s), { ...START, last: null }); saveState({ size: 650e3, bal: 40, last: { number: 75.5, reading: 18.3, readAt: "10:10 New York", date: "2026-10-09" }, cash: 1e6, shares: { MU: 5 } }, s);
  const kept = JSON.parse(s.getItem(STORE)); assert.deepEqual(Object.keys(kept).sort(), ["bal", "last", "size"], "nothing but the three"); const L = loadState(s); assert.equal(L.size, 650e3); assert.equal(L.bal, 40); assert.equal(L.last.number, 75.5);
  s.setItem(STORE, JSON.stringify({ size: 123456, bal: 140 })); assert.deepEqual(loadState(s), { ...START, last: null }); s.setItem(STORE, "{not json"); assert.deepEqual(loadState(s), { ...START, last: null }); });

/* a recorded live state, small: what summaryLines and dashboardHtml read */
const REC = { now: { date: "2026-10-09", weekday: "Fri", minutes: 610, hms: "10:10:16", ms: Date.now() }, readAt: { date: "2026-10-09", hms: "10:10:16", ms: Date.now() - 12000 }, error: null, A: { ...DIALS },
  view: { session: "2026-10-09", live: true, lastBar: "2026-10-08", missing: [], reading: { reading: 18.3, lightsCounted: 0, parts: [{ key: "rsi", value: 58.75, points: 2.5, missing: false }, { key: "creditOwn", value: -0.11, points: -14.5, fitted: -14.5, missing: false }], v1: { reading: 37 } },
    v2: { cash: true, since: "2026-08-13", fade: 1, beforeCash: 36.6 }, v3: { on: { vix: true, fear: true }, rules: { lo: 20, hi: 23, addLo: 10, addHi: 20, touch: 0.5 }, vixAdd: 0, vixClose: 15.09, vixHigh: 15.34, raisedByTheRally: false },
    facts: { vix: { price: 15.09, high: 15.34 }, credit: { own: -0.11 } }, moves: [8, 5, 3, 1.5, 0, -1.5, -3, -5].map((x) => ({ movePct: -x, reading: x === 0 ? 18.3 : x === 3 ? 25.8 : x === 5 ? 88.2 : x === 8 ? 100 : x === 1.5 ? 16.9 : x === -1.5 ? 18.6 : x === -3 ? 7.3 : 0, readingCalm: 18.3, spy: 600, qqq: 500, vix: 15 })) } };
test("4 · the executive summary: the formula line, one line per counted part in plain words with its points, the VIX by Alan's rule, the halving while cash is raised", () => {
  const L = summaryLines(REC.view, REC.A).map((l) => l.text); assert.equal(L.length, 5);
  assert.equal(L[0], "70% always in + 30% × the market reading (18 of 100) = 75.5%"); assert.equal(L[1], "SPY and QQQ's RSI 59: middling, +3"); assert.equal(L[2], "credit −0.1% over ten sessions, −15"); assert.equal(L[3], "the VIX at 15.1: under your 20, adds nothing"); assert.equal(L[4], "cash freed since 13 Aug near the highs: the swing is halved (37 → 18)");
  const hot = { ...REC.view, v3: { ...REC.view.v3, vixAdd: 10, vixClose: 21.3, vixHigh: 22 }, facts: { vix: { price: 21.3, high: 22 }, credit: { own: -0.11 } } }; assert.equal(summaryLines(hot, REC.A)[3].text, "the VIX at 21.3: over your 20, +10");
  const both = { ...hot, v3: { ...hot.v3, vixAdd: 20, vixClose: 24, vixHigh: 25 }, facts: { vix: { price: 24, high: 25 }, credit: { own: -0.11 } } }; assert.equal(summaryLines(both, REC.A)[3].text, "the VIX at 24.0: over your 23, both hands, +20");
  const touch = { ...hot, v3: { ...hot.v3, vixAdd: 5, vixClose: 19.2, vixHigh: 20.6 }, facts: { vix: { price: 19.2, high: 20.6 }, credit: { own: -0.11 } } }; assert.equal(summaryLines(touch, REC.A)[3].text, "the VIX touched 20 today (20.6): +5");
  const rally = { ...REC.view, v3: { ...REC.view.v3, raisedByTheRally: true } }; assert.ok(summaryLines(rally, REC.A)[2].text.endsWith("treasuries rallied, so it is read on HYG alone"));
  const calm = { ...REC.view, v2: { ...REC.view.v2, cash: false } }; assert.equal(summaryLines(calm, REC.A).length, 4, "no halving line when cash is not raised");
  const off = { ...REC.view, v3: { ...REC.view.v3, on: { vix: false, fear: true } } }; assert.equal(summaryLines(off, REC.A)[3].text, "the VIX at 15.1: not counted (switched off)");
  const low = { ...REC.view, reading: { ...REC.view.reading, parts: [{ key: "rsi", value: 31, points: 14, missing: false }, REC.view.reading.parts[1]] } }; assert.equal(summaryLines(low, REC.A)[1].text, "SPY and QQQ's RSI 31: washed out, +14");
  for (const t of L) assert.ok(!/quantile|percentile|sigma|clamp|ctx|fade|v2|v3|lights/i.test(t), "plain words: " + t); });

test("5 · the pies: two cakes — the whole account (conviction · core · kept in cash) and fully invested (conviction · core), labels with % and $ at the size", () => {
  const P = pies(modelAt({ number: 78.4, size: 500e3, bal: 25 }), 104); assert.equal((P.big.match(/Z" fill="var\(--/g) || []).length, 3, "three slices"); assert.equal((P.full.match(/Z" fill="var\(--/g) || []).length, 2); assert.ok(P.big.includes("</path>") && P.big.includes("stroke-width=\"1\"") && (P.big.match(/<path d="M[^"]*" fill="none"/g) || []).length >= 1, "a leader line for a small slice");
  for (const s of ["conviction", "19.6%", "$98K", "core", "58.8%", "$294K", "kept in cash", "21.6%", "$108K"]) assert.ok(P.big.includes(">" + s + "<"), s); for (const s of ["25.0%", "$125K", "75.0%", "$375K"]) assert.ok(P.full.includes(">" + s + "<"), s);
  assert.ok(!/stroke-width="(1[6-9]|[2-9]\d)"/.test(P.big), "whole slices, not a ring"); assert.ok(P.big.includes('fill="var(--conv') && P.big.includes('fill="var(--core') && P.big.includes('fill="var(--cashc')); });

test("6 · the screen as HTML: before the first read it says so and keeps the frame; after it the number is the live reading through the dials, the age is on it, and no account word is anywhere on it", () => {
  const cold = dashboardHtml(null, { ...START, last: null }); assert.ok(cold.includes("reading live prices…") && cold.includes("$500K") && cold.includes('data-bal') && cold.includes('data-size="1"'));
  const remembered = dashboardHtml(null, { ...START, last: { number: 75.5, reading: 18.3, readAt: "10:10 New York", date: "2026-10-09" } }); assert.ok(remembered.includes('class="big old"') && remembered.includes("$377.5K") && remembered.includes("last read 10:10 New York"));
  const h = dashboardHtml(REC, { size: 500e3, bal: 25, last: null }, 0, 1400); assert.ok(h.includes('data-number="75.49"') && h.includes('data-version="3"') && h.includes('data-live="1"') && h.includes(">$377.5K<") && h.includes("data-ds1-age") && h.includes("12 s old"));
  assert.equal((h.match(/class="chip"/g) || []).length, 8); assert.ok(h.includes('data-move="-3"') && h.includes(">−3%<") && h.includes(">+5%<") && h.includes(">now<"));
  const at = dashboardHtml(REC, { size: 500e3, bal: 25, last: null }, -3, 1400); assert.ok(at.includes('data-move="-3"') && at.includes('data-number="77.74"') && at.includes("if SPY &amp; QQQ move −3%"), "a chip moves the number and the pies");
  const low = /you hold|\broom\b|\bfree\b|\bused\b|to buy|shares|IBKR|Interactive Brokers|NLV|held/i; assert.ok(!low.test(h.replace(/<[^>]+>/g, " ")), "no account word on the first screen: " + (h.replace(/<[^>]+>/g, " ").match(low) || [])[0]);
  assert.ok(!/\b(MU|NBIS|NVDA|AVGO|TSM|ORCL|AMZN|GOOGL|VST)\b/.test(h.replace(/<[^>]+>/g, " ")), "no ticker on the first screen"); assert.deepEqual(MOVES, [8, 5, 3, 1.5, 0, -1.5, -3, -5]); assert.ok(!cold.includes("data-version") && h.includes("data-version"), "the version is on the screen only once a reading is"); });

test("7 · the dials and the rules carry version 3's two switches, on by default; the rule file's thresholds are Alan's steps; the switches off leave version 2's rules", () => {
  assert.equal(DIALS.vixRule, 1); assert.equal(DIALS.fearRule, 1); assert.equal(DIALS.creditRule, 1); assert.equal(DIALS.cashRule, 1);
  const base = { v2: J("study/ds2/data/ds2-live.json"), v3: J("study/ds3/data/ds3-live.json") }; for (const k of Object.keys(base.v2.rules)) assert.equal(base.v3.rules[k], base.v2.rules[k], "version 3's file carries version 2's rule " + k);
  const R = v2Rules(base, baseline(base)); assert.deepEqual(V3.stepsOf(R), { lo: 20, hi: 23, addLo: 10, addHi: 20, touch: 0.5 }); assert.equal(R.vixRule, 1); assert.equal(R.fearRule, 1);
  const off = v2Rules(base, { ...baseline(base), vixRule: 0, fearRule: 0 }); assert.equal(off.vixRule, 0); assert.equal(off.fearRule, 0); const no3 = v2Rules({ v2: base.v2 }, baseline(base)); assert.equal(no3.vixRule, undefined, "without the file, version 2's rules alone"); });

test("8 · index.html: the first screen is the dashboard, mounted before the live module and told after every drawing; everything else sits inside one closed details called THE LONG VERSION; the engine's check loads the rule files the page loads", () => {
  const html = T("index.html"), code = html.replace(/<!--[\s\S]*?-->/g, ""), i = (s) => code.indexOf(s);
  assert.ok(i('<div id="db1-dashboard"></div>') > 0 && i('<div id="db1-dashboard"></div>') < i('<details id="longversion" class="longv"><summary>THE LONG VERSION — study</summary>'), "the dashboard comes first");
  assert.ok(i("<h1>") < i('id="db1-dashboard"'), "under the title"); assert.ok(!/<details id="longversion"[^>]*\sopen/.test(code), "closed by default");
  const lv = code.slice(i('<details id="longversion"'), i("</details><!-- /longversion (DB1) -->")); for (const id of ["ds1money-host", "ds1live", "dataspine", "secbar", "stamp", "loading", "trace"]) assert.ok(lv.includes(`id="${id}"`), id + " is inside the long version"); assert.ok(lv.includes('class="sc-pagespecs"'), "PAGE SPECS inside");
  assert.equal((code.match(/class="grid"/g) || []).length, 1); assert.ok(lv.includes('class="grid"')); assert.ok(!code.slice(0, i('<details id="longversion"')).includes("id=\"ds1money-host\""));
  assert.match(code, /import \{ mountDashboard \} from "\.\/study\/db1\/dashboard\.mjs";/); assert.match(code, /onDraw: \(st\) => db1\.update\(st\)/); assert.equal((code.match(/startDeploymentSystem\(/g) || []).length, 1); assert.ok(code.includes('lv.addEventListener("toggle"'), "the long version redraws when first opened");
  assert.ok(!/position:fixed; inset:0/.test(code.match(/#loading\{[^}]*\}/)[0]), "the loading overlay no longer covers the first screen");
  const chk = T("scripts/ds1-live-check.mjs"); assert.ok(chk.includes("study/ds2/data/ds2-live.json") && chk.includes("study/ds3/data/ds3-live.json")); const dash = T("study/db1/dashboard.mjs"); assert.ok(!/account\.nlv|\.positions|shares|study\/private/.test(dash), "the dashboard never reads the account"); });

test("9 · on live prices: the tool's reading is version 3; with its two switches off it is version 2 to the digit; the moves are the dip engine's, 0 is now, and a −5% has the VIX up and credit down", async (t) => {
  let candles, live; try { candles = await fetchDaily(getApi); live = await fetchLive(getApi); } catch (e) { t.skip("the chart API did not answer: " + e.message); return; }
  const base = J("study/ds1/data/ds1-live.json"); base.v2 = J("study/ds2/data/ds2-live.json"); base.v3 = J("study/ds3/data/ds3-live.json"); const A = baseline(base), v = view({ base, candles, ...live, A });
  assert.ok(v.v3 && v.v3.on.vix && v.v3.on.fear && v.reading.v3, "version 3"); assert.ok(v.reading.v1 && v.reading.v2, "with versions 1 and 2 kept under it");
  const bare = (R) => V3.readingV3({ base: v.v2.typical, rsiPoints: v.reading.parts.find((p) => p.key === "rsi").points, creditPoints: v.v2.creditFitted, rsi: v.inputs.rsi, cash: v.v2.cash, vixClose: v.v3.vixClose, vixHigh: v.v3.vixHigh }, R);
  const v2 = view({ base, candles, ...live, A: { ...A, vixRule: 0, fearRule: 0 } }); assert.ok(near(v2.reading.readingExact, bare({ ...v.v2.rules, vixRule: 0, fearRule: 0 }), 1e-9), "both switches off: version 2's sum"); assert.ok(near(v2.reading.readingExact, N_V2(v2), 1e-9));
  const want = V3.readingV3({ base: v.v2.typical, rsiPoints: v.reading.parts.find((p) => p.key === "rsi").points, creditPoints: v.v2.creditFitted, rsi: v.inputs.rsi, cash: v.v2.cash, vixClose: v.v3.vixClose, vixHigh: v.v3.vixHigh }, v.v2.rules); assert.ok(near(v.reading.readingExact, want, 1e-9), "the tool's reading is version 3's sum from bare points");
  const base2 = { ...base, v3: undefined }; const only2 = view({ base: base2, candles, ...live, A }); assert.equal(only2.v3, null); assert.equal(only2.reading.reading, v2.reading.reading, "without version 3's file: version 2");
  assert.deepEqual(v.moves.map((m) => m.movePct), [-8, -5, -3, -1.5, 0, 1.5, 3, 5]); const now = v.moves.find((m) => m.movePct === 0); assert.equal(now.reading, v.reading.reading); const d5 = v.moves.find((m) => m.movePct === -5); assert.ok(d5.vix > now.vix && d5.spy < now.spy && d5.qqq < now.qqq);
  for (const m of v.moves) assert.ok(m.reading >= 0 && m.reading <= 100 && isFinite(numberAt(m.reading, A))); const d3 = v.dips.find((d) => d.dipPct === 3); assert.equal(v.moves.find((m) => m.movePct === -3).reading, d3.readingCreditSells, "the −3% chip is the −3% dip with credit selling as usual"); });

test("10 · one headless page at a time, 1680 and 390, as the page loads (the harness opens the long version for the older tests; this one asks for it closed): the first screen's number is the live reading through the dials, it moves with a chip, the balance and the size, Reset restores $500K and 25; nothing on it is under 11px or reads the account; the long version is closed and holds every old panel", async () => {
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h, longVersion: "closed" }); const { page } = P; try {
    await page.waitForFunction(() => window.DB1_READY === true, null, { timeout: 60000 }); const cold = await page.evaluate(() => ({ text: document.getElementById("db1-root").innerText, lvTop: document.getElementById("longversion").getBoundingClientRect().top })); assert.ok(cold.text.includes("reading live prices") || cold.text.includes("TOTAL MONEY INVESTED"));
    await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && document.querySelector("#db1-root[data-version]"), null, { timeout: 150000 }); await page.waitForTimeout(600);
    const r = await page.evaluate(() => { const d = document.getElementById("db1-root"), st = window.DS1_LIVE, lv = document.getElementById("longversion"), first = [...document.querySelectorAll("body *")].filter((e) => !lv.contains(e) && e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0);
      return { ds: { ...d.dataset }, reading: st.view.reading.reading, held: +st.A.heldPct, tac: +st.A.tacticalPct, text: d.innerText, allFirst: first.map((e) => e.textContent).join(" "), minFont: Math.min(...first.filter((e) => !e.closest("svg")).map((e) => parseFloat(getComputedStyle(e).fontSize))), svgMin: Math.min(...[...d.querySelectorAll("svg text")].map((t) => +t.getAttribute("font-size"))), scrollW: document.scrollingElement.scrollWidth, lvOpen: lv.open, lvTop: lv.getBoundingClientRect().top, age: d.querySelector("[data-ds1-age]").textContent, pies: d.querySelectorAll("[data-pie] svg").length, lines: d.querySelectorAll(".sum li, [data-how] [data-line]").length, v3: !!st.view.v3, err: st.error, onDrawError: st.onDrawError || null }; });
    assert.deepEqual(P.errors, []); assert.equal(P.nonGet.blocked + P.nonGet.allowed, 0); assert.equal(r.onDrawError, null); assert.ok(r.v3, "version 3 on the page");
    assert.equal(+r.ds.reading, r.reading); assert.ok(near(+r.ds.number, r.held + (r.tac * r.reading) / 100, 0.006), "the number is the live reading through the dials: " + r.ds.number); assert.equal(r.ds.version, "3"); assert.equal(r.ds.size, "500000"); assert.equal(r.ds.bal, "25");
    assert.ok(r.text.includes("TOTAL MONEY INVESTED") && r.text.includes("$500K") && r.text.includes("kept in cash") && r.text.includes("25 : 75") && r.text.includes("always in + ") && r.text.includes("the VIX at")); assert.ok(/read \d\d:\d\d:\d\d New York/.test(r.age), "the age beside the number: " + r.age);
    assert.equal(r.pies, 2); assert.ok(r.lines >= 5 && r.lines <= 9, "DB2 (9 Oct, later): the lines under the formula became the picture's captions — the formula, a typical day, a caption per counted part, the VIX, the bracket while cash is raised, the reading: " + r.lines); assert.ok(r.scrollW <= w, "no sideways scroll: " + r.scrollW); assert.ok(r.minFont >= 11, "nothing under 11px on the first screen: " + r.minFont); assert.ok(r.svgMin >= 11, "pie labels at 11px or more");
    const low = /you hold|\broom\b|\bfree\b|\bused\b|to buy|IBKR|Interactive Brokers|held/i; assert.ok(!low.test(r.allFirst), "no account word on the first screen: " + (r.allFirst.match(low) || [])[0]); assert.ok(!/\b(MU|NBIS|NVDA|AVGO|TSM|ORCL|AMZN|GOOGL|VST)\b/.test(r.allFirst), "no ticker");
    assert.equal(r.lvOpen, false); if (w === 1680) assert.ok(r.lvTop <= h + 40, "at 1680 the long version's fold is at the foot of the first screen or just under it: " + r.lvTop);
    /* a chip */ await page.locator('#db1-root .chip[data-move="-3"]').click(); await page.waitForTimeout(200); const dip = await page.evaluate(() => { const d = document.getElementById("db1-root"), m = window.DS1_LIVE.view.moves.find((x) => x.movePct === -3); return { ds: { ...d.dataset }, want: m.reading, lab: d.querySelector(".lab").textContent, pies: d.querySelectorAll("[data-pie] svg").length }; }); assert.equal(dip.ds.move, "-3"); assert.equal(+dip.ds.reading, dip.want); assert.equal(dip.pies, 2);
    /* the balance */ await page.locator("input[data-bal]").fill("50"); await page.locator("input[data-bal]").dispatchEvent("change"); await page.waitForTimeout(200); const half = await page.evaluate(() => { const d = document.getElementById("db1-root"); return { bal: d.dataset.bal, ratio: d.querySelector(".ratio").textContent, full: d.querySelector('[data-pie="full"] svg').getAttribute("aria-label"), kept: localStorage.getItem("db1.dashboard") }; }); assert.equal(half.bal, "50"); assert.ok(half.ratio.includes("50 : 50") && half.ratio.includes("even")); assert.ok(half.full.includes("conviction 50.0% $250K") && half.full.includes("core 50.0% $250K")); assert.ok(JSON.parse(half.kept).bal === 50 && !/cash|shares|nlv/.test(half.kept));
    /* the size */ await page.locator('#db1-root [data-size="1"]').click(); await page.waitForTimeout(150); const up = await page.evaluate(() => ({ size: document.getElementById("db1-root").dataset.size, val: document.querySelector("[data-size-val]").textContent })); assert.equal(up.size, "550000"); assert.equal(up.val, "$550K");
    /* reset */ await page.locator("#db1-root [data-reset]").click(); await page.waitForTimeout(150); const rs = await page.evaluate(() => ({ ...document.getElementById("db1-root").dataset })); assert.equal(rs.size, "500000"); assert.equal(rs.bal, "25"); assert.equal(rs.move, "0");
    /* the long version: opened, every old panel is there and the money panel draws */ await page.evaluate(() => { document.getElementById("longversion").open = true; }); await page.waitForTimeout(1200);
    const lv = await page.evaluate(() => ({ panels: document.querySelectorAll(".grid > .panel").length, money: !!document.querySelector("#ds1money-host .a9"), ds1: !!document.querySelector("#ds1live .ds1"), specs: document.querySelectorAll("details.sc-pagespecs").length, moneyW: document.getElementById("ds1money-host").clientWidth })); assert.ok(lv.panels >= 10, "the old panels: " + lv.panels); assert.ok(lv.money && lv.ds1, "AL9's panel and DS1's reading are drawn"); assert.ok(lv.specs >= 1, "PAGE SPECS is still there (the money panel carries its own too)"); assert.ok(lv.moneyW >= Math.min(600, w - 110), "drawn at its width once open: " + lv.moneyW + " of " + w);
  } finally { await P.close(); } } });
