/* DB2 tests (9 Oct 2026) — how it gets to the number, as a picture (the first screen's fourth card).
   What they hold: the account bar's fill ends at the number; the steps under it add from a typical day to the market reading — at the
   reading now and at every what-if chip, on a recorded read, on a made-up market run through the tool's own view(), and on the live page;
   every caption is the line DB1 wrote, to the letter; a part that adds nothing is drawn as a bar of no width and never hidden; a sum past
   the end of the scale says where it stops; the VIX's add is not repeated as "a part you switched on"; nothing in the picture can be
   restyled by the dashboard's other rules; and one headless page at a time at 1680 and 390: the picture is on the first screen, measured
   in pixels, beside its captions when wide and under them on a phone, and it is drawn again with a chip and with a new read. */
import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
import { howSteps, howHtml, HOW_CSS, CAPTIONS } from "../study/db2/how.mjs";
import { summaryLines, dashboardHtml, numberOf, START } from "../study/db1/dashboard.mjs";
import { view, baseline } from "../study/ds1/live.mjs"; import * as E from "../study/ds1/engine.mjs"; import { DIALS } from "../study/al9/chain.mjs";
import { openPage } from "./_harness.mjs";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), T = (f) => fs.readFileSync(path.join(ROOT, f), "utf8"), J = (f) => JSON.parse(T(f)), near = (a, b, tol) => Math.abs(a - b) <= tol, clamp = (x, a, b) => Math.max(a, Math.min(b, x));
const BASE = () => { const b = J("study/ds1/data/ds1-live.json"); b.v2 = J("study/ds2/data/ds2-live.json"); b.v3 = J("study/ds3/data/ds3-live.json"); return b; };
/* the picture's own sum, from what howSteps returned: a typical day + every bar, kept inside 0–100, cut while cash is raised */
const sumOf = (H) => { const by = (k) => H.steps.filter((s) => s.kind === k), raw = by("start")[0].points + by("part").reduce((a, s) => a + s.points, 0), level = clamp(raw, 0, 100); return { raw, level, end: by("cash").length ? level * H.cut : level }; };
/* the same, read back off the drawn HTML: the widths of the bars as they are drawn */
const attr = (html, re) => { const m = html.match(re); return m ? m[1] : null; }, lanesOf = (html) => [...html.matchAll(/<div class="hw-plot hw-lane[^"]*" data-step="([^"]+)" data-kind="([^"]+)" data-from="([^"]+)" data-to="([^"]+)" data-points="([^"]+)" title="[^"]*">(.*?)<\/div>/g)].map((m) => ({ key: m[1], kind: m[2], from: +m[3], to: +m[4], points: +m[5], marks: m[6] }));
const barOf = (marks) => { const m = marks.match(/<i class="([^"]*)" data-bar style="left:([\d.]+)%?(?:;width:([\d.]+)%)?"/); return { cls: m[1], left: +m[2], width: m[3] == null ? 0 : +m[3] }; };

/* the read of 21:43 New York on 9 Oct 2026 (the close of that day), as view() returned it: the reading, what versions 2 and 3 did, the facts */
const REC = { now: { date: "2026-10-09", weekday: "Fri", minutes: 1303, hms: "21:43:42", ms: Date.now() }, readAt: { date: "2026-10-09", hms: "21:43:42", ms: Date.now() - 9000 }, error: null, A: { ...DIALS },
  view: { session: "2026-10-09", live: false, lastBar: "2026-10-09", missing: [],
    reading: { reading: 19.8, readingExact: 19.770425853871117, raw: 39.5, base: 49.1, lightsCounted: 0, parts: [{ key: "rsi", value: 60.394053017990586, points: 1.919255381487493, missing: false }, { key: "creditOwn", value: -0.035140754230733595, points: -11.453491027535268, fitted: -11.453491027535268, missing: false }], v1: { reading: 39.5, raw: 39.5 }, v2: { creditFitted: -11.453491027535268, creditCounted: -11.453491027535268, fade: 1, cash: true, cashCut: 0.5, beforeCash: 39.5 }, v3: { vixAdd: 0, vixClose: 14.84, vixHigh: 15.34, raisedByTheRally: false } },
    v2: { typical: 49.07508735379, cash: true, since: "2026-08-13", fade: 1, beforeCash: 39.5 }, v3: { on: { vix: true, fear: true }, rules: { lo: 20, hi: 23, addLo: 10, addHi: 20, touch: 0.5 }, vixAdd: 0, vixClose: 14.84, vixHigh: 15.34, raisedByTheRally: false },
    facts: { vix: { price: 14.84, high: 15.34 }, credit: { own: -0.035140754230733595 } }, moves: [] } };
const picture = (v, A, mv = null, opt = {}) => { const r = mv ? mv.r : v.reading, lines = summaryLines(v, A, mv), H = howSteps({ r, A, number: numberOf(r.reading, A), typical: v.v2 ? v.v2.typical : null, lines }); return { r, lines, H, html: howHtml(H, opt) }; };

test("1 · the read of 9 Oct: a typical day 49, the RSI +2, credit −11, the VIX nothing = 40; cash is raised, so it is halved = 20; 70 + 30 × 20 ÷ 100 = 75.9%. The steps add to the engine's own reading and every caption is DB1's line, to the letter", () => {
  const { H, lines } = picture(REC.view, REC.A); assert.deepEqual(H.steps.map((s) => s.key), ["base", "rsi", "credit", "vix", "cash", "end"]); assert.deepEqual(H.steps.map((s) => s.kind), ["start", "part", "part", "part", "cash", "end"]);
  assert.ok(near(H.number, 75.94, 1e-9)); assert.equal(H.always, 70); assert.equal(H.zoneEnd, 100); assert.ok(near(H.base, 49.07508735379, 1e-12));
  const S = sumOf(H); assert.ok(near(S.raw, 49.07508735379 + 1.919255381487493 - 11.453491027535268, 1e-9)); assert.ok(near(S.end, REC.view.reading.readingExact, 1e-9), "the bars add from a typical day to the market reading"); assert.ok(near(H.sumsTo, S.end, 1e-12)); assert.ok(Math.abs(H.off) < 1e-9, "nothing left over: " + H.off);
  /* each step starts where the one before it ended */ for (let i = 1; i < H.steps.length - 1; i++) assert.ok(near(H.steps[i].from, H.steps[i - 1].to, 1e-12), H.steps[i].key + " starts where " + H.steps[i - 1].key + " ended"); assert.equal(H.steps.at(-1).from, 0); assert.ok(near(H.steps.at(-1).to, H.steps.at(-2).to, 1e-12));
  assert.deepEqual(H.steps.map((s) => s.caption), ["a typical day, 49", "SPY and QQQ's RSI 60: a little stretched, +2", "credit 0.0% over ten sessions, −11", "the VIX at 14.8: under your 20, adds nothing", "cash freed since 13 Aug near the highs: the swing is halved (40 → 20)", "the market reading, 20 of 100"]);
  for (const k of ["rsi", "credit", "vix", "cash"]) assert.equal(H.steps.find((s) => s.key === k).caption, lines.find((l) => l.key === k).text, k + ": the caption is the line");
  assert.equal(lines[0].text, "70% always in + 30% × the market reading (20 of 100) = 75.9%"); assert.equal(H.steps.find((s) => s.key === "vix").points, 0); assert.equal(H.cut, 0.5); });

test("2 · the picture of that read: the account bar is a solid block to 70, the swing a track from 70 to 100, and its fill ends at the number; a bright mark and the number sit there; a faint tick at 100. Under it: the up colour for what adds, the down colour for what takes away, the VIX as a bar of no width — drawn, never hidden —, the raise-cash bracket, and the reading it comes to", () => {
  for (const narrow of [false, true]) { const { H, html } = picture(REC.view, REC.A, null, { narrow });
    const always = +attr(html, /class="hw-in" style="width:([\d.]+)%"/), sw = html.match(/class="hw-sw" style="left:([\d.]+)%;width:([\d.]+)%"><i data-fill style="width:([\d.]+)%"/), fillEnd = +sw[1] + (+sw[2] * +sw[3]) / 100;
    assert.equal(always, 70); assert.equal(+sw[1], 70); assert.equal(+sw[2], 30); assert.ok(near(fillEnd, 75.94, 1e-3), "the fill ends at the number: " + fillEnd); assert.ok(near(fillEnd, numberOf(REC.view.reading.reading, REC.A), 1e-3));
    assert.equal(+attr(html, /class="hw-pin" data-pin style="left:([\d.]+)%"/), 75.94); assert.ok(/<b class="hw-mk" style="left:75\.94%">75\.9%<\/b>/.test(html), "the number at the mark"); assert.ok(html.includes('<i class="hw-tk" style="left:100%"></i>'), "a tick at 100"); assert.ok(html.includes(">always in</span>"));
    assert.ok(html.includes(`<polygon points="70,0 100,0 100,16 ${narrow ? 0 : CAPTIONS},16"/>`), "the wedge opens from the swing to the scale under it"); assert.ok(html.includes(`data-layout="${narrow ? "stacked" : "beside"}"`)); assert.equal(html.includes("hw-stack"), narrow);
    const L = lanesOf(html); assert.deepEqual(L.map((l) => l.key), H.steps.map((s) => s.key)); const bar = Object.fromEntries(L.map((l) => [l.key, barOf(l.marks)]));
    assert.ok(bar.base.cls.includes("hw-start") && near(bar.base.left, 0, 1e-9) && near(bar.base.width, 49.075, 1e-3)); assert.ok(bar.rsi.cls.includes("hw-up") && near(bar.rsi.left, 49.075, 1e-3) && near(bar.rsi.width, 1.919, 2e-3), "the RSI adds: the up colour, from 49 to 51");
    assert.ok(bar.credit.cls.includes("hw-dn") && near(bar.credit.left, 39.541, 2e-3) && near(bar.credit.left + bar.credit.width, 50.994, 2e-3), "credit takes away: the down colour, from 51 back to 40");
    assert.ok(bar.vix.cls.split(" ").includes("hw-z") && bar.vix.width === 0 && near(bar.vix.left, 39.541, 2e-3), "the VIX adds nothing: a bar of no width, drawn where the level stands"); assert.ok(!/hw-up|hw-dn/.test(bar.vix.cls), "in the neutral ink");
    assert.ok(bar.cash.cls.includes("hw-o") && near(bar.cash.left, 19.77, 2e-3) && near(bar.cash.left + bar.cash.width, 39.541, 2e-3), "what cash frees: in outline, from 20 to 40"); const k = L.find((l) => l.key === "cash").marks; assert.ok(/class="hw-k" style="left:0;width:39\.541%"/.test(k) && /class="hw-km" style="left:19\.77%"/.test(k), "the bracket spans the level before cash, its mark where the cut lands");
    assert.ok(bar.end.cls.includes("hw-end") && near(bar.end.width, 19.77, 2e-3)); assert.ok(near(bar.end.width, +sw[3], 0.05), "the reading's bar and the swing's fill are the same share: " + bar.end.width + " and " + sw[3]);
    /* the drawn bars add: a typical day, plus what is drawn in the up colour, less what is drawn in the down colour, less what is in outline = the reading's bar */
    assert.ok(near(bar.base.width + bar.rsi.width - bar.credit.width - bar.cash.width, bar.end.width, 5e-3), "the drawn widths add from a typical day to the market reading");
    for (const s of H.steps) assert.ok(html.includes(`<div class="hw-cap" data-line="${s.key}" title="`) && html.includes(">" + s.caption.replace(/&/g, "&amp;") + "</div>"), "the caption is on the page: " + s.caption);
    assert.ok(html.includes('role="img"') && html.includes("0 · stretched") && html.includes("washed out · 100")); const text = html.replace(/<[^>]+>/g, " ");
    assert.ok(!/you hold|\broom\b|\bfree\b|\bused\b|to buy|shares|IBKR|NLV|held/i.test(text), "no account word in the picture"); assert.ok(!/title="[^"]*>|aria-label="[^"]*>/.test(html), "no attribute carries a > (the older tests strip tags with it)"); } });

test("3 · the ends of the scale, a part no line names, the older versions, and other dials", () => {
  const A = { ...DIALS }, mk = (o) => ({ reading: +clamp(o.sum, 0, 100).toFixed(1), readingExact: clamp(o.sum, 0, 100) * (o.cash ? 0.5 : 1), base: 49.1, v2: { cash: !!o.cash, cashCut: o.cash ? 0.5 : 1 } });
  /* over 100: the bar that crosses the end is cut there and says so; the row after it says where the reading stops */
  { const lines = [{ key: "sum", text: "" }, { key: "rsi", text: "SPY and QQQ's RSI 29: washed out, +33", points: 33.45 }, { key: "credit", text: "credit −1.6% over ten sessions, +5", points: 5.15 }, { key: "vix", text: "the VIX at 24.1: over your 23, both hands, +20", points: 20 }], r = mk({ sum: 49.075 + 33.45 + 5.15 + 20 }), H = howSteps({ r, A, number: numberOf(r.reading, A), typical: 49.075, lines });
    assert.deepEqual(H.steps.map((s) => s.key), ["base", "rsi", "credit", "vix", "stop", "end"]); assert.equal(H.steps[4].caption, "the parts add to 108: the market reading stops at 100"); assert.ok(near(H.steps[4].points, 100 - 107.675, 1e-9)); assert.equal(H.steps.at(-1).to, 100); assert.ok(Math.abs(H.off) < 1e-9);
    const html = howHtml(H), L = lanesOf(html), vix = barOf(L[3].marks); assert.ok(vix.cls.includes("hw-past") && vix.cls.includes("hw-up") && near(vix.left + vix.width, 100, 1e-9) && near(vix.width, 100 - 87.675, 2e-3), "the VIX's bar is cut at 100 and marked as running past it"); assert.ok(barOf(L[4].marks).cls.includes("hw-z") && barOf(L[4].marks).left === 100); assert.ok(html.includes('<b class="hw-mk hw-r" style="left:100%">100.0%</b>'), "at 100 the number is kept inside the card"); }
  /* under 0, with cash raised: it stops at 0, and a part wholly past the end is a bar of no width in its own colour */
  { const lines = [{ key: "sum", text: "" }, { key: "rsi", text: "SPY and QQQ's RSI 75: stretched, −51", points: -50.675 }, { key: "credit", text: "credit +0.9% over ten sessions, 0", points: 0.454 }, { key: "vix", text: "the VIX at 9.1: under your 20, adds nothing", points: 0 }, { key: "cash", text: "cash freed since 13 Aug near the highs: the swing is halved (0 → 0)" }], r = mk({ sum: 49.075 - 50.675 + 0.454, cash: true }), H = howSteps({ r, A, number: numberOf(r.reading, A), typical: 49.075, lines });
    assert.deepEqual(H.steps.map((s) => s.key), ["base", "rsi", "credit", "vix", "stop", "cash", "end"]); assert.equal(H.steps[4].caption, "the parts add to −1: the market reading stops at 0"); assert.equal(H.steps.at(-1).to, 0); assert.ok(Math.abs(H.off) < 1e-9);
    const html = howHtml(H), L = lanesOf(html), rsi = barOf(L[1].marks), cr = barOf(L[2].marks); assert.ok(rsi.cls.includes("hw-low") && rsi.cls.includes("hw-dn") && rsi.left === 0 && near(rsi.width, 49.075, 1e-3)); assert.deepEqual([cr.cls, cr.left, cr.width], ["hw-z hw-up", 0, 0]); assert.equal(barOf(L[6].marks).cls, "hw-z", "a market reading of 0 is still drawn"); assert.ok(html.includes('data-number="70.00"')); assert.ok(/<i data-fill style="width:0%">/.test(html), "nothing of the swing is filled"); }
  /* a part that counts and that no line names is drawn as a row of its own, so the bars still add */
  { const lines = [{ key: "sum", text: "" }, { key: "rsi", text: "r", points: 2 }, { key: "credit", text: "c", points: -11 }], r = mk({ sum: 49.075 + 2 - 11 + 5 }), H = howSteps({ r, A, number: numberOf(r.reading, A), typical: 49.075, lines });
    assert.deepEqual(H.steps.map((s) => s.key), ["base", "rsi", "credit", "other", "end"]); assert.equal(H.steps[3].caption, "other parts, +5"); assert.ok(near(H.steps[3].points, 5, 1e-9)); assert.ok(near(sumOf(H).end, r.readingExact, 1e-9)); }
  /* version 1 (a rule file that did not load): the reading is rounded to a tenth, twice — the steps still add to it and nothing is invented */
  { const lines = [{ key: "sum", text: "" }, { key: "rsi", text: "r", points: 1.919 }, { key: "credit", text: "c", points: -11.453 }], r = { reading: 39.5, raw: 39.5, base: 49.1 }, H = howSteps({ r, A, number: numberOf(39.5, A), typical: null, lines });
    assert.deepEqual(H.steps.map((s) => s.key), ["base", "rsi", "credit", "end"]); assert.equal(H.base, 49.1); assert.equal(H.cut, 1); assert.ok(Math.abs(H.off) < 0.11); }
  /* no typical day at all (a state older than this round): the account bar alone, still filled to the number */
  { const H = howSteps({ r: { reading: 18.3 }, A, number: numberOf(18.3, A), typical: null, lines: [] }); assert.equal(H.steps, null); const html = howHtml(H); assert.ok(html.includes("data-acct") && !html.includes("data-step")); const sw = html.match(/class="hw-sw" style="left:([\d.]+)%;width:([\d.]+)%"><i data-fill style="width:([\d.]+)%"/); assert.ok(near(+sw[1] + (+sw[2] * +sw[3]) / 100, 75.49, 1e-3)); }
  assert.equal(howSteps({ r: null, A, number: 75, lines: [] }), null); assert.equal(howHtml(null), "");
  /* other dials (60 always in, 30 that swings): the block ends at 60, the swing at 90, the fill at the number, and the ends are named */
  { const B = { ...DIALS, heldPct: 60, tacticalPct: 30 }, r = mk({ sum: 50 }), n = numberOf(r.reading, B), H = howSteps({ r, A: B, number: n, typical: 49.075, lines: [{ key: "rsi", text: "r", points: 0.925 }] }), html = howHtml(H); assert.equal(n, 75); assert.equal(H.always, 60); assert.equal(H.zoneEnd, 90);
    const sw = html.match(/class="hw-sw" style="left:([\d.]+)%;width:([\d.]+)%"><i data-fill style="width:([\d.]+)%"/); assert.ok(near(+sw[1] + (+sw[2] * +sw[3]) / 100, 75, 1e-6)); assert.ok(html.includes(">60%</span>") && html.includes(">90%</span>") && html.includes(">100%</span>") && html.includes('points="60,0 90,0 100,16')); } });

/* ---------- a made-up market, the same every run: the tool's 26 symbols on 420 sessions ending 9 Oct 2026 ----------
   Every index, fund and name climbs steadily (so SPY and QQQ sit at an extended high); `last` moves SPY, QQQ and the rest over the final
   sessions, `hyg` and `ief` move credit and treasuries over them; `vix` and `vixHigh` are the last session's VIX. */
function market({ last = [], hyg = [], ief = [], vix = 14.8, vixHigh = null, n = 420 } = {}) {
  let s = 20261009; const rnd = () => ((s = (Math.imul(s, 1664525) + 1013904223) >>> 0) / 4294967296), days = []; for (let d = Date.UTC(2026, 9, 9); days.length < n; d -= 864e5) if (new Date(d).getUTCDay() % 6) days.unshift(d);
  const walk = (dr, vol, end) => { let p = 100; return days.map((t, i) => { const k = i - (n - end.length); p *= 1 + (k >= 0 ? end[k] : dr + (rnd() - 0.5) * vol); return { t, c: p, h: p * 1.004, l: p * 0.996 }; }); }, candles = {};
  for (const sym of E.ALL_SYMBOLS) candles[sym] = { series: sym === "VIX" ? days.map((t, i) => (i === n - 1 ? { t, c: vix, h: vixHigh ?? vix, l: Math.min(vix, 13) } : { t, c: 14 + rnd() * 3, h: 18, l: 12.5 })) : sym === "HYG" ? walk(0.0002, 0.002, hyg) : sym === "IEF" ? walk(0.0001, 0.002, ief) : walk(0.0013, 0.012, last) };
  return candles; }
const seen = (base, opts, A) => view({ base, candles: market(opts), quotes: {}, macro: null, intraday: null, geiger: null, A: A || baseline(base) });

test("4 · on a made-up market run through the tool's own view(): at the reading now and at every what-if chip the steps add from a typical day to that move's own reading, the fill ends at that move's number, every caption is that move's line — and the VIX's add is never said twice", () => {
  const base = BASE(), cases = { "an extended high, calm": {}, "a washout, the VIX at 31": { last: Array(12).fill(-0.017), hyg: Array(12).fill(-0.004), vix: 31, vixHigh: 34 }, "the VIX touched 20 and closed under it": { vix: 19.2, vixHigh: 20.6 }, "the VIX closed at 21": { vix: 21.3, vixHigh: 22 }, "stretched further": { last: Array(8).fill(0.012) }, "a treasury rally": { ief: Array(10).fill(0.004), hyg: Array(10).fill(-0.001) } };
  const saw = { cash: 0, noCash: 0, over: 0, under: 0, vix5: 0, vix10: 0, vix20: 0, zeroVix: 0, softened: 0, rally: 0, n: 0 };
  for (const [name, opts] of Object.entries(cases)) { const v = seen(base, opts), A = baseline(base); assert.ok(v.v3 && v.reading.v3 && v.reading.v2, name + ": version 3"); assert.deepEqual(v.moves.map((m) => m.movePct), [-8, -5, -3, -1.5, 0, 1.5, 3, 5]);
    for (const m of v.moves) { const at = name + " · " + (m.movePct === 0 ? "now" : m.movePct + "%"); assert.ok(m.r && m.r.parts && m.r.v2, at + ": the move carries its own reading"); assert.equal(m.r.reading, m.reading); if (m.movePct === 0) { assert.equal(m.r, v.reading); assert.equal(m.since, v.v2.since); }
      const { H, lines, html } = picture(v, A, m), S = sumOf(H); saw.n++;
      assert.ok(near(S.end, m.r.readingExact, 1e-9), at + ": the steps add to the reading — " + S.end + " against " + m.r.readingExact); assert.ok(Math.abs(H.off) < 1e-9, at + ": nothing left over"); assert.ok(!H.steps.some((s) => s.key === "other"), at + ": every part that counts has its own line");
      assert.ok(near(S.raw, v.v2.typical + m.r.parts.reduce((a, p) => a + p.points, 0) + m.r.v3.vixAdd, 1e-9), at + ": a typical day, the two counted parts as counted, and the VIX"); assert.ok(near(H.number, 70 + (30 * m.reading) / 100, 1e-9));
      const sw = html.match(/class="hw-sw" style="left:([\d.]+)%;width:([\d.]+)%"><i data-fill style="width:([\d.]+)%"/); assert.ok(near(+sw[1] + (+sw[2] * +sw[3]) / 100, H.number, 1e-3), at + ": the fill ends at the number"); assert.ok(html.includes(`data-reading="${m.reading}"`));
      /* the drawn bars, read back off the HTML, land where the sum does */ const L = lanesOf(html); assert.deepEqual(L.map((l) => l.key), H.steps.map((s) => s.key)); for (const l of L) { const b = barOf(l.marks), lo = clamp(Math.min(l.from, l.to), 0, 100), hi = clamp(Math.max(l.from, l.to), 0, 100); if (l.kind === "stop") assert.ok(near(b.left, clamp(l.to, 0, 100), 2e-3)); else { assert.ok(near(b.left, l.kind === "start" || l.kind === "end" ? 0 : lo, 2e-3), at + " " + l.key + " starts at " + b.left + ", not " + lo); assert.ok(near(b.left + b.width, hi < 0.05 || hi - lo < 0.05 ? b.left : hi, 2e-3), at + " " + l.key + " ends at " + (b.left + b.width) + ", not " + hi); } }
      { const last = barOf(L.at(-1).marks); assert.ok(m.r.readingExact < 0.05 ? last.width === 0 && last.cls === "hw-z" : near(last.width, m.r.readingExact, 2e-3), at + ": the last bar is the reading (a reading that rounds to nothing is a bar of no width)"); }
      /* the captions are the lines, and the lines are the move's own */ for (const s of H.steps.filter((x) => x.kind === "part" || x.kind === "cash")) assert.equal(s.caption, lines.find((l) => l.key === s.key).text); assert.ok(lines[0].text.includes(`(${m.reading.toFixed(0)} of 100)`), at + ": the formula line is the move's");
      assert.ok(lines.find((l) => l.key === "rsi").text.startsWith(`SPY and QQQ's RSI ${m.r.parts[0].value.toFixed(0)}: `)); { const t = lines.find((l) => l.key === "vix").text, touched = m.r.v3.vixAdd > 0 && m.r.v3.vixClose < 20; assert.ok(touched ? /^the VIX touched (20|23) today \(/.test(t) : t.startsWith(`the VIX at ${m.r.v3.vixClose.toFixed(1)}: `), at + ": the VIX at the move's own level — " + t); }
      /* the fix: version 3 hands the VIX's add over in the slot of the switched-on parts; it has its own line and must not get a second */ assert.equal(m.r.lightsCounted, m.r.v3.vixAdd, at + ": the engine's slot holds the VIX's add"); assert.ok(!lines.some((l) => l.key === "lights"), at + ": no line says the VIX's add again"); assert.equal(H.steps.find((s) => s.key === "vix").points, m.r.v3.vixAdd);
      const vixBar = barOf(L.find((l) => l.key === "vix").marks); if (m.r.v3.vixAdd === 0) { saw.zeroVix++; assert.ok(vixBar.cls.split(" ").includes("hw-z") && vixBar.width === 0, at + ": the VIX at nothing is still drawn"); } else assert.ok(/hw-up/.test(vixBar.cls), at + ": the VIX adds in the up colour");
      assert.equal(H.steps.some((s) => s.key === "cash"), !!m.r.v2.cash, at + ": the bracket is there exactly while cash is raised"); if (m.r.v2.cash) { saw.cash++; assert.ok(m.since, at + ": the day it began"); assert.ok(lines.find((l) => l.key === "cash").text.includes(`(${m.r.v2.beforeCash.toFixed(0)} → ${m.reading.toFixed(0)})`)); } else saw.noCash++;
      if (S.raw > 100) { saw.over++; assert.ok(H.steps.find((s) => s.key === "stop").caption.endsWith("stops at 100")); } if (S.raw < 0) { saw.under++; assert.ok(H.steps.find((s) => s.key === "stop").caption.endsWith("stops at 0")); } assert.equal(H.steps.some((s) => s.key === "stop"), S.raw > 100 || S.raw < 0);
      if (m.r.v3.vixAdd === 5) saw.vix5++; if (m.r.v3.vixAdd === 10) saw.vix10++; if (m.r.v3.vixAdd === 20) saw.vix20++; if (/softened from/.test(lines.find((l) => l.key === "credit").text)) saw.softened++; if (/treasuries rallied/.test(lines.find((l) => l.key === "credit").text)) saw.rally++; } }
  for (const [k, c] of Object.entries(saw)) assert.ok(c > 0, "the made-up market reaches this case: " + k + " — " + JSON.stringify(saw)); assert.equal(saw.n, 48);
  /* a part the viewer switched on (breadth) gets its own row, in its own points — and beside a VIX that adds, only its own */
  { const A = { ...baseline(base), count: { br50: true } }, v = seen(base, { vix: 21.3, vixHigh: 22 }, A), l = v.reading.lights.find((x) => x.key === "br50"), { H, lines } = picture(v, A); assert.ok(l && l.counted && Math.abs(l.points) >= 0.05, "breadth is counted: " + (l && l.points)); assert.equal(v.reading.v3.vixAdd, 10);
    assert.ok(near(v.reading.lightsCounted, 10 + l.points, 1e-9), "the engine's slot holds both"); const row = H.steps.find((s) => s.key === "lights"); assert.ok(row && near(row.points, l.points, 1e-9), "the row is the switched-on part alone"); assert.equal(row.caption, lines.find((x) => x.key === "lights").text); assert.ok(/ from the parts you switched on$/.test(row.caption)); assert.ok(near(sumOf(H).end, v.reading.readingExact, 1e-9)); assert.ok(Math.abs(H.off) < 1e-9); } });

test("5 · the card on the first screen: the one formula line stays above the picture and the four lines under it are gone; picked, a chip changes the heading, the formula and the picture to that move's own; on a phone the captions go above their bars; a state from before this round keeps DB1's heading and the lines of now", () => {
  const base = BASE(), v = seen(base, {}), A = baseline(base), st = { view: v, A, base, now: REC.now, readAt: REC.readAt, error: null }, S = { ...START, last: null };
  const h = dashboardHtml(st, S, 0, 1400), card = (x) => x.slice(x.indexOf('aria-label="How it gets to the number"'), x.indexOf('aria-label="What if SPY and QQQ move"')), c = card(h), n = numberOf(v.reading.reading, A);
  assert.ok(c.includes(`<div class="lab">How it gets to ${n.toFixed(1)}%</div>`)); assert.equal((c.match(/<li /g) || []).length, 1, "one line of text, the formula"); assert.ok(c.indexOf('<li data-line="sum">') > 0 && c.indexOf('<li data-line="sum">') < c.indexOf("data-how"), "the formula line is above the picture");
  assert.ok(c.includes(`<li data-line="sum">70% always in + 30% × the market reading (${v.reading.reading.toFixed(0)} of 100) = ${n.toFixed(1)}%</li>`)); assert.ok(c.includes('data-layout="beside"') && c.includes(`data-number="${n.toFixed(2)}"`) && h.includes(`id="db1-root" data-number="${n.toFixed(2)}"`), "the picture's number is the screen's");
  for (const k of ["base", "rsi", "credit", "vix", "end"]) assert.ok(c.includes(`data-line="${k}"`) && c.includes(`data-step="${k}"`), k + " has its caption and its bar");
  const m = v.moves.find((x) => x.movePct === -5), at = card(dashboardHtml(st, S, -5, 1400)), nm = numberOf(m.reading, A); assert.notEqual(m.reading, v.reading.reading);
  assert.ok(at.includes(`<div class="lab">How it gets to ${nm.toFixed(1)}% · if SPY &amp; QQQ move −5%</div>`)); assert.ok(at.includes(`(${m.reading.toFixed(0)} of 100) = ${nm.toFixed(1)}%</li>`)); assert.ok(at.includes(`data-reading="${m.reading}"`) && at.includes(`data-number="${nm.toFixed(2)}"`), "the picture is the chip's");
  assert.ok(at.includes(">" + summaryLines(v, A, m).find((l) => l.key === "rsi").text + "<") && !at.includes(">" + summaryLines(v, A).find((l) => l.key === "rsi").text + "<"), "its captions too");
  const phone = card(dashboardHtml(st, S, 0, 330)); assert.ok(phone.includes('class="hw hw-stack"') && phone.includes('data-layout="stacked"') && phone.includes('points="70,0 100,0 100,16 0,16"'));
  /* a state whose moves carry no reading of their own (as DB1's did) */ const old = { ...st, view: { ...v, moves: v.moves.map(({ r, since, ...rest }) => rest) } }, o = card(dashboardHtml(old, S, -5, 1400));
  assert.ok(o.includes(`How it gets to ${n.toFixed(1)}% now · at −5% the market reading is ${m.reading.toFixed(0)}, so ${nm.toFixed(1)}%`)); assert.ok(o.includes(`data-reading="${v.reading.reading}"`) && o.includes(`data-number="${n.toFixed(2)}"`), "the picture stays with the lines it is drawn from");
  assert.ok(card(dashboardHtml(null, S)).includes("the first read of the market is on its way") && !card(dashboardHtml(null, S)).includes("data-how"));
  /* should the rows ever not be drawable (a state with no typical day in it), no word is lost: every line stays as text and the account bar is still drawn */
  { const bare = { ...st, base: null, view: { ...v, v2: { ...v.v2, typical: null }, reading: { ...v.reading, base: undefined } } }, b = card(dashboardHtml(bare, S, 0, 1400)), L = summaryLines(bare.view, A); assert.ok(L.length >= 4); assert.equal((b.match(/<li /g) || []).length, L.length); for (const l of L) assert.ok(b.includes(`<li data-line="${l.key}">${l.text.replace(/&/g, "&amp;")}</li>`), l.key + " stays as text"); assert.ok(b.includes("data-acct") && !b.includes("data-step")); } });

test("6 · nothing on the dashboard can restyle the picture, and it uses the tool's own colours: every class in it starts with hw, the up colour is the tool's green, the down colour its red, and the tool's files carry no library", () => {
  const { html } = picture(REC.view, REC.A), used = new Set([...html.matchAll(/class="([^"]+)"/g)].flatMap((m) => m[1].split(/\s+/))); for (const c of used) assert.ok(c === "hw" || c.startsWith("hw-"), "a class of its own: " + c);
  const styled = new Set([...HOW_CSS.matchAll(/\.([a-zA-Z][\w-]*)/g)].map((m) => m[1])); styled.delete("db1"); for (const c of styled) assert.ok(c === "hw" || c.startsWith("hw-"), "a rule for a class of its own: ." + c); for (const c of used) assert.ok(styled.has(c), "styled: ." + c);
  /* the dashboard's sheet has rules for plain names — the first drawing of this picture used one (.under) and its bar came out 2px tall */ const dash = T("study/db1/dashboard.mjs"); assert.ok(/\.db1 \.under\{/.test(dash)); for (const c of used) assert.ok(!new RegExp("\\.db1 \\." + c + "[\\s{,.:]").test(dash), "the dashboard's own sheet has no rule for ." + c);
  assert.ok(/\.hw-b\.hw-up\{background:var\(--green,#38e07b\)/.test(HOW_CSS) && /\.hw-b\.hw-dn\{background:var\(--red,#ff5470\)/.test(HOW_CSS)); assert.ok(/\.hw-start\{background:var\(--dimc\)\}/.test(HOW_CSS) && /\.hw-end\{background:var\(--txt,#e8e8f0\)/.test(HOW_CSS), "the start and the end in the panel's neutral ink");
  const src = T("study/db2/how.mjs"); assert.ok(!/\bimport\b[^;]*from/.test(src.replace(/\/\*[\s\S]*?\*\//g, "")), "it imports nothing"); assert.ok(!/fetch\(|XMLHttpRequest|localStorage/.test(src), "and asks for nothing"); assert.ok(dash.includes('import { howSteps, howHtml, HOW_CSS } from "../db2/how.mjs";') && dash.includes("s.textContent = CSS + HOW_CSS"));
  for (const px of [...HOW_CSS.matchAll(/font-size:([\d.]+)px/g)].map((m) => +m[1])) assert.ok(px >= 11, "no text under 11px: " + px); });

test("7 · the page says how to read it where the tool keeps such words — under PAGE SPECS, not in the panel", () => {
  const html = T("index.html"), specs = html.slice(html.indexOf('<details class="sc-pagespecs"><summary>PAGE SPECS</summary>')); assert.ok(specs.includes("how it gets to the number is a picture (DB2)"), "the picture is described under PAGE SPECS"); for (const w of ["a typical day", "bar of no width", "rounded on its own"]) assert.ok(specs.includes(w), w);
  const { html: pic } = picture(REC.view, REC.A), words = pic.replace(/<[^>]+>/g, " ").replace(/\s+/g, " "); assert.ok(words.length < 420, "the picture carries captions, not sentences: " + words.length + " characters"); });

test("8 · one headless page at a time, 1680 and 390, on live prices: the picture is on the first screen; measured in pixels the fill ends at the number and every bar starts where the one above it ended; the captions are the lines; beside their bars when wide, above them on a phone, nothing spilling sideways; it is drawn again with every chip and with a new read", async () => {
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h, longVersion: "closed" }); const { page } = P; try {
    await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && document.querySelector("#db1-root[data-version]") && document.querySelector("#db1-root [data-how]"), null, { timeout: 150000 }); await page.waitForTimeout(600);
    const read = () => page.evaluate(() => { const d = document.getElementById("db1-root"), hw = d.querySelector("[data-how]"), st = window.DS1_LIVE, v = st.view, pick = +d.dataset.move, mv = v.moves.find((m) => Math.abs(m.movePct - pick) < 1e-9), r = mv.r, box = (e) => e.getBoundingClientRect();
      const rail = box(hw.querySelector("[data-rail]")), fill = box(hw.querySelector("[data-fill]")), pin = box(hw.querySelector("[data-pin]")), mk = box(hw.querySelector(".hw-mk")), card = box(hw.closest("section")), pct = (x, B) => ((x - B.left) / B.width) * 100;
      const lanes = [...hw.querySelectorAll("[data-step]")].map((l) => { const L = box(l), b = box(l.querySelector("[data-bar]")), cap = box(hw.querySelector(`[data-line="${l.dataset.step}"]`)); return { key: l.dataset.step, kind: l.dataset.kind, from: +l.dataset.from, to: +l.dataset.to, points: +l.dataset.points, left: pct(b.left, L), right: pct(b.right, L), barW: b.width, barH: b.height, laneW: L.width, laneTop: L.top, laneBottom: L.bottom, laneLeft: L.left, capLeft: cap.left, capRight: cap.right, capTop: cap.top, capBottom: cap.bottom, caption: hw.querySelector(`[data-line="${l.dataset.step}"]`).textContent, tone: l.querySelector("[data-bar]").className, colour: getComputedStyle(l.querySelector("[data-bar]")).backgroundColor }; });
      const leaf = [...hw.closest("section").querySelectorAll("*")].filter((e) => e.children.length === 0 && e.textContent.trim() && !e.closest("svg"));
      return { pick, number: +d.dataset.number, picNumber: +hw.dataset.number, picReading: +hw.dataset.reading, off: +hw.dataset.off, sum: +hw.dataset.sum, layout: hw.dataset.layout, want: { reading: r.reading, exact: r.readingExact, number: +st.A.heldPct + (+st.A.tacticalPct * r.reading) / 100, typical: v.v2.typical, cash: r.v2.cash, vixAdd: r.v3.vixAdd, version: v.v3 ? 3 : 2 },
        fillAt: pct(fill.right, rail), pinAt: pct(pin.left + pin.width / 2, rail), railW: rail.width, mkText: hw.querySelector(".hw-mk").textContent, mkLeft: mk.left, mkRight: mk.right, cardLeft: card.left, cardRight: card.right, lanes, lines: window.DB1.summaryLines(v, st.A, mv).map((l) => ({ key: l.key, text: l.text })), formula: d.querySelector('[data-line="sum"]').textContent, lab: hw.closest("section").querySelector(".lab").textContent,
        scrollW: document.scrollingElement.scrollWidth, minFont: Math.min(...leaf.map((e) => parseFloat(getComputedStyle(e).fontSize))), cardTop: card.top, cardBottom: card.bottom, chipsTop: box(d.querySelector(".chips")).top, lis: hw.closest("section").querySelectorAll("li").length, lvTop: box(document.getElementById("longversion")).top, green: getComputedStyle(document.documentElement).getPropertyValue("--green").trim(), red: getComputedStyle(document.documentElement).getPropertyValue("--red").trim() }; });
    const px = 100 / (w > 700 ? 560 : 290), check = (r, at) => { const tol = px * 1.2;   /* a pixel and a bit, in % of the scale */
      assert.equal(r.picNumber, r.number, at + ": the picture's number is the screen's"); assert.ok(near(r.number, r.want.number, 0.006), at + ": and it is the reading through the dials"); assert.equal(r.picReading, r.want.reading); assert.equal(r.want.version, 3);
      assert.ok(near(r.fillAt, r.number, 100 / r.railW + 0.05), at + ": measured on the screen the fill ends at the number — " + r.fillAt.toFixed(2) + " against " + r.number); assert.ok(near(r.pinAt, r.number, 100 / r.railW + 0.05), at + ": and the bright mark stands there — " + r.pinAt.toFixed(2)); assert.equal(r.mkText, r.number.toFixed(1) + "%"); assert.ok(r.mkLeft >= r.cardLeft && r.mkRight <= r.cardRight, at + ": the number stays inside the card");
      assert.ok(Math.abs(r.off) < 1e-5, at + ": the steps add to the engine's reading, nothing left over: " + r.off); assert.ok(near(r.sum, r.want.exact, 1e-3)); const L = r.lanes, kinds = L.map((l) => l.kind); assert.equal(kinds[0], "start"); assert.equal(kinds.at(-1), "end"); assert.ok(!L.some((l) => l.key === "other"), at + ": no part is unnamed");
      const raw = L[0].points + L.filter((l) => l.kind === "part").reduce((a, l) => a + l.points, 0), level = Math.max(0, Math.min(100, raw)), end = r.want.cash ? level * 0.5 : level; assert.ok(near(L[0].points, r.want.typical, 1e-3), at + ": it starts at a typical day"); assert.ok(near(end, r.want.exact, 1e-3), at + ": a typical day and the bars add to the market reading — " + end.toFixed(3) + " against " + r.want.exact); assert.ok(near(L.at(-1).to, r.want.exact, 1e-3));
      for (let i = 1; i < L.length; i++) { const l = L[i], lo = Math.max(0, Math.min(100, Math.min(l.from, l.to))), hi = Math.max(0, Math.min(100, Math.max(l.from, l.to))), thin = l.barW <= 2.5; if (l.kind !== "end") assert.ok(near(l.from, L[i - 1].to, 1e-3), at + " " + l.key + ": starts where the row above ended");
        if (l.kind === "end") { if (!thin) { assert.ok(near(l.left, 0, tol) && near(l.right, hi, tol), at + ": the last bar runs from 0 to the reading — " + l.right.toFixed(2)); } } else if (thin) assert.ok(near((l.left + l.right) / 2, l.kind === "stop" ? Math.max(0, Math.min(100, l.to)) : lo, tol), at + " " + l.key + ": a bar of no width stands at the level — " + ((l.left + l.right) / 2).toFixed(2) + " against " + lo); else { assert.ok(near(l.left, lo, tol), at + " " + l.key + ": drawn from " + l.left.toFixed(2) + ", the sum says " + lo.toFixed(2)); assert.ok(near(l.right, hi, tol), at + " " + l.key + ": drawn to " + l.right.toFixed(2) + ", the sum says " + hi.toFixed(2)); }
        assert.ok(l.barH >= 9, at + " " + l.key + ": the bar has its height (" + l.barH + "px) — no other rule has reached it"); assert.ok(l.barW >= 1.5, at + " " + l.key + ": it is drawn, whatever its size"); }
      for (const l of L.filter((x) => x.kind === "part" && x.barW > 2.5)) assert.equal(l.colour, l.points > 0 ? "rgb(56, 224, 123)" : "rgb(255, 84, 112)", at + " " + l.key + ": " + (l.points > 0 ? "the up colour" : "the down colour")); const vix = L.find((l) => l.key === "vix"); assert.ok(vix, at + ": the VIX has its row"); if (r.want.vixAdd === 0) assert.ok(vix.barW <= 2.5 && vix.barW >= 1.5 && vix.colour === "rgb(232, 232, 240)", at + ": the VIX at nothing is a bar of no width in the neutral ink");
      assert.equal(L.some((l) => l.key === "cash"), !!r.want.cash, at + ": the bracket while cash is raised"); for (const l of L.filter((x) => x.kind === "part" || x.kind === "cash")) assert.equal(l.caption, r.lines.find((x) => x.key === l.key).text, at + ": the caption is the line — " + l.key); assert.equal(r.formula, r.lines[0].text); assert.ok(r.formula.includes("always in + ") && r.formula.endsWith("= " + r.number.toFixed(1) + "%")); assert.ok(!r.lines.some((x) => x.key === "lights"), at + ": the VIX's add is not said twice");
      assert.equal(r.lis, 1, at + ": one line of text above the picture"); assert.ok(r.scrollW <= w, at + ": no sideways scroll: " + r.scrollW); assert.ok(r.minFont >= 11, at + ": nothing under 11px: " + r.minFont);
      if (w > 700) { assert.equal(r.layout, "beside"); for (const l of L) { assert.ok(l.capRight <= l.laneLeft + 1, at + " " + l.key + ": the caption is to the left of its bar"); assert.ok(Math.abs((l.capTop + l.capBottom) / 2 - (l.laneTop + l.laneBottom) / 2) <= 6, at + " " + l.key + ": on the same row"); } }
      else { assert.equal(r.layout, "stacked"); for (const l of L) { assert.ok(l.capBottom <= l.laneTop + 1, at + " " + l.key + ": the caption is above its bar"); assert.ok(near(l.capLeft, l.laneLeft, 1.5) && l.capRight <= r.cardRight, at + " " + l.key + ": and wraps inside the card"); } for (let i = 1; i < L.length; i++) assert.ok(L[i].laneTop > L[i - 1].laneBottom, "the bars stack"); } };
    const now = await read(); assert.deepEqual(P.errors, []); assert.equal(now.pick, 0); check(now, w + " now"); assert.equal(now.green, "#38e07b"); assert.equal(now.red, "#ff5470"); assert.ok(now.lab.startsWith("How it gets to " + now.number.toFixed(1) + "%"));
    if (w === 1680) { assert.ok(now.cardBottom < now.chipsTop && now.chipsTop < h, "at 1680 the picture and the chips under it are on the first screen: chips at " + now.chipsTop); assert.ok(now.lvTop <= h + 40, "and the long version's fold is still at its foot: " + now.lvTop); }
    /* every chip: the picture is that move's own */ const moves = [-8, -5, -3, -1.5, 1.5, 3, 5]; let changed = 0; for (const mv of moves) { await page.locator(`#db1-root .chip[data-move="${mv}"]`).click(); await page.waitForTimeout(120); const r = await read(); assert.equal(r.pick, mv); check(r, w + " at " + mv + "%"); assert.ok(r.lab.includes("if SPY & QQQ move " + (mv > 0 ? "+" : "−") + Math.abs(mv) + "%"), "the heading names the move: " + r.lab); if (r.picReading !== now.picReading) changed++; }
    assert.ok(changed >= 4, "the picture moved with the chips: " + changed + " of 7 readings differ from now");
    /* back to now, then a new read: the picture is drawn again from it */ await page.locator('#db1-root .chip[data-move="0"]').click(); await page.waitForTimeout(120); await page.evaluate(() => { document.querySelector("#db1-root [data-how]").dataset.mark = "the drawing before the read"; }); const reads = await page.evaluate(() => window.DS1_LIVE.reads);
    await page.evaluate(() => window.DS1_LIVE.readNow()); await page.waitForFunction((n) => window.DS1_LIVE.reads > n && !window.DS1_LIVE.busy, reads, { timeout: 120000 }); await page.waitForTimeout(300); const again = await read(); assert.equal(await page.evaluate(() => document.querySelector("#db1-root [data-how]").dataset.mark || null), null, "a new read draws the picture again"); check(again, w + " after a new read");
    assert.deepEqual(P.errors, []); assert.equal(P.nonGet.blocked + P.nonGet.allowed, 0, "nothing but GETs");
  } finally { await P.close(); } } });
