/* DS1 tests (7 Oct 2026) — the deployment system: the engine's arithmetic (indicators, the reading in points, the pie, the levels, the
   reset tracker), the keep rule against its own numbers, the model file against the study file, the live module's clock and arithmetic
   (pure, then against the chart API), and the pages rendering headless at 1680 and 390 — the panel inside the tool, the stand-in page for
   the money panel's takeover, and the study page. Nothing here writes: every page test runs with non-GET requests blocked and counted. */
import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import { execFileSync } from "node:child_process"; import { pathToFileURL } from "node:url";
import { openPage, ROOT } from "./_harness.mjs";
import * as E from "../study/ds1/engine.mjs";
import { view, fetchDaily, fetchLive, baseline, loadAssumptions, ds1Shape, readWith, nyParts, phaseOf, readDue, SESSION, alignBars, withLive, sessionRanges, hygWithPayouts, quotePrice, nameState, ageWords, DAILY_BARS } from "../study/ds1/live.mjs";
const J = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, f), "utf8")), D = J("study/ds1/data/ds1.json"), LV = J("study/ds1/data/ds1-live.json"), M = LV.model, near = (a, b, tol) => Math.abs(a - b) <= tol;
const API = "https://scintilla-massive-chart-api.fly.dev", getApi = async (p) => { const r = await fetch(API + p, { headers: { Origin: "https://scintillahub.ai" }, signal: AbortSignal.timeout(60000) }); if (!r.ok) throw new Error(p.split("?")[0] + " " + r.status); return r.json(); };
const part = (k) => M.parts.find((p) => p.key === k);

test("1 · indicators: RSI, the averages and Williams %R on series whose answers are known", () => {
  const up = Array.from({ length: 40 }, (_, i) => 100 + i), R = E.rsi(up); assert.equal(R[13], null); assert.equal(R[14], 100); assert.equal(R[39], 100);
  const zig = Array.from({ length: 60 }, (_, i) => 100 + (i % 2 ? 1 : 0)); assert.ok(near(E.rsi(zig)[59], 50, 4), "an even zig-zag reads near 50");
  assert.equal(E.sma([1, 2, 3, 4], 2)[3], 3.5); assert.equal(E.sma([1, 2, 3, 4], 5)[3], null); assert.equal(E.ema([5, 5, 5], 3)[2], 5);
  const h = Array.from({ length: 20 }, () => 110), l = Array.from({ length: 20 }, () => 90); assert.equal(E.willr(h, l, h.map(() => 110))[19], -0); assert.equal(E.willr(h, l, h.map(() => 90))[19], -100); assert.equal(E.willr(h, l, h.map(() => 100))[19], -50); assert.equal(E.willr(h, l, h)[12], null);
  const v = Array.from({ length: 300 }, (_, i) => i); assert.ok(near(E.placeInYear(v, 299), 100, 1e-9)); assert.equal(E.placeInYear(v, 100), null, "under 200 sessions of history there is no place"); });

test("2 · the Geiger's daily rung is the Hub's own rule: trend from the fan's order, momentum from RSI on 23–77 and Williams %R on −90…−10 — and equals the Hub's replay code where that file is on this machine", async () => {
  const c = Array.from({ length: 260 }, (_, i) => 100 * 1.004 ** i), g = E.geigerDaily(c.map((x) => x * 1.001), c.map((x) => x * 0.999), c); assert.equal(g.trend[259], 1, "a steady climb puts all nine lines in rising order"); assert.equal(g.trend[150], null, "no trend before the 200-day exists"); assert.ok(g.mom[259] > 0.9);
  const d = c.slice().reverse(), gd = E.geigerDaily(d.map((x) => x * 1.001), d.map((x) => x * 0.999), d); assert.equal(gd.trend[259], -1); assert.ok(gd.mom[259] < -0.9);
  const hub = "/Users/alanharvey/SCINTILLA 0.5/_worktrees/gh1-geiger-history-20261006/deliverables/20260927/geiger-review/geiger-replay.mjs"; if (!fs.existsSync(hub)) return;   // the Hub's replay is not part of this repo
  const { rungReading } = await import(pathToFileURL(hub)), j = await getApi("/candles?symbol=QQQ&tf=D&limit=520"), bars = j.series.filter((b) => b.c != null), mine = E.geigerDaily(bars.map((b) => b.h), bars.map((b) => b.l), bars.map((b) => b.c));
  for (const k of [bars.length - 1, bars.length - 40, bars.length - 120]) { const r = rungReading(bars.slice(k + 1 - 230, k + 1)); assert.ok(near(mine.trend[k], r.trend, 1e-9), "trend " + k); assert.ok(near(mine.mom[k], r.momentum, 2e-3), "momentum " + k + ": " + mine.mom[k] + " vs " + r.momentum); } });

test("3 · a value's place and a curve's read: flat beyond the ends, straight lines between", () => {
  const q = Array.from({ length: 101 }, (_, i) => i * 2); assert.equal(E.placeOf(q, -5), 0); assert.equal(E.placeOf(q, 500), 100); assert.ok(near(E.placeOf(q, 51), 25.5, 1e-9));
  const a = E.FGRID.map((u) => u * 2); assert.equal(E.curveAt(a, -3), 0); assert.equal(E.curveAt(a, 300), 200); assert.ok(near(E.curveAt(a, 12.5), 25, 1e-9)); assert.equal(E.FGRID.length, 21); });

test("4 · the reading is 50 plus the points of the parts that vote: the points add exactly, a light is never added, a part without a reading does not vote", () => {
  const inp = Object.fromEntries(D.tonight.parts.concat(D.tonight.lights).map((p) => [p.key, p.value])), r = E.readSystem(inp, M);
  assert.ok(near(r.raw, r.base + r.parts.reduce((a, p) => a + p.points, 0), 0.11), "base + the voters' points = the reading before the 0–100 clamp"); assert.ok(near(r.reading, D.tonight.reading, 0.6), "the stored evening is reproduced: " + r.reading + " vs " + D.tonight.reading);
  assert.deepEqual(r.parts.map((p) => p.key), D.kept); assert.equal(r.lights.length, M.parts.length - D.kept.length); assert.ok(r.lights.some((l) => Math.abs(l.points) > 5), "the lights do carry points — they are shown, not added");
  const gone = E.readSystem({ ...inp, creditOwn: null }, M); assert.equal(gone.missing, 1); assert.ok(near(gone.raw, r.raw - r.parts.find((p) => p.key === "creditOwn").points, 0.11));
  assert.ok(near(r.families.reduce((a, f) => a + f.points, 0), r.parts.reduce((a, p) => a + p.points, 0), 1e-9)); assert.ok(near(r.base, 50, 3), "a typical evening reads about 50: " + r.base);
  const hot = E.readSystem({ ...inp, rsi: 90, creditOwn: -0.8 }, M), cold = E.readSystem({ ...inp, rsi: 20, creditOwn: 3 }, M); assert.equal(hot.reading, 0); assert.equal(cold.reading, 100, "the clamp holds at both ends"); });

test("5 · a light the user ticks is counted with exactly its own points, and unticking takes them back", () => {
  const inp = Object.fromEntries(D.tonight.parts.concat(D.tonight.lights).map((p) => [p.key, p.value])), plain = readWith(inp, M, {}), l = plain.lights.find((x) => x.key === "br50"), on = readWith(inp, M, { br50: true });
  assert.ok(near(on.raw, plain.raw + l.points, 0.11)); assert.ok(on.lights.find((x) => x.key === "br50").counted); assert.ok(near(readWith(inp, M, { br50: false }).raw, plain.raw, 1e-9)); });

test("6 · the index RSI's curve never rises as the RSI rises — so a calm dip (credit holding) cannot lower the reading", () => {
  const p = part("rsi"); let prev = Infinity; for (let z = 15; z <= 90; z += 0.5) { const v = E.voteOf(p, z, M.scale).vote; assert.ok(v <= prev + 1e-9, "RSI " + z); prev = v; }
  for (const d of D.dips) assert.ok(d.reading >= D.tonight.reading - 0.05, `a calm ${d.dipPct}% dip reads ${d.reading}, not under tonight's ${D.tonight.reading}`); assert.ok(D.dips.every((d, i) => i === 0 || d.reading >= D.dips[i - 1].reading - 0.05), "a deeper calm dip never reads lower");
  assert.deepEqual(D.dips.map((d) => d.dipPct), [1.5, 3, 5]); assert.ok(D.dips.every((d) => typeof d.readingIfCreditSellsToo === "number")); });

test("7 · each part votes only at the horizon it proved at: its other horizon's curves are flat zero", () => {
  for (const k of D.kept) { const p = part(k), v = D.verdicts.find((x) => x.key === k); assert.ok(p.vote); assert.deepEqual(p.horizons, v.horizons); for (const H of [20, 60]) { const used = v.horizons.includes(H), flat = p["gm" + H].every((x) => x === 0) && p["gp" + H].every((x) => x === 0); assert.equal(flat, !used, k + " at " + H); } }
  assert.deepEqual(part("rsi").horizons, [60]); assert.deepEqual(part("creditOwn").horizons, [20]); });

test("8 · the keep rule against its own numbers: a part votes only if it passes at 20 or 60 sessions out of sample, is not the wrong way at the other, and is never negative in the three other fits", () => {
  const BAR = D.keepRule.bar, passes = (t, H) => !t.flat && t.gapMed >= BAR[H].med && t.gapShare >= BAR[H].share && t.years > 0 && t.yearsRight > t.years / 2; assert.deepEqual(BAR, { 20: { med: 0.5, share: 3 }, 60: { med: 1, share: 3 } });
  assert.equal(D.verdicts.length, 15); const kept = [];
  for (const v of D.verdicts) { const p20 = passes(v.main[20], 20), p60 = passes(v.main[60], 60); let vote = false; if (p20 || p60) { const H = p20 ? 20 : 60, O = p20 ? 60 : 20; vote = !(v.main[O].gapMed < 0 && !(p20 && p60)) && Object.values(v.others).every((t) => t[H].gapMed >= 0); }
    assert.equal(v.verdict, vote ? "vote" : "light", v.key); assert.deepEqual(v.testedOnTopOf, kept.slice(), v.key + " was tried on top of the parts kept before it"); if (vote) kept.push(v.key); assert.ok(v.main[20].years >= 6 && v.main[60].years >= 6); }
  assert.deepEqual(kept, D.kept); assert.deepEqual(D.kept, ["rsi", "creditOwn"]); assert.deepEqual(LV.kept, D.kept);
  assert.equal(D.families.length, 6); assert.ok(D.families.every((f) => f.verdict === "light"), "asked as whole families, none would have voted either"); });

test("9 · the odds table reads unseen evenings and sorts them: the top band did better than the bottom band, and the bands cover every reading", () => {
  const O = D.oddsOOS; assert.equal(O[0].lo, 0); assert.equal(O.at(-1).hi, 100); for (let i = 1; i < O.length; i++) assert.equal(O[i].lo, O[i - 1].hi); assert.ok(O.every((b) => b.n >= 100), "no band rests on a handful of evenings");
  assert.ok(O.at(-1).share60 > O[0].share60 + 0.1 && O.at(-1).med60 > O[0].med60 + 2 && O.at(-1).share20 > O[0].share20 + 0.08); assert.ok(D.ranking.at60 > 0.1 && D.ranking.at20 > 0.05);
  assert.deepEqual(LV.model.odds, O); for (const r of [0, 19.9, 20, 50, 99.9, 100]) assert.ok(E.oddsAt(r, LV.model), "a band for " + r); assert.equal(E.oddsAt(0, LV.model).lo, 0); assert.equal(E.oddsAt(100, LV.model).hi, 100); });

test("10 · the pie: three kinds of money that add to 100, the core split by its rank weights, what is held filling a name's conviction slot first", () => {
  const A = E.DEFAULTS, P = E.pie(40, A, { nlv: 500000, positions: { MU: { shares: 50, price: 1000 }, NBIS: { shares: 100, price: 250 }, NVDA: { shares: 10, price: 200 } } });
  assert.ok(near(P.slices.reduce((a, s) => a + s.pct, 0), 100, 1e-9)); assert.ok(near(P.tactical, A.tacticalPct * 0.4, 1e-9)); assert.ok(near(P.invested, A.corePct + A.micronPct + A.nebiusPct + A.tacticalPct * 0.4, 1e-6));
  const s = (k) => P.slices.find((x) => x.key === k), tot = Object.values(A.coreWeights).reduce((a, b) => a + b, 0); assert.ok(near(s("NVDA:core").pct, (A.corePct * 3) / tot, 1e-9)); assert.ok(near(s("GOOGL:core").pct, (A.corePct * 1) / tot, 1e-9)); assert.ok(s("NVDA:core").pct > s("AMZN:core").pct && s("AMZN:core").pct > s("GOOGL:core").pct, "comps order: four ahead, Amazon in the middle, Alphabet last");
  assert.ok(near(s("MU:conviction").held, 10, 1e-9)); assert.equal(s("MU:core").held, 0, "Micron's 10% sits in its conviction slot; nothing spills to its core share"); assert.ok(near(s("NBIS:conviction").held, 5, 1e-9)); assert.equal(s("NBIS:conviction").toBuy, 0); assert.ok(near(s("NVDA:core").held, 0.4, 1e-9)); assert.ok(near(P.held, 15.4, 1e-6)); assert.ok(near(P.cashNow, 84.6, 1e-6));
  const big = E.pie(40, A, { nlv: 100000, positions: { MU: { shares: 30, price: 1000 } } }); assert.ok(near(big.slices.find((x) => x.key === "MU:conviction").held, 20, 1e-9)); assert.ok(near(big.slices.find((x) => x.key === "MU:core").held, big.slices.find((x) => x.key === "MU:core").pct, 0.006), "past its slot, Micron fills its core share"); assert.ok(big.extraHeld.MU > 0);
  assert.equal(E.pie(0, A).tactical, 0); assert.ok(near(E.pie(100, A).invested, 100, 1e-9)); const over = E.pie(100, { ...A, corePct: 70 }); assert.ok(near(over.invested, 100, 1e-9), "a shape over 100 gives up tactical first"); assert.equal(over.slices.find((x) => x.kind === "cash").pct, 0); });

test("11 · levels: the four averages and the nearest named pivots under the price, each mapped to QQQ and SPY through the name's beta", () => {
  const N = 260, c = Array.from({ length: N }, (_, i) => 100 + i * 0.2), o = { c, s21: E.sma(c, 21), s50: E.sma(c, 50), s100: E.sma(c, 100), s200: E.sma(c, 200) }, k = N - 1, price = c[k], idx = { spy: 780, qqq: 760, qqqLevels: { "21-day": 760 * (1 - 0.0263 / 2) } };
  const L = E.levelsFor("X", o, k, price, idx, [{ id: "A", level: price * 0.98 }, { id: "B", level: price * 0.9801 }, { id: "C", level: price * 0.5 }, { id: "D", level: price * 1.2 }, { id: "E", level: price * 0.9 }, { id: "F", level: price * 0.8 }, { id: "G", level: price * 0.7 }, { id: "H", level: price * 0.6 }], 2, 0.5);
  assert.ok(L.every((r, i) => i === 0 || r.level <= L[i - 1].level), "highest first"); assert.ok(L.find((r) => r.id === "A / B") || L.find((r) => r.id === "B / A"), "two lines at one level are one row"); assert.ok(!L.find((r) => r.id === "D"), "a line above the price is not an add level"); assert.equal(L.filter((r) => r.kind !== "average").length, 4, "the nearest four named pivots");
  const r = L.find((x) => x.id === "21-day"); assert.ok(near(r.awayPct, (o.s21[k] / price - 1) * 100, 1e-9)); assert.ok(near(r.qqqAt, 760 * (1 + r.awayPct / 2 / 100), 1e-6), "beta 2: the name's move is twice QQQ's"); assert.ok(near(r.spyAt, 780 * (1 + (r.awayPct / 2) * 0.5 / 100), 1e-6)); assert.equal(r.qqqNear, "21-day"); assert.deepEqual(Object.keys(E.BETA_QQQ).sort(), E.NAMES.slice().sort());
  assert.deepEqual(E.BETA_QQQ, { NVDA: 1.14, TSM: 1.54, AVGO: 1.45, MU: 3.11, GOOGL: 0.58, AMZN: 0.56, ORCL: 1.43, NBIS: 2.72, VST: 0.76 }, "the coordinator's 120-day betas to QQQ"); assert.deepEqual(E.CORE, ["NVDA", "AVGO", "TSM", "ORCL", "AMZN", "GOOGL"], "comps order"); });

test("12 · the reset tracker on a made-up leg: a push, a five-session cool-off, a new high — measured from the top of the leg, in history and now alike", () => {
  const c = []; for (let i = 0; i < 330; i++) c.push(100 + Math.sin(i / 9) * 2 + i * 0.01); for (let i = 0; i < 25; i++) c.push(c.at(-1) * 1.012); const top = c.length - 1; for (const x of [0.99, 0.97, 0.955, 0.95, 0.96, 0.97, 0.985]) c.push(c[top] * x); const mid = c.length - 1; c.push(c[top] * 1.01, c[top] * 1.02);
  const g = E.geigerDaily(c.map((x) => x * 1.002), c.map((x) => x * 0.998), c), o = { c, rsi: g.rsi, wr: g.wr, mom: g.mom, trend: g.trend }, dates = c.map((_, i) => "d" + i);
  assert.ok(E.isPush(o, top), "the last day of the run is a push: a 60-session high with a hot RSI"); const now = E.coolNow(o, dates, mid); assert.equal(now.push, "d" + top); assert.equal(now.sessions, 7); assert.ok(near(now.dipPct, -5, 1e-6)); assert.ok(now.lowRsi < o.rsi[top] - 10 && now.lowWr < -40, "the gauges cooled: RSI " + now.lowRsi + ", Williams " + now.lowWr); assert.equal(now.atHigh, false);
  const list = E.coolOffs(o, dates), last = list.at(-1); assert.equal(last.push, "d" + top); assert.equal(last.how, "resumed"); assert.equal(last.sessions, 7); assert.ok(near(last.dipPct, -5, 1e-6)); assert.ok(near(last.lowRsi, now.lowRsi, 1e-9), "history and the live read see the same low");
  const after = E.coolNow(o, dates, c.length - 1); assert.equal(after.atHigh, true, "back above its top: the leg's top moved to today");
  const u = { q25: 30, med: 45, q75: 55, start: 72 }; assert.equal(E.resetState(60, u).state, "not yet"); assert.equal(E.resetState(55, u).state, "cooled"); assert.equal(E.resetState(45, u).state, "fully reset"); assert.ok(near(E.resetState(58.5, u).done, 0.5, 1e-9)); assert.equal(E.resetState(null, u).state, "no measure");
  assert.match(nameState({ push: "d1", atHigh: true }, null, null).word, /AT ITS HIGH/); assert.match(nameState({ push: "d1", wr: -20, dipPct: -3, sessions: 4 }, { wr: u, dipPct: { q25: -9 } }, { wr: { state: "not yet" }, rsi: { state: "not yet" } }).word, /Williams not reset yet/); assert.match(nameState({ push: "d1", wr: -20, dipPct: -30, sessions: 40 }, { wr: { q75: -50 }, dipPct: { q25: -9 } }, { wr: { state: "fully reset" }, rsi: { state: "fully reset" } }).word, /FULLY RESET · turned back up · a deeper fall/); });

test("13 · each name's usual cool-off is its own where it has eight or more past cases, the pooled leaders' otherwise; the live window finds the same top as the full history", () => {
  for (const s of E.NAMES) { const u = LV.cool[s]; assert.ok(u && u.rsi.med != null && u.wr.med != null && u.mom.med != null, s); assert.ok(u.wr.q25 <= u.wr.med && u.wr.med <= u.wr.q75 && u.wr.q75 <= u.wr.start, s + " Williams marks in order"); assert.ok(u.rsi.q25 <= u.rsi.med && u.rsi.med <= u.rsi.q75 && u.rsi.q75 <= u.rsi.start, s + " RSI marks in order"); assert.ok(u.dipPct.med < 0 && u.sessions.med >= 5); if (!u.pooled) assert.ok(u.resumed >= 8, s); }
  assert.ok(LV.cool.NBIS.pooled, "Nebius has too little history of its own"); assert.ok(!LV.cool.NVDA.pooled && !LV.cool.MU.pooled && !LV.cool.TSM.pooled);
  for (const [s, [full, win, d1, d2]] of Object.entries(D.coolWindow)) { assert.equal(full, win, s + " top date"); assert.equal(d1, d2, s + " deepest dip"); }
  for (const [k, [a, b]] of Object.entries(D.windowCheck)) assert.ok(near(a, b, 0.002), k + ": the 540-bar window reads the full history's number"); assert.ok(DAILY_BARS >= E.PUSH.hotYears + E.PUSH.lookBack + 30, "the live window holds the look-back and the hot mark's year"); });

test("14 · the stretched end: a rule is called a two-thirds call only if the trade paid two times in three on both halves of history with a dozen cases in each — none is", () => {
  const any = D.trim.find((t) => t.key === "any"); assert.ok(near(any.all.paid, 0.5, 0.03), "on any evening the trade is a coin flip: " + any.all.paid); assert.ok(D.trim.length >= 14);
  for (const t of D.trim) { const want = t.key !== "any" && t.to2017.n >= 12 && t.from2018.n >= 12 && t.to2017.paid >= 2 / 3 && t.from2018.paid >= 2 / 3; assert.equal(!!t.twoThirds, want, t.key); assert.ok(t.all.n >= t.to2017.n && t.all.n <= t.to2017.n + t.from2018.n + 1, t.key + ": the halves make the whole"); }
  assert.equal(D.trim.filter((t) => t.twoThirds).length, 0); assert.ok(D.trim.find((t) => t.key === "narrow").addedAfterFirstRun, "the rule added after the first run says so");
  assert.deepEqual(E.STRETCH.map((r) => r.key), D.trim.filter((t) => !["any", "readingLow"].includes(t.key)).map((t) => t.key), "the build scores the same rules the page lights up");
  for (const s of E.CORE.concat(["MU"])) assert.ok(D.nameTrims[s].n >= 30 && D.nameTrims[s].paid < 2 / 3, s + ": trimming a leader at a push was not a two-thirds call either"); });

test("15 · credit: the coordinator's 18 washouts are reproduced on the price-only series; both directions are measured; a rates-led dip is told from a credit scare", () => {
  const C = D.credit; assert.equal(C.washoutPriceOnlyUnder22.n, 18); assert.ok(near(C.lowLately.priceOnly.rsi, 17.3, 0.15), "price-only, HYG's RSI bottomed at 17.3 on 1 Oct"); assert.equal(C.lowLately.priceOnly.date, "2026-10-01"); assert.ok(C.lowLately.withPayouts.rsi > C.lowLately.priceOnly.rsi, "with the payout added back the low is shallower");
  assert.ok(C.washoutPriceOnlyUnder22.spyShare20 > C.anyDay.spyShare20 && Math.abs(C.washoutPriceOnlyUnder22.spyShare60 - C.anyDay.spyShare60) < 0.05, "better at 20 sessions, the same as any day at 60");
  assert.equal(C.hygBands.length, 7); assert.ok(C.hygBands[0].share20 > C.hygBands[2].share20 + 0.1, "washed out (RSI under 25) beat the soft band (30–40) at 20 sessions"); assert.ok(C.hygBands[2].share20 < C.anyDay.share20 - 0.05, "the soft band was worse than any day");
  assert.equal(C.ratesLed.n + C.creditLed.n, C.washoutWithPayoutsUnder30.n); assert.ok(C.ratesLed.n <= 8, "the rates-led cases are few, and the page says how few"); assert.equal(C.lowLately.withPayouts.ledBy, "rates");
  assert.ok(C.spread.proxyCheck.withRatesTakenOut < -0.8 && C.spread.proxyCheck.withRatesTakenOut < C.spread.proxyCheck.rawHyg, "taking the rates leg out makes HYG follow FRED's spread more closely"); assert.equal(C.spread.series, "FRED BAMLH0A0HYM2"); assert.ok(near(C.spread.rows.find((r) => r[0] === "2026-10-01")[1], 3.24, 1e-9)); assert.ok(near(C.spread.last[1], 3.12, 1e-9));
  const ep = C.thisEpisode[0]; assert.ok(near(ep.ratesLegPct + ep.creditOwnPct, ep.hygPct, 0.011), "the rates leg and credit's own move add back to HYG's move"); });

test("16 · the VIX as it trades: a touch and a close are counted apart, every evening is in exactly one group", () => {
  for (const k of ["at80", "at90"]) { const v = D.vixTouch[k]; assert.ok(v.touchOnly.evenings > 100 && v.closeConfirmed.evenings > 300); assert.ok(v.closeConfirmed.med20 > v.neither.med20, k + ": a close above did better than a calm evening"); }
  assert.ok(D.vixTouch.at80.touchOnly.evenings + D.vixTouch.at80.closeConfirmed.evenings + D.vixTouch.at80.neither.evenings === D.vixTouch.at90.touchOnly.evenings + D.vixTouch.at90.closeConfirmed.evenings + D.vixTouch.at90.neither.evenings);
  assert.ok(near(D.vixTouch.now.p80, 19.85, 0.3) && near(D.vixTouch.now.p90, 23.56, 0.4), "Alan's 20 and 23 are still the year's 80th and 90th percentiles"); });

test("17 · the clock: every minute while New York is open, every five minutes around it, once more after the close, never on a weekend", () => {
  const at = (iso) => nyParts(new Date(iso)), open = at("2026-10-07T15:00:00Z"); assert.equal(open.date, "2026-10-07"); assert.equal(open.minutes, 11 * 60); assert.equal(phaseOf(open), "open"); assert.equal(phaseOf(at("2026-10-07T12:00:00Z")), "pre-market"); assert.equal(phaseOf(at("2026-10-07T21:00:00Z")), "after hours"); assert.equal(phaseOf(at("2026-10-08T03:00:00Z")), "closed"); assert.equal(phaseOf(at("2026-10-10T15:00:00Z")), "closed");
  assert.equal(readDue(open, null), true); assert.equal(readDue(at("2026-10-07T15:00:59Z"), open), false); assert.equal(readDue(at("2026-10-07T15:01:00Z"), open), true); assert.equal(readDue(at("2026-10-07T13:30:05Z"), at("2026-10-07T13:29:30Z")), true, "the open itself is a read");
  const pre = at("2026-10-07T12:00:00Z"); assert.equal(readDue(at("2026-10-07T12:04:00Z"), pre), false); assert.equal(readDue(at("2026-10-07T12:05:00Z"), pre), true); assert.equal(readDue(at("2026-10-07T20:10:10Z"), at("2026-10-07T20:09:00Z")), true, "once more from 16:10 for the settled bars"); assert.equal(readDue(at("2026-10-10T15:00:00Z"), open), false);
  assert.equal(SESSION.openEverySec, 60); assert.match(ageWords({ readAt: open }, open.ms + 37000), /37 s old/); assert.match(ageWords({ readAt: open }, open.ms + 600000), /10 min old/); assert.equal(ageWords({}), "no reading yet"); });

test("18 · live prices to one more bar: a quote becomes today's bar, a missing quote keeps the last close and is named, the session's own high and low come from the 30-minute bars, HYG's payouts are added back", () => {
  const day0 = Date.UTC(2026, 9, 5), mk = (c) => ({ series: [0, 1].map((d) => ({ t: day0 + d * 864e5, c: c + d, h: c + d + 1, l: c + d - 1 })) }), candles = Object.fromEntries(E.ALL_SYMBOLS.map((s, i) => [s, mk(100 + i)])); delete candles.VST;
  const S0 = alignBars(candles); assert.deepEqual(S0.dates, ["2026-10-05", "2026-10-06"]); assert.deepEqual(S0.absent, ["VST"]); assert.equal(S0.bars.VST, null);
  const quotes = Object.fromEntries(E.ALL_SYMBOLS.filter((s) => s !== "VIX" && s !== "NBIS").map((s) => [s, { price: 200, price_session_et: "2026-10-07", today_session_close_state: "ABSENT" }])), macro = { VIX: { quote: { price: 16, day_high: 17, day_low: 15, session_et: "2026-10-07" } } };
  const L = withLive(S0, quotes, macro, { SPY: { hi: 205, lo: 195 } }); assert.equal(L.live, true); assert.equal(L.session, "2026-10-07"); assert.deepEqual(L.missing, ["NBIS"]); assert.equal(L.S.bars.NBIS.c.at(-1), S0.bars.NBIS.c.at(-1)); assert.equal(L.S.bars.SPY.h.at(-1), 205); assert.equal(L.S.bars.SPY.l.at(-1), 195); assert.equal(L.S.bars.VIX.h.at(-1), 17); assert.equal(L.S.bars.QQQ.h.at(-1), 200, "no range served: the price alone"); assert.ok(L.noRange.includes("QQQ"));
  assert.equal(withLive(S0, { SPY: { price: 200, price_session_et: "2026-10-06" } }, macro).live, false, "a quote for a session the bars already hold adds nothing"); assert.equal(quotePrice({ price: 5, today_session_close: 6, today_session_close_state: "SETTLED" }), 6); assert.equal(quotePrice({ price: 5, today_session_close_state: "ABSENT" }), 5);
  const r = sessionRanges({ SPY: { series: [{ t: Date.UTC(2026, 9, 7, 13, 0), h: 999, l: 1 }, { t: Date.UTC(2026, 9, 7, 13, 30), h: 10, l: 8 }, { t: Date.UTC(2026, 9, 7, 19, 30), h: 12, l: 9 }, { t: Date.UTC(2026, 9, 7, 20, 0), h: 999, l: 1 }, { t: Date.UTC(2026, 9, 6, 15, 0), h: 999, l: 1 }] } }, "2026-10-07"); assert.deepEqual(r.SPY, { hi: 12, lo: 8 }, "09:30 to 16:00 New York only, this session only");
  const h = hygWithPayouts(["a", "b", "c"], [100, 99, 99], [["b", 1]]); assert.ok(near(h.tr[1], 100, 1e-9), "an ex-payout drop of the payout's size is no loss"); assert.equal(h.estimated, 0); });

test("19 · the assumptions: every one has a baseline, a saved value overrides it, a broken save falls back", () => {
  /* AL9 re-pin (7 Oct): the dials are the chain's — the held part where the three fixed slots were, no average over days (tests/al9.test.mjs 13 holds the new ones). DS1's own pie is fed the same held part split at the baseline conviction share. */
  const B = baseline(LV), SH = ds1Shape(B); assert.ok(near(SH.corePct + SH.micronPct + SH.nebiusPct + B.tacticalPct, 100, 1e-9), "the baseline shape is fully invested at a reading of 100"); assert.equal(B.heldPct + B.tacticalPct, 100); assert.equal("lineEvenings" in B, false); assert.deepEqual(B.dips, [1.5, 3, 5]); assert.equal(B.dipCredit, 0); assert.deepEqual(B.shares, { MU: 50, NBIS: 70 }); assert.ok(B.cash > 400000); assert.deepEqual(B.beta, E.BETA_QQQ);
  const mem = (v) => ({ getItem: () => v, setItem() {} }); assert.equal(loadAssumptions(LV, mem(JSON.stringify({ heldPct: 60, shares: { NVDA: 5 } }))).heldPct, 60); assert.deepEqual(loadAssumptions(LV, mem(JSON.stringify({ shares: { NVDA: 5 } }))).shares, { MU: 50, NBIS: 70, NVDA: 5 }); assert.deepEqual(loadAssumptions(LV, mem("{not json")), B); assert.deepEqual(loadAssumptions(LV, null), B); });

test("20 · the live reading, taken from the chart API the way the page takes it: every part read, the pie adds up, a calm dip never lowers the reading, every name carries its levels and its tracker", async () => {
  const A = baseline(LV), candles = await fetchDaily(getApi), live = await fetchLive(getApi), v = view({ base: LV, candles, ...live, A });
  assert.ok(v.reading.reading >= 0 && v.reading.reading <= 100); assert.equal(v.reading.parts.length, 2); assert.equal(v.reading.lights.length, 13); assert.equal(v.reading.missing, 0, "both voters have a reading"); assert.ok(v.session >= LV.asOf); assert.deepEqual(v.absent, []);
  assert.ok(near(v.pie.slices.reduce((a, s) => a + s.pct, 0), 100, 1e-6)); assert.ok(near(v.pie.tactical, (A.tacticalPct * v.deployed) / 100, 0.011)); assert.ok(near(v.deployed, v.reading.reading, 1e-9), "the baseline deploys this minute's own reading"); assert.ok(v.account.nlv > 400000 && v.pie.held > 5 && v.pie.held < 40);
  assert.equal(v.dips.length, 3); for (const d of v.dips) { assert.ok(d.readingCalm >= v.reading.reading - 0.05, `a calm ${d.dipPct}% dip reads ${d.readingCalm} against ${v.reading.reading} now`); assert.equal(d.reading, d.readingCalm); assert.ok(near(d.spy, v.idx.spy * (1 - d.dipPct / 100), 1e-6)); assert.ok(d.pie.tactical >= v.pie.tactical - 0.02); }
  assert.equal(v.names.length, 9); for (const n of v.names) { assert.ok(!n.absent, n.sym); assert.ok(n.levels.filter((l) => l.kind === "average").length === 4, n.sym + " has its four averages"); assert.ok(n.usual && n.st, n.sym + " has its usual cool-off"); assert.ok(typeof n.state.word === "string" && n.state.word.length > 3); for (const l of n.levels.filter((x) => x.below)) assert.ok(near(l.qqqAt, v.idx.qqq * (1 + l.awayPct / n.beta / 100), 1e-6), n.sym + " " + l.id); }
  assert.ok(v.names.find((n) => n.sym === "NVDA").hasLines && !v.names.find((n) => n.sym === "TSM").hasLines, "TSMC has no named pivots stored, and the page says so");
  const on = view({ base: LV, candles, ...live, A: { ...A, count: { br50: true } } }), l = v.reading.lights.find((x) => x.key === "br50"); assert.ok(near(on.reading.raw, v.reading.raw + l.points, 0.11)); assert.equal(typeof v.stretch.rsi70, "boolean"); assert.ok(v.odds && v.odds.n > 100); });

/* AL9 re-pin (7 Oct): the money panel at the top is now AL9's panel (the number, its history, the pies, room to play — tests/al9.test.mjs 15),
   drawn into the host this module hands over; DS1's own pie, slice table and dip bars are not drawn there any more. The words on screen
   changed to plain ones (Alan: "I don't know what an evening is"): the reading is "the market reading", an evening is a day, "votes" is
   "counted". The dial tried is the held part (the three fixed slots are gone). Everything else this test held, it still holds. */
test("21 · the tool: the reading sits under the ladder in step 2 and the pie in the money panel at the top, live, at 1680 and 390 — no error, no write, no sideways scroll, no text under 11px; a ticked light, a changed assumption and a failed read each do what the page says", async () => {
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h }); try { const { page } = P;
    await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view, null, { timeout: 120000 }); await page.waitForTimeout(1200);
    const read = () => page.evaluate(() => { const root = document.getElementById("ds1-root"), el = document.getElementById("ds1live"), host = document.getElementById("ds1money-host"), st = window.DS1_LIVE, pol = document.getElementById("policy"), q = (s2) => document.querySelectorAll(s2), leaves = [...q("#ds1live *, #ds1money-host *")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg"));
      return { has: !!root, reading: +root.dataset.reading, invested: +root.dataset.invested, held: +root.dataset.held, live: root.dataset.live, after: pol.nextElementSibling === el, samePanel: pol.closest(".panel") === el.closest(".panel"), reads: st.reads, error: st.error, parts: q("#ds1live .pt").length, votes: [...q('#ds1live .pt[data-vote="1"]')].map((e) => e.dataset.part), names: [...q("#ds1live .nc")].map((e) => e.dataset.name), slices: q("#ds1money-host [data-room]").length, a9: !!document.getElementById("a9-root"), panelError: st.panelError || null, pieInStep2: q("#ds1live #ds1money").length, dips: [...q("#ds1live .dipline span")].map((e) => +e.dataset.reading), rules: q("#ds1live .rule").length, br50: +document.querySelector('#ds1live .pt[data-part="br50"]').dataset.points, age: document.getElementById("ds1-age").textContent, text: el.innerText + "\n" + host.innerText, hasOld: !!document.getElementById("dm2live") || !!window.DM2_LIVE || !!document.getElementById("scenbars") || q(".a8-scen").length > 0,
        panel: { id: host.closest(".panel").id, first: document.querySelector(".grid > .panel") === host.closest(".panel"), folded: host.closest(".panel").classList.contains("folded"), h2: host.closest(".panel").querySelector("h2").innerText, asmOpen: document.querySelector("#ds1money-host details.asm").open }, spine: typeof SPINE !== "undefined" && SPINE.deployment_scenarios, scrollW: document.scrollingElement.scrollWidth, minFont: Math.min(...leaves.map((e) => parseFloat(getComputedStyle(e).fontSize))), policyText: pol.innerText.slice(0, 60) }; });
    const r = await read(); assert.deepEqual(P.errors, []); assert.ok(r.has && r.after && r.samePanel, "the reading is the ladder's next sibling, in step 2"); assert.equal(r.error, null); assert.equal(r.hasOld, false, "neither the matrix's line nor the five-market bars are mounted"); assert.match(r.policyText, /THE LADDER/, "the ladder is untouched");
    assert.equal(r.panel.id, "p-scen"); assert.ok(r.panel.first && !r.panel.folded, "the pie is the first panel of the page, open as it loads"); assert.match(r.panel.h2, /^THE MONEY — the number, how it splits, how much room is left/); assert.ok(r.a9 && r.panelError === null, "AL9's panel is drawn into the host"); assert.equal(r.pieInStep2, 0, "nothing of the money panel is drawn in step 2"); assert.equal(r.panel.asmOpen, false, "the assumptions fold under the pie, one click away");
    assert.equal(r.spine.mode, "LIVE"); assert.match(r.spine.note, /the number on live prices — \d+% invested, the market reading \d+ of 100/, "the sources line says what the money panel read");
    assert.ok(r.reading >= 0 && r.reading <= 100); assert.equal(r.parts, 15); assert.deepEqual(r.votes, D.kept); assert.deepEqual(r.names, E.NAMES); assert.equal(r.slices, 9, "eight names and the account in room to play"); assert.equal(r.dips.length, 3); assert.ok(r.dips.every((d) => d >= r.reading - 0.05), "no calm dip reads under now"); assert.ok(r.rules >= 13); assert.match(r.age, /^read \d\d:\d\d:\d\d New York · \d+ s old$/);
    for (const s of ["THE MARKET READING, LIVE", "THE MARKET READING · 0 STRETCHED · 100 WASHED OUT", "WHAT MAKES THE MARKET READING, IN POINTS", "SPY AND QQQ TOGETHER", "THE VIX AS IT TRADES", "BREADTH", "CREDIT", "THE LEADERS' OWN STATE", "THE NUMBER", "4 · INSIDE CONVICTION", "5 · INSIDE THE CORE", "tactical — moves with the market", "WHAT A FURTHER DIP WOULD REACH", "ASSUMPTIONS", "LEVELS AND THE RESET TRACKER", "Williams", "QQQ at", "THE STRETCHED END", "any day", "New York"]) assert.ok(r.text.includes(s), s);
    assert.ok(r.scrollW <= w, "no sideways scroll: " + r.scrollW); assert.ok(r.minFont >= 11, "no text under 11px: " + r.minFont);
    /* a light, ticked: the reading moves by exactly that light's points (inside the 0–100 clamp) */
    await page.evaluate(() => { const p = document.getElementById("ds1live").closest(".panel"); if (p.classList.contains("folded")) { const b = p.querySelector(".pfold"); if (b) b.click(); } }); await page.locator('#ds1live input[data-count="br50"]').check(); await page.waitForTimeout(250);
    const t = await read(); assert.ok(near(t.reading, Math.max(0, Math.min(100, r.reading + r.br50)), 0.25), `ticking breadth moved ${r.reading} to ${t.reading} (its points ${r.br50})`); await page.locator('#ds1live input[data-count="br50"]').uncheck(); await page.waitForTimeout(250); assert.ok(near((await read()).reading, r.reading, 0.11));
    /* an assumption, changed: the shape follows, and the fold the user opened stays open through the redraw; the baseline button takes it back */
    await page.locator("#ds1money-host details.asm > summary").click(); await page.waitForTimeout(150); await page.locator('#ds1money-host input[data-in="heldPct"]').fill("55"); await page.locator('#ds1money-host input[data-in="heldPct"]').dispatchEvent("change"); await page.waitForTimeout(250); const c = await read(); assert.ok(near(c.invested, r.invested - 15, 0.2), `the held part 70 → 55 took the shape from ${r.invested} to ${c.invested}`); assert.equal(c.panel.asmOpen, true, "the opened fold stayed open");
    await page.locator("#ds1money-host button[data-reset]").click(); await page.waitForTimeout(250); assert.ok(near((await read()).invested, r.invested, 0.2));
    /* the liveness rule: a read that fails leaves the last reading on screen, with its cause; the age keeps ticking */
    await page.route("**/quotes*", (rt) => rt.abort()); await page.evaluate(() => window.DS1_LIVE.readNow()); await page.waitForTimeout(600); const f = await read(); assert.ok(f.error, "the failed try is recorded"); assert.equal(f.reads, r.reads, "no new reading was counted"); assert.ok(near(f.reading, r.reading, 0.11), "the last reading is still on screen"); assert.match(f.text, /last try failed/); assert.equal(f.parts, 15); assert.equal(f.slices, 9, "the panel is still drawn");
    await page.waitForTimeout(2100); const later = await read(); assert.notEqual(later.age, f.age, "the age ticks while nothing new arrives");
    await page.unroute("**/quotes*"); await page.evaluate(() => window.DS1_LIVE.readNow()); await page.waitForTimeout(400); const back = await read(); assert.equal(back.error, null); assert.equal(back.reads, r.reads + 1); assert.ok(!/last try failed/.test(back.text));
    assert.equal(P.nonGet.blocked + P.nonGet.allowed, 0, "no write of any kind");
  } finally { await P.close(); } } });

test("22 · where the page carries the money panel (AL8's #scenbars), the pie is drawn there and AL8's own renderer finds nothing to draw into — without a line of AL8's code changed", async () => {
  const P = await openPage({ width: 1680, height: 1050, path: "study/ds1/seam-check.html" }); try { await P.page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && window.SEAM_AL8_DREW !== undefined, null, { timeout: 120000 });
    const r = await P.page.evaluate(() => ({ scen: !!document.getElementById("scenbars"), host: document.getElementById("ds1money-host"), inHost: !!document.querySelector("#ds1money-host #ds1money .pie"), inSlot: !!document.querySelector("#ds1live #ds1money"), slotHasReading: !!document.querySelector("#ds1live .big .n"), h2: document.querySelector("#ds1money-host").closest(".panel").querySelector("h2").innerText, drew: window.SEAM_AL8_DREW, fold: !!document.querySelector("#ds1money-host").closest(".panel").querySelector("h2 .pfold"), slices: document.querySelectorAll("#ds1money-host tr[data-slice]").length }));
    assert.deepEqual(P.errors, []); assert.equal(r.scen, false, "the id AL8's renderer looks for is gone"); assert.equal(r.drew, false, "AL8's renderer drew nothing"); assert.ok(r.inHost && !r.inSlot && r.slotHasReading, "the pie is in the money panel, the reading stays in step 2"); assert.match(r.h2, /THE MONEY — the pie today and on a dip/); assert.ok(r.fold, "the panel's own fold button is kept"); assert.equal(r.slices, 11); assert.equal(P.nonGet.blocked + P.nonGet.allowed, 0);
  } finally { await P.close(); } });

test("23 · the study page renders headless at 1680 and 390: ready, no error, no write, no sideways scroll, no text under 11px, its numbers on screen", async () => {
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h, path: "study/ds1/DS1.html" }); try {
    await P.page.waitForFunction(() => window.DS1_PAGE_READY === true, null, { timeout: 120000 }); await P.page.waitForFunction(() => [...document.querySelectorAll("img")].every((i) => i.complete), null, { timeout: 60000 });
    const r = await P.page.evaluate(() => { const els = [...document.querySelectorAll("body *")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg")), q = (s) => document.querySelectorAll(s).length;
      return { scrollW: document.scrollingElement.scrollWidth, minFont: Math.min(...els.map((e) => parseFloat(getComputedStyle(e).fontSize))), panels: q("section.panel[id]"), parts: q("#parts tbody tr"), trim: q("#trim tbody tr"), odds: q("#odds tbody tr"), names: q("#cool tbody tr"), dec: q("#dec li"), wrong: q("#wrong li"), imgs: [...document.querySelectorAll("#shots img")].map((i) => i.naturalWidth > 0), tiles: document.getElementById("tiles").innerText, specs: q("details.sc-pagespecs"), text: document.body.innerText }; });
    assert.deepEqual(P.errors, []); assert.equal(P.nonGet.blocked + P.nonGet.allowed, 0); assert.ok(r.scrollW <= w, "no sideways scroll: " + r.scrollW); assert.ok(r.minFont >= 11, "no text under 11px: " + r.minFont);
    assert.ok(r.panels >= 9); assert.equal(r.parts, 15); assert.equal(r.trim, D.trim.length); assert.equal(r.odds, D.oddsOOS.length + 1); assert.equal(r.names, 9); assert.ok(r.dec >= 1 && r.dec <= 3, "at most three decisions"); assert.ok(r.wrong >= 8); assert.equal(r.specs, 1); assert.ok(r.imgs.length >= 4 && r.imgs.every(Boolean), "the pictures of the tool load");
    assert.ok(r.tiles.includes(String(Math.round(D.tonight.reading)))); const low = r.text.toLowerCase(); for (const s of ["earned a vote", "light", "two times in three", "rates-led", "its usual cool-off", "what could be wrong", "what was not done", "decisions for alan"]) assert.ok(low.includes(s), s);
  } finally { await P.close(); } } });

test("24 · index.html: the deployment system is wired in once — the reading under the ladder, the pie in the money panel — the matrix's line and its hand-over are gone, the five-market bars' code is left unused, and no key is in any committed file of this study", () => {
  const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8"), code = html.replace(/<!--[\s\S]*?-->/g, "").replace(/\/\*[\s\S]*?\*\//g, "");
  assert.equal((code.match(/id="ds1live"/g) || []).length, 1); assert.equal((code.match(/id="ds1money-host"/g) || []).length, 1); assert.equal((code.match(/startDeploymentSystem\(/g) || []).length, 1); assert.match(code, /import \{ startDeploymentSystem \} from "\.\/study\/ds1\/live\.mjs";/); assert.match(code, /moneyEl: ds1Money/);
  assert.ok(code.indexOf('id="ds1money-host"') < code.indexOf('id="brief"') && code.indexOf('id="policy"') < code.indexOf('id="ds1live"'), "the pie above THE BRIEF, the reading after the ladder");
  assert.ok(!/id="dm2live"|startLiveMatrix|fiveMarkets|dm2Markets|id="scenbars"/.test(code), "the matrix's slot, its script, its hand-over to the money panel and the bars' host are gone together");
  assert.match(code, /function renderScen\(\)/, "the code that drew the five-market bars is still in the page, unused — listed for removal, not removed"); assert.match(code, /window\.setDeployLive=function\(v\)\{/); assert.match(code, /const DEPLOY_SOURCES=\[\];/, "and no scenario file feeds anything");
  /* against the release this branch started from, when that commit is here: a few dozen lines at most, every one of them this block's */
  let base = null; try { base = execFileSync("git", ["-C", ROOT, "rev-parse", "--verify", "-q", "42b3dab^{commit}"], { encoding: "utf8" }).trim(); } catch (e) { base = null; }
  /* AL9 re-pin (7 Oct): the two commits are compared with each other (DS1's own 832240d against the release), not the release against whatever the file is now — AL9's panel and its plain-words pass changed more lines, and tests/al9.test.mjs 16 holds those */
  let own = null; try { own = execFileSync("git", ["-C", ROOT, "rev-parse", "--verify", "-q", "832240d^{commit}"], { encoding: "utf8" }).trim(); } catch (e) { own = null; }
  if (base && own) { const lines = execFileSync("git", ["-C", ROOT, "diff", "-U0", base, own, "--", "index.html"], { encoding: "utf8" }).split("\n").filter((l) => /^[+-]/.test(l) && !/^(\+\+\+|---)/.test(l)); assert.ok(lines.length > 0 && lines.length <= 40, "a few dozen changed lines at most: " + lines.length);
    for (const l of lines) assert.ok(/ds1|DS1|dm2|DM2|deployment system|deployment engine|matrix|MONEY|scenbars|held inside|engine's own file|<script type="module">|<\/script>|catch\(/i.test(l), "a changed line that is not this block's: " + l.slice(0, 90)); }
  for (const f of ["study/ds1/engine.mjs", "study/ds1/live.mjs", "study/ds1/DS1.html", "study/ds1/seam-check.html", "scripts/ds1-build.mjs", "scripts/ds1-pull.mjs", "scripts/ds1-live-check.mjs", "scripts/ds1-shots.mjs", "study/ds1/data/ds1.json", "study/ds1/data/ds1-live.json"]) { const t = fs.readFileSync(path.join(ROOT, f), "utf8"); assert.ok(!/apikey=[A-Za-z0-9]{10,}/.test(t) && !/eyJ[A-Za-z0-9_-]{20,}\./.test(t) && !/Bearer\s+[A-Za-z0-9._-]{20,}/.test(t), "no key in " + f); }
  for (const f of fs.readdirSync(path.join(ROOT, "study/ds1/pictures"))) assert.ok(/\.png$/.test(f)); assert.ok(fs.readdirSync(path.join(ROOT, "study/ds1/pictures")).length >= 12); });
