/* DS2 tests (7 Oct 2026) — the % invested number at lows and tops.
   What they hold: the study's lab is the deployment study's lab; version 2's arithmetic (one file for the study, the tool, the history
   and the pane's proof); the scorecard and its pass rule as stored; the dates Alan named, before and after; the stored history and the
   tool's short window against the full history; the two dials (Micron 60 / Nebius 40, Oracle a dollar-cost starter); the pane's
   version 2 script — its numbers, its budget, its plain words, a replay of it against the tool's sum on every day, a second witness
   made by machine, and version 1 exactly when both switches are off; the installer's task; the page for Alan.
   Nothing here writes. Two tests read the chart API (skipped if it does not answer) and three open one headless page each, one at a time. */
import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
import * as E from "../study/ds1/engine.mjs"; import * as N from "../study/ds2/number.mjs"; import * as C from "../study/al9/chain.mjs";
import { view, fetchDaily, fetchLive, baseline, v2Rules, STORE } from "../study/ds1/live.mjs"; import { explain, makeReadAt } from "../study/al9/panel.mjs";
import { parsePine2, replay2, labelOf2, labelsOf2, offHigh, overAvg } from "../study/ds2/pane-replay.mjs"; import { parsePine, replay as replay1 } from "../study/pn1/pine-replay.mjs"; import { runFromText2 } from "../study/pn1/pine-transliterate.mjs";
import { buildPine2, blockOf, stretches } from "../scripts/ds2-build-pine.mjs"; import { engineV2On, scriptV2On, seriesOf, codeHash, codeOf } from "../scripts/ds2-prove-pane.mjs"; import { checkSaved2 } from "../scripts/ds2-check-saved.mjs";
import { openPage } from "./_harness.mjs";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), J = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, f), "utf8")), T = (f) => fs.readFileSync(path.join(ROOT, f), "utf8"), near = (a, b, tol) => Math.abs(a - b) <= tol;
const S = J("study/ds2/data/ds2.json"), LIVE = J("study/ds2/data/ds2-live.json"), R = LIVE.rules, LV = J("study/ds1/data/ds1-live.json"), LV2 = { ...LV, v2: LIVE }, D1 = J("study/ds1/data/ds1.json"), H = J("study/al9/data/history.json"), F = J("tests/fixtures/pn1-closes-20261006.json"), P = J("study/ds2/data/ds2-pane-proof.json");
const SRC = T("study/pn1/SCINTILLA-DEPLOYMENT-PANE.v2.pine")   /* DS3 (8 Oct): the installer's path now holds version 3; these tests are about version 2, kept beside it byte for byte */, SRC1 = T("study/pn1/SCINTILLA-DEPLOYMENT-PANE.v1.pine"), K = parsePine2(SRC), CODE = codeOf(SRC), STRINGS = [...CODE.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => m[1]);
const ix = Object.fromEntries(F.dates.map((d, i) => [d, i])), LAST = F.dates.length - 1, cand = (k) => S.candidates.find((c) => c.key === k), BANNED = /\bevenings?\b|\brungs?\b|\bv1\b|\bv2\b|line vs reading|\bDS\d\b|\bAL\d\b|\bPN\d\b|\ba2f?\b|\bd2L\b/;
let ENG, SAME; const sides = () => { ENG ??= engineV2On(F, LV.model, R); SAME ??= scriptV2On(K, F, F.hygWithPayouts); return { eng: ENG, same: SAME }; };
const API = "https://scintilla-massive-chart-api.fly.dev", getApi = async (p) => { const r = await fetch(API + p, { headers: { Origin: "https://scintillahub.ai" }, signal: AbortSignal.timeout(60000) }); if (!r.ok) throw new Error(p.split("?")[0] + " " + r.status); return r.json(); };

test("1 · the lab is the deployment study's lab: the same model to the last digit and the same replay — as the build recorded it, and again from the cache folder when one is given (DS2_CACHE)", async (t) => {
  const c = S.labCheck; assert.equal(c.modelWorstDifference, 0); assert.equal(c.scaleIsTheStudys, true); assert.deepEqual(c.scale, LV.model.scale); assert.deepEqual(c.replay, D1.pieReplay.lineTest.find((x) => x.readings === 1).core70); assert.equal(c.buyAndHold.became, D1.pieReplay.buyAndHold.became); assert.equal(c.buyAndHold.worstFall, D1.pieReplay.buyAndHold.worstFall);
  assert.deepEqual(cand("base").payoff.became, c.replay.became, "today's number in the scorecard is that replay"); assert.equal(cand("c3").payoff.became, D1.pieReplay.lineTest.find((x) => x.readings === 3).core70.became, "and the 3-day average is the deployment study's own 3-day figure"); assert.equal(cand("c5").payoff.became, D1.pieReplay.lineTest.find((x) => x.readings === 5).core70.became);
  const cache = process.env.DS2_CACHE; if (!cache || !fs.existsSync(path.join(cache, "SPY_D.json"))) { t.diagnostic("no cache folder given (DS2_CACHE): the build's own record is what was checked"); return; }
  const { lab } = await import("../scripts/ds2-lib.mjs"), L = lab(cache), M = L.fitAdditive(L.ALLROWS, ["rsi", "creditOwn"], undefined, { rsi: [60], creditOwn: [20] }, { rsi: true }); let w = 0; for (const p of M.parts) { const q = LV.model.parts.find((x) => x.key === p.key); for (const k of ["q", "gm20", "gp20", "gm60", "gp60"]) for (let i = 0; i < p[k].length; i++) w = Math.max(w, Math.abs(p[k][i] - q[k][i])); } assert.equal(w, 0, "the lab's fit is the model the tool reads"); });

test("2 · version 2's arithmetic: credit's subtraction fades out between an RSI of 45 and 35 and its additions never change; the two things the raise-cash rule looks at; the rule's state", () => {
  assert.equal(N.fadeAt(60, R), 1); assert.equal(N.fadeAt(45, R), 1); assert.equal(N.fadeAt(40, R), 0.5); assert.equal(N.fadeAt(35, R), 0); assert.equal(N.fadeAt(20, R), 0); assert.equal(N.fadeAt(null, R), 1);
  assert.equal(N.creditCounted(-20, 50, R), -20); assert.equal(N.creditCounted(-20, 40, R), -10); assert.equal(N.creditCounted(-20, 30, R), 0); assert.equal(Math.abs(N.creditCounted(-20, 30, R)), 0); assert.equal(N.creditCounted(12, 30, R), 12, "what credit adds, it adds in full"); assert.equal(N.creditCounted(-20, 30, { ...R, creditRule: 0 }), -20, "switched off, credit subtracts in full"); assert.equal(N.creditCounted(null, 30, R), null);
  const up = Array.from({ length: 300 }, (_, i) => 100 + i); assert.equal(N.offHighPct(up, 250, 252), null, "no high until there are 252 closes"); assert.equal(N.offHighPct(up, 251, 252), 0); const dn = up.slice(); dn[299] = dn[298] * 0.97; assert.ok(near(N.offHighPct(dn, 299, 252), -3, 1e-9));
  assert.equal(N.overAvgPct(up, 198, 200), null); assert.ok(near(N.overAvgPct(up, 199, 200), (299 / 199.5 - 1) * 100, 1e-9)); const flat = new Array(260).fill(50); assert.equal(N.overAvgPct(flat, 259, 200), 0);
  const t0 = N.topAt(up, up, 299, R); assert.equal(t0.near, true); assert.ok(t0.x200 > R.extPct); assert.equal(N.topAt(dn, up, 299, R).near, false, "both funds must be at their high"); assert.equal(N.topAt(flat, flat, 259, R).x200, 0);
  const hi = { near: true, x200: R.extPct + 1 }, lo = { near: true, x200: R.extPct - 1 }, far = { near: false, x200: 30 };
  assert.equal(N.cashStep(false, 60, hi, R), true, "on at an extended high"); assert.equal(N.cashStep(false, 60, lo, R), false, "at the high but not extended: nothing"); assert.equal(N.cashStep(false, 60, far, R), false, "extended but not at the high: nothing");
  assert.equal(N.cashStep(true, 55, far, R), true, "it holds"); assert.equal(N.cashStep(true, 40, far, R), true, "an RSI of exactly 40 is not under 40"); assert.equal(N.cashStep(true, 39.9, hi, R), false, "off at a washout, whatever else is true"); assert.equal(N.cashStep(true, null, hi, R), true, "a day with no RSI changes nothing"); assert.equal(N.cashStep(true, 60, hi, { ...R, cashRule: 0 }), false, "switched off, it is never on");
  assert.equal(N.inEpisode([["2026-01-05", "2026-01-09"], ["2026-08-13", null]], "2026-01-07"), true); assert.equal(N.inEpisode([["2026-01-05", "2026-01-09"], ["2026-08-13", null]], "2026-01-12"), false); assert.equal(N.inEpisode([["2026-08-13", null]], "2026-10-06"), true); assert.equal(N.cashSince(["a", "b", "c", "d"], [false, true, true, true], 3), "b"); assert.equal(N.cashSince(["a", "b"], [true, false], 1), null); });

test("3 · one reading through version 2: with both switches off it is the deployment study's reading; faded credit and raised cash are each what the words say; the parts shown are the parts counted", () => {
  const { eng } = sides(), base = N.typicalDay(LV.model), bars = Object.fromEntries(E.ALL_SYMBOLS.map((s) => [s, F[s] ? { c: F[s], h: F[s], l: F[s] } : null])), X = E.allReadings({ dates: F.dates, bars }, F.hygWithPayouts).X, at = (d) => E.readSystem(E.inputsAt(X, ix[d]), LV.model);
  for (const d of ["2026-03-30", "2025-12-11", "2025-07-21", "2025-04-08"]) { const r = at(d), off = N.applyV2(r, { rsi: X.rsi[ix[d]], cash: true, base }, { ...R, creditRule: 0, cashRule: 0 }); assert.equal(off.reading, r.reading, d + ": both switches off"); assert.equal(off.v1.reading, r.reading); }
  /* the March 2026 low: RSI 27.9, credit's −23.6 not counted at all → 49.1 + 33.6 = 82.7 */
  const lo = at("2026-03-30"), a = N.applyV2(lo, { rsi: X.rsi[ix["2026-03-30"]], cash: false, base }, R); assert.equal(lo.reading, 59.1); assert.equal(a.reading, 82.7); assert.equal(a.v2.fade, 0); assert.ok(near(a.v2.creditFitted, -23.6, 0.06)); assert.equal(Math.abs(a.v2.creditCounted), 0); assert.equal(Math.abs(a.parts.find((p) => p.key === "creditOwn").points), 0, "credit's row shows what was counted"); assert.ok(near(a.parts.find((p) => p.key === "creditOwn").fitted, -23.6, 0.06)); assert.ok(near(a.families.find((f) => f.family === "credit").points, 0, 1e-9));
  assert.ok(near(a.parts.reduce((s, p) => s + p.points, 0) + base, a.readingExact, 1e-9), "the typical day plus the parts as shown is the reading");
  /* mid-December 2025: nothing faded (RSI 60), cash raised → 51.6 halved */
  const dc = at("2025-12-11"), b = N.applyV2(dc, { rsi: X.rsi[ix["2025-12-11"]], cash: true, base }, R); assert.equal(dc.reading, 51.6); assert.equal(b.reading, 25.8); assert.equal(b.v2.cash, true); assert.equal(b.v2.beforeCash, 51.6); assert.equal(N.applyV2(dc, { rsi: 60, cash: false, base }, R).reading, 51.6);
  assert.ok(near(N.readingV2({ base, rsiPoints: 33.6, creditPoints: -23.6, rsi: 27.9, cash: false }, R), base + 33.6, 1e-9)); assert.ok(near(N.readingV2({ base, rsiPoints: 2, creditPoints: 0.5, rsi: 60, cash: true }, R), (base + 2.5) / 2, 1e-9)); assert.equal(N.readingV2({ base, rsiPoints: null, creditPoints: 1, rsi: 60, cash: false }, R), null);
  /* a light the user counts rides inside the reading, and is halved with it */
  const lit = N.applyV2({ ...dc, lightsCounted: 10 }, { rsi: 60, cash: true, base }, R); assert.ok(near(lit.readingExact, (dc.parts.reduce((s, p) => s + p.points, 0) + base + 10) / 2, 1e-9));
  assert.equal(eng[ix["2026-03-30"]].reading, 82.7); assert.equal(eng[ix["2025-12-11"]].reading, 25.8); });

test("4 · the scorecard as stored: thirteen changes declared before the run and three added after it, each marked; every verdict is the pass rule applied to that line's own numbers", () => {
  assert.deepEqual(S.candidates.map((c) => c.key), ["base", "a1", "a2", "a3", "b50", "b100", "b", "c3", "c5", "cUp", "d1", "d2", "d3", "a2f", "d0", "d2L"]);
  assert.deepEqual(S.candidates.filter((c) => c.addedAfterFirstRun).map((c) => c.key), ["a2f", "d0", "d2L"], "the three shaped after the first results say so"); assert.deepEqual(S.candidates.filter((c) => c.shapedByHisDate).map((c) => c.key), ["d3"]);
  const B = cand("base"); for (const c of S.candidates.slice(1)) { const whole = c.payoff.timing >= B.payoff.timing - 0.005 && c.payoff.worstFall >= B.payoff.worstFall - 1.0, up = [c.dates.L25 - B.dates.L25, c.dates.L26 - B.dates.L26, B.dates.T25 - c.dates.T25], dates = up.some((v) => v >= 1.0) && !up.some((v) => v <= -1.0);
    assert.equal(c.passWhole, whole, c.key + " whole period"); if (c.family !== "c") { assert.equal(c.passDates, dates, c.key + " his dates"); assert.equal(c.verdict, whole && dates ? "in" : dates ? "dial, off" : "out", c.key); } else { const sm = c.dates.MOVE <= (2 / 3) * B.dates.MOVE && c.payoff.becameAfterCost >= 0.99 * B.payoff.becameAfterCost; assert.equal(c.passSmooth, sm); assert.equal(c.verdict, sm ? "in" : "out"); }
    assert.ok(near(c.payoff.timing, c.payoff.became / c.payoff.untimed, 0.0006), c.key + ": timing is what 1 became over what the same average share became untimed"); }
  assert.deepEqual(S.candidates.filter((c) => c.verdict === "in").map((c) => c.key), ["a2", "d2", "d3", "a2f", "d0", "d2L"]); for (const k of ["c3", "c5", "cUp"]) assert.equal(cand(k).verdict, "out", "no smoother met its bar"); for (const k of ["b50", "b100", "b"]) assert.equal(cand(k).verdict, "dial, off", "the depth add helps his dates and fails the whole period alone");
  /* the literal reading of (a) does nothing on his dates: credit was not washed out on them */
  assert.deepEqual([cand("a1").dates.L25, cand("a1").dates.L26, cand("a1").dates.L26low], [B.dates.L25, B.dates.L26, B.dates.L26low]);
  /* no depth part earned a vote by the deployment study's bar */
  for (const p of S.evidence.partTests) assert.equal(p.verdict, "light", p.key);
  /* no top rule pays as a trade: under one time in two, all years */
  for (const k of ["d0", "d2", "d3"]) assert.ok(S.evidence.topRules[k].all.paid <= 0.5, k); assert.ok(near(S.evidence.topRules.any.all.paid, 0.5, 0.02));
  /* the windows were found from the closes, not typed */
  assert.equal(S.windows.LOW25, "2025-03-28"); assert.equal(S.windows.LOW26, "2026-03-30"); assert.deepEqual(S.windows.MAR26, ["2026-03-24", "2026-03-25", "2026-03-26", "2026-03-27", "2026-03-30"]); assert.equal(S.windows.TOP, "2026-01-27"); assert.equal(S.windows.DEC25[2], 22); assert.equal(S.windows.unseen[0], "2018-01-02"); });

test("5 · the recommended version, before and after: bolder at the two lows, no cut into the March 2026 low, lighter through December 2025 — and on the years it had not seen the same end result with a shallower worst fall", () => {
  const b = S.recommended.before, a = S.recommended.after; assert.equal(S.recommended.key, "a2f + d2L"); assert.deepEqual(S.recommended.rules, R);
  assert.deepEqual([b.dates.L26low, a.dates.L26low], [87.7, 94.8], "the March 2026 low"); assert.deepEqual([b.dates.CUT, a.dates.CUT], [-3.6, 0], "26 → 30 March 2026"); assert.deepEqual([b.dates.L25low, a.dates.L25low], [85.9, 91.4], "the late-March 2025 low"); assert.deepEqual([b.dates.T25, a.dates.T25], [85.9, 78.7], "December 2025"); assert.deepEqual([b.dates.T25top, a.dates.T25top], [84.2, 77.1]); assert.equal(a.dates.apr8, 100, "April 2025 is left at 100");
  assert.ok(a.dates.GAP > b.dates.GAP + 8); assert.ok(a.dates.MOVE <= b.dates.MOVE, "not jumpier than today's"); assert.ok(a.dates.MOVE > 0.9 * b.dates.MOVE, "and not much steadier either — the page says so");
  assert.deepEqual([b.payoff.became, b.payoff.worstFall, b.payoff.invested], [3.54, -30, 85]); assert.ok(near(a.payoff.became, b.payoff.became, 0.01), "the same end result: " + a.payoff.became); assert.ok(a.payoff.worstFall >= b.payoff.worstFall); assert.ok(a.payoff.invested < b.payoff.invested); assert.ok(a.payoff.timing > b.payoff.timing);
  /* with the curves fitted to 2017 only, the same direction on every one of his dates */
  const a17 = a.dates17, b17 = b.dates17; assert.ok(a17.L26low > b17.L26low && a17.L25low > b17.L25low && a17.T25 < b17.T25 && a17.CUT >= 0 && b17.CUT < 0);
  /* the same test three other ways: never worse than 1.5% in the end result, timing better every time, the worst fall within half a point */
  for (const k of ["17", "15", "19", "17w"]) { const t = S.firm.otherFits[k].rows.find((r) => r.name === "today"), v = S.firm.otherFits[k].rows.find((r) => r.name === "a2f + d2L"); assert.ok(v.became >= 0.985 * t.became, k + ": " + v.became + " against " + t.became); assert.ok(v.timing > t.timing, k); assert.ok(v.worstFall >= t.worstFall - 0.5, k); }
  /* 2004 to March 2009, which holds 2008: version 2 is today's number there, and both are under buying and holding — said on the page */
  const e = S.firm.earlier.y0409, t = e.rows.find((r) => r.name === "today"), v = e.rows.find((r) => r.name === "a2f + d2L"), d = e.rows.find((r) => r.name === "a2f + d2L + depth add-on"); assert.ok(near(v.became, t.became, 0.002)); assert.ok(t.became < e.buyAndHold.became); assert.ok(d.became < v.became - 0.015, "the depth add cost through 2008");
  /* fewer days on which the market fell and the number was cut too, 23 Feb → 30 Mar 2026 */
  assert.ok(S.recommended.wrongWay.after.cutOnADownDay < S.recommended.wrongWay.before.cutOnADownDay); assert.equal(S.recommended.wrongWay.before.sessions, 26);
  /* the raise-cash stretches of the rule as the tool carries it: not a call on the top */
  const eps = S.firm.latchAll.filter((x) => x.from >= "2018-01-01"), done = eps.filter((x) => !x.open); assert.equal(eps.length, 15); assert.equal(done.filter((x) => x.blendPct > 0).length, 7); assert.equal(done.length, 14); assert.deepEqual(stretches(S), { n: 14, higher: 7 }); assert.ok(eps.some((x) => x.from === "2025-12-03" && x.to === "2026-02-04" && x.blendPct < 0), "the stretch he asked about"); assert.ok(eps.at(-1).open && eps.at(-1).from === "2026-08-13"); });

test("6 · the diagnosis adds up: on each of his dates the change in the number is the RSI part's change plus the credit part's (in points of the account), and the cut into the March 2026 low is credit's", () => {
  for (const key of Object.keys(S.diagnosis)) for (const m of S.diagnosis[key].moves) { assert.ok(near(m.d, m.numberTo - m.numberFrom, 0.11), key + " " + m.from); assert.ok(near(m.byRsi + m.byCredit + m.heldAtAStop, m.d, 0.21), key + " " + m.from + ": " + m.byRsi + " + " + m.byCredit + " + " + m.heldAtAStop + " against " + m.d); }
  const cut = S.diagnosis.mar26.moves[1]; assert.deepEqual([cut.from, cut.to], ["2026-03-26", "2026-03-30"]); assert.deepEqual([cut.numberFrom, cut.numberTo], [91.3, 87.7]); assert.ok(cut.byRsi > 0 && cut.byCredit < -4 && cut.spyPct < -1.9); assert.ok(cut.hygPct > -0.3, "the high-yield fund barely moved"); assert.ok(cut.iefPct > 0.5, "treasuries rallied"); assert.ok(cut.number2To >= cut.number2From, "version 2 does not cut there");
  const spr = S.diagnosis.spring25.moves[0]; assert.ok(spr.byCredit < -6 && spr.byRsi > 3 && spr.d < -3, "the same thing on 28 March 2025");
  const jul = S.diagnosis.jul21.moves[0], sep = S.diagnosis.sep22.moves[0]; assert.ok(jul.byRsi < -8 && Math.abs(jul.byCredit) < 2 && sep.byRsi < -10, "July and September 2025 are the RSI part");
  const dec = S.diagnosis.end25.december; assert.ok(dec.numberMax - dec.numberMin < 5 && dec.rsiMax < 62 && Math.abs(dec.pC) < 3, "December 2025: neither part had anything to say"); assert.ok(near(dec.number, S.recommended.before.dates.T25, 0.05)); assert.ok(near(dec.number2, S.recommended.after.dates.T25, 0.05));
  assert.ok(S.moveSplit.rsiPart > 1 && S.moveSplit.creditPart > 1 && S.moveSplit.together === S.recommended.before.dates.MOVE);
  /* the named days carry both numbers, and the study's are the tool's sum on the closes kept in the repo */
  const { eng } = sides(); for (const n of S.recommended.named) { const e = eng[ix[n.d]]; assert.ok(near(e.reading, n.reading2, 0.1000001), n.d); assert.ok(near(e.readingOld, n.reading, 0.1000001), n.d); assert.equal(e.cash ? 1 : 0, n.cash, n.d + " cash"); } });

test("7 · the stored history is the number the tool shows: version 2 in r, version 1 in r1, cash raised in cash — and each is the sum on the closes kept in the repo", () => {
  assert.equal(H.version, 2); assert.deepEqual(H.rules, R); assert.equal(H.r.length, H.d.length); assert.equal(H.r1.length, H.d.length); assert.equal(H.cash.length, H.d.length); const { eng } = sides(); let n = 0, w = 0, w1 = 0, cd = 0;
  H.d.forEach((d, i) => { const e = eng[ix[d]]; if (!e || e.reading == null) return; n++; w = Math.max(w, Math.abs(e.reading - H.r[i])); w1 = Math.max(w1, Math.abs(e.readingOld - H.r1[i])); if ((e.cash ? 1 : 0) !== H.cash[i]) cd++; });
  assert.equal(n, H.d.length); assert.ok(w <= 0.1000001, "worst gap, version 2: " + w); assert.ok(w1 <= 0.1000001, "worst gap, version 1: " + w1); assert.equal(cd, 0, "the raise-cash days are the same");
  const at = Object.fromEntries(H.d.map((d, i) => [d, i])); assert.equal(H.r[at["2026-03-30"]], 82.7); assert.equal(H.r1[at["2026-03-30"]], 59.1); assert.equal(H.cash[at["2025-12-11"]], 1); assert.equal(H.cash[at["2026-03-30"]], 0); assert.deepEqual(LIVE.cashEpisodes.at(-1), ["2026-08-13", null]); assert.equal(LIVE.now.cash, true); assert.equal(LIVE.now.since, "2026-08-13"); assert.equal(H.r.at(-1), LIVE.now.readingV2); });

test("8 · the tool holds 540 daily bars and the rule needs 252 before it can see a high: seeded from the stored stretches, the tool's window gives the full history's state on every day, for a window ending on any of the last 300 sessions", () => {
  const bars = Object.fromEntries(E.ALL_SYMBOLS.map((s) => [s, F[s] ? { c: F[s], h: F[s], l: F[s] } : null])), X = E.allReadings({ dates: F.dates, bars }, F.hygWithPayouts).X, has = F.dates.map((_, i) => X.rsi[i] != null && X.creditOwn[i] != null), full = N.cashSeries({ rsi: X.rsi, spy: F.SPY, qqq: F.QQQ, has }, R).cash; let checked = 0;
  for (let end = LAST; end > LAST - 300; end -= 7) { const a = end - 539, w = N.cashWindow({ dates: F.dates.slice(a, end + 1), rsi: X.rsi.slice(a, end + 1), spy: F.SPY.slice(a, end + 1), qqq: F.QQQ.slice(a, end + 1), has: has.slice(a, end + 1) }, R, LIVE.cashEpisodes, LIVE.asOf);
    assert.equal(w.seededTo, F.dates[a + 250]); for (let i = 0; i < 540; i++) { assert.equal(w.cash[i], full[a + i], "a window ending " + F.dates[end] + ", on " + F.dates[a + i]); checked++; } }
  assert.ok(checked > 20000); const off = N.cashWindow({ dates: F.dates.slice(-540), rsi: X.rsi.slice(-540), spy: F.SPY.slice(-540), qqq: F.QQQ.slice(-540), has: has.slice(-540) }, { ...R, cashRule: 0 }, LIVE.cashEpisodes, LIVE.asOf); assert.ok(off.cash.every((c) => c === false), "switched off, never on"); });

test("9 · the dials: Micron 60 / Nebius 40 of conviction at the baseline, Oracle out of the core as a dollar-cost starter, the two rule switches on — and saved dials from before are not read", () => {
  const A = baseline(LV); assert.equal(A.micronOfConv, 60); assert.equal(C.DIALS.micronOfConv, 60); assert.equal(A.coreWeights.ORCL, 0); assert.equal(LV.defaults.coreWeights.ORCL, 3, "the model file is untouched: the baseline is set in the tool"); assert.equal(A.creditRule, 1); assert.equal(A.cashRule, 1); assert.deepEqual(C.STARTERS, { ORCL: "dollar-cost starter" }); assert.equal(STORE, "ds2.assumptions");
  for (const k of ["NVDA", "AVGO", "TSM", "AMZN", "GOOGL", "MU"]) assert.equal(A.coreWeights[k], LV.defaults.coreWeights[k], k + " keeps its weight");
  const c = C.chainAt(15.2, A), f = C.ceilingsOf(A), conv = (n) => n.parts.find((p) => p.kind === "conviction").pct; assert.ok(near(conv(c.names.MU) / conv(c.names.NBIS), 60 / 40, 1e-9)); assert.equal(c.names.ORCL, undefined, "Oracle is in no pie"); assert.ok(near(Object.values(c.names).reduce((s, n) => s + n.pct, 0), c.number, 1e-9), "the pies still add to the number");
  assert.ok(near(f.names.MU.pct, 18 + 10, 1e-9) && near(f.names.NBIS.pct, 12, 1e-9)); assert.equal(f.capped.length, 0, "at 60 / 40 Micron's ceiling of 28% is under its cap of 30%"); assert.ok(near(f.names.NVDA.pct, 15, 1e-9) && near(f.names.AMZN.pct, 10, 1e-9) && near(f.names.GOOGL.pct, 5, 1e-9), "Oracle's share of the core went to the other core names");
  /* room to play: Oracle's row is there, as a starter — never "to buy", never "over", whatever is held of it */
  const acct = { nlv: 500000, positions: { MU: { shares: 50, price: 1000 }, ORCL: { shares: 100, price: 150 } } }, Rm = C.roomToPlay(c, f, acct, A, {}), o = Rm.rows.find((x) => x.sym === "ORCL"); assert.deepEqual(Rm.rows.map((x) => x.sym), C.ROWS); assert.equal(o.starter, "dollar-cost starter"); assert.equal(o.target, 0); assert.equal(o.room, 0); assert.equal(o.over, 0); assert.ok(near(o.held, 3, 1e-9)); assert.ok(near(Rm.held, 10 + 3, 1e-9), "what is held of a starter still counts as held");
  assert.equal(C.roomToPlay(c, f, { nlv: 500000, positions: {} }, A, {}).rows.find((x) => x.sym === "ORCL").starter, "dollar-cost starter", "the row is there with nothing held"); assert.equal(Rm.rows.find((x) => x.sym === "NVDA").starter, null);
  /* give Oracle a weight again and it is an ordinary core name */
  const back = { ...A, coreWeights: { ...A.coreWeights, ORCL: 3 } }, cb = C.chainAt(15.2, back); assert.ok(cb.names.ORCL.pct > 0); assert.equal(C.roomToPlay(cb, C.ceilingsOf(back), acct, back, {}).rows.find((x) => x.sym === "ORCL").starter, null);
  /* the breakout band is shared as conviction is: 3 and 2 of its 5 points */
  const band = C.roomToPlay(C.chainAt(30, A), f, { nlv: 500000, positions: {} }, A, {}); assert.ok(near(band.rows.find((x) => x.sym === "MU").band, 3, 1e-9) && near(band.rows.find((x) => x.sym === "NBIS").band, 2, 1e-9));
  assert.deepEqual(v2Rules(LV, A), null, "no rule file, no version 2"); assert.deepEqual(v2Rules(LV2, A), { ...R, creditRule: 1, cashRule: 1 }); assert.equal(v2Rules(LV2, { ...A, cashRule: 0 }).cashRule, 0); });

test("10 · the pane's script is what the build writes; its thresholds are the rule file's; the lines version 2 did not change are version 1's, byte for byte", () => {
  assert.equal(SRC, buildPine2(), "run node scripts/ds2-build-pine.mjs"); assert.deepEqual([K.FADE_FROM, K.FADE_TO, K.HIGH_DAYS, K.AVG_DAYS, K.NEAR_PCT, K.EXT_PCT, K.RESET_RSI, K.CASH_CUT], [R.fadeFrom, R.fadeTo, R.highDays, R.avgDays, R.nearPct, R.extPct, R.resetRsi, R.cashCut]); assert.equal(K.creditRule, true); assert.equal(K.cashRule, true); assert.equal(K.heldPct, 70); assert.equal(K.tacticalPct, 30);
  const K1 = parsePine(SRC1); for (const k of ["RSI_DAYS", "CREDIT_DAYS", "RATES_SHARE", "TYPICAL_DAY", "RSI_PLACES", "CREDIT_PLACES", "RSI_POINTS", "CREDIT_POINTS", "funds"]) assert.deepEqual(K[k], K1[k], k + " is version 1's");
  for (const [a, b] of [["// colours —", "// ── inputs"], ["// ── Wilder's RSI", "// ── requests"], ["// ── a part's points", "// ── the sum"], ["// numbers as the allocation tool writes them", "// ── labels on the last bar"]]) assert.equal(blockOf(SRC, a, b === "// ── requests" ? "// ── version 2: where a fund stands" : b), blockOf(SRC1, a, b), "the block from " + a);
  assert.match(SRC, /^indicator\("SCINTILLA · DEPLOYMENT PANE", shorttitle = "DEPLOYMENT", overlay = false/m, "the same script name, so it is saved as version 2 of the same script"); assert.equal(codeHash(SRC), P.script.codeHash, "the script's code changed after the proof was made — run node scripts/ds2-prove-pane.mjs"); assert.notEqual(codeHash(SRC), codeHash(SRC1));
  assert.equal(checkSaved2(SRC).identical, true); assert.equal(checkSaved2(SRC.replace(/\n/g, "\r\n")).identical, true); const bad = checkSaved2(SRC.replace("const float  RESET_RSI   = 40.0", "const float  RESET_RSI   = 45.0")); assert.equal(bad.numbersUnchanged, false); assert.equal(bad.ok, false);
  const words = checkSaved2(SRC.replace('"Labels on the last bar"', '"Labels on the newest bar"')); assert.equal(words.identical, false); assert.equal(words.numbersUnchanged, true); assert.equal(words.ok, true, "a changed word that touches no number still passes, with its line named"); assert.equal(words.differs.length, 1); });

test("11 · the TradingView protocol: version 6, the plot budget stated in the header and counted from the code, eight requests, none looking ahead, no white", () => {
  assert.ok(SRC.startsWith("//@version=6\n"));
  /* the protocol's count: a plot with a constant colour 1, a plot whose colour changes from bar to bar 2, a fill 1, the band 2 */
  const plots = [...CODE.matchAll(/^(?:\w+\s*=\s*)?plot\((.*)\)\s*$/gm)].map((m) => m[1]), fills = (CODE.match(/^fill\(/gm) || []).length, bands = (CODE.match(/^bgcolor\(/gm) || []).length, constCol = (a) => /color = (C_[A-Z_]+|color\.new\(C_[A-Z_]+, \d+\))(,|$)/.test(a);
  const count = plots.reduce((n, a) => n + (constCol(a) ? 1 : 2), 0) + fills + 2 * bands, stated = SRC.match(/^\/\/ PLOTS (\d+)\/64/m); assert.equal(plots.length, 11); assert.equal(fills, 1); assert.equal(bands, 1); assert.equal(count, 17); assert.equal(+stated[1], count); assert.ok(count <= 64);
  const req = (CODE.match(/request\.\w+\(/g) || []).length, statedReq = SRC.match(/^\/\/ REQUESTS (\d+)\/40/m); assert.equal(req, 8); assert.equal(+statedReq[1], req); assert.equal((CODE.match(/lookahead = barmerge\.lookahead_off/g) || []).length, 8, "no request looks ahead");
  assert.ok(!/color\.white|#fff\b|#ffffff/i.test(SRC)); for (const [, h] of CODE.matchAll(/#([0-9A-Fa-f]{6})\b/g)) { const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)); assert.ok(!(Math.min(r, g, b) >= 200 && Math.max(r, g, b) - Math.min(r, g, b) <= 40), "#" + h + " reads as white"); }
  assert.ok(!/color\.(gray|silver|black|red|green|blue|yellow|orange|purple|aqua|lime|teal|navy|olive|maroon|fuchsia)\b/.test(CODE), "only the named palette at the top of the script");
  /* shape: no tabs, wrapped lines indented by five spaces, every bracket and quote closed, blocks on the four-space grid */
  assert.ok(!SRC.includes("\t")); const lines = CODE.split("\n"); let depth = 0; for (const [i, ln] of lines.entries()) { const bare = ln.replace(/"(?:[^"\\]|\\.)*"/g, '""').replace(/\/\/.*$/, ""); if (depth > 0) assert.match(ln, /^ {5}\S/, "wrapped line " + (i + 1)); assert.equal((bare.match(/"/g) || []).length % 2, 0, "an open quote on line " + (i + 1)); depth += (bare.match(/\(/g) || []).length - (bare.match(/\)/g) || []).length; assert.ok(depth >= 0); }
  assert.equal(depth, 0); for (const ln of lines) if (!/^ {5}\S/.test(ln)) assert.equal(ln.match(/^ */)[0].length % 4, 0, "off the four-space grid: " + ln.slice(0, 40));
  /* no reading is ever made by leaning on how a missing value passes through max and min: where a part is missing the script says so */
  assert.ok(CODE.includes("float beforeCut = na(ptsRsi) or na(ptsCredit) ? na :")); assert.ok(CODE.includes("float reading   = na(beforeCut) ? na :")); assert.ok(CODE.includes("if not na(ptsRsi) and not na(ptsFitted)"), "the raise-cash state only moves on a day with a reading"); });

test("12 · plain words: nothing a person reads on the chart or in the settings carries an internal code or a banned word; the label says when cash is raised", () => {
  const banned = [/\bv\d\b/i, /\bevening/i, /\brung/i, /\bDS\d\b/, /\bPN\d\b/, /\bAL\d\b/, /\blane\b/i, /\bn\/a\b/i, /\bNaN\b/, /undefined/, /\blatch/i, /\ba2f?\b/, /\bd2L?\b/];
  assert.ok(STRINGS.length > 35); for (const s of STRINGS) for (const b of banned) assert.ok(!b.test(s), JSON.stringify(s) + " carries " + b); for (const b of banned) assert.ok(!b.test(SRC.replace(/\bd2\b/g, "")), "the script's header carries " + b);
  for (const want of ["Invested ", "% · market reading ", " · cash raised", "version 1: ", "Credit does not subtract in a washed-out market", "Raise cash at an extended high, put it back at the next washout", "Show version 1's line beside it", "Shade the stretches where cash is raised", "cash raised at an extended high (1 = yes)", "% invested, version 1", "version 1 (line)", "% invested", "market reading", "SPY and QQQ's RSI, averaged", "credit's own move over ten sessions, %"]) assert.ok(STRINGS.includes(want), "the script says " + JSON.stringify(want));
  const { same } = sides(), on = same[ix["2025-12-11"]], off = same[ix["2026-03-30"]]; assert.equal(labelOf2(on), "Invested 78% · market reading 26 · cash raised"); assert.equal(labelOf2(off), "Invested 95% · market reading 83"); assert.deepEqual(labelsOf2(off, { showOld: true }).map((l) => l.text), ["Invested 95% · market reading 83", "version 1: 88%"]);
  assert.ok(CODE.includes('array.push(ts, "Invested " + whole(invested) + "% · market reading " + whole(reading) + (cashOn ? " · cash raised" : ""))'), "the label's words in the script are the words the replay prints"); assert.equal(labelOf2({ invested: null, spyRsi: 60, qqqRsi: 60, hygMove: null, iefMove: 0.1 }), "No reading yet · waiting for prices from HYG"); });

test("13 · a replay of the script against the tool's sum, on the tool's own prices: the same reading and the same raise-cash days on every day there is; the money; the days he named", () => {
  const { eng, same } = sides(); let n = 0, w = 0, wi = 0, cd = 0; for (let i = 0; i <= LAST; i++) { assert.equal(eng[i].reading == null, same[i].reading == null, F.dates[i]); if (eng[i].reading == null) continue; n++; w = Math.max(w, Math.abs(eng[i].reading - same[i].reading)); wi = Math.max(wi, Math.abs(eng[i].invested - same[i].invested)); if (eng[i].cash !== same[i].cashOn) cd++; assert.ok(near(same[i].invested, 70 + 0.3 * same[i].reading, 1e-9) && same[i].invested >= 70 && same[i].invested <= 100); }
  assert.equal(n, 4894); assert.ok(w <= 0.1000001, "worst reading gap " + w); assert.ok(wi <= 0.0300001); assert.equal(cd, 0, "cash is raised on the same days"); assert.equal(same.filter((r) => r.cashOn).length, P.history.raiseCashDays.script); assert.equal(F.dates[same.findIndex((r) => r.reading != null)], "2007-04-25");
  for (const n2 of S.recommended.named) { const r = same[ix[n2.d]]; assert.ok(near(r.reading, n2.reading2, 0.1000001), n2.d + ": " + r.reading + " against " + n2.reading2); assert.ok(near(r.invested, n2.number2, 0.07), n2.d); assert.ok(near(r.investedOld, n2.number, 0.07), n2.d + " version 1's line"); }   /* the study rounds the number once; the tool and the pane round the reading to a tenth first, then take 30% of it: 0.05 + 0.015 */
  /* the two new measures, bar for bar against the tool's own */
  for (const s of ["SPY", "QQQ"]) { const a = offHigh(K)(), b = overAvg(K)(); let wa = 0, wb = 0; F[s].forEach((c, i) => { const x = a(c), y = b(c), ex = N.offHighPct(F[s], i, R.highDays), ey = N.overAvgPct(F[s], i, R.avgDays); assert.equal(x == null, ex == null); assert.equal(y == null, ey == null); if (x != null) wa = Math.max(wa, Math.abs(x - ex)); if (y != null) wb = Math.max(wb, Math.abs(y - ey)); }); assert.ok(wa < 1e-9 && wb < 1e-9, s + ": " + wa + " " + wb); }
  /* the proof file says what the code says */
  assert.equal(P.allWithinOnePoint, true); assert.equal(P.history.samePrices.days, 4894); assert.equal(P.history.samePrices.worst, 0); assert.equal(P.history.samePrices.raiseCashDaysThatDiffer, 0); assert.ok(P.history.tradingViewPayouts.shareWithin1 >= 99.5); assert.equal(P.history.tradingViewPayouts.raiseCashDaysThatDiffer, 0, "the high-yield fund's payouts cannot touch the raise-cash rule"); assert.ok(P.history.lastYear.tradingViewPayouts.worst <= 1);
  assert.equal(P.rows.length, 29); for (const r of P.rows) { assert.equal(r.engine.reading, eng[ix[r.date]].reading); assert.equal(r.script.reading, same[ix[r.date]].reading); assert.ok(r.gap <= 0.1 && r.gapTradingViewPayouts <= 1 && r.sameRaiseCashState); }
  assert.ok(P.history.aHairOnAThreshold.worst.daysTheStateDiffers <= 20 && P.history.aHairOnAThreshold.nudges.every((x) => x.inTheLastYear === 0)); assert.ok(P.today && P.today.engine && P.today.gap <= 0.1 && P.today.sameRaiseCashState, "the proof holds tonight's live row"); });

test("14 · with both switches off the script is version 1 on every day; and a second witness made by machine — the script's own text, translated rule by rule and run — gives the hand-written replay's reading and the tool's", () => {
  const { eng, same } = sides(), funds = { spy: seriesOf(F, F.SPY), qqq: seriesOf(F, F.QQQ), ief: seriesOf(F, F.IEF), hyg: seriesOf(F, F.hygWithPayouts) }, v1 = replay1(parsePine(SRC1), funds, F.dates), off = scriptV2On(K, F, F.hygWithPayouts, { creditRule: false, cashRule: false }); let n = 0;
  for (let i = 0; i <= LAST; i++) { assert.equal(v1[i].reading == null, off[i].reading == null); if (v1[i].reading == null) continue; n++; assert.equal(off[i].reading, v1[i].reading, F.dates[i] + ": both switches off"); assert.equal(same[i].readingOld, v1[i].reading, F.dates[i] + ": the thin line is version 1"); assert.equal(off[i].cashOn, false); } assert.equal(n, 4894);
  const one = scriptV2On(K, F, F.hygWithPayouts, { cashRule: false }), two = scriptV2On(K, F, F.hygWithPayouts, { creditRule: false }); assert.equal(one[ix["2026-03-30"]].reading, 82.7, "the credit change alone fixes the low"); assert.equal(one[ix["2025-12-11"]].reading, 51.6); assert.equal(two[ix["2026-03-30"]].reading, 59.1); assert.equal(two[ix["2025-12-11"]].reading, 25.8, "the raise-cash rule alone makes December lighter");
  const mech = runFromText2(SRC, funds, F.dates, { heldPct: K.heldPct, tacticalPct: K.tacticalPct, creditRule: true, cashRule: true }); let m = 0, w = 0, we = 0; for (let i = 0; i <= LAST; i++) { const has = !(mech[i].reading == null || Number.isNaN(mech[i].reading)); assert.equal(has, same[i].reading != null, F.dates[i]); if (!has) continue; m++; w = Math.max(w, Math.abs(mech[i].reading - same[i].reading)); we = Math.max(we, Math.abs(mech[i].reading - eng[i].reading)); assert.equal(!!mech[i].cashOn, same[i].cashOn, F.dates[i] + " cash"); }
  assert.equal(m, 4894); assert.ok(w < 1e-9, "the two witnesses: " + w); assert.ok(we <= 0.1000001);
  /* the translation is of the text: a flipped sign in the script's sum, or a moved threshold, shows */
  const broken = runFromText2(SRC.replace("float ptsCredit = creditRule and ptsFitted < 0.0 ? ptsFitted * fade : ptsFitted", "float ptsCredit = creditRule and ptsFitted < 0.0 ? ptsFitted * (1.0 - fade) : ptsFitted"), funds, F.dates, { heldPct: 70, tacticalPct: 30 }); assert.ok(broken.filter((r, i) => same[i].reading != null && Math.abs(r.reading - same[i].reading) > 1).length > 100);
  assert.throws(() => runFromText2(SRC.replace("    else if atHigh and extended >= EXT_PCT", "    else if atHigh and extended >= EXT_PCT ?? 1"), funds, F.dates.slice(0, 400), { heldPct: 70, tacticalPct: 30 }), "a line it cannot run stops it"); });

test("15 · the installer's task: its eight days are the proof's own numbers, the same script name, one tab, and the way back", () => {
  const task = T("study/ds2/TASK-KIMI-DEPLOYMENT-PANE-VERSION-2.md"), rows = [...task.matchAll(/^\| (\d{4}-\d{2}-\d{2}) \| ([\d.]+) \| ([\d.]+) \| ([\d.]+) \| (-?[\d.]+) \| ([01]) \| ([\d.]+) \|$/gm)]; assert.equal(rows.length, 8);
  for (const [, d, inv, rd, rsi, cr, cash, old] of rows) { const r = P.rows.find((x) => x.date === d); assert.ok(r, d + " is one of the proved days"); assert.equal(+inv, r.scriptTradingViewPayouts.invested); assert.equal(+rd, r.scriptTradingViewPayouts.reading); assert.equal(+rsi, r.script.rsi); assert.equal(+cr, r.scriptTradingViewPayouts.creditOwn); assert.equal(+cash, r.script.cash ? 1 : 0); assert.equal(+old, r.script.version1.invested); }
  assert.ok(rows.some((r) => r[6] === "1") && rows.some((r) => r[6] === "0"), "days with cash raised and days without");
  for (const want of ["Scintilla — Deployment", "Scintilla Deployment Pane", "Do NOT use \"Save as\"", "EVERY other tab is forbidden", "Zero errors is the only pass", "scripts/ds2-check-saved.mjs", "SCINTILLA-DEPLOYMENT-PANE.v1.pine", "The way back", "NOT authorised by being written", "study/pn1/TASK-KIMI-DEPLOYMENT-LAYOUT.md", "DEPLOYMENT 70 30"]) assert.ok(task.includes(want), "the task says: " + want);
  for (const name of ["% invested", "market reading", "SPY and QQQ's RSI, averaged", "credit's own move over ten sessions, %", "cash raised at an extended high (1 = yes)", "% invested, version 1"]) { assert.ok(task.replace(/\s+/g, " ").includes('"' + name + '"'), name); assert.ok(STRINGS.includes(name), "the script has a plot called " + name); } });

test("16 · live: the tool's own read with the rule file riding on the model — version 2's reading, version 1 beside it, the same two rules at any five-minute price, on the dips and in the last year's days (skipped if the chart API does not answer)", async (t) => {
  let candles, live; try { candles = await fetchDaily(getApi); live = await fetchLive(getApi); } catch (e) { t.skip("the chart API did not answer: " + e.message); return; }
  const A = baseline(LV2), v = view({ base: LV2, candles, ...live, A }), v1 = view({ base: LV, candles, ...live, A }), offA = { ...A, creditRule: 0, cashRule: 0 }, off = view({ base: LV2, candles, ...live, A: offA });
  assert.equal(v1.v2, null); assert.equal(v1.reading.v1, undefined, "without the rule file the tool is version 1"); assert.ok(v.v2 && v.reading.v1, "with it, version 2"); assert.equal(v.reading.v1.reading, v1.reading.reading, "version 1 is kept beside it"); assert.equal(off.reading.reading, v1.reading.reading, "both switches off is version 1"); for (let i = 0; i < 3; i++) assert.equal(off.dips[i].reading, v1.dips[i].reading);
  const w = v.v2, want = N.readingV2({ base: w.typical, rsiPoints: v.reading.parts.find((p) => p.key === "rsi").points, creditPoints: w.creditFitted, rsi: v.inputs.rsi, cash: w.cash }, w.rules); assert.ok(near(v.reading.readingExact, want, 1e-9)); assert.equal(v.reading.reading, +want.toFixed(1)); if (w.cash) { assert.ok(w.since && w.since <= v.session); assert.ok(near(v.reading.readingExact, w.beforeCash * w.rules.cashCut, 0.051)); }
  /* the panel's own sum at the live prices is the live reading, and a calm dip never reads under now */
  const px = Object.fromEntries(C.VOTERS.map((s) => [s, v.S.bars[s].c[v.k]])); assert.ok(near(makeReadAt(v, LV2)(px), v.reading.reading, 0.15)); assert.ok(v.dips.every((d) => d.readingCalm >= v.reading.reading - 0.05));
  /* a fall deep enough to wash the market out puts the cash back: at −12% the reading is not halved */
  const deep = view({ base: LV2, candles, ...live, A: { ...A, dips: [12] } }).dips[0], deep1 = view({ base: LV, candles, ...live, A: { ...A, dips: [12] } }).dips[0]; assert.ok(deep.reading >= deep1.reading - 0.05, "a 12% fall: version 2 " + deep.reading + " against version 1 " + deep1.reading);
  /* the last year of days the page works out by itself joins the stored history (different sources for the bars and the payouts: a point or two; the raise-cash state must be the same) */
  const at = Object.fromEntries(H.d.map((d, i) => [d, [H.r[i], H.cash[i]]])); let n = 0, worst = 0; v.tail.dates.forEach((d, i) => { if (at[d] != null && (i < v.tail.dates.length - 1 || !v.live)) { worst = Math.max(worst, Math.abs(at[d][0] - v.tail.reading[i])); n++; } }); assert.ok(n > 200); assert.ok(worst <= 6, "worst gap against the stored history " + worst.toFixed(1));
  /* the odds and the stretch rules are still asked with the reading they were measured on */
  assert.deepEqual(v.odds, E.oddsAt(v.reading.v1.reading, LV.model)); const X = explain({ base: LV2, A, history: H, bars5: live.bars5, view: v, now: { date: v.session }, ui: {} }); assert.ok(near(X.live.number, C.numberAt(v.reading.reading, A), 1e-9)); assert.ok(X.room.rows.some((r) => r.sym === "ORCL" && r.starter)); });

test("17 · the tool, headless at 1680 and 390: version 2's two states, the split dial above the pies, Oracle's starter row, the two switches — and each does what it says; no error, no write, no sideways scroll, no text under 11px", async () => {
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const Pg = await openPage({ width: w, height: h }); try { const { page } = Pg;
    await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && document.getElementById("a9-root"), null, { timeout: 120000 }); await page.waitForTimeout(1200);
    const read = () => page.evaluate(() => { const st = window.DS1_LIVE, v = st.view, X = st.explain, host = document.getElementById("ds1money-host"), q = (s) => host.querySelector(s), leaves = [...host.querySelectorAll("*")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg"));
      return { v2: !!v.v2, v2Error: st.v2Error || null, cash: v.v2 && v.v2.cash, since: v.v2 && v.v2.since, v1: v.v2 && v.v2.v1 && v.v2.v1.reading, reading: v.reading.reading, number: +X.live.number.toFixed(2), kvCash: (q('[data-kv="cash"]') || {}).innerText, kvCashOn: q('[data-kv="cash"]') && q('[data-kv="cash"]').dataset.on, kvCredit: (q('[data-kv="credit"]') || {}).innerText, kvV1: (q('[data-kv="v1"]') || {}).innerText || null, dial: !!q('[data-a9="split"]'), dialValue: q("#a9-split") && +q("#a9-split").value, dialBeforePies: q('[data-a9="split"]') && q('.a9-row[data-chain="now"]') && !!(q('[data-a9="split"]').compareDocumentPosition(q('.a9-row[data-chain="now"]')) & Node.DOCUMENT_POSITION_FOLLOWING), dialVisible: q('[data-a9="split"]') && (() => { const d = q('[data-a9="split"]').closest("details"); return !d || d.id === "longversion"; })(),   /* DB1 (9 Oct): the whole panel sits under THE LONG VERSION; "in the open" = under no other fold (not inside ASSUMPTIONS) */
        mu: +X.today.names.MU.pct.toFixed(3), nb: +X.today.names.NBIS.pct.toFixed(3), orclRow: !!q('[data-room="ORCL"][data-starter="1"]'), orclText: (q('[data-room="ORCL"]') || {}).innerText || "", orclInPies: [...host.querySelectorAll(".a9-pie")].some((p) => /Oracle/.test(p.textContent)), rows: host.querySelectorAll("[data-room]").length, error: st.error, panelError: st.panelError || null, marks: [...host.querySelectorAll(".hd .warn")].map((e) => e.innerText), scrollW: document.scrollingElement.scrollWidth, minFont: Math.min(...leaves.map((e) => parseFloat(getComputedStyle(e).fontSize))), text: host.innerText, micronOfConv: st.A.micronOfConv, cashRule: st.A.cashRule }; });
    const r = await read(); assert.deepEqual(Pg.errors, []); assert.equal(r.error, null); assert.equal(r.panelError, null); assert.equal(r.v2, true, "the rule file loaded: " + r.v2Error); assert.deepEqual(r.marks, []);
    assert.ok(r.dial && r.dialVisible && r.dialBeforePies, "the split is a dial in the open, above the pies"); assert.equal(r.dialValue, 60); assert.equal(r.micronOfConv, 60); assert.match(r.text, /CONVICTION SPLIT\s+Micron 60 \/ Nebius 40/); assert.match(r.text, /baseline 60 \/ 40/);
    assert.ok(r.orclRow, "Oracle's row is a starter's"); assert.match(r.orclText, /dollar-cost starter/); assert.match(r.orclText, /0%/); assert.equal(r.orclInPies, false, "and it is in no pie"); assert.equal(r.rows, 9, "eight names and the account");
    assert.ok(r.kvCash && r.kvCredit, "the two states are on the number's block"); assert.equal(r.kvCashOn, r.cash ? "1" : "0"); if (r.cash) { assert.match(r.kvCash, /ON — tactical halved/); assert.match(r.text, /cash raised · since \d+ [A-Z][a-z]{2}/); assert.ok(r.kvV1, "and what today's rule would say is beside it"); }
    assert.ok(r.scrollW <= w, "no sideways scroll: " + r.scrollW); assert.ok(r.minFont >= 11, "no text under 11px: " + r.minFont); assert.ok(!/\bevenings?\b|\brungs?\b|\bv1\b|\bv2\b/i.test(r.text));
    /* the dial moved: Micron's conviction part grows, Nebius's shrinks, the two still add to conviction; BACK puts 60 / 40 back */
    await page.locator("#a9-split").evaluate((e) => { e.value = "80"; e.dispatchEvent(new Event("change", { bubbles: true })); }); await page.waitForTimeout(350); const d = await read(); assert.equal(d.micronOfConv, 80); assert.ok(d.mu > r.mu + 3 && d.nb < r.nb - 3, `Micron ${r.mu} → ${d.mu}, Nebius ${r.nb} → ${d.nb}`); assert.ok(Math.abs(d.mu + d.nb - (r.mu + r.nb)) < 0.01, "what one gains the other gives"); assert.match(d.text, /BACK TO 60 \/ 40/);
    await page.locator("[data-a9-split]").click(); await page.waitForTimeout(350); const e = await read(); assert.equal(e.micronOfConv, 60); assert.ok(Math.abs(e.mu - r.mu) < 0.01);
    /* the raise-cash rule switched off: the number is today's rule's (when credit is not being faded), and the block says so; the baseline button puts it back */
    await page.evaluate(() => { document.querySelector("#ds1money-host details.asm").open = true; }); await page.locator('#ds1money-host input[data-in="cashRule"]').fill("0"); await page.locator('#ds1money-host input[data-in="cashRule"]').dispatchEvent("change"); await page.waitForTimeout(350); const o = await read(); assert.equal(o.cashRule, 0); assert.match(o.kvCash, /switched off/); if (r.cash) assert.ok(o.reading > r.reading + 1, `with the rule off the reading is ${o.reading}, with it on ${r.reading}`);
    await page.locator('#ds1money-host input[data-in="creditRule"]').fill("0"); await page.locator('#ds1money-host input[data-in="creditRule"]').dispatchEvent("change"); await page.waitForTimeout(350); const o2 = await read(); assert.ok(Math.abs(o2.reading - r.v1) <= 0.11, `both switches off: ${o2.reading}, version 1 ${r.v1}`);
    await page.locator("#ds1money-host button[data-reset]").click(); await page.waitForTimeout(350); const b = await read(); assert.equal(b.cashRule, 1); assert.ok(Math.abs(b.reading - r.reading) <= 0.11);
    assert.equal(Pg.nonGet.blocked + Pg.nonGet.allowed, 0, "no write of any kind");
  } finally { await Pg.close(); } } });

test("18 · the page written for Alan: its figures are the study's own, plain words only, at most three decisions; it renders headless at 1680 and 390 — pictures load, the chart draws and reads a day, no error, no write, no sideways scroll, no text under 11px", async () => {
  const html = T("study/ds2/DS2.html"), text = html.replace(/<script[\s\S]*?<\/script>/g, "").replace(/<style[\s\S]*?<\/style>/g, "").replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/\s+/g, " "); const a = S.recommended.after, b = S.recommended.before;
  for (const want of [`${a.dates.L26low.toFixed(0)}% was ${b.dates.L26low.toFixed(0)}%`, `${a.dates.L25low.toFixed(0)}% was ${b.dates.L25low.toFixed(0)}%`, `${a.dates.T25.toFixed(0)}% was ${b.dates.T25.toFixed(0)}%`, `${b.payoff.became.toFixed(2)}× → ${a.payoff.became.toFixed(2)}×`, "added after the first run", "shaped by one of his dates", "It is not a call on the top", "Not pushed, not deployed", "has never been compiled"]) assert.ok(text.includes(want), "the page says: " + want);
  assert.ok(!BANNED.test(text), "an internal word on the page: " + (text.match(BANNED) || [])[0]); assert.equal((html.match(/<details class="sc-pagespecs">/g) || []).length, 1); assert.ok(!/−?-\d+\.\d%/.test(text.replace(/−/g, "")), "a figure with a hyphen for a minus");
  for (const f of [...html.matchAll(/<img src="pictures\/([^"]+)"/g)].map((m) => m[1])) assert.ok(fs.existsSync(path.join(ROOT, "study/ds2/pictures", f)), "the picture " + f + " exists");
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const Pg = await openPage({ width: w, height: h, path: "study/ds2/DS2.html" }); try { const { page } = Pg;
    await page.waitForFunction(() => window.DS2_PAGE_READY === true && [...document.querySelectorAll("img")].every((i) => i.complete), null, { timeout: 60000 });
    const r = await page.evaluate(() => { const els = [...document.querySelectorAll("body *")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0), q = (s) => document.querySelectorAll(s).length;
      return { scrollW: document.scrollingElement.scrollWidth, minFont: Math.min(...els.map((e) => parseFloat(getComputedStyle(e).fontSize))), imgs: [...document.querySelectorAll("img")].map((i) => i.naturalWidth > 0), dec: q("#dec li"), wrong: q("#wrong li"), not: q("#notdone li"), tiles: q("#tiles .tile"), paths: q("#svg path"), svgW: +document.getElementById("svg").getAttribute("width"), hostW: document.getElementById("chart").clientWidth, tables: q("table"), unwrapped: [...document.querySelectorAll("table")].filter((t) => !t.closest(".wrap")).length }; });
    assert.deepEqual(Pg.errors, []); assert.equal(Pg.nonGet.blocked + Pg.nonGet.allowed, 0); assert.ok(r.scrollW <= w, "no sideways scroll: " + r.scrollW); assert.ok(r.minFont >= 11, "no text under 11px: " + r.minFont); assert.ok(r.imgs.length >= 6 && r.imgs.every(Boolean), "every picture loads"); assert.ok(r.dec >= 1 && r.dec <= 3, "at most three decisions"); assert.ok(r.wrong >= 6 && r.not >= 4); assert.equal(r.tiles, 5); assert.equal(r.paths, 3, "SPY, before and after"); assert.ok(r.svgW <= r.hostW + 1); assert.equal(r.unwrapped, 0, "every table can scroll inside its own box");
    /* point at the March 2026 low: the read-out is that day's two numbers */
    await page.evaluate(() => document.getElementById("svg").scrollIntoView({ block: "center" })); await page.waitForTimeout(120); const at = await page.evaluate(() => { const D = DATA.series, i = D.d.indexOf("2026-03-30"), s = document.getElementById("svg").getBoundingClientRect(), W = +document.getElementById("svg").getAttribute("width"), x0 = 38, x1 = W - (W < 640 ? 8 : 92); return { x: s.left + x0 + (i / (D.d.length - 1)) * (x1 - x0), y: s.top + s.height * 0.7 }; });
    await page.mouse.move(at.x, at.y); await page.waitForTimeout(150); assert.equal(await page.evaluate(() => document.getElementById("read").innerText), `30 Mar 2026 · SPY ${S.recommended.named.find((n) => n.d === "2026-03-30").spy.toFixed(2)} · before ${b.dates.L26low.toFixed(1)}% · after ${a.dates.L26low.toFixed(1)}%`);
    await page.locator('#rg button[data-r="long"]').click(); await page.waitForTimeout(200); assert.equal(await page.evaluate(() => document.querySelectorAll("#svg path").length), 3);
  } finally { await Pg.close(); } } });
