/* DS3 tests (8 Oct 2026) — the % invested number, round 3.
   What they hold: the study's lab is DS1's lab and its version 2 is DS2's, as the build recorded it; version 3's arithmetic (one file for
   the study, this morning's read and the pane's proof); the scorecard and its pass rule as stored; the recommended version, before and
   after; the pane's version 3 script — its numbers, its budget, its plain words, a replay of it against the study's sum on every day, a
   second witness made by machine, and versions 2 and 1 exactly when its switches are off; the installer's task; the account kept out of
   the repository; this morning's record; the page for Alan.
   Nothing here writes and nothing reads the network. One test opens one headless page at a time (the study page, from disk). */
import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import crypto from "node:crypto"; import { execFileSync } from "node:child_process"; import { fileURLToPath } from "node:url";
import * as E from "../study/ds1/engine.mjs"; import * as V2 from "../study/ds2/number.mjs"; import * as V3 from "../study/ds3/number.mjs";
import { BASE_ACCOUNT, EXAMPLE_ACCOUNT, setAccount, useExampleAccount, accountIsExample, baseline } from "../study/ds1/live.mjs";
import { parsePine3, labelOf3, labelsOf3 } from "../study/ds3/pane-replay.mjs"; import { parsePine2, replay2 } from "../study/ds2/pane-replay.mjs"; import { runFromText3, functionText } from "../study/pn1/pine-transliterate.mjs";
import { buildPine3 } from "../scripts/ds3-build-pine.mjs"; import { engineV3On, scriptV3On, vixSeries, codeOf, rulesInScript } from "../scripts/ds3-prove-pane.mjs"; import { seriesOf } from "../scripts/ds2-prove-pane.mjs"; import { checkSaved3 } from "../scripts/ds3-check-saved.mjs"; import { DAYS } from "../scripts/ds3-build-task.mjs";
import { openPage } from "./_harness.mjs";
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), ".."), J = (f) => JSON.parse(fs.readFileSync(path.join(ROOT, f), "utf8")), T = (f) => fs.readFileSync(path.join(ROOT, f), "utf8"), near = (a, b, tol) => Math.abs(a - b) <= tol, sha = (t) => crypto.createHash("sha256").update(t).digest("hex");
const S = J("study/ds3/data/ds3.json"), LIVE = J("study/ds3/data/ds3-live.json"), R = LIVE.rules, LV = J("study/ds1/data/ds1-live.json"), DS2 = J("study/ds2/data/ds2.json"), F = J("tests/fixtures/pn1-closes-20261006.json"), VX = J("tests/fixtures/ds3-vix-20261006.json"), P = J("study/ds3/data/ds3-pane-proof.json"), M = J("study/ds3/data/ds3-morning.json");
const SRC = T("study/pn1/SCINTILLA-DEPLOYMENT-PANE.pine"), SRC2 = T("study/pn1/SCINTILLA-DEPLOYMENT-PANE.v2.pine"), K = parsePine3(SRC), CODE = codeOf(SRC), STRINGS = [...CODE.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => m[1]);
const ix = Object.fromEntries(F.dates.map((d, i) => [d, i])), LAST = F.dates.length - 1, ALL = [...S.candidates, ...S.combos], cand = (k) => ALL.find((c) => c.key === k), REC = S.recommended, V2B = S.version2;
let ENG, SAME; const sides = () => { ENG ??= engineV3On(F, VX, LV.model, R); SAME ??= scriptV3On(K, F, VX, F.hygWithPayouts); return { eng: ENG, same: SAME }; };

test("1 · the lab is DS1's lab and its version 2 is DS2's, as the build recorded it before it scored anything", () => {
  const L = S.labCheck; assert.equal(L.modelWorstDifference, 0); assert.equal(L.version1.same, true); assert.deepEqual(L.version1.here, { became: 3.54, worstFall: -30, invested: 85 });
  assert.equal(L.version2.samePayoff, true); assert.equal(L.version2.sameDates, true); assert.deepEqual(S.version2.payoff, DS2.recommended.after.payoff); for (const k of ["L25", "L25low", "L26", "L26low", "CUT", "T25", "T25top", "MOVE"]) assert.equal(S.version2.dates[k], DS2.recommended.after.dates[k], k);
  assert.equal(R.extPct, DS2.recommended.rules.extPct); assert.equal(S.asOf, DS2.asOf, "the same days DS2 ran on"); });

test("2 · version 3's arithmetic: Alan's steps add nothing under 20, 10 at a close of 20, 20 at a close of 23, half for a touch; a treasury rally can only raise the credit part; with both switches off it is version 2", () => {
  const st = (c, h) => V3.vixAdd(c, h, R); assert.equal(st(15.73, 16.02), 0, "at this morning's VIX it adds nothing"); assert.equal(st(19.99, 19.99), 0); assert.equal(st(20, 20), 10); assert.equal(st(22.99, 22.99), 10); assert.equal(st(23, 23), 20); assert.equal(st(52.33, 57.52), 20);
  assert.equal(st(19.2, 20.6), 5, "a touch of 20 counts half"); assert.equal(st(21, 23.5), 15, "a close over 20 with a touch of 23: 10 and half of the second 10"); assert.equal(st(19.5, 23.2), 10, "a touch of both: half of each"); assert.equal(st(21, 20), 10, "a high under the close is the close"); assert.equal(st(null, 25), null); assert.equal(V3.vixAdd(null, null, { ...R, vixRule: 0 }), 0, "switched off it needs no VIX");
  assert.deepEqual(V3.stepsOf(R), { lo: 20, hi: 23, addLo: 10, addHi: 20, touch: 0.5 });
  /* the credit part: read on credit's own move as before; when treasuries rallied, also on HYG's move alone, and the higher counts */
  const cr = LV.model.parts.find((p) => p.key === "creditOwn"), sc = LV.model.scale, pts = (z) => V3.partPoints(cr, z, sc);
  for (const [hyg, ief] of [[0.06, 1.43], [-0.1, 0.65], [-2.2, 1.5], [-6, 3], [0.5, 0.2], [1.2, 2.5]]) { const own = hyg - E.RATES_SHARE * ief, a = pts(own), b = V3.creditPointsV3(cr, sc, own, hyg, ief, R); assert.ok(b >= a - 1e-12, "never lower than version 2's"); assert.ok(near(b, Math.max(a, pts(hyg)), 1e-12)); }
  for (const [hyg, ief] of [[-0.55, -1.15], [-0.81, -0.78], [0.3, -0.4], [-0.74, 0]]) { const own = hyg - E.RATES_SHARE * ief; assert.equal(V3.creditPointsV3(cr, sc, own, hyg, ief, R), pts(own), "treasuries did not rally: nothing changes"); }
  assert.ok(V3.creditPointsV3(cr, sc, -2.95, -0.74, 4.42, R) > 0 && pts(-0.74) < 0, "on a big flight to safety the washout's add is kept, not swapped for HYG's own mild reading");
  assert.equal(V3.creditPointsV3(cr, sc, -0.65, 0.06, 1.43, { ...R, fearRule: 0 }), pts(-0.65));
  /* one reading, from bare points */
  const b = { base: 49.1, rsiPoints: 12, creditPoints: -8, rsi: 50, cash: false, vixClose: 21, vixHigh: 22 }; assert.equal(V3.readingV3(b, R), 49.1 + 12 - 8 + 10); assert.equal(V3.readingV3({ ...b, cash: true }, R), (49.1 + 12 - 8 + 10) / 2, "the VIX's points are halved with the rest while cash is raised"); assert.equal(V3.readingV3({ ...b, rsiPoints: 60 }, R), 100, "held to 100");
  assert.equal(V3.readingV3(b, { ...R, vixRule: 0, fearRule: 0 }), V2.readingV2({ base: b.base, rsiPoints: b.rsiPoints, creditPoints: b.creditPoints, rsi: b.rsi, cash: b.cash }, R)); assert.equal(V3.readingV3({ ...b, vixClose: null, vixHigh: null }, R), null, "the VIX is counted and has no price: no reading"); });

test("3 · the scorecard as stored: nineteen changes declared before the run and one added after it, marked; every verdict is the pass rule applied to that line's own numbers", () => {
  assert.equal(S.candidates.length, 20); assert.deepEqual(S.candidates.filter((c) => c.addedAfterFirstRun).map((c) => c.key), ["f1x"]); assert.deepEqual(S.candidates.map((c) => c.key), ["e1c", "e1h", "e1", "e1u", "e1a", "e2", "e2x", "e2m", "e2p", "b50", "b100", "b", "b100a", "ba", "f1", "f1r", "f2", "f2a", "f3", "f1x"]);
  const b = V2B.payoff, e = V2B.dates, base26 = cand("f1").stretch.onToday.byCredit === undefined ? null : S.recommended.stretches.mar26.today.byCredit;
  for (const c of ALL) { const p = c.payoff, d = c.dates, whole = p.timing >= b.timing - 0.005 && p.worstFall >= b.worstFall - 1.0 && p.becameAfterCost >= 0.99 * b.becameAfterCost; assert.equal(c.passWhole, whole, c.key + " whole period");
    const up = [d.L25 - e.L25, d.L26 - e.L26, e.T25 - d.T25], noWorse = !up.some((v) => v <= -1.0), dates = c.family === "f" ? noWorse && (up.some((v) => v >= 1.0) || (base26 < 0 && c.stretch.onToday.byCredit >= base26 / 2)) : noWorse && up.some((v) => v >= 1.0); assert.equal(c.passDates, dates, c.key + " his dates");
    assert.ok(near(c.bar.afterCostPct, (p.becameAfterCost / b.becameAfterCost - 1) * 100, 0.006)); assert.ok(near(c.bar.y0409Pct, (c.y0409.became / V2B.y0409.became - 1) * 100, 0.006)); }
  assert.deepEqual(S.candidates.filter((c) => c.passWhole && c.passDates).map((c) => c.key), ["e2", "f1r"], "the two that passed both bars alone");
  /* what the page says of each family */
  for (const k of ["e1c", "e1h", "e1", "e1u", "e1a", "e2x", "e2m", "e2p", "b50", "b100", "b", "b100a", "ba"]) { assert.equal(cand(k).passWhole, false, k); assert.equal(cand(k).passDates, true, k); }
  for (const k of ["b50", "b100", "b", "b100a", "ba"]) { assert.equal(cand(k).dates.L26low, 100); assert.equal(cand(k).dates.L25low, 100); assert.equal(cand(k).bar.timing, false, k + " fails on timing against version 2"); }
  assert.equal(cand("b100a").bar.y0409Pct, -4.4, "DS2's figure for depth through 2008"); assert.ok(cand("b100a").payoff.timing >= S.version1.payoff.timing - 0.005, "against today's rule, DS2's bar, depth still passes");
  for (const k of ["e2", "e2x", "e2m", "e2p", "e1a", "b100a", "ba", "f1", "f1x", "f2a", "f3"]) assert.equal(cand(k).today.adds, 0, k + " adds nothing at a VIX of 15.7"); assert.ok(cand("e1c").today.adds > 0.5 && cand("e1h").today.adds > 0.5, "the free measured curves add at a low VIX");
  assert.equal(cand("f2a").payoff.became, Math.max(...S.candidates.map((c) => c.payoff.became)), "the fear add had the best end result of the twenty"); assert.ok(cand("f2a").datesUp[2] <= -1, "and makes December 2025 heavier"); assert.ok(cand("f2").datesUp[1] <= -1, "as a third part it lowers the March 2026 low");
  /* (f): no form changes 26 → 30 March 2026 by reading a rally — treasuries were down over the ten sessions on both days */
  const m26 = S.recommended.stretches.mar26; assert.ok(m26.legs.every((l) => l.ief10 < 0)); for (const k of ["f1", "f1x", "f2a", "f3"]) assert.equal(cand(k).stretch.onToday.byCredit, m26.today.byCredit, k);
  /* the first form lowered the number on flight-to-safety days; the corrected form never does */
  const D = S.evidence.fear.f1Days; for (const w of ["everyDay", "fittedTo2017"]) { assert.ok(D[w].f1.lowered.n > 100); assert.ok(D[w].f1.lowered.share20 > D[w].any.share20, "the days it lowered were followed by a higher market more often than an ordinary day"); assert.equal(D[w].f1x.lowered, 0); assert.ok(D[w].f1x.raised.n > 500); }
  /* DS1's keep rule: Alan's steps and a treasury rally earn a vote; the VIX's place does not */
  const pt = Object.fromEntries(S.evidence.partTests.map((p) => [p.key, p.verdict])); assert.equal(pt.vixStep, "vote"); assert.equal(pt.tRally, "vote"); assert.equal(pt.vixStepFree, "vote", "his steps earn it with the curve left free too"); assert.equal(pt.tRallyFree, "light", "a treasury rally earns it only while its curve is held — and the page says so"); for (const k of ["vixPct", "vixHiPct", "cVix", "cVixUp", "depth50", "depth100", "depth"]) assert.equal(pt[k], "light", k); });

test("4 · the recommended version, before and after: both lows higher, 23 February higher, December unchanged, never under version 2 on any day — and ahead on the years it had not seen every way the test was run, at a cost through 2008", () => {
  assert.equal(REC.key, "e2 + f1x"); const A = REC.after, B = REC.before; assert.deepEqual(B.payoff, V2B.payoff);
  assert.ok(A.dates.L25low >= B.dates.L25low + 3 && A.dates.L26low === 100 && B.dates.L26low < 96); assert.ok(A.dates.feb23 >= B.dates.feb23 + 5); assert.ok(near(A.dates.T25, B.dates.T25, 0.2) && A.dates.T25top === B.dates.T25top); assert.equal(A.dates.CUT, 0); assert.equal(A.dates.last, B.dates.last, "nothing changes on the last day: the VIX is under 20 and treasuries are down");
  assert.ok(A.payoff.became > B.payoff.became && A.payoff.becameAfterCost > B.payoff.becameAfterCost && A.payoff.timing >= B.payoff.timing - 0.005 && A.payoff.worstFall >= B.payoff.worstFall - 1.0); assert.equal(cand(REC.key).passWhole && cand(REC.key).passDates, true);
  for (const k of Object.keys(S.firm.otherFits)) { const r = (n) => S.firm.otherFits[k].rows.find((x) => x.name === n); for (const n of [REC.key, "e2", "f1x"]) assert.ok(r(n).became > r("version 2").became, n + " ahead in: " + S.firm.otherFits[k].label); assert.ok(r(REC.key).timing >= r("version 2").timing - 0.005); }
  assert.ok(A.y0409.became < B.y0409.became, "it does worse through 2008, and the page says so"); const worse = S.firm.years.filter((y) => y[REC.key] < y["version 2"] - 0.049).map((y) => y.year); assert.deepEqual(worse, [2018, 2022]); assert.ok(S.firm.years.filter((y) => worse.includes(y.year)).every((y) => y.buyAndHold < 0), "the two years the market fell");
  /* never under version 2, on any session the page draws */
  for (const D of [S.series, S.long]) for (let i = 0; i < D.d.length; i++) if (D.n3[i] != null) assert.ok(D.n3[i] >= D.n2[i] - 0.051, D.d[i]);
  const nm = Object.fromEntries(REC.named.map((n) => [n.d, n])); assert.equal(nm["2026-03-30"].number3, 100); assert.equal(nm["2026-03-30"].number2, 94.8); assert.equal(nm["2025-03-28"].number3, 95); assert.equal(nm["2026-02-23"].number3, 90); assert.equal(nm["2026-02-23"].raisedByRally, 1); assert.equal(nm["2025-03-28"].raisedByRally, 1); assert.equal(nm["2026-03-30"].raisedByRally, 0); assert.equal(nm["2026-09-16"].number3, nm["2026-09-16"].number2);
  /* the stretches: on 23 Feb 2026 and 28 Mar 2025 treasuries had rallied over the ten sessions; on 26–30 Mar 2026 they had not */
  const st = REC.stretches; assert.ok(st.feb23.legs[1].ief10 > 1 && st.feb23.legs[1].hyg10 > 0 && st.feb23.today.d < 0 && st.feb23.version3.d > 0); assert.ok(st.mar25.legs[1].ief10 > 0 && st.mar25.version3.byCredit > st.mar25.version2.byCredit); assert.ok(st.mar26.legs.every((l) => l.ief10 < 0));
  assert.ok(REC.wrongWay.version3.cutOnADownDay <= REC.wrongWay.version2.cutOnADownDay); assert.equal(REC.fearDays.loweredOn, 0);
  /* the sensitivity: every level and size the steps were moved to ends ahead of version 2 */
  assert.equal(S.firm.sensitivity.length, 13); for (const s of S.firm.sensitivity) assert.ok(s.became > B.payoff.became, s.what); });

test("5 · the rule file and the one sum: version 3's thresholds; every plan the morning's read uses; applyV3 is readingV3", () => {
  assert.deepEqual({ vixRule: R.vixRule, vixLo: R.vixLo, vixHi: R.vixHi, vixAddLo: R.vixAddLo, vixAddHi: R.vixAddHi, vixTouch: R.vixTouch, fearRule: R.fearRule }, { vixRule: 1, vixLo: 20, vixHi: 23, vixAddLo: 10, vixAddHi: 20, vixTouch: 0.5, fearRule: 1 }); for (const k of Object.keys(V2.RULES)) if (k !== "extPct") assert.equal(R[k], V2.RULES[k], k);
  assert.equal(LIVE.recommended, REC.key); for (const k of ["v1", "v2", "e2", "f1x", "e2 + f1x", "f1x@v1"]) assert.ok(LIVE.plans[k], "a plan for " + k); assert.equal(LIVE.plans[REC.key].creditBest, true); assert.deepEqual(LIVE.plans[REC.key].steps, { by: "level", T: V3.STEPS });
  const { eng } = sides(); let n = 0; const cr = LV.model.parts.find((p) => p.key === "creditOwn"), rs = LV.model.parts.find((p) => p.key === "rsi"), sc = LV.model.scale, base = V2.typicalDay(LV.model);
  for (const d of REC.named.map((x) => x.d)) { const e = eng[ix[d]], pts = V3.creditPointsV3(cr, sc, e.creditOwn, e.hyg10, e.ief10, R), want = V3.readingV3({ base, rsiPoints: V3.partPoints(rs, e.rsi, sc), creditPoints: pts, rsi: e.rsi, cash: e.cash, vixClose: e.vixClose, vixHigh: e.vixHigh }, R); assert.ok(near(e.reading, want, 0.0500001), d); n++; } assert.equal(n, REC.named.length); });

test("6 · the pane's script is what the build writes; its numbers are the rule file's; version 2 is kept byte for byte; the lines version 3 did not change are version 2's", () => {
  assert.equal(buildPine3(), SRC, "study/pn1/SCINTILLA-DEPLOYMENT-PANE.pine is what scripts/ds3-build-pine.mjs writes"); rulesInScript(K, R); assert.deepEqual({ creditRule: K.creditRule, cashRule: K.cashRule, vixRule: K.vixRule, fearRule: K.fearRule }, { creditRule: true, cashRule: true, vixRule: true, fearRule: true }); assert.equal(K.funds.vix.symbol, "TVC:VIX");
  assert.match(T("study/ds2/TASK-KIMI-DEPLOYMENT-PANE-VERSION-2.md"), new RegExp(sha(SRC2)), "version 2's file has the sha256 DS2's task was written for");
  for (const f of ["wilderRsi", "pointsAt", "offHigh", "overAvg"]) assert.deepEqual(functionText(SRC, f), functionText(SRC2, f), f + " is version 2's, word for word");
  const K2 = parsePine2(SRC2); for (const k of ["RSI_DAYS", "CREDIT_DAYS", "RATES_SHARE", "TYPICAL_DAY", "RSI_PLACES", "CREDIT_PLACES", "RSI_POINTS", "CREDIT_POINTS", "FADE_FROM", "FADE_TO", "HIGH_DAYS", "AVG_DAYS", "NEAR_PCT", "EXT_PCT", "RESET_RSI", "CASH_CUT", "heldPct", "tacticalPct"]) assert.deepEqual(K[k], K2[k], k);
  /* every line of version 2's code is still in version 3, in the same order, except the lines version 3 rewrote */
  const a = codeOf(SRC2).split("\n"), b = codeOf(SRC).split("\n"); let j = 0, kept = 0; for (const ln of a) { const at = b.indexOf(ln, j); if (at >= 0) { kept++; j = at + 1; } } assert.ok(a.length - kept <= 16, "version 3 rewrote " + (a.length - kept) + " of version 2's " + a.length + " code lines"); assert.ok(kept >= 200); });

test("7 · the TradingView protocol: version 6, the plot budget stated in the header and counted from the code, ten requests, none looking ahead, no white", () => {
  assert.ok(SRC.startsWith("//@version=6\n"));
  const plots = [...CODE.matchAll(/^(?:\w+\s*=\s*)?plot\((.*)\)\s*$/gm)].map((m) => m[1]), fills = (CODE.match(/^fill\(/gm) || []).length, bands = (CODE.match(/^bgcolor\(/gm) || []).length, constCol = (x) => /color = (C_[A-Z_]+|color\.new\(C_[A-Z_]+, \d+\))(,|$)/.test(x);
  const count = plots.reduce((n, x) => n + (constCol(x) ? 1 : 2), 0) + fills + 2 * bands, stated = SRC.match(/^\/\/ PLOTS (\d+)\/64/m); assert.equal(plots.length, 16); assert.equal(fills, 1); assert.equal(bands, 1); assert.equal(count, 23); assert.equal(+stated[1], count); assert.ok(count <= 64);
  const req = (CODE.match(/request\.\w+\(/g) || []).length, statedReq = SRC.match(/^\/\/ REQUESTS (\d+)\/40/m); assert.equal(req, 10); assert.equal(+statedReq[1], req); assert.equal((CODE.match(/lookahead = barmerge\.lookahead_off/g) || []).length, 10, "no request looks ahead");
  assert.ok(!/color\.white|#fff\b|#ffffff/i.test(SRC)); for (const [, h] of CODE.matchAll(/#([0-9A-Fa-f]{6})\b/g)) { const [r, g, bl] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)); assert.ok(!(Math.min(r, g, bl) >= 200 && Math.max(r, g, bl) - Math.min(r, g, bl) <= 40), "#" + h + " reads as white"); }
  assert.ok(!/color\.(gray|silver|black|red|green|blue|yellow|orange|purple|aqua|lime|teal|navy|olive|maroon|fuchsia)\b/.test(CODE), "only the named palette at the top of the script");
  assert.ok(!SRC.includes("\t")); const lines = CODE.split("\n"); let depth = 0; for (const [i, ln] of lines.entries()) { const bare = ln.replace(/"(?:[^"\\]|\\.)*"/g, '""').replace(/\/\/.*$/, ""); if (depth > 0) assert.match(ln, /^ {5}\S/, "wrapped line " + (i + 1)); assert.equal((bare.match(/"/g) || []).length % 2, 0, "an open quote on line " + (i + 1)); depth += (bare.match(/\(/g) || []).length - (bare.match(/\)/g) || []).length; assert.ok(depth >= 0); }
  assert.equal(depth, 0); for (const ln of lines) if (!/^ {5}\S/.test(ln)) assert.equal(ln.match(/^ */)[0].length % 4, 0, "off the four-space grid: " + ln.slice(0, 40));
  /* a missing value is never leaned on: where a part is missing the script says so, and the raise-cash state only moves on a day with a reading */
  for (const want of ["float ptsFitted = na(ptsOwn) ? na : fearRule and rally and not na(ptsAlone) ? math.max(ptsOwn, ptsAlone) : ptsOwn", "float vixTop    = na(vixHigh) ? vixClose : math.max(vixHigh, vixClose)", "float ptsVix    = not vixRule ? 0.0 : na(vixClose) ? na :", "float beforeCut = na(ptsRsi) or na(ptsCredit) or na(ptsVix) ? na :", "if not na(ptsRsi) and not na(ptsFitted) and not na(ptsVix)"]) assert.ok(CODE.includes(want), want); });

test("8 · plain words: nothing a person reads on the chart or in the settings carries an internal code; the labels say what the VIX adds and when cash is raised", () => {
  const banned = [/\bv\d\b/i, /\bevening/i, /\brung/i, /\bDS\d\b/, /\bPN\d\b/, /\bAL\d\b/, /\blane\b/i, /\bn\/a\b/i, /\bNaN\b/, /undefined/, /\blatch/i, /\ba2f?\b/, /\bd2L?\b/, /\be2[xmp]?\b/, /\bf1[xr]?\b/, /\bf2a?\b/];
  assert.ok(STRINGS.length > 45); for (const s of STRINGS) for (const b of banned) assert.ok(!b.test(s), JSON.stringify(s) + " carries " + b); for (const b of banned) assert.ok(!b.test(SRC.slice(0, SRC.indexOf("\nindicator(")).replace(/\bd2\b/g, "")), "the script's header carries " + b);
  for (const want of ["Count the VIX: adds from 20, more from 23", "A Treasury rally can only raise the credit part", "Show version 2's line beside it", "Show version 1's line beside it", "the VIX adds, points of the market reading", "a Treasury rally raised the credit part (1 = yes)", "% invested, version 2", "% invested, version 1", "version 2 (line)", "the VIX: 50 + its points", "The VIX", "TVC:VIX", "Credit does not subtract in a washed-out market", "Raise cash at an extended high, put it back at the next washout"]) assert.ok(STRINGS.includes(want), "the script says " + JSON.stringify(want));
  const { same } = sides(), low = same[ix["2026-03-30"]], feb = same[ix["2026-02-23"]], dec = same[ix["2025-12-11"]]; assert.equal(labelOf3(low), "Invested 100% · market reading 100 · VIX +20"); assert.equal(labelOf3(feb), "Invested 90% · market reading 67 · VIX +10"); assert.equal(labelOf3(dec), "Invested 78% · market reading 26 · cash raised");
  assert.deepEqual(labelsOf3(low, { showOld: true, showV2: true }).map((l) => l.text), ["Invested 100% · market reading 100 · VIX +20", "version 2: 95%", "version 1: 88%"]);
  assert.ok(CODE.includes('array.push(ts, "Invested " + whole(invested) + "% · market reading " + whole(reading) + (cashOn ? " · cash raised" : "") + (ptsVix > 0 ? " · VIX +" + whole(ptsVix) : ""))'), "the label's words in the script are the words the replay prints");
  assert.equal(labelOf3({ invested: null, spyRsi: 60, qqqRsi: 60, hygMove: 0.1, iefMove: 0.1, vixWaiting: true }), "No reading yet · waiting for prices from VIX"); });

test("9 · a replay of the script against the study's sum, on the same closes: the same reading, the same raise-cash days, the same VIX add and the same treasury flag on every day there is — and the proof as stored says the same", () => {
  const { eng, same } = sides(); let days = 0, worst = 0, cash = 0, parts = 0, oneSided = 0; for (let i = 0; i <= LAST; i++) { if ((eng[i].reading == null) !== (same[i].reading == null)) { oneSided++; continue; } if (eng[i].reading == null) continue; days++; worst = Math.max(worst, Math.abs(eng[i].reading - same[i].reading)); if (!!eng[i].cash !== !!same[i].cashOn) cash++; if (eng[i].vixAdd !== same[i].ptsVix || !!eng[i].raisedByRally !== !!same[i].raisedByRally) parts++; }
  assert.equal(days, 4894); assert.equal(oneSided, 0); assert.ok(worst <= 1e-9, "worst gap " + worst); assert.equal(cash, 0); assert.equal(parts, 0); assert.equal(F.dates[eng.findIndex((e) => e.reading != null)], "2007-04-25");
  const H = P.history; assert.equal(H.samePrices.days, days); assert.equal(H.samePrices.worst, 0); assert.equal(H.samePrices.raiseCashDaysThatDiffer, 0); assert.equal(H.raiseCashDays.engine, H.raiseCashDays.script); assert.equal(H.version3Parts.daysItsAddDiffers, 0); assert.equal(H.version3Parts.daysThatFlagDiffers, 0); assert.equal(H.version3Parts.daysTheVixAdds, eng.filter((e) => e.vixAdd > 0).length);
  assert.equal(P.allWithinOnePoint, true); assert.equal(P.script.codeHash, crypto.createHash("sha256").update(CODE).digest("hex").slice(0, 16), "the proof is of the script on disk"); assert.ok(H.tradingViewPayouts.shareWithin1 > 99.5 && H.lastYear.tradingViewPayouts.worst <= 1);
  for (const n of REC.named) { const r = P.rows.find((x) => x.date === n.d); assert.ok(r, n.d); assert.equal(r.gap, 0); assert.ok(near(r.script.invested, n.number3, 0.0600001), n.d + " the script's % invested is the study's"); assert.ok(near(r.script.version2.invested, n.number2, 0.0600001)); assert.ok(near(r.script.version1.invested, n.number1, 0.0600001)); }
  assert.ok(P.today.length >= 1); for (const t of P.today) { assert.ok(t.engine, "a stored read failed: " + t.failed); assert.equal(t.gap, 0); assert.equal(t.sameRaiseCashState, true); assert.equal(t.engine.vixAdd, 0); assert.equal(t.engine.treasuriesUpOverTenSessions, false); assert.ok(near(t.script.invested, t.script.version2.invested, 1e-9), "this morning version 3 is version 2"); } });

test("10 · with version 3's two switches off the script is version 2's own script on every day, with all four off version 1's; a second witness made by machine gives the hand-written replay's reading; a changed number is caught", () => {
  const { same } = sides(), funds = { spy: seriesOf(F, F.SPY), qqq: seriesOf(F, F.QQQ), ief: seriesOf(F, F.IEF), hyg: seriesOf(F, F.hygWithPayouts) }, v2 = replay2(parsePine2(SRC2), funds, F.dates), off = scriptV3On(K, F, VX, F.hygWithPayouts, { vixRule: false, fearRule: false });
  let n = 0, w = 0, wThin = 0; for (let i = 0; i <= LAST; i++) { assert.equal(v2[i].reading == null, off[i].reading == null); if (v2[i].reading == null) continue; n++; w = Math.max(w, Math.abs(v2[i].reading - off[i].reading)); assert.equal(!!v2[i].cashOn, !!off[i].cashOn); if (same[i].reading != null) wThin = Math.max(wThin, Math.abs(v2[i].reading - same[i].reading2)); } assert.equal(n, 4894); assert.ok(w <= 1e-9 && wThin <= 1e-9);
  assert.equal(P.history.newSwitchesOff.worstAgainstVersion2sOwnScript, 0); assert.equal(P.history.allSwitchesOff.worstAgainstVersion1sOwnScript, 0); assert.equal(P.history.theThinLines.worstOfVersion2sLine, 0); assert.equal(P.history.theThinLines.worstOfVersion1sLine, 0);
  const mech = runFromText3(SRC, { ...funds, vix: vixSeries(VX) }, F.dates, { heldPct: K.heldPct, tacticalPct: K.tacticalPct }); let m = 0, wm = 0; for (let i = 0; i <= LAST; i++) { const has = !(mech[i].reading == null || Number.isNaN(mech[i].reading)); assert.equal(has, same[i].reading != null); if (!has) continue; m++; wm = Math.max(wm, Math.abs(mech[i].reading - same[i].reading), Math.abs(mech[i].ptsVix - same[i].ptsVix)); assert.equal(!!mech[i].cashOn, !!same[i].cashOn); } assert.equal(m, 4894); assert.ok(wm <= 1e-9);
  /* the translation refuses a line it has no rule for, and a changed sign shows */
  assert.throws(() => runFromText3(SRC.replace("float hygAlone  = hygMove * 100.0", "hygAlone = hygMove * 100.0"), { ...funds, vix: vixSeries(VX) }, F.dates, { heldPct: 70, tacticalPct: 30 }));
  const flipped = runFromText3(SRC.replace("TYPICAL_DAY + ptsRsi + ptsCredit + ptsVix))", "TYPICAL_DAY + ptsRsi + ptsCredit - ptsVix))"), { ...funds, vix: vixSeries(VX) }, F.dates, { heldPct: 70, tacticalPct: 30 }); let differ = 0; for (let i = LAST - 251; i <= LAST; i++) if (Math.abs(flipped[i].reading - same[i].reading) > 0.05) differ++; assert.ok(differ >= 20, "a flipped sign shows on " + differ + " days of the last year");
  /* the check of the saved text */
  assert.deepEqual(checkSaved3(SRC).identical, true); const bad = checkSaved3(SRC.replace("const float  VIX_HI      = 23.0", "const float  VIX_HI      = 25.0")); assert.equal(bad.ok, false); assert.equal(bad.numbersUnchanged, false); assert.ok(bad.replay.daysVersion3sPartsDiffer > 50);
  const cosmetic = checkSaved3(SRC.replace("// ── the sum ", "//  ── the sum ")); assert.equal(cosmetic.identical, false); assert.equal(cosmetic.ok, true, "a changed comment that touches no number still passes"); });

test("11 · the installer's task: beside the script, its nine days are the proof's own numbers, the three files with their sha256, one tab, not authorised by being written, and the way back", () => {
  const md = T("study/pn1/TASK-KIMI-DEPLOYMENT-PANE-VERSION-3.md"); assert.equal(DAYS.length, 9);
  for (const d of DAYS) { const r = P.rows.find((x) => x.date === d); assert.ok(r, d); assert.ok(md.includes(`| ${d} | ${r.scriptTradingViewPayouts.invested.toFixed(2)} | ${r.scriptTradingViewPayouts.reading.toFixed(1)} | ${r.script.rsi.toFixed(2)} | ${r.scriptTradingViewPayouts.creditOwn.toFixed(3)} | ${r.scriptTradingViewPayouts.cash ? 1 : 0} | ${r.script.vixAdd.toFixed(0)} | ${r.script.raisedByRally ? 1 : 0} | ${r.script.version2.invested.toFixed(2)} | ${r.script.version1.invested.toFixed(2)} |`), d); }
  for (const f of ["SCINTILLA-DEPLOYMENT-PANE.pine", "SCINTILLA-DEPLOYMENT-PANE.v2.pine", "SCINTILLA-DEPLOYMENT-PANE.v1.pine"]) assert.ok(md.includes("`" + f + "`") && md.includes(sha(T("study/pn1/" + f))), f + " with its sha256");
  for (const want of ["NOT authorised by being written", "You work in ONE tab", "Scintilla — Deployment", "Do NOT use \"Save as\"", "Zero errors is the only pass", "## The way back", "scripts/ds3-check-saved.mjs", "TVC:VIX", "never type or paste the script", "has never met the compiler"]) assert.ok(md.includes(want), want);
  assert.ok(!/buy \d+ shares|trim \d+ shares/.test(md)); });

test("12 · the account is not in the repository: the code starts from a made-up example and says so; the private file is ignored, never served to a test, and none of its figures is in a tracked file", () => {
  assert.equal(BASE_ACCOUNT, EXAMPLE_ACCOUNT, "at import the account is the example"); assert.equal(EXAMPLE_ACCOUNT.example, true); assert.match(EXAMPLE_ACCOUNT.asOf, /EXAMPLE ACCOUNT — made up/); assert.deepEqual(EXAMPLE_ACCOUNT.shares, {}); assert.equal(EXAMPLE_ACCOUNT.cash, 100000);
  const A = baseline(LV); assert.equal(A.cash, 100000); assert.deepEqual(A.shares, {}); assert.equal(accountIsExample(A), true); assert.equal(accountIsExample({ ...A, cash: 100001 }), false, "once a figure is typed it is no longer the example"); assert.equal(accountIsExample({ ...A, shares: { MU: 1 } }), false);
  for (const [bad, why] of [[null, /not an account/], [{ example: true, cash: 1 }, /the example/], [{ cash: "1" }, /cash/], [{ cash: -1 }, /cash/], [{ cash: 1, shares: [] }, /shares/], [{ cash: 1, shares: { XYZ: 1 } }, /XYZ/], [{ cash: 1, shares: { MU: -1 } }, /MU/]]) { const r = setAccount(bad); assert.equal(r.ok, false); assert.match(r.why, why); }
  /* a well-formed file is taken, and the example can be put back (made-up figures here) */
  assert.equal(setAccount({ cash: 123456, shares: { MU: 3 }, asOf: "a test" }).ok, true); const B = baseline(LV); assert.equal(B.cash, 123456); assert.deepEqual(B.shares, { MU: 3 }); assert.equal(accountIsExample(B), false); useExampleAccount(); assert.equal(baseline(LV).cash, 100000);
  const live = T("study/ds1/live.mjs"); assert.ok(!/export const BASE_ACCOUNT = \{ cash: \d/.test(live)); assert.ok(live.includes('"study/private/account.json"') && live.includes("localhost"), "the private file is asked for only on this machine");
  assert.match(T(".gitignore"), /^study\/private\/$/m); assert.equal(execFileSync("git", ["ls-files", "study/private"], { cwd: ROOT, encoding: "utf8" }).trim(), "", "nothing under study/private is tracked");
  const ex = J("study/account.example.json"); assert.equal(ex.example, true); assert.match(ex.note, /EXAMPLE — made up/); assert.equal(setAccount(ex).ok, false, "the example file is never taken for an account");
  assert.match(T("tests/_harness.mjs"), /startsWith\("\/study\/private\/"\)[^\n]*404/, "the test server refuses the private folder");
  /* when the private file is on this machine, none of its figures is in any tracked text file */
  const pf = path.join(ROOT, "study/private/account.json"); if (!fs.existsSync(pf)) return; const a = JSON.parse(fs.readFileSync(pf, "utf8")), words = { MU: "Micron", NBIS: "Nebius" }, needles = [String(a.cash), a.cash.toLocaleString("en-US"), "$" + Math.round(a.cash / 1000) + "K"]; for (const [s, n] of Object.entries(a.shares)) { needles.push(`${s}: ${n}`, `"${s}":${n}`, `"${s}": ${n}`, `${n} ${s}`); if (words[s]) needles.push(`${n} ${words[s]}`); }
  const files = execFileSync("git", ["ls-files"], { cwd: ROOT, encoding: "utf8" }).split("\n").filter((f) => f && !/\.(png|jpe?g|gif|webp|ico|woff2?)$/i.test(f) && fs.existsSync(path.join(ROOT, f))), hits = []; for (const f of files) { const t = fs.readFileSync(path.join(ROOT, f), "utf8"); needles.forEach((n, k) => { if (t.includes(n)) hits.push(f + " (figure " + k + ")"); }); } assert.deepEqual(hits, [], "a tracked file holds a figure of the private account"); });

test("13 · this morning as recorded: two reads of the market, before and after the open; treasuries were not up over the ten sessions; the window's day cancels; version 3 read what version 2 read", () => {
  assert.ok(M.reads.length >= 2); assert.equal(M.reads[0].phase, "pre-market"); assert.ok(M.reads.some((r) => r.phase === "open"));
  for (const r of M.reads) { assert.equal(r.session, "2026-10-08"); assert.equal(r.live, true); assert.deepEqual(r.missing, []); assert.ok(r.inputs[1].ief10 < 0, "treasuries are down over the ten sessions"); assert.ok(r.roll.iefToday <= 0.05, "and were not up on the day"); assert.ok(r.inputs[1].vix < R.vixLo && r.inputs[1].vixHigh < R.vixLo);
    assert.ok(near(r.roll.ofWhich.hygWindow + r.roll.ofWhich.treasuriesWindow, 0, 0.03), "what the window's day took off the treasury half it put back on HYG's own"); assert.ok(near(r.roll.ofWhich.hygToday + r.roll.ofWhich.hygWindow + r.roll.ofWhich.treasuriesToday + r.roll.ofWhich.treasuriesWindow, r.roll.dCreditOwn, 0.021), "the four pieces add to the change in credit's own move");
    const g = (k) => r.rows.find((x) => x.key === k); assert.equal(g(REC.key).to, g("v2").to); assert.equal(g(REC.key).from, g("v2").from); assert.equal(g("f1x@v1").to, g("v1").to, "the treasury rule would not have changed today's rule this morning either"); assert.equal(g("v1").from, 79.1); assert.ok(near(r.inputs[0].creditOwn, M.asAlanSawIt.creditOwn[0], 0.011), "7 Oct's close is the figure in the brief"); }
  assert.equal(M.reads[0].roll.theDayThatLeftTheWindow.date, "2026-09-24"); assert.ok(M.reads[0].roll.theDayThatLeftTheWindow.treasuries < -0.5); });

test("14 · the page written for Alan: its figures are the study's own, plain words only, no level and no order on it, at most three decisions; it renders headless at 1680 and 390 — pictures load, the chart draws and reads a day, no error, no write, no sideways scroll, no text under 11px", async () => {
  const html = T("study/ds3/DS3.html"), body = html.slice(html.indexOf("<body>"), html.indexOf("<script>")), text = body.replace(/<[^>]+>/g, " ").replace(/&amp;/g, "&").replace(/\s+/g, " ");
  const BANNED = /\bevenings?\b|\brungs?\b|\bv1\b|\bv2\b|\bv3\b|line vs reading|\bDS\d\b|\bAL\d\b|\bPN\d\b|\ba2f?\b|\bd2L\b|\be2[xmp]?\b|\bf1[xr]?\b|\bf2a?\b|\bb100a?\b|\blane\b|\bNaN\b|undefined|\blatch/; assert.ok(!BANNED.test(text), "the page carries " + (text.match(BANNED) || [])[0]);
  assert.ok(!/buy \d+ shares|trim \d+ shares|limit order|\bstop at \d|buy at \d|sell at \d/i.test(text), "no level and no order on the page"); assert.equal((body.match(/<section [^>]*id="p-decide"[\s\S]*?<\/section>/)[0].match(/<li>/g) || []).length, 3);
  const A = REC.after, B = REC.before, nm = Object.fromEntries(REC.named.map((n) => [n.d, n])); for (const want of [`${A.payoff.became.toFixed(2)}×`, `${B.payoff.became.toFixed(2)}×`, `${nm["2026-03-30"].number3.toFixed(0)}%`, "by your own rule, no", "This morning was not a treasury rally", "already on GitHub", "EXAMPLE ACCOUNT", "added after the first run", "has never met TradingView's compiler", "Not pushed, not deployed", "TASK-KIMI-DEPLOYMENT-PANE-VERSION-3.md", "earns a vote only while its curve is held"]) assert.ok(text.includes(want), "the page says " + JSON.stringify(want));
  for (const r of M.reads) assert.ok(text.includes(r.readAt.slice(11, 16)), "the read of " + r.readAt.slice(11, 16) + " is on the page");
  for (const f of [...html.matchAll(/<img src="pictures\/([^"]+)"/g)].map((m) => m[1])) assert.ok(fs.existsSync(path.join(ROOT, "study/ds3/pictures", f)), f);
  for (const [w, h] of [[1680, 1050], [390, 844]]) { const Pg = await openPage({ width: w, height: h, path: "study/ds3/DS3.html" }); try { const { page } = Pg; await page.waitForFunction(() => window.DS3_PAGE_READY === true && [...document.querySelectorAll("img")].every((i) => i.complete), null, { timeout: 60000 });
      const info = await page.evaluate(() => { const leaves = [...document.body.querySelectorAll("*")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg") && !e.closest("script") && !e.closest("style")); return { scrollW: document.scrollingElement.scrollWidth, innerW: innerWidth, minFont: Math.min(...leaves.map((e) => parseFloat(getComputedStyle(e).fontSize))), svgMinFont: Math.min(...[...document.querySelectorAll("svg text")].map((e) => parseFloat(e.getAttribute("font-size")))), imgs: [...document.querySelectorAll("img")].every((i) => i.naturalWidth > 0), paths: document.querySelectorAll("#svg path").length, svgW: +document.getElementById("svg").getAttribute("width"), svgTextRight: Math.max(...[...document.querySelectorAll("#svg text")].map((e) => e.getBoundingClientRect().right)), svgRight: document.getElementById("svg").getBoundingClientRect().right }; });
      assert.deepEqual(Pg.errors, [], "no error at " + w); assert.equal(Pg.nonGet.blocked + Pg.nonGet.allowed, 0, "no write at " + w); assert.ok(info.scrollW <= info.innerW, "no sideways scroll at " + w); assert.ok(info.minFont >= 11 && info.svgMinFont >= 11, "no text under 11px at " + w); assert.equal(info.imgs, true); assert.equal(info.paths, 4, "SPY, the VIX and the two versions are drawn"); assert.ok(info.svgTextRight <= info.svgRight + 0.5, "no chart label runs off the chart at " + w);
      const at = await page.evaluate(() => { document.getElementById("svg").scrollIntoView({ block: "center" }); const D = DATA.series, i = D.d.indexOf("2026-03-30"), s = document.getElementById("svg").getBoundingClientRect(), W = +document.getElementById("svg").getAttribute("width"), x0 = 38, x1 = W - (W < 640 ? 8 : 96); return { x: s.left + x0 + (i / (D.d.length - 1)) * (x1 - x0), y: s.top + s.height * 0.55 }; }); await page.mouse.move(at.x, at.y); await page.waitForTimeout(150);
      assert.equal(await page.evaluate(() => document.getElementById("read").innerText), `30 Mar 2026 · SPY ${nm["2026-03-30"].spy.toFixed(2)} · before ${nm["2026-03-30"].number2.toFixed(1)}% · after ${nm["2026-03-30"].number3.toFixed(1)}% · VIX ${nm["2026-03-30"].vixClose.toFixed(2)} (high ${nm["2026-03-30"].vixHigh.toFixed(2)})`);
      await page.locator('#rg button[data-r="long"]').click(); await page.waitForTimeout(200); assert.equal(await page.evaluate(() => document.querySelectorAll("#svg path").length), 4); } finally { await Pg.close(); } } });
