/* AL9 (7 Oct 2026) — the panel that explains itself: the first thing on the allocation tool. One number for how much of the account to
   have invested, how it moved today and since 2018, the chain that turns it into a size for every name (drawn as pies, now and fully
   invested), and the room left to play with the next two buy levels and the next two trim levels per name.
   Alan, 7 Oct ~15:30 New York: "I need to be able to just open the tool and it explain everything" · "All of this needs to be seen as
   one whole" · "I need it to be a specific number and to see how it changes throughout the day, and how it has changed in recent weeks,
   and what it would have looked like at those important lows".

   WHERE EVERY FIGURE COMES FROM
     the market reading     DS1's own sum (study/ds1/engine.mjs), on live prices: 0 = stretched, 100 = washed out
     the number             held part + tactical part × market reading ÷ 100 (study/al9/chain.mjs), averaged over the last hour
     today's path           the same sum at every five-minute price of SPY, QQQ, HYG and the 7–10 year treasury fund since 09:30 — worked
                            out again on every read from the market's own five-minute bars, so it is the same after a reload and on any
                            device, and nothing is stored anywhere
     the history            study/al9/data/history.json (every session since 2 Jan 2018, scripts/al9-history.mjs), then the sessions since
                            from the page's own daily bars
     the chain, the room    study/al9/chain.mjs on the dials in the assumptions panel and the account typed there
     the levels             each name's 21-, 50-, 100- and 200-day averages, the lines Alan reviewed (ds1-live.json), its usual cool-off
                            and its 60-session high
   Reads only. It draws into the money panel that study/ds1/live.mjs hands over; if this file throws, DS1's own picture is drawn instead. */
import * as E from "../ds1/engine.mjs";
import * as C from "./chain.mjs";
import { hygWithPayouts, phaseOf, nextReadWords, day, dayY } from "../ds1/live.mjs";

export const TITLE = "THE MONEY — the number, how it splits, how much room is left";   // the section bar calls this panel THE MONEY, so its title starts with the same words
const clamp = (x, a, b) => Math.max(a, Math.min(b, x)), esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const f0 = (x) => (x == null || !isFinite(x) ? "—" : x.toFixed(0)), f1 = (x) => (x == null || !isFinite(x) ? "—" : x.toFixed(1)), pc = (x, d = 1) => (x == null || !isFinite(x) ? "—" : x.toFixed(d) + "%");
const sg = (x, d = 1) => (x == null || !isFinite(x) ? "—" : (x > 0 ? "+" : x < 0 ? "−" : "") + Math.abs(x).toFixed(d)), px = (x) => (x == null || !isFinite(x) ? "—" : x >= 1000 ? x.toLocaleString("en-US", { maximumFractionDigits: x >= 10000 ? 0 : 2, minimumFractionDigits: x >= 10000 ? 0 : 2 }) : x.toFixed(2));
const usd = (x) => (x == null || !isFinite(x) ? "—" : (x < 0 ? "−" : "") + (Math.abs(x) >= 1000 ? "$" + (Math.abs(x) / 1000).toFixed(Math.abs(x) >= 100000 ? 0 : 1) + "K" : "$" + Math.abs(x).toFixed(0)));
const NYF = typeof Intl !== "undefined" ? new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", hourCycle: "h23", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }) : null;
export const nyClock = (ms) => { const p = Object.fromEntries(NYF.formatToParts(new Date(ms)).map((x) => [x.type, x.value])); return { date: `${p.year}-${p.month}-${p.day}`, minutes: +p.hour * 60 + +p.minute }; };
const hm = (min) => String(Math.floor(min / 60)).padStart(2, "0") + ":" + String(min % 60).padStart(2, "0");

/* ---------- the market reading at any four prices: DS1's own two counted parts, every other day as it closed ---------- */
export function makeReadAt(v, base) { const S = v.S, k = v.k, model = base.model, payouts = base.hygPayouts || [], lights = (v.reading && v.reading.lightsCounted) || 0, W = E.CREDIT_WINDOW;
  const spy = S.bars.SPY.c.slice(), qqq = S.bars.QQQ.c.slice(), hyg = S.bars.HYG ? S.bars.HYG.c.slice() : null, ief = S.bars.IEF ? S.bars.IEF.c.slice() : null;
  return (p) => { spy[k] = p.SPY; qqq[k] = p.QQQ; const rs = E.rsi(spy)[k], rq = E.rsi(qqq)[k]; if (rs == null || rq == null) return null; let own = null;
    if (hyg && ief && p.HYG != null && p.IEF != null) { hyg[k] = p.HYG; ief[k] = p.IEF; const tr = hygWithPayouts(S.dates, hyg, payouts).tr; if (tr[k] != null && tr[k - W] != null && ief[k - W] != null) own = ((tr[k] / tr[k - W] - 1) - E.RATES_SHARE * (ief[k] / ief[k - W] - 1)) * 100; }
    return clamp(E.readSystem({ rsi: (rs + rq) / 2, creditOwn: own }, model).raw + lights, 0, 100); }; }

/* ---------- everything the panel shows, from the live state (pure: the tests call it with a recorded state) ---------- */
export function explain(st, nowMs = Date.now()) {
  const v = st.view, A = st.A, base = st.base, S = v.S, k = v.k, ui = st.ui || {}, readAt = makeReadAt(v, base);
  const lastClose = {}; for (const s of C.VOTERS) lastClose[s] = S.bars[s] ? S.bars[s].c[k - 1] : null;   /* the close before the session shown — the bar before it, whether that session's own bar is the live one or already settled */
  const path = st.bars5 ? C.dayPath(st.bars5, v.session, nyClock, readAt, A, lastClose) : [], liveR = v.reading.reading, livePt = { number: C.numberAt(liveR, A), reading: liveR };
  const sm = C.smoothed(path, livePt, A, nowMs) || { ...livePt, points: 1, minutes: +A.smoothMin, min: livePt.number, max: livePt.number }, marks = C.dayMarks(path);
  const prevR = (v.prior && v.prior[0]) || null, yest = prevR ? { date: prevR.date, reading: prevR.reading, number: C.numberAt(prevR.reading, A) } : null;
  const hist = C.dailyHistory(st.history, v.tail, A), named = ((st.history && st.history.marks) || C.NAMED).map((m) => { const i = hist.d.indexOf(m.d); return i < 0 ? null : { d: m.d, kind: m.kind, i, reading: hist.r[i], number: hist.n[i], spy: hist.s[i] }; }).filter(Boolean);
  /* a moment picked on the chart shows the chain as it would have been then; the room to play is always today's */
  const asOf = ui.asOf && ui.asOf.reading != null ? ui.asOf : null, rChain = asOf ? asOf.reading : sm.reading, now = C.chainAt(rChain, A), today = asOf ? C.chainAt(sm.reading, A) : now, full = C.ceilingsOf(A);
  const breaking = {}, highs = {}; for (const s of C.CONVICTION) { const c = S.bars[s] && S.bars[s].c; breaking[s] = C.breakingOut(c, k, +A.breakoutDays); highs[s] = C.highOf(c, k, +A.breakoutDays); }
  const room = C.roomToPlay(today, full, v.account, A, breaking), lines = (base.lines && base.lines.names) || {};
  const levels = {}; for (const n of v.names) { if (n.absent || !C.ROWS.includes(n.sym)) continue; const cands = []; for (const lv of n.levels) { if (lv.kind === "average") cands.push({ id: lv.id + " average", level: lv.level }); if (lv.kind === "usual") cands.push({ id: "its usual cool-off", level: lv.level }); }
    for (const ln of lines[n.sym] || []) cands.push({ id: ln.id, level: ln.level }); const top = C.highOf(S.bars[n.sym].c, k, +A.breakoutDays); if (top != null) cands.push({ id: `its ${f0(+A.breakoutDays)}-session high`, level: top });
    const row = room.rows.find((x) => x.sym === n.sym) || { target: 0, allowed: 0, shares: 0 }; levels[n.sym] = { price: n.price, ...C.sizeOrders(row, C.nextLevels(n.price, cands, 2, +A.zonePct || 0.15), A, room.nlv), hasLines: !!(lines[n.sym] && lines[n.sym].length) }; }
  const dips = v.dips.map((d) => ({ dipPct: d.dipPct, reading: d.reading, number: C.numberAt(d.reading, A), spy: d.spy, qqq: d.qqq, reached: d.reached }));
  /* the session shown is today's own only while New York's date is that session's; after midnight, on a weekend or a holiday it is the last one traded, and the panel names it by its date instead of saying "today" */
  const nyDate = (st.now && st.now.date) || nyClock(nowMs).date, isToday = v.session === nyDate, dayWord = isToday ? "today" : day(v.session);
  return { v, A, path, sm, live: livePt, marks, yest, hist, named, asOf, now, today, full, room, levels, dips, breaking, highs, isToday, dayWord, prop: C.proportional(A, sm.reading) }; }

/* ---------- the pictures ---------- */
const CSS = `.a9{--a9-held:#74819a;--a9-ink:#0a0a0f;--a9-acc:var(--cyan,#00d4ff);border-top:0!important;margin-top:0!important;padding-top:0!important}
.a9 .a9-top{display:grid;grid-template-columns:minmax(0,372px) minmax(0,1fr);gap:10px 30px;margin-top:10px;align-items:start}
.a9 .a9-big{font-size:60px;font-weight:700;line-height:.95;letter-spacing:-.01em}.a9 .a9-sub{font-size:12px;color:var(--dimc);margin-top:5px}.a9 .a9-sub b{color:var(--txt,#e8e8f0);font-weight:600}
.a9 .a9-why{margin:7px 0 0;color:var(--dimc);font-size:11.5px}.a9 .a9-why b{color:var(--txt,#e8e8f0);font-weight:600}
.a9 .a9-kv{margin:9px 0 0;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:2px 12px;font-size:12px;border-top:1px solid #14141e;padding-top:7px}.a9 .a9-kv span{color:var(--dimc)}.a9 .a9-kv b{font-weight:600;text-align:right;font-variant-numeric:tabular-nums}.a9 .a9-kv i{font-style:normal;color:var(--dimc);font-weight:400}
.a9 .a9-asof{margin:8px 0 0;padding:6px 9px;border:1px solid var(--gold,#ffd166);border-radius:5px;font-size:11.5px;color:var(--txt,#e8e8f0)}.a9 .a9-asof b{color:var(--gold,#ffd166)}
.a9 button{background:none;border:1px solid var(--line,#1c1c28);color:var(--dimc);border-radius:5px;font:inherit;font-size:11px;padding:3px 9px;cursor:pointer;letter-spacing:.06em}.a9 button.on{color:var(--txt,#e8e8f0);border-color:#6a6a80}.a9 button:hover{color:var(--txt,#e8e8f0)}
.a9 .a9-hh{display:flex;flex-wrap:wrap;gap:6px 10px;align-items:center;justify-content:space-between}.a9 .a9-hh h4{margin:0}.a9 .a9-rg{display:flex;flex-wrap:wrap;gap:5px}
.a9 .a9-read{min-height:17px;margin:4px 0 0;font-size:11.5px;color:var(--dimc);font-variant-numeric:tabular-nums}.a9 .a9-read b{color:var(--txt,#e8e8f0);font-weight:600}
.a9 svg{display:block;max-width:100%}.a9 svg text{font-family:inherit}.a9 .a9-chart{cursor:crosshair;touch-action:pan-y}
.a9 .a9-sec{margin-top:16px;padding-top:12px;border-top:1px solid var(--line,#1c1c28)}
.a9 .a9-row{display:flex;flex-wrap:wrap;align-items:flex-start;gap:4px 8px;margin-top:8px}.a9 .a9-row .a9-ar,.a9 .a9-row .a9-rl{align-self:center}.a9 .a9-rl{flex:0 0 118px;font-size:11px;letter-spacing:.1em;color:var(--dimc)}.a9 .a9-rl b{display:block;font-size:22px;letter-spacing:0;color:var(--txt,#e8e8f0);font-weight:700;line-height:1.1}.a9 .a9-rl u{text-decoration:none;color:var(--gold,#ffd166)}
.a9 .a9-pie{flex:0 0 auto}.a9 .a9-pie .t{font-size:11px;color:var(--dimc);margin:0 0 3px;white-space:nowrap;line-height:1.35}.a9 .a9-pie .t b{display:block;color:var(--txt,#e8e8f0);font-weight:600;letter-spacing:.1em}
.a9 .a9-ar{flex:0 0 auto;color:#8a8aa0;font-size:18px;padding:0}
@media (min-width:1101px){.a9 .a9-pie[data-pie="account"]{min-width:190px}.a9 .a9-pie[data-pie="invested"],.a9 .a9-pie[data-pie="who"],.a9 .a9-pie[data-pie="conviction"]{min-width:204px}}
.a9 .a9-say{margin:10px 0 0;font-size:12px;line-height:1.6;color:var(--dimc);max-width:1320px}.a9 .a9-say b{color:var(--txt,#e8e8f0);font-weight:600}
.a9 .a9-rt{margin-top:8px;font-size:11.5px;font-variant-numeric:tabular-nums}
.a9 .a9-rt .r{display:grid;grid-template-columns:minmax(118px,1fr) minmax(78px,.7fr) minmax(80px,.7fr) minmax(104px,.9fr) minmax(96px,1fr) minmax(56px,.5fr) minmax(150px,1.35fr) repeat(4,minmax(146px,1.35fr));gap:0 11px;align-items:center;padding:5px 0;border-bottom:1px solid #14141e}
.a9 .a9-rt .r.h{color:var(--dimc);font-size:11px;letter-spacing:.06em;padding:2px 0 4px;align-items:end}.a9 .a9-rt .r.tot{border-bottom:0;border-top:1px solid var(--line,#1c1c28)}.a9 .a9-rt .r.tot .c{font-weight:600}
.a9 .a9-rt .c{min-width:0}.a9 .a9-rt .c b{font-weight:600}.a9 .a9-rt .c small{display:block;font-size:11px;color:var(--dimc);font-weight:400;line-height:1.4}.a9 .a9-rt .c.nm b{font-size:13px}.a9 .a9-rt .c.nm em{font-style:normal;color:var(--dimc);font-size:11px;margin-left:6px}
.a9 .a9-rt .c .go{color:var(--green,#38e07b)}.a9 .a9-rt .c .ov{color:var(--gold,#ffd166)}.a9 .a9-rt .c .open{color:var(--gold,#ffd166);font-weight:600}
.a9 .a9-bar{position:relative;height:14px;background:var(--trk);border-radius:2px}.a9 .a9-bar i{position:absolute;top:0;bottom:0;display:block}.a9 .a9-bar .hl{left:0;background:#d6d6e0;border-radius:2px 0 0 2px;top:3px;bottom:3px}
.a9 .a9-bar .tg{width:2px;background:var(--a9-acc);top:-3px;bottom:-3px}.a9 .a9-bar .cl{width:2px;background:#8a8aa0;top:-3px;bottom:-3px}.a9 .a9-bar .bd{background:repeating-linear-gradient(45deg,var(--gold,#ffd166) 0 2px,transparent 2px 5px);opacity:.75}
.a9 .a9-key{display:flex;flex-wrap:wrap;gap:3px 16px;margin:6px 0 0;font-size:11px;color:var(--dimc)}.a9 .a9-key i{display:inline-block;width:12px;height:8px;margin-right:6px;vertical-align:0;border-radius:1px}
.a9 details{margin-top:10px}.a9 details.sc-pagespecs p{margin:6px 0;max-width:1100px;color:var(--dimc);font-size:12px;line-height:1.6}.a9 details.sc-pagespecs p b{color:var(--txt,#e8e8f0);font-weight:600}
.a9 .a9-dip{margin:6px 0 0;font-size:11.5px;color:var(--dimc)}.a9 .a9-dip b{color:var(--txt,#e8e8f0);font-weight:600}
@media (max-width:1100px){.a9 .a9-top{grid-template-columns:minmax(0,1fr)}}
@media (max-width:1240px){.a9 .a9-rt .r.h{display:none}.a9 .a9-rt .r{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:3px 14px;padding:9px 0}.a9 .a9-rt .c.nm{grid-column:1/-1}.a9 .a9-rt .c::before{content:attr(data-l);display:block;font-size:11px;letter-spacing:.06em;color:var(--dimc)}.a9 .a9-rt .c.nm::before{content:none}.a9 .a9-rt .c small{white-space:normal}}
@media (max-width:760px){.a9 .a9-big{font-size:50px}.a9 .a9-rl{flex-basis:100%}.a9 .a9-ar{display:none}.a9 .a9-row{gap:8px 10px}}`;

/* one pie: a whole split into slices, every slice labelled on the drawing — its name, its share of the whole account (bright) and its
   share of this pie. A big slice carries its label inside; a small one carries it beside itself on a short line. */
const FILL = { held: "var(--a9-held)", invested: "var(--a9-held)", tactical: "url(#a9hatch)", conviction: "var(--conv,#b38d3c)", core: "var(--core,#2196b8)", cash: "var(--cashc,#26263a)" };
export function pieSvg(slices, { r = 54, label = "" } = {}) { const CH = 6.7, LH = 12, GAP = 3, TAU = 2 * Math.PI, live = slices.filter((s) => s.frac > 0.0005), tot = live.reduce((a, s) => a + s.frac, 0) || 1, big = live.find((s) => s.frac / tot >= 0.5); let a0 = 0;
  if (big) { let before = 0; for (const s of live) { if (s === big) break; before += s.frac / tot; } a0 = 0.5 - (before + big.frac / tot / 2); }   /* turn the pie so the big slice is centred at the bottom */
  const arcs = live.map((s) => { const f = s.frac / tot, o = { ...s, f, a0, a1: a0 + f, mid: a0 + f / 2 }; a0 += f; o.lines = [s.name, s.acct != null ? pc(s.acct) : null, s.of || null].filter(Boolean); o.ws = o.lines.map((t, i) => t.length * (i === 1 && s.acct != null ? 7.3 : CH) + 2); o.w = Math.max(...o.ws); o.h = o.lines.length * LH; o.side = Math.sin(o.mid * TAU) >= -1e-9 ? 1 : -1; return o; });
  /* inside: the first distance from the centre at which every line of the label lies within the slice (a point is in the slice when it is inside the circle and no further than half the slice's angle from its middle) */
  const within = (x, dx, dy) => { const rad = Math.hypot(dx, dy); if (rad > r - 1.5) return false; if (x.f >= 0.9995 || rad < 2) return true; const t = Math.atan2(dx, -dy) / TAU, d = Math.abs((((t - x.mid) % 1) + 1.5) % 1 - 0.5); return d <= x.f / 2 - 1.5 / (TAU * Math.max(rad, 1)); };
  for (const x of arcs) { x.inside = null; if (x.f < 0.5) continue; for (const k of [0.3, 0.36, 0.24, 0.42, 0.18, 0.48, 0.1, 0]) { const cxl = k * r * Math.sin(x.mid * TAU), cyl = -k * r * Math.cos(x.mid * TAU); let ok = true; for (let i = 0; i < x.lines.length && ok; i++) { const hw = x.ws[i] / 2, y0 = cyl - x.h / 2 + i * LH, y1 = y0 + LH; ok = [[-hw, y0], [hw, y0], [-hw, y1], [hw, y1]].every(([ox, oy]) => within(x, cxl + ox, oy)); } if (ok) { x.inside = [cxl, cyl]; break; } } }
  const out = arcs.filter((x) => !x.inside), padL = Math.max(6, ...out.filter((x) => x.side < 0).map((x) => x.w + 18)), padR = Math.max(6, ...out.filter((x) => x.side > 0).map((x) => x.w + 18));
  const need = (sd) => out.filter((x) => x.side === sd).reduce((t, x) => t + x.h + GAP, 0), H = Math.max(2 * r + 8, need(1) + 4, need(-1) + 4), W = padL + 2 * r + padR, cx = padL + r, cy = H / 2, P = (t, rad) => [cx + rad * Math.sin(t * TAU), cy - rad * Math.cos(t * TAU)];
  /* the labels beside the pie: each as near its own slice as it can sit without touching its neighbour */
  for (const sd of [1, -1]) { const L = out.filter((x) => x.side === sd).sort((p, q) => P(p.mid, r)[1] - P(q.mid, r)[1]); let y = 2; for (const x of L) { x.y = Math.max(y, P(x.mid, r + 6)[1] - x.h / 2); y = x.y + x.h + GAP; } let lim = H - 2; for (let i = L.length - 1; i >= 0; i--) { if (L[i].y + L[i].h > lim) L[i].y = lim - L[i].h; lim = L[i].y - GAP; } }
  const gapA = arcs.length > 1 ? 1.1 / (TAU * r) : 0, wedge = (x) => { if (x.f >= 0.9995) return `<circle cx="${cx}" cy="${cy}" r="${r}" fill="${FILL[x.kind]}"${x.kind === "cash" ? ' stroke="#3a3a4a"' : ""}/>`; const [x0, y0] = P(x.a0 + gapA, r), [x1, y1] = P(x.a1 - gapA, r); return `<path d="M${cx} ${cy.toFixed(1)}L${x0.toFixed(2)} ${y0.toFixed(2)}A${r} ${r} 0 ${x.f - 2 * gapA > 0.5 ? 1 : 0} 1 ${x1.toFixed(2)} ${y1.toFixed(2)}Z" fill="${FILL[x.kind]}"${x.kind === "cash" ? ' stroke="#3a3a4a" stroke-width="1"' : ""}><title>${esc(x.lines.join(" · "))}</title></path>`; };
  const text = (x, tx, ty, anchor, dark) => x.lines.map((t, i) => `<text x="${tx.toFixed(1)}" y="${(ty + (i + 0.8) * LH).toFixed(1)}" text-anchor="${anchor}" font-size="${i === 1 && x.acct != null ? 12 : 11}" font-weight="${i === 1 && x.acct != null ? 700 : i === 0 ? 600 : 400}" fill="${dark ? "var(--a9-ink)" : i === 2 || (i === 1 && x.acct == null) ? "var(--dimc)" : "var(--txt,#e8e8f0)"}">${esc(t)}</text>`).join("");
  const labels = arcs.map((x) => { if (x.inside) return text(x, cx + x.inside[0], cy + x.inside[1] - x.h / 2, "middle", x.kind !== "cash");
    const [ex, ey] = P(x.mid, r + 1), tx = x.side > 0 ? cx + r + 16 : cx - r - 16, my = x.y + x.h / 2; return `<path d="M${ex.toFixed(1)} ${ey.toFixed(1)}L${(tx - x.side * 4).toFixed(1)} ${my.toFixed(1)}" fill="none" stroke="#5a5a6c" stroke-width="1"/>` + text(x, tx, x.y, x.side > 0 ? "start" : "end", false); });
  return `<svg width="${Math.ceil(W)}" height="${Math.ceil(H)}" viewBox="0 0 ${Math.ceil(W)} ${Math.ceil(H)}" role="img" aria-label="${esc(label + ": " + arcs.map((x) => x.lines.join(" ")).join("; "))}">${arcs.map(wedge).join("")}${labels.join("")}</svg>`; }

/* the chain as five pies, left to right: each pie is one link, and its whole is the slice of the pie before it */
export function chainPies(ch, r = 54) { const of = (p) => `${p >= 99.95 ? "100" : p >= 10 ? f0(p) : f1(p)}% of it`, nm = (s) => C.LABEL[s] || s, inv = ch.number || 1;
  const conv = ch.slices.filter((s) => s.kind === "conviction"), core = ch.slices.filter((s) => s.kind === "core");
  return [
    { id: "account", t: "1 · THE ACCOUNT", sub: null, slices: [{ kind: "invested", name: "invested", acct: ch.number, frac: ch.number }, { kind: "cash", name: "cash", acct: ch.cash, frac: ch.cash }] },
    { id: "invested", t: "2 · WHAT IS INVESTED", sub: pc(ch.number), slices: [{ kind: "held", name: "held part", acct: ch.held, of: of((100 * ch.held) / inv), frac: ch.held }, { kind: "tactical", name: "tactical", acct: ch.tactical, of: of((100 * ch.tactical) / inv), frac: ch.tactical }] },
    { id: "who", t: "3 · WHO GETS IT", sub: pc(ch.number), slices: [{ kind: "conviction", name: "conviction", acct: ch.conviction, of: of(ch.convOfInvested), frac: ch.conviction }, { kind: "core", name: "core", acct: ch.core, of: of(ch.coreOfInvested), frac: ch.core }] },
    { id: "conviction", t: "4 · INSIDE CONVICTION", sub: pc(ch.conviction), slices: conv.map((s) => ({ kind: "conviction", name: nm(s.sym), acct: s.pct, of: of(s.ofAbove), frac: s.pct })) },
    { id: "core", t: "5 · INSIDE THE CORE", sub: pc(ch.core), slices: core.map((s) => ({ kind: "core", name: s.sym === "MU" ? "Micron memory" : nm(s.sym), acct: s.pct, of: of(s.ofAbove), frac: s.pct })) },
  ].map((p) => ({ ...p, svg: pieSvg(p.slices, { r, label: p.t }) })); }
function chainRow(ch, key, head, sub, r) { const pies = chainPies(ch, r);
  return `<div class="a9-row" data-chain="${key}" data-number="${ch.number.toFixed(2)}" data-conv="${ch.convOfInvested.toFixed(2)}"><div class="a9-rl">${head}<b>${pc(ch.number, ch.number >= 99.95 ? 0 : 1)}</b>${sub}</div>${pies.map((p, i) => `${i ? '<span class="a9-ar" aria-hidden="true">→</span>' : ""}<div class="a9-pie" data-pie="${p.id}"><div class="t"><b>${esc(p.t)}</b><span>${p.sub ? "= " + esc(p.sub) + " of the account" : "all of it"}</span></div>${p.svg}</div>`).join("")}</div>`; }

/* the history: SPY above, the number below, on one time axis — every day on the left, today every five minutes on the right */
export const RANGES = [["3m", "3 MONTHS"], ["low25", "SINCE THE APRIL 2025 LOW"], ["all", "SINCE 2018"]];
export function chartSvg({ W, hist, named, path, range, A, live, narrow, dayLabel = "TODAY" }) {
  const padL = 42, padR = 8, todayW = path.length > 1 ? clamp(Math.round(W * 0.22), 96, 300) : 0, gap = todayW ? 26 : 0, x0 = padL, x1 = Math.max(x0 + 60, W - padR - todayW - gap), xT0 = x1 + gap, xT1 = W - padR;
  const rows = 3, topLab = rows * 13 + 6, hS = narrow ? 66 : 84, gapP = 17, hN = narrow ? 80 : 104, yS0 = topLab, yN0 = topLab + hS + gapP, H = yN0 + hN + 20, n = hist.d.length;
  let a = 0; if (range === "3m") a = Math.max(0, n - 64); else if (range === "low25") { a = hist.d.findIndex((d) => d >= "2025-03-03"); if (a < 0) a = 0; } const m = Math.max(1, n - a), X = (i) => x0 + (m > 1 ? ((i - a) / (m - 1)) * (x1 - x0) : 0);
  const sW = hist.s.slice(a).filter((x) => x != null), sLo = Math.min(...sW), sHi = Math.max(...sW), sPad = (sHi - sLo) * 0.06 || 1, YS = (val) => yS0 + hS - ((val - (sLo - sPad)) / (sHi - sLo + 2 * sPad)) * hS;
  const nAll = [...hist.n.slice(a), ...path.map((p) => p.number), live.number].filter((x) => x != null && isFinite(x)), nLo = Math.max(0, Math.floor((Math.min(+A.heldPct, ...nAll) - 0.5) / 5) * 5), nHi = 100, YN = (val) => yN0 + hN - ((clamp(val, nLo, nHi) - nLo) / (nHi - nLo || 1)) * hN;
  const line = (arr, Y) => { let d = "", pen = false; for (let i = a; i < n; i++) { if (arr[i] == null) { pen = false; continue; } d += (pen ? "L" : "M") + X(i).toFixed(1) + " " + Y(arr[i]).toFixed(1); pen = true; } return d; };
  const o = [`<rect x="${x0}" y="${yS0}" width="${x1 - x0}" height="${hS}" fill="#0d0d15"/><rect x="${x0}" y="${yN0}" width="${x1 - x0}" height="${hN}" fill="#0d0d15"/>`];
  /* the number's own grid: fully invested, the held part (its floor), and one line between */
  const grid = [[nHi, "100%"], [+A.heldPct >= nLo ? +A.heldPct : null, f0(+A.heldPct) + "%"], [nLo < +A.heldPct - 9 ? nLo : null, f0(nLo) + "%"], [+A.heldPct + (nHi - +A.heldPct) / 2, f0(+A.heldPct + (nHi - +A.heldPct) / 2) + "%"]].filter((g) => g[0] != null && g[0] >= nLo && g[0] <= nHi);
  for (const [gv, gt] of grid) o.push(`<line x1="${x0}" x2="${xT1}" y1="${YN(gv).toFixed(1)}" y2="${YN(gv).toFixed(1)}" stroke="#1c1c28" stroke-width="1"/><text x="${x0 - 6}" y="${(YN(gv) + 4).toFixed(1)}" text-anchor="end" font-size="11" fill="var(--dimc)">${gt}</text>`);
  o.push(`<text x="${x0 - 6}" y="${(YS(sHi) + 4).toFixed(1)}" text-anchor="end" font-size="11" fill="var(--dimc)">${f0(sHi)}</text><text x="${x0 - 6}" y="${(YS(sLo) + 4).toFixed(1)}" text-anchor="end" font-size="11" fill="var(--dimc)">${f0(sLo)}</text>`);
  /* the time axis: years on the long view, months on the short ones */
  { let lastX = -99, prev = ""; for (let i = a; i < n; i++) { const d = hist.d[i], key = range === "all" ? d.slice(0, 4) : d.slice(0, 7); if (key === prev) continue; const first = prev === ""; prev = key; if (first) continue; const x = X(i); o.push(`<line x1="${x.toFixed(1)}" x2="${x.toFixed(1)}" y1="${yS0}" y2="${yN0 + hN}" stroke="#16161f" stroke-width="1"/>`); if (x - lastX < 46 || x > x1 - 14) continue; lastX = x;
      o.push(`<text x="${x.toFixed(1)}" y="${H - 5}" text-anchor="middle" font-size="11" fill="var(--dimc)">${range === "all" ? d.slice(0, 4) : day("2000-" + d.slice(5, 7) + "-01").slice(2) + (d.slice(5, 7) === "01" ? " " + d.slice(2, 4) : "")}</text>`); } }
  o.push(`<path d="${line(hist.s, YS)}" fill="none" stroke="#c9c9d6" stroke-width="1.5" stroke-linejoin="round"/><path d="${line(hist.n, YN)}" fill="none" stroke="var(--a9-acc)" stroke-width="2" stroke-linejoin="round"/>`);
  o.push(`<text x="${x0 + 6}" y="${yS0 + 13}" font-size="11" font-weight="600" fill="var(--txt,#e8e8f0)" paint-order="stroke" stroke="#0d0d15" stroke-width="4">SPY</text><text x="${x0}" y="${yN0 - 5}" font-size="11" font-weight="600" fill="var(--txt,#e8e8f0)">THE NUMBER${narrow ? "" : " — % INVESTED, EVERY DAY"}</text>`);
  /* the lows and the highs Alan named: a line through both panes, the date above, the number beside its dot */
  { const used = new Array(rows).fill(-1e9), vUsed = [-1e9, -1e9], thisYear = (hist.d[n - 1] || "").slice(0, 4), inWin = named.filter((k) => k.i >= a).sort((p, q) => p.i - q.i); for (const k of inWin) { const x = X(k.i), t = (k.kind === "low" ? "▼ " : "▲ ") + day(k.d) + (k.d.slice(0, 4) === thisYear ? "" : " " + k.d.slice(0, 4)), tw = t.length * 6.7, tx = clamp(x, x0 + tw / 2, x1 - tw / 2), row = used.findIndex((u) => tx - tw / 2 >= u + 6); if (row >= 0) used[row] = tx + tw / 2;
      const ny = YN(k.number), want = k.kind === "low" ? 0 : 1, up = want === 0 && ny - yN0 < 22 ? 1 : want === 1 && yN0 + hN - ny < 20 ? 0 : want, vt = pc(k.number, 0), vw = vt.length * 6.9, vx = clamp(x, x0 + vw / 2 + 2, x1 - vw / 2 - 2), showV = vx - vw / 2 >= vUsed[up] + 3; if (showV) vUsed[up] = vx + vw / 2;
      o.push(`<g data-mark="${k.d}" data-kind="${k.kind}" data-number="${k.number.toFixed(1)}" data-labelled="${row >= 0 ? 1 : 0}"><line x1="${x.toFixed(1)}" x2="${x.toFixed(1)}" y1="${topLab - 3}" y2="${yN0 + hN}" stroke="${k.kind === "low" ? "var(--green,#38e07b)" : "var(--red,#ff5470)"}" stroke-width="1" stroke-dasharray="2 3" opacity=".8"/>${row >= 0 ? `<text x="${tx.toFixed(1)}" y="${row * 13 + 11}" text-anchor="middle" font-size="11" fill="var(--txt,#e8e8f0)">${esc(t)}</text>` : ""}<circle cx="${x.toFixed(1)}" cy="${YS(k.spy).toFixed(1)}" r="3.5" fill="#c9c9d6" stroke="#0d0d15" stroke-width="2"/><circle cx="${x.toFixed(1)}" cy="${ny.toFixed(1)}" r="4" fill="var(--a9-acc)" stroke="#0d0d15" stroke-width="2"/>${showV ? `<text x="${vx.toFixed(1)}" y="${(up === 0 ? ny - 8 : ny + 17).toFixed(1)}" text-anchor="middle" font-size="11" font-weight="700" fill="var(--txt,#e8e8f0)" paint-order="stroke" stroke="#0d0d15" stroke-width="4">${vt}</text>` : ""}</g>`); } }
  /* today, every five minutes: SPY on its own scale, the number on the same scale as the days beside it */
  const geo = { W, H, x0, x1, a, m, n, xT0, xT1, todayW, y0: topLab - 3, y1: yN0 + hN };
  if (todayW) { const XT = (min) => xT0 + ((clamp(min, C.OPEN_MIN, C.CLOSE_MIN) - C.OPEN_MIN) / (C.CLOSE_MIN - C.OPEN_MIN)) * (xT1 - xT0), ps = path.map((p) => p.spy), tLo = Math.min(...ps), tHi = Math.max(...ps), tPad = (tHi - tLo) * 0.08 || 0.5, YT = (val) => yS0 + hS - ((val - (tLo - tPad)) / (tHi - tLo + 2 * tPad)) * hS;
    o.push(`<rect x="${xT0}" y="${yS0}" width="${xT1 - xT0}" height="${hS}" fill="#0d0d15"/><rect x="${xT0}" y="${yN0}" width="${xT1 - xT0}" height="${hN}" fill="#0d0d15"/>`); for (const [gv] of grid) o.push(`<line x1="${xT0}" x2="${xT1}" y1="${YN(gv).toFixed(1)}" y2="${YN(gv).toFixed(1)}" stroke="#1c1c28" stroke-width="1"/>`);
    o.push(`<path d="${path.map((p, i) => (i ? "L" : "M") + XT(p.minutes).toFixed(1) + " " + YT(p.spy).toFixed(1)).join("")}" fill="none" stroke="#c9c9d6" stroke-width="1.5" stroke-linejoin="round"/><path d="${path.map((p, i) => (i ? "L" : "M") + XT(p.minutes).toFixed(1) + " " + YN(p.number).toFixed(1)).join("")}" fill="none" stroke="var(--a9-acc)" stroke-width="2" stroke-linejoin="round"/>`);
    const last = path[path.length - 1]; o.push(`<circle cx="${XT(last.minutes).toFixed(1)}" cy="${YN(last.number).toFixed(1)}" r="4" fill="var(--a9-acc)" stroke="#0d0d15" stroke-width="2"/>`);
    o.push(`<text x="${xT0 + 6}" y="${yS0 + 13}" font-size="11" font-weight="600" fill="var(--txt,#e8e8f0)" paint-order="stroke" stroke="#0d0d15" stroke-width="4">${esc(dayLabel)}</text><text x="${xT0}" y="${yN0 - 5}" font-size="11" font-weight="600" fill="var(--txt,#e8e8f0)">${todayW > 150 ? "EVERY 5 MINUTES" : "5 MINUTES"}</text>`);
    for (const [min, anchor] of [[C.OPEN_MIN, "start"], [12 * 60 + 45, "middle"], [C.CLOSE_MIN, "end"]]) if (anchor !== "middle" || todayW > 150) o.push(`<text x="${XT(min).toFixed(1)}" y="${H - 5}" text-anchor="${anchor}" font-size="11" fill="var(--dimc)">${hm(min)}</text>`); geo.tMin = C.OPEN_MIN; geo.tMax = C.CLOSE_MIN; }
  o.push(`<line id="a9-cross" x1="-10" x2="-10" y1="${geo.y0}" y2="${geo.y1}" stroke="#8a8aa0" stroke-width="1" pointer-events="none"/>`);
  return { svg: `<svg class="a9-chart" id="a9-chart" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="SPY above and the number below, every session since ${esc(dayY(hist.d[a] || ""))}, with ${esc(dayLabel.toLowerCase())} every five minutes beside them">${o.join("")}</svg>`, geo }; }

function numberBlock(X, st) { const { v, A, sm, live, marks, yest, room, dips, asOf, now, today, isToday, dayWord } = X, kv = [], t = (x) => (x == null ? "—" : pc(x));
  kv.push(`<span>at the open${marks.open ? " · " + marks.open.hm : ""}</span><b data-kv="open">${marks.open ? t(marks.open.number) : `<i>not open yet</i>`}</b>`);
  kv.push(`<span title="the moment SPY and QQQ together were lowest${marks.low ? ": " + sg(marks.low.offOpenPct, 1) + "% from the open" : ""}">${isToday ? "at today's market low" : "at the market low of " + esc(dayWord)}${marks.low ? " · " + marks.low.hm : ""}</span><b data-kv="low">${marks.low ? t(marks.low.number) : "<i>—</i>"}</b>`);
  kv.push(`<span>${isToday ? "at yesterday's close" : "at the close before"}${yest ? " · " + esc(day(yest.date)) : ""}</span><b data-kv="yest">${yest ? t(yest.number) : "<i>—</i>"}</b>`);
  kv.push(`<span>the account holds <b style="color:var(--txt,#e8e8f0);font-weight:600" data-kv="held">${pc(room.held)}</b> · room to play</span><b data-kv="room">${usd(room.roomUsd)}</b>`);
  const whyR = `market reading <b>${f0(sm.reading)}</b> of 100`, tac = today.tactical;
  return `<div class="a9-num"><h4>THE NUMBER — % OF THE ACCOUNT TO INVEST</h4><div class="a9-big" data-a9="number">${pc(sm.number, 0)}</div><div class="a9-sub">${sm.sessionOver ? "average of the session's last " + f0(sm.minutes) + " minutes" : "average of the last " + f0(sm.minutes) + " minutes"} · this minute <b>${pc(live.number)}</b></div>
  <p class="a9-why">= <b>${f0(today.held)}</b> held part + <b>${f1(tac)}</b> tactical: the ${whyR} puts ${f0(sm.reading)}% of the ${f0(A.tacticalPct)} tactical points to work</p>
  ${asOf ? `<div class="a9-asof"><b>${esc(asOf.label)}</b> the number would have been <b>${pc(now.number)}</b> (market reading ${f0(asOf.reading)}) — the first row of pies shows that moment. <button data-a9-now="1">BACK TO NOW</button></div>` : ""}
  <div class="a9-kv">${kv.join("")}</div>
  <p class="a9-dip">a further dip in SPY and QQQ together: ${dips.map((d) => `−${d.dipPct}% → <b data-dipn="${d.dipPct}">${pc(d.number, 0)}</b>`).join(" · ")}</p></div>`; }

function roomTable(X) { const { room, levels, A, highs, v, today, full } = X, scale = Math.max(10, ...room.rows.map((r) => Math.max(r.ceiling, r.held, r.allowed))) * 1.04, w = (p) => clamp((100 * p) / scale, 0, 100).toFixed(2) + "%";
  const lvCell = (l, side, lab) => { if (!l) return `<div class="c" data-l="${lab}"><small>no level in our data</small></div>`; const act = l.shares > 0 ? `<b class="${side === "buy" ? "go" : "ov"}">${side} ${l.shares} share${l.shares === 1 ? "" : "s"}</b> · ${usd(l.usd)}` : `<span class="dim">${side === "buy" ? "no buy" : "no trim"}: ${esc(l.why || "")}</span>`; return `<div class="c" data-l="${lab}" data-level="${l.level}" data-shares="${l.shares}"><b>${px(l.level)}</b> <span class="dim">${sg(l.awayPct, 1)}%</span><small title="${esc(l.id)}">${esc(l.id)}</small><small>${act}</small></div>`; };
  const rows = room.rows.map((r) => { const L = levels[r.sym] || { buys: [], trims: [] }, parts = r.parts.length > 1 ? r.parts.map((p) => f1(p.pct) + " " + (p.kind === "core" ? "core" : "conviction")).join(" + ") : r.conviction ? "conviction" : "core";
    const band = !r.conviction ? `<span class="dim">core: no band</span>` : r.bandOpen ? `<span class="open">OPEN</span> to ${pc(r.allowed)}<small>+${f1(r.band)} points</small><small>it is over its ${f0(+A.breakoutDays)}-session high ${px(highs[r.sym])}</small>` : `shut<small>+${f1(r.band)} points, to ${pc(r.target + r.band)}</small><small>opens over ${px(highs[r.sym])}</small>`;
    const roomTxt = r.room > 0.05 ? `<b class="go">${usd(r.roomUsd)}</b> to buy<small>${f1(r.room)} points</small>` : r.over > 0.05 ? `<b class="ov">${usd(r.overUsd)}</b> over<small>${f1(r.over)} points too many</small>` : r.room < -0.05 ? `<b>inside its band</b><small>${f1(-r.room)} points over target, trimmed first</small>` : `<b>at its target</b>`;
    return `<div class="r" data-room="${r.sym}" data-target="${r.target.toFixed(2)}" data-held="${r.held.toFixed(2)}" data-ceiling="${r.ceiling.toFixed(2)}" data-band="${r.band.toFixed(2)}" data-open="${r.bandOpen ? 1 : 0}"><div class="c nm"><b>${esc(r.name)}</b><em>${r.sym}${L.price != null ? " " + px(L.price) : ""}</em><small>${esc(parts)}</small></div>
    <div class="c" data-l="TARGET NOW"><b>${pc(r.target)}</b><small>${usd(r.targetUsd)}</small></div><div class="c" data-l="HELD"><b>${pc(r.held)}</b><small>${r.shares ? r.shares + " shares" : "none"}</small></div><div class="c" data-l="ROOM">${roomTxt}</div>
    <div class="c" data-l="HELD · TARGET · CEILING"><div class="a9-bar" title="held ${pc(r.held)} · target ${pc(r.target)} · ceiling ${pc(r.ceiling)}">${r.band > 0 ? `<i class="bd" style="left:${w(r.target)};width:${w(r.band)}"></i>` : ""}<i class="hl" style="width:${w(r.held)}"></i><i class="tg" style="left:${w(r.target)}"></i><i class="cl" style="left:${w(r.ceiling)}"></i></div></div>
    <div class="c" data-l="CEILING"><b>${pc(r.ceiling)}</b>${r.capped ? `<small>its cap</small>` : ""}</div><div class="c" data-l="OVER TARGET ON A BREAKOUT">${band}</div>${lvCell(L.buys[0], "buy", "NEXT BUY")}${lvCell(L.buys[1], "buy", "BUY AFTER THAT")}${lvCell(L.trims[0], "trim", "NEXT TRIM")}${lvCell(L.trims[1], "trim", "TRIM AFTER THAT")}</div>`; }).join("");
  const other = room.other.length ? `<small>also held outside the chain: ${room.other.map((o) => o.sym + " " + pc(o.held)).join(", ")}</small>` : "";
  return `<div class="a9-rt"><div class="r h"><div class="c">NAME</div><div class="c">TARGET NOW</div><div class="c">HELD</div><div class="c">ROOM</div><div class="c">HELD · TARGET · CEILING</div><div class="c">CEILING</div><div class="c">OVER TARGET ON A BREAKOUT</div><div class="c">NEXT BUY</div><div class="c">BUY AFTER THAT</div><div class="c">NEXT TRIM</div><div class="c">TRIM AFTER THAT</div></div>${rows}
  <div class="r tot" data-room="ALL"><div class="c nm"><b>THE ACCOUNT</b><em>${usd(room.nlv)}</em>${other}</div><div class="c" data-l="TARGET NOW">${pc(room.target)}<small>${usd((room.target / 100) * room.nlv)}</small></div><div class="c" data-l="HELD">${pc(room.held)}</div><div class="c" data-l="ROOM"><b class="go">${usd(room.roomUsd)}</b> to buy<small>${f1(room.room)} points</small></div><div class="c" data-l=""></div><div class="c" data-l="CEILING">${pc(room.ceiling, 0)}</div><div class="c" data-l="OVER TARGET ON A BREAKOUT">${room.bandOpen > 0 ? `<span class="open">OPEN</span> to ${pc(room.allowed)}` : `shut`}<small>${f1(room.bandPts)} points in all</small></div><div class="c"></div><div class="c"></div><div class="c"></div><div class="c"></div></div></div>
  <div class="a9-key"><span><i style="background:#d6d6e0"></i>held today</span><span><i style="background:var(--a9-acc);width:2px"></i>target now</span><span><i style="background:#8a8aa0;width:2px"></i>ceiling (fully invested)</span><span><i style="background:repeating-linear-gradient(45deg,var(--gold,#ffd166) 0 2px,transparent 2px 5px)"></i>the breakout band — conviction names only, trimmed first</span></div>`; }

function sayHtml(X) { const { today, full, A, prop, sm } = X, mu = today.names.MU, muF = full.names.MU, part = (n, k) => (n && n.parts.find((p) => p.kind === k)) || { pct: 0 }, lift = +A.convLift;
  const micron = mu ? `<b>Micron sits in two pies:</b> ${f1(part(mu, "conviction").pct)}% as conviction + ${f1(part(mu, "core").pct)}% as its memory share of the core = <b>${f1(mu.pct)}% of the account now</b>; fully invested ${f1(part(muF, "conviction").pct)} + ${f1(part(muF, "core").pct)} = <b>${f1(muF.pct)}%</b>${muF.capped ? `, its cap` : ""}.` : "";
  const propS = prop.exact ? `<b>Is it always directly proportional? Yes:</b> every name keeps the same share of what is invested at any number, so when the number moves every name moves with it.`
    : `<b>Is it always directly proportional? Inside each pie, yes</b> — a name keeps the same share of conviction or of the core at any number, so every name moves with the number. ${lift ? `One share is not fixed: conviction is ${f1(prop.conv[0])}% of what is invested at a market reading of 0, <b>${f1(prop.conv[1])}% now</b> and ${f1(prop.conv[2])}% at 100, and the core gives up the same.` : ""}${prop.capBinds[2] ? ` Micron stops at its cap of ${f0(+A.capMicron)}% of the account; what it gives up goes to the other core names.` : ""}`;
  return `<p class="a9-say" data-a9="say" data-exact="${prop.exact ? 1 : 0}">${micron} ${propS}<br><b>What each dial moves:</b> the market reading moves only the tactical part, so the number runs from ${f0(+A.heldPct)}% (the held part) to ${f0(C.numberAt(100, A))}%; the conviction dials split conviction from core; Micron's part and the core weights split each pie; the cap and the breakout band limit a name. Every dial is under ASSUMPTIONS below.</p>`; }

const specs = (X) => `<details class="sc-pagespecs" data-a9-fold="specs"><summary>PAGE SPECS</summary>
<p><b>The number.</b> The share of the account to have invested. It is the held part (${f0(+X.A.heldPct)}% of the account, invested whatever the market does) plus the tactical part (up to ${f0(+X.A.tacticalPct)}%) multiplied by the market reading. It is worked out on every read (each minute while New York trades) and shown as the average of the last ${f0(+X.A.smoothMin)} minutes; nothing is averaged over days.</p>
<p><b>The market reading.</b> 0 to 100, from live prices: 0 is a stretched market, 100 a washed-out one, 50 a typical day. Two things are counted in it — the RSI of SPY and QQQ together, and credit's own ten-session move with rates taken out — and every other thing measured is shown in step 2 with what it would add. It is the same sum on the live page, on today's path and on every past day.</p>
<p><b>Today's path.</b> The same sum at each five-minute price of SPY, QQQ, the high-yield fund and the 7–10 year treasury fund since 09:30 New York, with every other day as it closed. It is rebuilt from the market's own five-minute prices on every read, so it is the same after a reload and on any device; nothing is stored. "At today's low" is the moment SPY and QQQ together were lowest.</p>
<p><b>The history.</b> Every session since 2 January 2018: what today's rule would have said on that day's own closing prices. It is today's rule looked back on, not a record of what an older rule said at the time; the rule's test on years it had never seen is in the deployment study. The marked days are the lows and highs Alan named on 7 October; each is the lowest or highest SPY close of the 21 sessions around it. Click any day, or any moment of today, and the first row of pies shows that moment.</p>
<p><b>The pies.</b> Read left to right; each pie's whole is one slice of the pie before it. On every slice: its name, its share of the whole account (bright), and its share of that pie. The second row is the same chain with the market reading at 100 — fully invested — and a name's size there is its ceiling.</p>
<p><b>Room to play.</b> A name's target less what the account holds of it, at live prices. The account is the cash and the share counts typed under ASSUMPTIONS (the baseline is the broker's reading of 7 October, 13:05); it is not read from the broker. The next two buy levels are the nearest two levels under the price, the next two trim levels the nearest two above it, among: the 21-, 50-, 100- and 200-day averages, the chart lines Alan reviewed (named as on his charts), the name's usual cool-off, and its ${f0(+X.A.breakoutDays)}-session high. Levels within ${f1(+X.A.zonePct)}% of each other count as one level, named for all of them and priced at the nearest, so the two orders are two different prices (step 2 lists every level on its own). TSMC and Oracle have no reviewed lines stored. A buy is sized as ${f0(+X.A.buyFirst)}% of the room at the first level and the rest at the second, the room being counted at that level's price; a trim is whatever would be over the allowed size at that level's price. The account's value is held where it is for these sums.</p>
<p><b>The breakout band.</b> The one way over the number. A conviction name trading above its highest close of the past ${f0(+X.A.breakoutDays)} sessions may be held above its target by its part of the band (${f1(+X.A.bandPts)} points of the account in all, shared as conviction is shared), never above its ceiling. When the breakout ends, that part is trimmed first.</p>
<p><b>What could be wrong.</b> The dials are baselines, not measurements: 1 in 4 for conviction is Alan's figure, the lift of ${f1(+X.A.convLift)} points and the band of ${f1(+X.A.bandPts)} points are proposals. The history uses today's rule on past prices. A box ticked in step 2 to count an extra part is added to today's path as it stands now, not replayed through the day. The steps further down the page still size the sectors from the earlier five-step table, not from this number.</p></details>`;

function ensureCss() { if (typeof document === "undefined" || document.getElementById("a9-css")) return; const s = document.createElement("style"); s.id = "a9-css"; s.textContent = CSS; document.head.appendChild(s); }
/* the panel, as study/ds1/live.mjs calls it after every read and every changed dial */
export function draw(host, st, h) { ensureCss(); const X = explain(st), v = X.v, ui = (st.ui ||= {}), W0 = Math.floor(host.clientWidth || 1400), narrow = W0 < 760, wide = W0 >= 1100, chartW = Math.max(280, wide ? W0 - 372 - 30 : W0), range = ui.range || (narrow ? "3m" : "low25"), ph = phaseOf(st.now);
  const chart = chartSvg({ W: chartW, hist: X.hist, named: X.named, path: X.path, range, A: X.A, live: X.live, narrow, dayLabel: X.isToday ? "TODAY" : X.dayWord.toUpperCase() }); ui.geo = chart.geo; ui.X = X; st.explain = X;
  const r = narrow ? 52 : 54, nowHead = X.asOf ? `<u>${esc(X.asOf.short)}</u>` : "NOW", open = (id, def) => ((ui.open || {})[id] ?? def ? " open" : "");
  const first = X.hist.d[chart.geo.a], histNote = st.history ? "" : st.historyError ? ` · the stored history did not load (${esc(st.historyError)}) — the past year is shown` : " · loading the days before the past year…";
  host.innerHTML = `<div class="ds1 a9" id="a9-root" data-number="${X.sm.number.toFixed(2)}" data-live-number="${X.live.number.toFixed(2)}" data-reading="${X.sm.reading.toFixed(1)}" data-held="${X.room.held.toFixed(2)}" data-room-points="${X.room.room.toFixed(2)}" data-path="${X.path.length}" data-days="${X.hist.d.length}" data-range="${range}">
  <svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs><pattern id="a9hatch" width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="5" height="5" fill="#55556a"/><rect width="2.5" height="5" fill="#b9b9c6"/></pattern></defs></svg>
  <div class="hd"><span><span class="livedot${v.live && ph === "open" && !st.error ? "" : " off"}"></span><b>LIVE</b></span><span>${h.when}</span><span data-ds1-age>${esc(h.ageWords())}</span><span>${esc(nextReadWords(st.now))}</span>${h.marks.map((m) => `<span class="warn">${m}</span>`).join("")}</div>
  <div class="a9-top">${numberBlock(X, st)}
  <div class="a9-hist"><div class="a9-hh"><h4>ITS HISTORY — SPY ABOVE, THE NUMBER BELOW · ▼ A LOW ▲ A HIGH ALAN NAMED${esc(histNote)}</h4><div class="a9-rg">${RANGES.map(([k, t]) => `<button data-a9-range="${k}" class="${k === range ? "on" : ""}">${t}</button>`).join("")}</div></div>
  ${chart.svg}<div class="a9-read" id="a9-read">from ${esc(dayY(first || ""))} · point at any day, or any moment of ${X.isToday ? "today" : esc(X.dayWord)}, to read it · click to see the pies as they would have been</div></div></div>
  <div class="a9-sec" data-sec="chain"><h4>HOW THE NUMBER BECOMES A SIZE FOR EVERY NAME — READ THE PIES LEFT TO RIGHT · ON EACH SLICE: ITS SHARE OF THE WHOLE ACCOUNT, THEN ITS SHARE OF THAT PIE</h4>
  ${chainRow(X.now, "now", nowHead, X.asOf ? "invested then" : "invested", r)}${chainRow(X.full, "full", "FULLY INVESTED", "each name's ceiling", r)}
  <div class="a9-key"><span><i style="background:var(--a9-held)"></i>the held part — invested whatever the market does</span><span><i style="background:repeating-linear-gradient(45deg,#b9b9c6 0 2px,#55556a 2px 4px)"></i>tactical — moves with the market</span><span><i style="background:var(--conv,#b38d3c)"></i>conviction</span><span><i style="background:var(--core,#2196b8)"></i>core</span><span><i style="background:var(--cashc,#26263a);outline:1px solid #3a3a4a"></i>cash</span></div>
  ${sayHtml(X)}</div>
  <div class="a9-sec" data-sec="room"><h4>ROOM TO PLAY — TARGET LESS HELD · THE NEXT TWO BUY LEVELS AND THE NEXT TWO TRIM LEVELS OF EACH NAME, WITH SIZES</h4>${roomTable(X)}</div>
  <div class="a9-sec" data-sec="more">${h.inputsHtml(st.asmOpen ?? false)}
  <details data-a9-fold="dips"${open("dips", false)}><summary>WHAT A FURTHER DIP WOULD REACH</summary>${X.dips.map((d) => `<p class="a9-dip">−${d.dipPct}% in SPY and QQQ together (SPY ${px(d.spy)}, QQQ ${px(d.qqq)}): the number <b>${pc(d.number, 0)}</b> · reaches ${d.reached.length ? d.reached.map((x) => `<b>${x.sym}</b> ${esc(x.deepest)}${x.ids.length > 1 ? " +" + (x.ids.length - 1) : ""}`).join(" · ") : "no level of any name"}</p>`).join("")}</details>
  ${specs(X).replace('data-a9-fold="specs">', `data-a9-fold="specs"${open("specs", false)}>`)}</div></div>`; }

/* the panel's own clicks and the pointer on the chart. Nothing here reads the network: a click redraws from what is already in memory. */
export function attach(host, st) { const ui = (st.ui ||= {});
  const at = (ev) => { const svg = host.querySelector("#a9-chart"), g = ui.geo, X = ui.X; if (!svg || !g || !X) return null; const b = svg.getBoundingClientRect(), x = ((ev.clientX - b.left) / (b.width || 1)) * g.W, y = ((ev.clientY - b.top) / (b.height || 1)) * g.H; if (y < 0 || y > g.H) return null;
    if (g.todayW && x >= g.xT0 - 8) { const min = g.tMin + ((clamp(x, g.xT0, g.xT1) - g.xT0) / (g.xT1 - g.xT0)) * (g.tMax - g.tMin); let best = null; for (const p of X.path) if (!best || Math.abs(p.minutes - min) < Math.abs(best.minutes - min)) best = p; if (!best) return null;
      return { x: g.xT0 + ((best.minutes - g.tMin) / (g.tMax - g.tMin)) * (g.xT1 - g.xT0), words: `${esc(X.dayWord)} ${best.hm} New York · SPY <b>${px(best.spy)}</b> · QQQ <b>${px(best.qqq)}</b> · market reading <b>${f0(best.reading)}</b> · the number <b>${pc(best.number)}</b>`, asOf: { reading: best.reading, label: `${X.isToday ? "Today" : "On " + X.dayWord} at ${best.hm} New York:`, short: `${X.dayWord.toUpperCase()} ${best.hm}` } }; }
    if (x < g.x0 - 4 || x > g.x1 + 4) return null; const xOf = (j) => g.x0 + (g.m > 1 ? ((j - g.a) / (g.m - 1)) * (g.x1 - g.x0) : 0), snap = X.named.filter((k) => k.i >= g.a && Math.abs(xOf(k.i) - x) <= 5).sort((p, q) => Math.abs(xOf(p.i) - x) - Math.abs(xOf(q.i) - x))[0];   /* within five pixels of a named day, it is that day */
    const i = snap ? snap.i : clamp(g.a + Math.round(((x - g.x0) / (g.x1 - g.x0 || 1)) * (g.m - 1)), g.a, g.n - 1), d = X.hist.d[i], mk = X.named.find((k) => k.d === d);
    return { x: g.x0 + (g.m > 1 ? ((i - g.a) / (g.m - 1)) * (g.x1 - g.x0) : 0), words: `${esc(dayY(d))}${mk ? ` — a ${mk.kind} Alan named` : ""} · SPY <b>${px(X.hist.s[i])}</b> · market reading <b>${f0(X.hist.r[i])}</b> · the number <b>${pc(X.hist.n[i])}</b>`, asOf: { reading: X.hist.r[i], label: `On ${dayY(d)}${mk ? " (a " + mk.kind + ")" : ""}:`, short: day(d).toUpperCase() + " " + d.slice(0, 4) } }; };
  host.addEventListener("pointermove", (ev) => { if (!ev.target.closest || !ev.target.closest("#a9-chart")) return; const p = at(ev), c = host.querySelector("#a9-cross"), rd = host.querySelector("#a9-read"); if (!p || !c || !rd) return; c.setAttribute("x1", p.x.toFixed(1)); c.setAttribute("x2", p.x.toFixed(1)); rd.innerHTML = p.words; });
  host.addEventListener("click", (ev) => { const t = ev.target; if (!t || !t.closest) return; const rg = t.closest("[data-a9-range]"); if (rg) { ui.range = rg.dataset.a9Range; st.redraw(); return; } if (t.closest("[data-a9-now]")) { ui.asOf = null; st.redraw(); return; }
    if (t.closest("#a9-chart")) { const p = at(ev); if (p) { ui.asOf = p.asOf; st.redraw(); const rd = host.querySelector("#a9-read"); if (rd) rd.innerHTML = p.words; } } });
  host.addEventListener("toggle", (ev) => { const t = ev.target; if (t && t.dataset && t.dataset.a9Fold) (ui.open ||= {})[t.dataset.a9Fold] = t.open; }, true);
  if (typeof window !== "undefined") { let timer = null, w = host.clientWidth; window.addEventListener("resize", () => { clearTimeout(timer); timer = setTimeout(() => { if (host.clientWidth !== w && st.view) { w = host.clientWidth; st.redraw(); } }, 150); }); } }

export const panel = { title: TITLE, draw, attach };
