/* DS1 (7 Oct 2026) — the deployment system, live in the allocation tool. Turns live prices into every part's reading, reads the engine,
   and draws: the reading in points, the pie on today's account, the dips, the levels and the reset tracker per name, the stretch rules.
   Reads only: GETs to the chart API through the page's own rewrites (/candles-multi, /quotes, /macro, /geiger) and one static file
   (study/ds1/data/ds1-live.json). No write, no key, no table.

   WHAT IS LIVE AND WHAT IS NOT
     live every read      every fund and name (the chart API's /quotes), the VIX with its session high and low (/macro), today's own high
                          and low per symbol (the chart API's 30-minute bars), the Hub's own Geiger for the indices and the names (/geiger)
     daily closes         the last 540 sessions of all 26 symbols (/candles-multi, two requests of 13) — on load, on a new day, after the close
     static, dated        the model, each name's usual cool-off, the trim odds, the named pivots, HYG's payout list, FRED's spread (ds1-live.json)

   THE LIVENESS RULE (Alan, 3 Oct: "a little bit wrong rather than a little bit old")
     · a read that fails never blanks the panel: the last reading stays, with its age and the cause of the failed try;
     · a symbol with no live price keeps its last close and is named with that close's date; a part with no reading does not vote and says so;
     · the age is always on screen and ticks every second; nothing here can hold a reading back.

   WHEN IT READS
     on load · every 60 seconds while New York is open (09:30–16:00) · every 5 minutes before the open and after the close (04:00–20:00)
     · once more from 16:10 for the settled daily bars. Not while the tab is hidden; a tab that comes back reads at once if one is due. */
import * as E from "./engine.mjs";

import { DIALS } from "../al9/chain.mjs";

export const DAILY_BARS = 540, FIVE_MIN_BARS = 220, STORE = "al9.assumptions";   // AL9: the dials changed shape (held part, conviction's share, the cap, the band), so a set saved under DS1's key is not read into them
const NONVIX = E.ALL_SYMBOLS.filter((s) => s !== "VIX"), iso = (t) => new Date(t).toISOString().slice(0, 10), clamp = (x, a, b) => Math.max(a, Math.min(b, x));

/* ---------- the clock (New York wall-clock from the browser's own time-zone table) ---------- */
export function nyParts(now = new Date()) { const f = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", hourCycle: "h23", weekday: "short", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit" });
  const p = Object.fromEntries(f.formatToParts(now).map((x) => [x.type, x.value])); return { date: `${p.year}-${p.month}-${p.day}`, weekday: p.weekday, minutes: +p.hour * 60 + +p.minute, hms: `${p.hour}:${p.minute}:${p.second}`, ms: +now }; }
export const SESSION = { pre: 4 * 60, open: 9 * 60 + 30, close: 16 * 60, afterClose: 16 * 60 + 10, late: 20 * 60, openEverySec: 60, extEverySec: 300 };
export const phaseOf = (now) => (now.weekday === "Sat" || now.weekday === "Sun" ? "closed" : now.minutes >= SESSION.open && now.minutes < SESSION.close ? "open" : now.minutes >= SESSION.pre && now.minutes < SESSION.open ? "pre-market" : now.minutes >= SESSION.close && now.minutes < SESSION.late ? "after hours" : "closed");
/* is a read due? last = nyParts() of the last successful read (null = never) */
export function readDue(now, last) { if (!last) return true; const ph = phaseOf(now); if (ph === "closed") return false; const age = (now.ms - last.ms) / 1000;
  if (ph === "open") return last.date !== now.date || last.minutes < SESSION.open || age >= SESSION.openEverySec;
  if (ph === "after hours" && now.minutes >= SESSION.afterClose && (last.date !== now.date || last.minutes < SESSION.afterClose)) return true;
  return last.date !== now.date || age >= SESSION.extEverySec; }
export const nextReadWords = (now) => { const ph = phaseOf(now); return ph === "open" ? "reads every minute" : ph === "closed" ? "reads again when New York trades" : "reads every 5 minutes outside the session"; };

/* ---------- HYG with its payouts added back (the same chain as study/dm2/live.mjs): after the last payout the file knows, last year's
   ex-dates are repeated with the last known amount; "estimated" counts how many such payouts were assumed ---------- */
export function hygWithPayouts(dates, price, payouts) { const known = new Map(payouts), last = payouts[payouts.length - 1], proj = new Map(); let estimated = 0;
  if (last) for (const [d] of payouts) { const next = (+d.slice(0, 4) + 1) + d.slice(4); if (next <= last[0]) continue; const at = dates.find((x) => x >= next); if (at && !known.has(at) && !proj.has(at)) { proj.set(at, last[1]); estimated++; } }
  const tr = []; let prev = null, cur = null; for (let i = 0; i < dates.length; i++) { const p = price[i]; if (p == null) { tr.push(null); continue; } if (prev == null) cur = p; else cur *= (p + (known.get(dates[i]) ?? proj.get(dates[i]) ?? 0)) / prev; prev = p; tr.push(cur); } return { tr, estimated }; }

/* ---------- the chart API's answers → one aligned series ---------- */
export function alignBars(candles) { const spy = (candles.SPY?.series || []).filter((b) => b && b.c != null), dates = spy.map((b) => iso(b.t)), bars = {}, absent = [];
  for (const s of E.ALL_SYMBOLS) { const ser = (candles[s]?.series || []).filter((b) => b && b.c != null); if (!ser.length) { absent.push(s); bars[s] = null; continue; } const m = new Map(ser.map((b) => [iso(b.t), b])); let cur = null; const c = [], h = [], l = [];
    for (const d of dates) { const b = m.get(d); if (b) { cur = b.c; c.push(b.c); h.push(Math.max(b.h ?? b.c, b.c)); l.push(Math.min(b.l ?? b.c, b.c)); } else { c.push(cur); h.push(cur); l.push(cur); } } bars[s] = { c, h, l }; }
  return { dates, bars, absent }; }
/* a quote's price for the session: the session's own completed close once the provider has it, else the live price */
export const quotePrice = (q) => (!q ? null : q.today_session_close != null && q.today_session_close_state && q.today_session_close_state !== "ABSENT" ? q.today_session_close : q.price ?? null);
/* today's own high and low per symbol from the 30-minute bars of the regular session (09:30–16:00 New York) */
export function sessionRanges(intraday, session) { const out = {}; if (!intraday) return out; const f = new Intl.DateTimeFormat("en-US", { timeZone: "America/New_York", hourCycle: "h23", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" });
  for (const [s, o] of Object.entries(intraday)) { let hi = -Infinity, lo = Infinity; for (const b of (o && o.series) || []) { if (!b || b.h == null || b.l == null) continue; const p = Object.fromEntries(f.formatToParts(new Date(b.t)).map((x) => [x.type, x.value])), min = +p.hour * 60 + +p.minute; if (`${p.year}-${p.month}-${p.day}` !== session || min < SESSION.open || min >= SESSION.close) continue; if (b.h > hi) hi = b.h; if (b.l < lo) lo = b.l; } if (isFinite(hi)) out[s] = { hi, lo }; } return out; }
/* add today's live prices as one more bar when the session is newer than the last settled daily bar */
export function withLive(S0, quotes, macro, ranges = {}) { const q = quotes || {}, session = q.SPY?.price_session_et, spy = quotePrice(q.SPY), lastBar = S0.dates[S0.dates.length - 1], k0 = S0.dates.length - 1;
  if (!session || spy == null || session <= lastBar) return { S: S0, live: false, session: lastBar, missing: [], noRange: [], prices: Object.fromEntries(E.ALL_SYMBOLS.map((s) => [s, S0.bars[s] ? S0.bars[s].c[k0] : null])), prev: Object.fromEntries(E.ALL_SYMBOLS.map((s) => [s, S0.bars[s] ? S0.bars[s].c[k0 - 1] : null])) };
  const bars = {}, missing = [], noRange = [], prices = {}, prev = {}, vq = macro?.VIX?.quote;
  for (const s of E.ALL_SYMBOLS) { const b = S0.bars[s]; if (!b) { bars[s] = null; prices[s] = null; continue; } const last = b.c[k0]; let p, hi, lo;
    if (s === "VIX") { const ok = vq && vq.price != null && (!vq.session_et || vq.session_et === session); p = ok ? vq.price : null; hi = ok ? vq.day_high : null; lo = ok ? vq.day_low : null; } else { p = quotePrice(q[s]); const r = ranges[s]; hi = r ? r.hi : null; lo = r ? r.lo : null; }
    if (p == null) { missing.push(s); p = last; hi = lo = last; } else if (hi == null || lo == null) { noRange.push(s); hi = Math.max(hi ?? p, p); lo = Math.min(lo ?? p, p); }
    bars[s] = { c: b.c.concat(p), h: b.h.concat(Math.max(hi, p)), l: b.l.concat(Math.min(lo, p)) }; prices[s] = p; prev[s] = last; }
  return { S: { dates: S0.dates.concat(session), bars }, live: true, session, missing, noRange, prices, prev }; }

/* ---------- the assumptions: every one an editable input with its baseline ---------- */
export const BASE_ACCOUNT = { cash: 452050, shares: { MU: 50, NBIS: 70 }, asOf: "7 Oct 2026, 13:05 New York (IBKR): about $520K, 50 Micron, 70 Nebius, the rest cash" };
/* AL9 (7 Oct): the dials are the chain's (study/al9/chain.mjs DIALS) — the held part and the tactical part, conviction's share of what is
   invested and its lift, Micron's part of conviction, the cap, the breakout band, the minutes averaged, the first buy's share. DS1's three
   fixed slots (core 45, Micron 20, Nebius 5) are what those dials come to when fully invested with no lift; its average over days is gone
   (Alan: no three-day averaging — the number is smoothed over the last hour only). */
export function baseline(base) { const d = (base && base.defaults) || E.DEFAULTS; return { ...DIALS, coreWeights: { ...d.coreWeights }, dips: d.dips.slice(), dipCredit: d.dipCredit || 0, spyPerQqq: d.spyPerQqq, beta: { ...((base && base.beta) || E.BETA_QQQ) }, count: {}, cash: BASE_ACCOUNT.cash, shares: { ...BASE_ACCOUNT.shares } }; }
/* DS1's own pie (E.pie) wants three fixed slots: the held part split at the baseline conviction share. Only its totals are read now
   (invested, tactical, held) and they do not depend on the split. */
export const ds1Shape = (A) => { const c = clamp(+A.convShare, 0, 100) / 100, m = clamp(+A.micronOfConv, 0, 100) / 100; return { ...A, corePct: A.heldPct * (1 - c), micronPct: A.heldPct * c * m, nebiusPct: A.heldPct * c * (1 - m) }; };
export function loadAssumptions(base, store = typeof localStorage !== "undefined" ? localStorage : null) { const A = baseline(base); try { const s = store && JSON.parse(store.getItem(STORE) || "null"); if (s && typeof s === "object") for (const k of Object.keys(A)) if (s[k] != null) A[k] = typeof A[k] === "object" && !Array.isArray(A[k]) ? { ...A[k], ...s[k] } : s[k]; } catch (e) { /* a broken saved value falls back to the baseline */ } return A; }
export const saveAssumptions = (A, store = typeof localStorage !== "undefined" ? localStorage : null) => { try { store && store.setItem(STORE, JSON.stringify(A)); } catch (e) { /* private mode: the inputs still work for this visit */ } };

/* ---------- the reading, with any light the user has switched on counted ---------- */
export function readWith(inputs, model, count = {}) { const r = E.readSystem(inputs, model); let add = 0; for (const l of r.lights) if (count[l.key] && !l.missing) { add += l.points; l.counted = true; } if (add) { r.raw = +(r.raw + add).toFixed(1); r.reading = +clamp(r.raw, 0, 100).toFixed(1); } r.lightsCounted = add; return r; }

/* ---------- everything the panel shows, from one set of prices ---------- */
export function view({ base, candles, quotes, macro, intraday, geiger, A }) {   // bars5 (AL9) stays on the state: the panel reads it there
  const S0 = alignBars(candles); if (S0.dates.length < 260) throw new Error("the chart API served " + S0.dates.length + " daily bars; 260 are needed");
  const session0 = quotes?.SPY?.price_session_et, L = withLive(S0, quotes, macro, sessionRanges(intraday, session0)), S = L.S, k = S.dates.length - 1, model = base.model;
  const hyg = S.bars.HYG ? hygWithPayouts(S.dates, S.bars.HYG.c, base.hygPayouts || []) : { tr: null, estimated: 0 }, RD = E.allReadings(S, hyg.tr), X = RD.X;
  const rd = (i) => readWith(E.inputsAt(X, i), model, A.count), now = rd(k), prior = [1, 2, 3, 4].map((n) => ({ date: S.dates[k - n], reading: rd(k - n).reading }));
  const nAvg = 1, avg = (r0) => r0, deployed = now.reading, AP = ds1Shape(A);   // AL9: no average over days
  /* the account, at live prices */
  const positions = {}; for (const [s, n] of Object.entries(A.shares || {})) if (n > 0 && L.prices[s] != null) positions[s] = { shares: +n, price: L.prices[s] };
  const nlv = (+A.cash || 0) + Object.values(positions).reduce((a, p) => a + p.shares * p.price, 0), account = { nlv, positions };
  const pieNow = E.pie(deployed, AP, account);
  /* the dips: SPY and QQQ fall together from here; everything else moves the way it usually has */
  const scn = base.scn, idx = { spy: L.prices.SPY, qqq: L.prices.QQQ, qqqLevels: {}, spyLevels: {} };
  for (const [nm, a] of [["21-day", "s21"], ["50-day", "s50"], ["100-day", "s100"], ["200-day", "s200"]]) { idx.qqqLevels[nm] = RD.ind.QQQ[a][k]; idx.spyLevels[nm] = RD.ind.SPY[a][k]; }
  const lines = (base.lines && base.lines.names) || {}, names = E.NAMES.map((s) => { const o = RD.ind[s], price = L.prices[s]; if (!o || price == null) return { sym: s, absent: true };
    const cool = E.coolNow(o, S.dates, k), usual = (base.cool && (base.cool[s] || base.cool.pooled)) || null, g = geiger && geiger[s];
    /* where this name's own usual cool-off would take it from the top of this leg — one more level, when it is still under the price */
    const usualAt = usual && cool.push && !cool.gaveUp && usual.dipPct.med != null ? cool.pushClose * (1 + usual.dipPct.med / 100) : null;
    /* the four averages and the nearest four named pivots under the price — and the usual cool-off's level always, however many pivots sit above it */
    const levels = E.levelsFor(s, o, k, price, idx, lines[s] || [], A.beta[s], A.spyPerQqq, 4);
    if (usualAt != null && usualAt < price) { const u = E.levelsFor(s, o, k, price, idx, [{ id: "usual cool-off", level: usualAt, kind: "usual" }], A.beta[s], A.spyPerQqq, 1).find((r) => r.kind === "usual"); if (u) { u.note = `${usual.dipPct.med.toFixed(1)}% from its top of ${cool.pushClose >= 1000 ? cool.pushClose.toFixed(0) : cool.pushClose.toFixed(2)}`; levels.push(u); levels.sort((x, y) => y.level - x.level); } }
    const st = usual ? { wr: E.resetState(cool.lowWr, usual.wr), rsi: E.resetState(cool.lowRsi, usual.rsi), mom: E.resetState(cool.lowMom, usual.mom) } : null;
    return { sym: s, price, chgPct: L.prev[s] ? (price / L.prev[s] - 1) * 100 : null, beta: A.beta[s], role: E.CORE.includes(s) ? "core #" + (E.CORE.indexOf(s) + 1) : E.CONVICTION.includes(s) ? "conviction" : "watch", levels, cool, usual, st, hub: g ? { trend: g.trend, momentum: g.momentum, composite: g.composite } : null, gauges: { rsi: o.rsi[k], wr: o.wr[k], mom: o.mom[k], trend: o.trend[k] }, hasLines: !!(lines[s] && lines[s].length), state: nameState(cool, usual, st) }; });
  const dips = A.dips.map((x) => { const rdOn = (holds) => { const d = E.dipSeries(S, hyg.tr, +x, scn, A.beta, holds), R = E.allReadings(d.S, d.hygTR); return { r: readWith(E.inputsAt(R.X, k), model, A.count), vix: d.S.bars.VIX ? d.S.bars.VIX.c[k] : null }; };
    const calm = rdOn(true), usual = rdOn(false), main = A.dipCredit ? usual : calm, dep = avg(main.r.reading), p = E.pie(dep, AP, account);
    /* the add levels each name would touch on the way: the deepest one is named, the count of the others follows it */
    const reached = names.filter((n) => !n.absent).map((n) => { const after = n.price * (1 - (n.beta * x) / 100), hit = n.levels.filter((lv) => lv.below && lv.level >= after); return hit.length ? { sym: n.sym, ids: hit.map((h) => h.id), deepest: hit[hit.length - 1].id, after } : null; }).filter(Boolean);
    return { dipPct: +x, reading: main.r.reading, readingCalm: calm.r.reading, readingCreditSells: usual.r.reading, deployed: dep, pie: p, spy: idx.spy * (1 - x / 100), qqq: idx.qqq * (1 - x / 100), vix: main.vix, reached, families: main.r.families }; });
  /* the plain facts beside each part */
  const vixYear = S.bars.VIX ? S.bars.VIX.c.slice(Math.max(0, k - 251), k + 1).filter((v) => v != null).sort((a, b) => a - b) : [], q = (p) => (vixYear.length ? vixYear[Math.min(vixYear.length - 1, Math.round(((vixYear.length - 1) * p) / 100))] : null);
  const cnt = (list, a) => { let n = 0, up = 0; for (const s of list) { const o = RD.ind[s]; if (!o || o.c[k] == null || o[a][k] == null) continue; n++; if (o.c[k] > o[a][k]) up++; } return { n, up }; };
  let hygLow = null; for (let i = Math.max(0, k - 15); i <= k; i++) if (X.hygRsi[i] != null && (hygLow == null || X.hygRsi[i] < X.hygRsi[hygLow])) hygLow = i;
  const iefMove = S.bars.IEF && k >= E.CREDIT_WINDOW ? (S.bars.IEF.c[k] / S.bars.IEF.c[k - E.CREDIT_WINDOW] - 1) * 100 : null, hygMove = hyg.tr && k >= E.CREDIT_WINDOW ? (hyg.tr[k] / hyg.tr[k - E.CREDIT_WINDOW] - 1) * 100 : null;
  const facts = { spyRsi: RD.ind.SPY.rsi[k], qqqRsi: RD.ind.QQQ.rsi[k], spyWr: RD.ind.SPY.wr[k], qqqWr: RD.ind.QQQ.wr[k], hub: { SPY: geiger && geiger.SPY, QQQ: geiger && geiger.QQQ },
    vix: { price: L.prices.VIX, high: S.bars.VIX ? S.bars.VIX.h[k] : null, pct: X.vixPct[k], hiPct: X.vixHiPct[k], p80: q(80), p90: q(90), state: X.vixPct[k] >= 80 ? "closed above" : X.vixHiPct[k] >= 80 ? "touched" : "calm" },
    br50: cnt(E.BREADTH, "s50"), br200: cnt(E.BREADTH, "s200"), ld21: cnt(E.CORE, "s21"), ld50: cnt(E.CORE, "s50"),
    credit: { hygRsi: X.hygRsi[k], hygWr: X.hygWr[k], own: X.creditOwn[k], hygMove, ratesLeg: iefMove == null ? null : E.RATES_SHARE * iefMove, low: hygLow == null ? null : { date: S.dates[hygLow], rsi: X.hygRsi[hygLow] }, payoutsEstimated: hyg.estimated, spread: base.credit && base.credit.spread } };
  const stretch = E.stretchNow(E.stretchCtx(RD, S), k, now.reading);
  /* AL9: the last year of daily market readings by the same sum (the stored history ends at its own last day; these carry it to today),
     and the series itself, so the panel can work the reading out at any five-minute price of today */
  const t0 = Math.max(260, k - 260), tail = { dates: S.dates.slice(t0, k + 1), reading: [], spy: S.bars.SPY.c.slice(t0, k + 1), live: L.live }; for (let i = t0; i <= k; i++) tail.reading.push(i === k ? now.reading : rd(i).reading);
  return { S, k, hygTr: hyg.tr, tail, session: L.session, live: L.live, lastBar: S0.dates[S0.dates.length - 1], missing: L.missing, noRange: L.noRange, absent: S0.absent, inputs: E.inputsAt(X, k), reading: now, deployed, prior, nAvg, odds: E.oddsAt(now.reading, model), oddsAny: model.oddsAny, account, pie: pieNow, dips, names, idx, facts, stretch, modelAsOf: base.asOf }; }
/* one line for where a name stands in its cool-off (the Williams is the fast gauge, so it leads the sentence) */
export function nameState(c, u, st) { if (!c || !c.push) return { word: "NO PUSH IN THE PAST YEAR", tone: "" }; if (c.atHigh) return { word: "AT ITS HIGH — no cool-off yet", tone: "hot" };
  if (!st) return { word: "COOLING", tone: "" };
  const deep = !!(u && u.dipPct && c.dipPct < 2 * u.dipPct.q25), w = st.wr.state, r = st.rsi.state; let word, tone;
  if (w === "not yet") { word = "COOLING — Williams not reset yet"; tone = "hot"; }
  else { word = w === "fully reset" && r === "fully reset" ? "FULLY RESET" : r !== "not yet" ? "RESET" : "WILLIAMS RESET — RSI not yet"; tone = "ok"; word += c.wr != null && u.wr && c.wr <= u.wr.q75 ? " · in the zone now" : " · turned back up"; }
  if (deep) word += " · a deeper fall than its cool-offs"; else if (c.gaveUp) word += " · no new high in " + c.sessions + " sessions"; return { word, tone: deep ? "deep" : tone }; }

/* ---------- the fetches (the page passes its own apiGet; a study page or a test passes its own) ---------- */
export async function fetchDaily(getApi) { const half = Math.ceil(E.ALL_SYMBOLS.length / 2), parts = [E.ALL_SYMBOLS.slice(0, half), E.ALL_SYMBOLS.slice(half)];   // the chart API serves at most 25 symbols per request at this depth
  const rs = await Promise.all(parts.map((p) => getApi(`/candles-multi?symbols=${p.join(",")}&tf=1d&limit=${DAILY_BARS}`))); const candles = {}; for (const j of rs) Object.assign(candles, (j && j.candles) || {}); if (!candles.SPY) throw new Error("no daily bars"); return candles; }
export async function fetchLive(getApi) { const [q, m, g, h] = await Promise.all([getApi(`/quotes?symbols=${NONVIX.join(",")}`), getApi("/macro").catch(() => null), getApi(`/geiger?symbols=${[...E.INDEX, ...E.NAMES].join(",")}`).catch(() => null), getApi(`/candles-multi?symbols=${NONVIX.join(",")}&tf=30m&limit=16`).catch(() => null)]);
  const f = await getApi(`/candles-multi?symbols=SPY,QQQ,HYG,IEF&tf=5m&limit=${FIVE_MIN_BARS}`).catch(() => null);   // AL9: the number through the day — a failed read leaves the last path on screen
  return { quotes: (q && q.quotes && !Array.isArray(q.quotes) ? q.quotes : {}) || {}, macro: (m && m.macro) || null, geiger: (g && g.symbols) || null, intraday: (h && h.candles) || null, bars5: f && f.candles ? Object.fromEntries(Object.entries(f.candles).map(([sym, o]) => [sym, (o && o.series) || []])) : null, generated: q && q.generated_utc }; }

/* ---------- the picture ---------- */
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const MON = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]; export const day = (d) => (d ? +d.slice(8, 10) + " " + MON[+d.slice(5, 7) - 1] : "—"), dayY = (d) => day(d) + " " + d.slice(0, 4);
const f0 = (x) => (x == null || !isFinite(x) ? "—" : x.toFixed(0)), f1 = (x) => (x == null || !isFinite(x) ? "—" : x.toFixed(1)), f2 = (x) => (x == null || !isFinite(x) ? "—" : x.toFixed(2));
const sg = (x, d = 0) => (x == null || !isFinite(x) ? "—" : (x > 0 ? "+" : x < 0 ? "−" : "") + Math.abs(x).toFixed(d)), px = (x) => (x == null || !isFinite(x) ? "—" : x >= 1000 ? x.toLocaleString("en-US", { maximumFractionDigits: 0 }) : x.toFixed(2));
const usd = (x) => (x == null || !isFinite(x) ? "—" : Math.abs(x) >= 1000 ? "$" + (x / 1000).toFixed(Math.abs(x) >= 100000 ? 0 : 1) + "K" : "$" + x.toFixed(0)), pc = (x, d = 1) => (x == null || !isFinite(x) ? "—" : x.toFixed(d) + "%"), ord = (n) => { const v = Math.round(n), s = ["th", "st", "nd", "rd"], m = v % 100; return v + (s[(m - 20) % 10] || s[m] || s[0]); };
const tone = (x) => (x > 0.5 ? "up" : x < -0.5 ? "dn" : "");
const CSS = `.ds1{margin:14px 0 0;border-top:1px solid var(--line,#1c1c28);padding-top:12px;font-size:12px;line-height:1.55;color:var(--txt,#e8e8f0);--c-core:var(--core,#2196b8);--c-conv:var(--conv,#b38d3c);--c-cash:var(--cashc,#26263a);--c-tac:#b9b9c6;--trk:#22222e;--dimc:var(--dim,#8a8aa0)}
.ds1 *{box-sizing:border-box}.ds1 .up{color:var(--green,#38e07b)}.ds1 .dn{color:var(--red,#ff5470)}.ds1 .dim{color:var(--dimc)}
.ds1 .hd{display:flex;flex-wrap:wrap;gap:4px 14px;align-items:baseline;color:var(--dimc);font-size:11px;letter-spacing:.06em}.ds1 .hd b{color:var(--txt,#e8e8f0);font-weight:600;letter-spacing:.12em}
.ds1 .hd .livedot{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--green,#38e07b);margin-right:6px;vertical-align:1px}.ds1 .hd .livedot.off{background:#5a5a6c}.ds1 .hd .warn{color:var(--gold,#ffd166)}
.ds1 h4{margin:0 0 6px;font-size:11px;font-weight:600;letter-spacing:.14em;color:var(--dimc)}
.ds1 .g2{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,2.1fr);gap:14px 34px;margin-top:12px}
.ds1 .big{display:flex;flex-wrap:wrap;gap:6px 22px;align-items:flex-end}.ds1 .big .n{font-size:46px;font-weight:700;line-height:.95}.ds1 .big .n small{font-size:11px;font-weight:400;color:var(--dimc);letter-spacing:.04em;margin-left:8px}
.ds1 .big .s{font-size:12px;color:var(--dimc)}.ds1 .big .s b{color:var(--txt,#e8e8f0);font-weight:600}
.ds1 .track{position:relative;height:60px;margin:14px 0 0}.ds1 .track .bar{position:absolute;left:0;right:0;top:30px;height:6px;border-radius:3px;background:var(--trk)}
.ds1 .track .fill{position:absolute;left:0;top:30px;height:6px;border-radius:3px;background:#8a8aa0}.ds1 .track .tk{position:absolute;top:25px;width:1px;height:16px;background:#3a3a4a}
.ds1 .track .tl{position:absolute;top:44px;transform:translateX(-50%);font-size:11px;color:var(--dimc)}.ds1 .track .tl.end{transform:translateX(-100%)}.ds1 .track .tl.start{transform:none}
.ds1 .track .mk{position:absolute;top:2px;transform:translateX(-50%);font-size:11px;white-space:nowrap}.ds1 .track .mk i{display:block;width:2px;height:20px;margin:1px auto 0;background:#e8e8f0}
.ds1 .track .mk.l{transform:none}.ds1 .track .mk.l i{margin-left:0}.ds1 .track .mk.r{transform:translateX(-100%)}.ds1 .track .mk.r i{margin-right:0}
.ds1 .track .dp{position:absolute;top:22px;width:0;height:0;border-left:5px solid transparent;border-right:5px solid transparent;border-top:8px solid var(--gold,#ffd166);transform:translateX(-50%)}
.ds1 .dipline{display:flex;flex-wrap:wrap;gap:2px 16px;font-size:11.5px;color:var(--dimc);margin-top:4px}.ds1 .dipline b{color:var(--txt,#e8e8f0);font-weight:600}.ds1 .dipline i{display:inline-block;width:0;height:0;border-left:4px solid transparent;border-right:4px solid transparent;border-top:7px solid var(--gold,#ffd166);margin-right:5px}
.ds1 table{border-collapse:collapse;width:100%;font-size:11.5px;font-variant-numeric:tabular-nums}.ds1 td,.ds1 th{padding:3px 8px 3px 0;text-align:right;border-bottom:1px solid #14141e;white-space:nowrap}.ds1 td:first-child,.ds1 th:first-child{text-align:left;white-space:normal}.ds1 td:last-child,.ds1 th:last-child{padding-right:0}.ds1 th{font-weight:400;color:var(--dimc);font-size:11px;letter-spacing:.06em}
.ds1 .odds{margin-top:16px}.ds1 .odds td b{font-size:13px;font-weight:600}.ds1 .odds tr.any td{color:var(--dimc)}
.ds1 .ptsgrid{columns:2;column-gap:34px}.ds1 .famb{break-inside:avoid;margin-bottom:10px}
.ds1 .pt{display:grid;grid-template-columns:minmax(0,1fr) 110px 40px 58px;grid-template-areas:"nm bar v lab";gap:2px 10px;align-items:center;padding:4px 0;border-bottom:1px solid #14141e}.ds1 .famb .pt:last-child{border-bottom:0}
.ds1 .pt .nm{grid-area:nm;min-width:0}.ds1 .pt .nm b{font-weight:600}.ds1 .pt .nm span{color:var(--dimc);font-size:11px;display:block}
.ds1 .dv{grid-area:bar;position:relative;height:12px;background:var(--trk);border-radius:2px}.ds1 .dv::after{content:"";position:absolute;left:50%;top:-2px;bottom:-2px;width:1px;background:#5a5a6c}
.ds1 .dv i{position:absolute;top:1px;bottom:1px;border-radius:2px}.ds1 .dv i.p{left:50%;background:var(--green,#38e07b)}.ds1 .dv i.m{right:50%;background:var(--red,#ff5470)}.ds1 .dv.light i{background:none;border:1px solid var(--dimc)}.ds1 .dv.light.on i.p{background:var(--green,#38e07b);border:0}.ds1 .dv.light.on i.m{background:var(--red,#ff5470);border:0}
.ds1 .pt .v{grid-area:v;text-align:right;font-weight:600;font-variant-numeric:tabular-nums}.ds1 .pt label{grid-area:lab;font-size:11px;color:var(--dimc);white-space:nowrap;cursor:pointer;text-align:right}.ds1 .pt label input{vertical-align:-2px;margin:0 4px 0 0;accent-color:#8a8aa0}
.ds1 .fam{margin:0 0 2px;font-size:11px;letter-spacing:.14em;color:var(--dimc);display:flex;justify-content:space-between;gap:10px}.ds1 .fam b{color:var(--txt,#e8e8f0);font-weight:600;white-space:nowrap}
.ds1 .money{display:grid;grid-template-columns:minmax(0,280px) minmax(0,1fr) minmax(0,1.15fr);gap:14px 30px;margin-top:18px;padding-top:14px;border-top:1px solid var(--line,#1c1c28)}.ds1 .money .asm{grid-column:1/-1}
.ds1 svg text{font-family:inherit}.ds1 .pie{width:100%;max-width:280px;height:auto;display:block}
.ds1 .sw{display:inline-block;width:10px;height:10px;border-radius:2px;margin-right:7px;vertical-align:-1px}.ds1 .sw.core{background:var(--c-core)}.ds1 .sw.conviction{background:var(--c-conv)}.ds1 .sw.cash{background:var(--c-cash);outline:1px solid #3a3a4a}.ds1 .sw.tactical{background:repeating-linear-gradient(45deg,var(--c-tac) 0 2px,#55556a 2px 4px)}
.ds1 .dipr{margin:0 0 10px}.ds1 .dipr .lb{display:flex;flex-wrap:wrap;justify-content:space-between;gap:0 10px;font-size:11.5px}.ds1 .dipr .lb b{font-weight:600}.ds1 .dipr .lb span{color:var(--dimc)}
.ds1 .stk{display:flex;height:14px;border-radius:3px;overflow:hidden;gap:2px;margin:3px 0 2px}.ds1 .stk span{display:block;height:100%}.ds1 .stk .conviction{background:var(--c-conv)}.ds1 .stk .core{background:var(--c-core)}.ds1 .stk .cash{background:var(--c-cash)}.ds1 .stk .tactical{background:repeating-linear-gradient(45deg,var(--c-tac) 0 2px,#55556a 2px 4px)}
.ds1 .dipr .rc{font-size:11px;color:var(--dimc)}.ds1 .dipr .rc b{color:var(--txt,#e8e8f0);font-weight:500}
.ds1 .in{display:grid;grid-template-columns:repeat(auto-fill,minmax(196px,1fr));gap:6px 12px;margin-top:6px}.ds1 .in label{display:block;font-size:11px;color:var(--dimc)}.ds1 .in label>span{display:flex;justify-content:space-between;gap:8px}.ds1 .in label>span>u{text-decoration:none;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ds1 .in input{display:block;width:100%;background:#0d0d15;border:1px solid var(--line,#1c1c28);color:var(--txt,#e8e8f0);font:inherit;font-size:12px;padding:3px 6px;border-radius:4px}
.ds1 .in .bl{color:#7a7a90;font-weight:400;white-space:nowrap}.ds1 details>summary{cursor:pointer;font-size:11px;letter-spacing:.14em;color:var(--dimc);font-weight:600;margin-top:4px}.ds1 button.rst{background:none;border:1px solid var(--line,#1c1c28);color:var(--dimc);border-radius:5px;font:inherit;font-size:11px;padding:3px 10px;cursor:pointer;margin-top:8px}
.ds1 .names{display:grid;grid-template-columns:repeat(auto-fill,minmax(470px,1fr));gap:12px 16px;margin-top:8px}.ds1 .nc{border:1px solid var(--line,#1c1c28);border-radius:6px;padding:10px 12px;min-width:0;background:#0d0d15}
.ds1 .nc .t{display:flex;flex-wrap:wrap;gap:2px 10px;align-items:baseline}.ds1 .nc .t b{font-size:14px;font-weight:700}.ds1 .nc .t span{color:var(--dimc);font-size:11px}.ds1 .nc .t .p{color:var(--txt,#e8e8f0);font-size:13px;font-weight:600;margin-left:auto}
.ds1 .nc .st{font-size:11px;letter-spacing:.08em;margin:4px 0 6px;color:var(--dimc)}.ds1 .nc .st b{font-weight:600;color:var(--txt,#e8e8f0)}.ds1 .nc .st b.hot{color:var(--gold,#ffd166)}.ds1 .nc .st b.ok{color:var(--green,#38e07b)}.ds1 .nc .st i{font-style:normal;color:var(--red,#ff5470)}
.ds1 .gg{display:grid;grid-template-columns:66px minmax(0,1fr) 108px;gap:3px 10px;align-items:center;font-size:11px;margin-bottom:3px}.ds1 .gg .k{color:var(--dimc)}.ds1 .gg .w{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
.ds1 .gt{position:relative;height:14px}.ds1 .gt::before{content:"";position:absolute;left:0;right:0;top:6px;height:2px;background:var(--trk)}.ds1 .gt .zone{position:absolute;top:4px;height:6px;background:#2f2f40;border-radius:2px}.ds1 .gt .zone.full{background:#4a4a66}
.ds1 .gt .lo{position:absolute;top:0;width:0;height:0;border-left:4px solid transparent;border-right:4px solid transparent;border-top:6px solid #8a8aa0;transform:translateX(-50%)}.ds1 .gt .now{position:absolute;top:2px;width:10px;height:10px;border-radius:50%;background:#e8e8f0;border:2px solid #0d0d15;transform:translateX(-50%)}
.ds1 .gnote{font-size:11px;color:var(--dimc);margin:2px 0 6px}.ds1 .nc td.near{color:var(--gold,#ffd166)}.ds1 .nc tr.above td{color:#74748a}.ds1 .nc tr.usual td:first-child{color:var(--gold,#ffd166)}.ds1 .nc table{margin-top:4px;table-layout:fixed}.ds1 .nc td:first-child{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ds1 .nc th:nth-child(2){width:64px}.ds1 .nc th:nth-child(3){width:58px}.ds1 .nc th:nth-child(4),.ds1 .nc th:nth-child(5){width:62px}.ds1 .nc th:nth-child(6){width:92px}.ds1 .nc th{white-space:nowrap;overflow:hidden}.ds1 .nc .nr{display:none;color:var(--gold,#ffd166)}
.ds1 .sec{margin-top:18px;padding-top:14px;border-top:1px solid var(--line,#1c1c28)}.ds1 .rules{display:flex;flex-wrap:wrap;gap:6px 8px}.ds1 .rule{border:1px solid var(--line,#1c1c28);border-radius:5px;padding:4px 9px;font-size:11px;color:var(--dimc)}.ds1 .rule b{color:var(--txt,#e8e8f0);font-weight:600}.ds1 .rule.on{border-color:#6a6a80}.ds1 .rule.on b.o{color:var(--gold,#ffd166)}
@media (max-width:1300px){.ds1 .g2{grid-template-columns:minmax(0,1fr)}.ds1 .money{grid-template-columns:minmax(0,260px) minmax(0,1fr)}.ds1 .money .dipsb{grid-column:1/-1}}
@media (max-width:760px){.ds1 .money{grid-template-columns:minmax(0,1fr)}.ds1 .big .n{font-size:40px}.ds1 .ptsgrid{columns:1}.ds1 .pt{grid-template-columns:minmax(0,1fr) 40px 58px;grid-template-areas:"nm v lab" "bar bar bar"}.ds1 .names{grid-template-columns:minmax(0,1fr)}.ds1 .nc td.sp,.ds1 .nc th.sp{display:none}.ds1 td.hide-s,.ds1 th.hide-s{display:none}.ds1 .pie{margin:0 auto}.ds1 .nc th:nth-child(2){width:54px}.ds1 .nc th:nth-child(3){width:48px}.ds1 .nc th:nth-child(4){width:86px}.ds1 .nc td.near,.ds1 .nc th:nth-child(6){display:none}.ds1 .nc .nr{display:inline}.ds1 .nc td:first-child{white-space:normal;overflow:visible}.ds1 .nc td,.ds1 .nc th{padding-right:5px}.ds1 .gg{grid-template-columns:60px minmax(0,1fr) 92px}.ds1 td,.ds1 th{padding-right:6px}}`;

const WORDS = {
  rsi: (v) => `average RSI ${f0(v.inputs.rsi)} — SPY ${f0(v.facts.spyRsi)}, QQQ ${f0(v.facts.qqqRsi)}`,
  d21: (v) => `${sg(v.inputs.d21, 1)}% from the 21-day (the two averaged)`, d50: (v) => `${sg(v.inputs.d50, 1)}% from the 50-day`, d100: (v) => `${sg(v.inputs.d100, 1)}% from the 100-day`,
  gTrend: (v) => `daily Geiger trend ${sg(v.inputs.gTrend, 2)}${v.facts.hub.SPY ? ` · the Hub's own now: SPY ${sg(v.facts.hub.SPY.trend, 2)}, QQQ ${sg(v.facts.hub.QQQ?.trend, 2)}` : ""}`,
  gMom: (v) => `daily Geiger momentum ${sg(v.inputs.gMom, 2)}${v.facts.hub.SPY ? ` · the Hub's own now: SPY ${sg(v.facts.hub.SPY.momentum, 2)}, QQQ ${sg(v.facts.hub.QQQ?.momentum, 2)}` : ""}`,
  vixPct: (v) => `VIX ${f1(v.facts.vix.price)} — the ${ord(v.inputs.vixPct ?? 0)} percentile of its year · its lines: ${f1(v.facts.vix.p80)} and ${f1(v.facts.vix.p90)}`,
  vixHiPct: (v) => `today's high ${f1(v.facts.vix.high)} — ${v.facts.vix.state === "closed above" ? "ABOVE its 80th-percentile line" : v.facts.vix.state === "touched" ? "TOUCHED its 80th-percentile line, not holding above" : "no touch of " + f1(v.facts.vix.p80)}`,
  br50: (v) => `${v.facts.br50.up} of ${v.facts.br50.n} funds above their 50-day`, br200: (v) => `${v.facts.br200.up} of ${v.facts.br200.n} funds above their 200-day`,
  hygRsi: (v) => `HYG RSI ${f0(v.inputs.hygRsi)}${v.facts.credit.low ? ` · low ${f0(v.facts.credit.low.rsi)} on ${day(v.facts.credit.low.date)}` : ""}`, hygWr: (v) => `HYG Williams %R ${f0(v.inputs.hygWr)}`,
  creditOwn: (v) => `${sg(v.inputs.creditOwn, 2)}% in ten sessions with rates taken out (HYG ${sg(v.facts.credit.hygMove, 2)}%, the rates leg ${sg(v.facts.credit.ratesLeg, 2)}%)${v.facts.credit.spread ? ` · spread ${f2(v.facts.credit.spread.last[1])}% on ${day(v.facts.credit.spread.last[0])}` : ""}`,
  ld21: (v) => `${v.facts.ld21.up} of ${v.facts.ld21.n} core candidates above their 21-day`, ld50: (v) => `${v.facts.ld50.up} of ${v.facts.ld50.n} above their 50-day`,
};
function partsHtml(v) { const R = v.reading, all = [...R.parts, ...R.lights], out = [];
  for (const [fam, name] of Object.entries(E.FAMILY)) { const rows = all.filter((p) => p.family === fam); if (!rows.length) continue; const counted = rows.filter((p) => p.vote || p.counted).reduce((a, p) => a + p.points, 0), any = rows.some((p) => p.vote || p.counted);
    out.push(`<div class="famb" data-family="${fam}"><div class="fam"><span>${esc(name.toUpperCase())}</span><b class="${any ? tone(counted) : "dim"}">${any ? sg(counted) + " counted" : "shown, not counted"}</b></div>`);
    for (const p of rows) { const w = Math.min(50, (Math.abs(p.points) / 60) * 50), bar = p.missing ? "" : `<i class="${p.points >= 0 ? "p" : "m"}" style="width:${w.toFixed(1)}%"></i>`;
      out.push(`<div class="pt" data-part="${p.key}" data-points="${p.points.toFixed(1)}" data-vote="${p.vote ? 1 : 0}"><div class="nm"><b>${esc(p.name)}</b><span>${p.missing ? "no price for it — it is not counted" : esc((WORDS[p.key] || (() => ""))(v))}</span></div><div class="dv${p.vote ? "" : " light"}${p.counted ? " on" : ""}" title="${p.vote ? "counted" : "shown, not counted — tick the box to count it"}">${bar}</div><div class="v ${p.vote || p.counted ? tone(p.points) : "dim"}">${p.missing ? "—" : sg(p.points)}</div>${p.vote ? `<label class="dim">counted</label>` : `<label><input type="checkbox" data-count="${p.key}"${p.counted ? " checked" : ""}>count</label>`}</div>`); }
    out.push("</div>"); }
  return `<div class="ptsgrid">${out.join("")}</div>`; }
function trackHtml(v) { const x = (p) => clamp(p, 0, 100), R = v.reading.reading, side = (p) => (p > 80 ? " r" : p < 20 ? " l" : ""), ticks = [0, 20, 35, 50, 65, 80, 100];
  return `<div class="track"><div class="bar"></div><div class="fill" style="width:${x(R)}%"></div>${ticks.map((t) => `<div class="tk" style="left:${t}%"></div><div class="tl${t === 100 ? " end" : t === 0 ? " start" : ""}" style="left:${t}%">${t}</div>`).join("")}${v.dips.map((d) => `<div class="dp" style="left:${x(d.reading)}%" title="a further −${d.dipPct}%: SPY ${px(d.spy)}, QQQ ${px(d.qqq)}"></div>`).join("")}<div class="mk${side(R)}" style="left:${x(R)}%">now ${f0(R)}<i></i></div></div>
  <div class="dipline">${v.dips.map((d) => `<span data-dip="${d.dipPct}" data-reading="${d.reading}"><i></i>a further −${d.dipPct}% → <b>${f0(d.reading)}</b></span>`).join("")}</div>`; }
function oddsHtml(v) { const o = v.odds, a = v.oddsAny; if (!o) return ""; const p = (x) => (x == null ? "—" : (x * 100).toFixed(0) + "%"), m = (x) => (x == null ? "—" : sg(x, 1) + "%");
  return `<table class="odds" title="days the rule had never seen: it was fitted on prices to 2017 and read on 2018 to 2026"><tr><th colspan="5" style="text-align:left;white-space:normal">WHAT SPY AND QQQ DID 20 AND 60 SESSIONS ON FROM A MARKET READING OF ${o.lo}–${o.hi} · ${o.n} DAYS THE RULE HAD NEVER SEEN</th></tr><tr><th></th><th>higher 20 on</th><th>median</th><th>higher 60 on</th><th>median</th></tr><tr data-odds="band"><td>this band</td><td><b>${p(o.share20)}</b></td><td><b>${m(o.med20)}</b></td><td><b>${p(o.share60)}</b></td><td><b>${m(o.med60)}</b></td></tr><tr class="any" data-odds="any"><td>any day</td><td>${p(a.share20)}</td><td>${m(a.med20)}</td><td>${p(a.share60)}</td><td>${m(a.med60)}</td></tr></table>`; }
/* the pie: the outer ring is the shape at this reading, the inner ring is the account today */
function pieSvg(v) { const P = v.pie, C = 130, ring = (r, w, parts, id) => { let a = 0; const out = []; for (const s of parts) { if (!(s.pct > 0.05)) { a += s.pct; continue; } const gap = Math.min(0.9, s.pct * 0.45) * (2 / (r * 0.0628)), a0 = a + gap / 2, a1 = a + s.pct - gap / 2, pt = (t) => { const g = (t / 100) * 2 * Math.PI - Math.PI / 2; return [C + r * Math.cos(g), C + r * Math.sin(g)]; }, [x0, y0] = pt(a0), [x1, y1] = pt(a1);
      out.push(`<path d="M${x0.toFixed(2)} ${y0.toFixed(2)}A${r} ${r} 0 ${a1 - a0 > 50 ? 1 : 0} 1 ${x1.toFixed(2)} ${y1.toFixed(2)}" fill="none" stroke="${s.kind === "tactical" ? "url(#ds1hatch)" : `var(--c-${s.kind === "conviction" ? "conv" : s.kind})`}" stroke-width="${w}"><title>${esc(s.name)} — ${pc(s.pct)}${id === "o" && s.dollars != null ? " · " + usd(s.dollars) : ""}</title></path>`); a += s.pct; } return out.join(""); };
  const held = []; let cashNow = 100; for (const s of P.slices) if (s.sym && s.held > 0) { held.push({ kind: s.kind, name: s.name + " held", pct: s.held }); cashNow -= s.held; } for (const [s, pct] of Object.entries(P.extraHeld || {})) { held.push({ kind: "tactical", name: s + " held beyond its slot", pct }); cashNow -= pct; } held.push({ kind: "cash", name: "cash today", pct: Math.max(0, cashNow) });
  /* the inner ring keeps each held slice under its own outer slice */
  const inner = []; let at = 0; for (const s of P.slices) { if (s.sym && s.held > 0) inner.push({ kind: s.kind, name: s.name + " — held", pct: s.held }); const rest = s.pct - (s.sym ? s.held || 0 : 0); if (rest > 0) inner.push({ kind: "cash", name: "not yet bought", pct: rest }); at += s.pct; }
  const labels = []; { let at2 = 0; for (const sl of P.slices) { const mid = at2 + sl.pct / 2; at2 += sl.pct; if (sl.pct < 4.6 || sl.kind === "cash") continue; const g = (mid / 100) * 2 * Math.PI - Math.PI / 2, lx = C + 104 * Math.cos(g), ly = C + 104 * Math.sin(g) + 3.5; labels.push(`<text x="${lx.toFixed(1)}" y="${ly.toFixed(1)}" text-anchor="middle" font-size="10.5" font-weight="600" fill="${sl.kind === "tactical" ? "#0d0d15" : "#0d0d15"}" paint-order="stroke" stroke="${sl.kind === "tactical" ? "#b9b9c6" : "none"}" stroke-width="${sl.kind === "tactical" ? 3 : 0}">${sl.kind === "tactical" ? "tactical" : sl.sym}</text>`); } }
  return `<svg class="pie" viewBox="0 0 260 260" role="img" aria-label="the pie: the shape at this reading (outer ring) and the account today (inner ring)"><defs><pattern id="ds1hatch" width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="5" height="5" fill="#55556a"/><rect width="2.5" height="5" fill="#b9b9c6"/></pattern></defs>
  ${ring(104, 32, P.slices, "o")}${ring(70, 12, inner, "i")}${labels.join("")}
  <text x="130" y="118" text-anchor="middle" font-size="28" font-weight="700" fill="currentColor">${f0(P.invested)}%</text><text x="130" y="136" text-anchor="middle" font-size="11" fill="#8a8aa0">the shape, invested</text><text x="130" y="156" text-anchor="middle" font-size="13" font-weight="600" fill="currentColor">${f0(P.held)}% held today</text></svg>`; }
function pieTable(v) { const P = v.pie, rows = P.slices.map((s) => `<tr data-slice="${s.key}"><td><i class="sw ${s.kind}"></i>${esc(s.name)}</td><td>${pc(s.pct)}</td><td class="hide-s">${usd(s.dollars)}</td><td>${s.sym ? pc(s.held) : s.kind === "cash" ? pc(P.cashNow) : "—"}</td><td>${s.sym && s.toBuy > 0.05 ? usd(s.toBuyDollars) : s.kind === "tactical" && s.pct > 0.05 ? usd(s.dollars) : "—"}</td></tr>`).join("");
  return `<table><tr><th>of ${usd(P.nlv)}</th><th>the shape</th><th class="hide-s">in dollars</th><th>held</th><th>to buy</th></tr>${rows}</table>`; }
function dipsHtml(v) { const row = (label, sub, P, extra) => { const g = (k) => P.slices.filter((s) => s.kind === k).reduce((a, s) => a + s.pct, 0), w = (x) => Math.max(0, x).toFixed(2) + "%";
    return `<div class="dipr"><div class="lb"><b>${label}</b><span>${sub}</span></div><div class="stk" title="conviction ${pc(g("conviction"))} · core ${pc(g("core"))} · tactical ${pc(g("tactical"))} · cash ${pc(g("cash"))}"><span class="conviction" style="width:${w(g("conviction"))}"></span><span class="core" style="width:${w(g("core"))}"></span><span class="tactical" style="width:${w(g("tactical"))}"></span><span class="cash" style="width:${w(g("cash"))}"></span></div>${extra ? `<div class="rc">${extra}</div>` : ""}</div>`; };
  const K = (x) => sg(x / 1000, 1) + "K", nlv = v.account.nlv, tac = (P) => (P.tactical / 100) * nlv;
  return row(`now · reading ${f0(v.reading.reading)}`, `tactical ${pc(v.pie.tactical)} of the account = ${usd(tac(v.pie))}`, v.pie, `the shape is ${f0(v.pie.invested)}% invested · the account holds ${f0(v.pie.held)}%`) + v.dips.map((d) => row(`a further −${d.dipPct}% · reading ${f0(d.reading)}`, `tactical ${pc(d.pie.tactical)} = ${usd(tac(d.pie))} (${K(tac(d.pie) - tac(v.pie))})`, d.pie,
    `SPY ${px(d.spy)} · QQQ ${px(d.qqq)} · ${d.reading === d.readingCalm ? `if credit sells off with it: reading <b>${f0(d.readingCreditSells)}</b>` : `if credit holds: reading <b>${f0(d.readingCalm)}</b>`}<br>reaches: ${d.reached.length ? d.reached.map((r) => `<b>${r.sym}</b> ${esc(r.deepest)}${r.ids.length > 1 ? " +" + (r.ids.length - 1) : ""}`).join(" · ") : "no add level of any name"}`)).join(""); }
function inputsHtml(v, A, B, open = true) { const n = (key, label, val, base, step = 1, attr = "") => `<label title="${esc(label)} — baseline ${base}"><span><u>${esc(label)}</u><b class="bl">[${base}]</b></span><input type="number" step="${step}" data-in="${key}" value="${val}"${attr}></label>`;
  return `<details class="asm"${open ? " open" : ""}><summary>ASSUMPTIONS — yours to change · baseline in brackets</summary><div class="in">${n("heldPct", "held part, % of account", A.heldPct, B.heldPct)}${n("tacticalPct", "tactical at full, %", A.tacticalPct, B.tacticalPct)}${n("convShare", "conviction share, %", A.convShare, B.convShare)}${n("convLift", "its lift at reading 100", A.convLift, B.convLift)}${n("micronOfConv", "Micron, % of conviction", A.micronOfConv, B.micronOfConv)}${n("capMicron", "Micron cap, % of account", A.capMicron, B.capMicron)}${n("bandPts", "breakout band, points", A.bandPts, B.bandPts)}${n("breakoutDays", "breakout high, sessions", A.breakoutDays, B.breakoutDays)}${n("smoothMin", "minutes averaged", A.smoothMin, B.smoothMin, 5)}${n("buyFirst", "first buy, % of room", A.buyFirst, B.buyFirst, 5)}${n("zonePct", "one level within, %", A.zonePct, B.zonePct, 0.05)}${n("dips", "dips drawn, %", A.dips.join(" "), B.dips.join(" "), "any", ' type="text"').replace('type="number" ', "")}${n("dipCredit", "dip: credit sells? 0 / 1", A.dipCredit, B.dipCredit)}${n("cash", "cash, $", A.cash, B.cash, 100)}${E.NAMES.map((s) => n("shares." + s, s + " shares", A.shares[s] || 0, B.shares[s] || 0)).join("")}${[...E.CORE, "MU"].map((s) => n("w." + s, s + " core weight", A.coreWeights[s] ?? 0, B.coreWeights[s] ?? 0, 0.5)).join("")}${E.NAMES.map((s) => n("beta." + s, s + " beta to QQQ", A.beta[s], B.beta[s], 0.01)).join("")}${n("spyPerQqq", "SPY per 1% of QQQ", A.spyPerQqq, B.spyPerQqq, 0.01)}</div><button class="rst" data-reset="1">back to the baseline</button></details>`; }
function gauge(label, now, low, u, unit) { if (!u || u.med == null) return ""; const span = (u.start - u.q25) || 1, pos = (x) => clamp(((u.start - x) / span) * 100, 0, 100), fmt = (x) => (unit === 2 ? sg(x, 2) : f0(x));
  return `<div class="gg" title="its own past cool-offs: the shallowest quarter stopped by ${f2(u.q75)}, the usual one reached ${f2(u.med)}, the deepest quarter went under ${f2(u.q25)}"><div class="k">${label}</div><div class="gt"><span class="zone" style="left:${pos(u.q75)}%;width:${Math.max(1, pos(u.med) - pos(u.q75))}%"></span><span class="zone full" style="left:${pos(u.med)}%;width:${Math.max(1, 100 - pos(u.med))}%"></span>${low != null ? `<span class="lo" style="left:${pos(low)}%"></span>` : ""}${now != null ? `<span class="now" style="left:${pos(now)}%"></span>` : ""}</div><div class="w">${fmt(now)} <span class="dim">${low != null ? "▾ " + fmt(low) : "zone " + fmt(u.q75)}</span></div></div>`; }
function nameCard(n, v) { if (n.absent) return `<div class="nc" data-name="${n.sym}"><div class="t"><b>${n.sym}</b><span>no bars served — nothing to show</span></div></div>`; const c = n.cool, u = n.usual, ses = (k) => k + (k === 1 ? " session" : " sessions");
  const sub = !c.push ? "" : (c.atHigh ? `at the top of its leg today` : `top ${day(c.push)} at ${px(c.pushClose)} · ${ses(c.sessions)} ago · deepest ${sg(c.dipPct, 1)}%${c.dipAt ? " on " + day(c.dipAt) : ""} · now ${sg(c.offPushPct, 1)}%`) + (u ? ` · its usual cool-off: ${sg(u.dipPct.med, 1)}% over ${f0(u.sessions.med)} sessions, Williams to ${f0(u.wr.med)}, RSI to ${f0(u.rsi.med)} (${u.resumed} past cases${u.pooled ? ", pooled leaders — too few of its own" : ""})` : "");
  const lv = n.levels.map((r) => `<tr class="${r.below ? "" : "above"}${r.kind === "usual" ? " usual" : ""}" data-level="${esc(r.id)}"><td title="${esc(r.id + (r.note ? " — " + r.note : ""))}">${esc(r.id)}</td><td>${px(r.level)}</td><td>${sg(r.awayPct, 1)}%</td><td>${r.below ? px(r.qqqAt) + (r.qqqNear ? `<span class="nr"> ≈${r.qqqNear.replace("-day", "d")}</span>` : "") : "—"}</td><td class="sp">${r.below ? px(r.spyAt) : "—"}</td><td class="near">${r.below && r.qqqNear ? "its " + r.qqqNear : ""}</td></tr>`).join("");
  const [head, ...tail] = n.state.word.split(" · a deeper fall"), deepNote = tail.length ? " · a deeper fall" + tail.join("") : "";
  return `<div class="nc" data-name="${n.sym}" data-state="${esc(n.state.word)}"><div class="t"><b>${n.sym}</b><span>${n.role} · beta ${f2(n.beta)}</span><span class="p">${px(n.price)} <span class="${tone(n.chgPct * 10)}">${sg(n.chgPct, 1)}%</span></span></div>
  <div class="st"><b class="${n.state.tone === "deep" ? "ok" : n.state.tone}">${esc(head)}</b>${deepNote ? `<i>${esc(deepNote)}</i>` : ""}</div>${gauge("Williams", n.gauges.wr, c.lowWr, u && u.wr, 0)}${gauge("RSI", n.gauges.rsi, c.lowRsi, u && u.rsi, 0)}${gauge("momentum", n.gauges.mom, c.lowMom, u && u.mom, 2)}
  <div class="gnote">${esc(sub)}${n.hub ? ` · the Hub's Geiger now ${sg(n.hub.composite, 2)} (trend ${sg(n.hub.trend, 2)}, momentum ${sg(n.hub.momentum, 2)})` : ""}${n.hasLines ? "" : " · no named pivots are stored for it"}</div>
  <table><tr><th>add level</th><th>at</th><th>away</th><th>QQQ at</th><th class="sp">SPY at</th><th>≈ QQQ's own</th></tr>${lv}</table></div>`; }
const plain = (t) => String(t).replace(/\bevenings\b/g, "days").replace(/\bevening\b/g, "day");   /* AL9: a rule's name is stored with DS1's word for a day's close; on screen it is a day */
function rulesHtml(v, base) { const T = base.trim || [], any = T.find((t) => t.key === "any"), cell = (t) => { const on = t.key === "any" ? false : !!v.stretch[t.key]; return `<div class="rule${on ? " on" : ""}" data-rule="${t.key}" data-on="${on ? 1 : 0}" title="to 2017: paid ${Math.round(t.to2017.paid * t.to2017.n)} of ${t.to2017.n} · 2018 on: ${Math.round(t.from2018.paid * t.from2018.n)} of ${t.from2018.n}"><b class="o">${on ? "ON NOW" : "off"}</b> · ${esc(plain(t.name))} · <b>paid ${Math.round(t.all.paid * t.all.n)} of ${t.all.n} (${(t.all.paid * 100).toFixed(0)}%)</b></div>`; };
  const rows = T.filter((t) => t.key !== "any").sort((a, b) => (v.stretch[b.key] ? 1 : 0) - (v.stretch[a.key] ? 1 : 0) || b.all.paid - a.all.paid);
  return `<div class="sec"><h4>THE STRETCHED END — DID TRIMMING PAY? ${any ? `· ON ANY DAY IT PAID ${(any.all.paid * 100).toFixed(0)}% OF THE TIME` : ""}</h4><div class="rules">${rows.map(cell).join("")}</div></div>`; }
export function ageWords(st, nowMs = Date.now()) { if (!st.readAt) return "no reading yet"; const s = Math.max(0, Math.round((nowMs - st.readAt.ms) / 1000)); return `read ${st.readAt.hms} New York · ${s < 90 ? s + " s old" : s < 5400 ? Math.round(s / 60) + " min old" : (s / 3600).toFixed(1) + " h old"}`; }
export function render(el, st, moneyEl = null) {
  if (typeof document !== "undefined" && !document.getElementById("ds1-css")) { const s = document.createElement("style"); s.id = "ds1-css"; s.textContent = CSS; document.head.appendChild(s); }
  if (!st.view) { const none = `<div class="hd"><span class="livedot off"></span><b>THE MARKET READING, LIVE</b><span class="warn">no reading yet: ${esc(st.error || "reading live prices…")}</span></div>`; el.innerHTML = `<div class="ds1" id="ds1-root">${none}</div>`;
    if (moneyEl) moneyEl.innerHTML = `<div class="ds1" style="border-top:0;margin-top:0;padding-top:0">${none}</div>`; return; }
  const v = st.view, A = st.A, B = baseline(st.base), R = v.reading, ph = phaseOf(st.now), marks = [];
  if (st.error) marks.push(`last try failed (${esc(st.error)}) — showing the reading before it`);
  if (v.missing.length) marks.push(`no live price for ${esc(v.missing.join(", "))} — the close of ${esc(day(v.lastBar))} is used`);
  if (v.absent.length) marks.push(`no bars for ${esc(v.absent.join(", "))}`); if (v.noRange.length > 3) marks.push(`today's high and low not served for ${v.noRange.length} symbols — their Williams reads on the price alone`);
  if (v.facts.credit.payoutsEstimated) marks.push(`${v.facts.credit.payoutsEstimated} HYG payout${v.facts.credit.payoutsEstimated > 1 ? "s" : ""} assumed at the last known size`); if (R.missing) marks.push(`${R.missing} counted part${R.missing > 1 ? "s" : ""} without a price`);
  const when = v.live ? `${ph === "open" ? "live" : ph} · session of ${esc(dayY(v.session))}` : `at the close of ${esc(dayY(v.session))} (New York is not trading)`;
  const money = `<div><h4>THE PIE — THE SHAPE (OUTER) · THE ACCOUNT TODAY (INNER)</h4>${pieSvg(v)}</div><div><h4>SLICE BY SLICE</h4>${pieTable(v)}</div><div class="dipsb"><h4>ON A DIP IN SPY AND QQQ TOGETHER</h4>${dipsHtml(v)}</div>${inputsHtml(v, A, B, st.asmOpen ?? !moneyEl)}`;
  el.innerHTML = `<div class="ds1" id="ds1-root" data-reading="${R.reading}" data-deployed="${v.deployed.toFixed(1)}" data-session="${esc(v.session)}" data-live="${v.live ? 1 : 0}" data-invested="${v.pie.invested}" data-held="${v.pie.held}">
  <div class="hd"><span><span class="livedot${v.live && ph === "open" && !st.error ? "" : " off"}"></span><b>THE MARKET READING, LIVE</b></span><span>${when}</span><span id="ds1-age" data-ds1-age>${esc(ageWords(st))}</span><span>${esc(nextReadWords(st.now))}</span>${marks.map((m) => `<span class="warn">${m}</span>`).join("")}</div>
  <div class="g2"><div><div class="big"><div class="n">${f0(R.reading)}<small>THE MARKET READING · 0 STRETCHED · 100 WASHED OUT</small></div><div class="s">puts <b>${f0(v.deployed)}%</b> of the tactical ${f0(A.tacticalPct)} points to work = <b>${pc(v.pie.tactical)}</b> of the account, on top of the ${f0(A.heldPct)}% held part · at the close of ${v.prior.slice(0, 3).map((p) => `${esc(day(p.date))} <b>${f0(p.reading)}</b>`).join(", ")}</div></div>${trackHtml(v)}${oddsHtml(v)}</div>
  <div><h4>WHAT MAKES THE MARKET READING, IN POINTS — 50 IS A TYPICAL DAY · A FILLED BAR IS COUNTED · AN OUTLINE IS SHOWN BUT NOT COUNTED</h4>${partsHtml(v)}</div></div>
  ${moneyEl ? "" : `<div class="money" id="ds1money">${money}</div>`}
  <div class="sec"><h4>LEVELS AND THE RESET TRACKER — ● NOW · ▾ THE LOW SINCE THE TOP · THE SHADED ZONE IS THAT NAME'S OWN USUAL COOL-OFF</h4><div class="names">${v.names.map((n) => nameCard(n, v)).join("")}</div></div>
  ${rulesHtml(v, st.base)}</div>`;
  if (moneyEl && st.moneyPanel) { let ok = false; try { st.moneyPanel.draw(moneyEl, st, { inputsHtml: (open) => inputsHtml(v, A, B, open), ageWords: () => ageWords(st), when, marks }); ok = true; } catch (e) { st.panelError = String((e && e.message) || e); }   /* AL9: the panel that explains itself; if its drawing throws, DS1's own picture is drawn instead and the cause is kept */
    if (ok) { st.panelError = null; return; } }
  if (moneyEl) moneyEl.innerHTML = `<div class="ds1" style="border-top:0;margin-top:0;padding-top:0"><div class="money" id="ds1money" style="border-top:0;margin-top:0;padding-top:0">${money}</div></div>`; }

/* ---------- the loop ---------- */
export async function startDeploymentSystem({ el, moneyEl = null, getApi, baseUrl = "study/ds1/data/ds1-live.json", clock = () => new Date(), tickMs = 1000, onRead = null, store, moneyPanel = null, historyUrl = "study/al9/data/history.json" }) {
  const st = { base: null, candles: null, candlesAt: null, live: null, view: null, readAt: null, error: null, now: nyParts(clock()), A: null, reads: 0, tries: 0, busy: false, moneyPanel, history: null, bars5: null, ui: {} }; if (typeof window !== "undefined") window.DS1_LIVE = st;
  /* the money panel: on the release the page hands over its own host. Where a page still carries AL8's id (#scenbars), the panel is taken
     over without editing AL8's code: its id is changed, so AL8's renderer finds nothing to draw into (study/ds1/seam-check.html) */
  if (moneyEl) { moneyEl.id = "ds1money-host"; const h = moneyEl.closest && moneyEl.closest(".panel") && moneyEl.closest(".panel").querySelector("h2"); if (h && h.firstChild) h.firstChild.textContent = (moneyPanel && moneyPanel.title ? moneyPanel.title : "THE MONEY — the pie today and on a dip") + " "; }
  /* one drawing at a time. Replacing the panel while one of its inputs has the caret makes the browser fire that input's own 'change' as it
     leaves the page — in the middle of the replacement — and the handler below asks for a drawing again. Drawn there and then, the two
     would pull the page from under each other (the browser throws); so a drawing asked for while one is under way waits and is done once
     the first has finished. */
  let drawing = false, again = false;
  const draw = () => { if (drawing) { again = true; return; } drawing = true; try { render(el, st, moneyEl); } finally { drawing = false; } if (typeof window !== "undefined") window.DS1_LIVE_READY = true; if (again) { again = false; draw(); } };
  const recompute = () => { if (!st.candles || !st.live) return; try { st.view = view({ base: st.base, candles: st.candles, ...st.live, A: st.A }); } catch (e) { st.error = String((e && e.message) || e); } };
  async function read() { if (st.busy) return; st.busy = true; st.tries++; const now = nyParts(clock()); st.now = now; let fresh = false;
    try { if (!st.base) { const r = await fetch(baseUrl, { cache: "no-store" }); if (!r.ok) throw new Error("the model file " + r.status); st.base = await r.json(); st.A = loadAssumptions(st.base, store); }
      /* AL9: the number's stored history (every session since 2018). Asked for once and not waited on — the panel draws the days it has */
      if (moneyPanel && !st.history && !st.historyAsked) { st.historyAsked = true; fetch(historyUrl, { cache: "no-store" }).then((r) => (r.ok ? r.json() : Promise.reject(new Error("the history file " + r.status)))).then((h) => { st.history = h; draw(); }).catch((e) => { st.historyError = String((e && e.message) || e); st.historyAsked = false; }); }
      if (!st.candles || st.candlesAt.date !== now.date || (now.minutes >= SESSION.afterClose && st.candlesAt.minutes < SESSION.afterClose)) { st.candles = await fetchDaily(getApi); st.candlesAt = now; }
      const live = await fetchLive(getApi); st.live = live; if (live.bars5) { st.bars5 = live.bars5; st.bars5At = nyParts(clock()); } st.view = view({ base: st.base, candles: st.candles, ...live, A: st.A }); st.readAt = nyParts(clock()); st.error = null; st.reads++; fresh = true;
    } catch (e) { st.error = String((e && e.message) || e); } finally { st.busy = false; }
    draw(); if (fresh && onRead) { try { onRead(st); } catch (e) { /* the page's own courtesy after a read (its sources line, AL9's note): it is told once the panel is drawn, and its failure never touches the reading */ } } }
  const onChange = (ev) => { const t = ev.target; if (!t || !st.A) return; const B = baseline(st.base);
    if (t.dataset && t.dataset.count) { st.A.count = { ...st.A.count, [t.dataset.count]: !!t.checked }; }
    else if (t.dataset && t.dataset.in) { const key = t.dataset.in, num = parseFloat(t.value);
      if (key === "dips") { const d = String(t.value).split(/[\s,;]+/).map(parseFloat).filter((x) => x > 0 && x <= 30).slice(0, 4); st.A.dips = d.length ? d : B.dips.slice(); }
      else if (!isFinite(num)) return; else if (key.startsWith("shares.")) st.A.shares = { ...st.A.shares, [key.slice(7)]: Math.max(0, num) }; else if (key.startsWith("w.")) st.A.coreWeights = { ...st.A.coreWeights, [key.slice(2)]: Math.max(0, num) }; else if (key.startsWith("beta.")) st.A.beta = { ...st.A.beta, [key.slice(5)]: num }; else st.A[key] = key === "dipCredit" ? (num ? 1 : 0) : Math.max(0, num); }
    else return; saveAssumptions(st.A, store); recompute(); draw(); };
  const onClick = (ev) => { const t = ev.target; if (t && t.dataset && t.dataset.reset) { st.A = baseline(st.base); saveAssumptions(st.A, store); recompute(); draw(); } };
  const onToggle = (ev) => { const t = ev.target; if (t && t.classList && t.classList.contains("asm")) st.asmOpen = t.open; };   /* a fold the user opened stays open through every redraw */
  for (const host of [el, moneyEl]) if (host && host.addEventListener) { host.addEventListener("change", onChange); host.addEventListener("click", onClick); host.addEventListener("toggle", onToggle, true); }
  st.redraw = draw; if (moneyPanel && moneyPanel.attach && moneyEl) moneyPanel.attach(moneyEl, st);   /* AL9: the panel's own clicks (the chart's range, a day picked on it) redraw without a read */
  st.readNow = read;   // the tests (and a console) can ask for a read; the page itself never needs to
  render(el, st, moneyEl);   // "reading live prices…" in both places at once, so neither sits empty while the first read is on its way
  await read();
  const tick = () => { const now = nyParts(clock()); st.now = now; if (typeof document !== "undefined") for (const a of document.querySelectorAll("[data-ds1-age]")) a.textContent = ageWords(st, now.ms); if (typeof document !== "undefined" && document.hidden) return; if (readDue(now, st.readAt) && !st.busy) { /* a failed try is retried at the same pace as a read, never faster than every 20 s */ if (st.error && st.lastTry && now.ms - st.lastTry < 20000) return; st.lastTry = now.ms; read(); } };
  const timer = setInterval(tick, tickMs); if (typeof document !== "undefined") document.addEventListener("visibilitychange", () => { if (!document.hidden) tick(); });
  return { state: st, read, stop: () => clearInterval(timer) }; }
