/* AL9 — the pictures, headless, every non-GET blocked, one page at a time: the allocation tool's first panel (index.html) at 1680 and 390.
     node scripts/al9-shots.mjs [outdir] [tool|page|all]
   Each picture is one part of the panel, cut from the full page so the sticky section bar never sits on top of it; the report printed at
   the end says what was on the page when they were taken. */
import fs from "node:fs"; import path from "node:path"; import { openPage, ROOT } from "../tests/_harness.mjs";
const OUT = process.argv[2] || path.join(ROOT, "study/al9/pictures"), WHAT = process.argv[3] || "all"; fs.mkdirSync(OUT, { recursive: true });
const report = [];
const clipOf = (page, sel) => page.evaluate((s) => { const e = document.querySelector(s); if (!e) return null; const r = e.getBoundingClientRect(); return { x: Math.max(0, r.left + scrollX), y: r.top + scrollY, width: Math.min(r.width, innerWidth), height: r.height }; }, sel);
if (WHAT !== "page") for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h }); const { page } = P;
  const shot = async (name, sel, pad = 8) => { const clip = await clipOf(page, sel); if (clip && clip.height > 4) await page.screenshot({ path: path.join(OUT, `al9-tool-${name}-${w}.png`), fullPage: true, clip: { x: Math.max(0, clip.x - pad), y: Math.max(0, clip.y - pad), width: Math.min(w, clip.width + 2 * pad), height: clip.height + 2 * pad } }); return !!clip; };
  try { await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && document.getElementById("a9-root"), null, { timeout: 120000 }); await page.waitForFunction(() => window.DS1_LIVE.history, null, { timeout: 60000 }).catch(() => {}); await page.waitForTimeout(1500);
    /* 0 · the first screen as it loads */
    await page.evaluate(() => window.scrollTo(0, 0)); await page.waitForTimeout(300); await page.screenshot({ path: path.join(OUT, `al9-tool-0-the-first-screen-as-it-loads-${w}.png`) });
    await shot("1-the-number-and-its-history", "#a9-root .a9-top"); await shot("2-the-chain-as-pies-now-and-fully-invested", '#a9-root [data-sec="chain"]'); await shot("3-room-to-play", '#a9-root [data-sec="room"]');
    const info = await page.evaluate(() => { const st = window.DS1_LIVE, r = document.getElementById("a9-root"), host = document.getElementById("ds1money-host"), X = st.explain, leaves = [...host.querySelectorAll("*")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg")), f = (x, d = 1) => (x == null ? null : +x.toFixed(d));
      return { readAt: st.readAt && st.readAt.date + " " + st.readAt.hms + " New York", session: st.view.session, live: st.view.live, number: f(X.sm.number), thisMinute: f(X.live.number), marketReading: f(X.sm.reading), averaged: X.sm.points + " points" + (X.sm.sessionOver ? " (the session's last hour)" : ""), open: X.marks.open && [X.marks.open.hm, f(X.marks.open.number)], marketLow: X.marks.low && [X.marks.low.hm, f(X.marks.low.number)], yesterday: X.yest && [X.yest.date, f(X.yest.number)], pathPoints: X.path.length, days: X.hist.d.length, named: X.named.map((k) => [k.d, k.kind, f(k.number)]),
        micron: X.today.names.MU && { now: f(X.today.names.MU.pct, 2), parts: X.today.names.MU.parts.map((p) => [p.kind, f(p.pct, 2)]), ceiling: f(X.full.names.MU.pct, 2) }, conv: [f(X.today.convOfInvested, 2), f(X.full.convOfInvested, 2)], held: f(X.room.held, 2), room: [f(X.room.room, 2), Math.round(X.room.roomUsd)], nlv: Math.round(X.room.nlv), breakingOut: X.breaking, dips: X.dips.map((d) => [d.dipPct, f(d.number)]),
        error: st.error, panelError: st.panelError || null, historyLoaded: !!st.history, range: r.dataset.range, pies: host.querySelectorAll(".a9-pie svg").length, roomRows: host.querySelectorAll("[data-room]").length, levels: host.querySelectorAll("[data-level]").length, marksLabelled: [...host.querySelectorAll("#a9-chart [data-mark]")].map((e) => e.dataset.mark.slice(2) + (e.dataset.labelled === "1" ? "" : " (no date)")),
        panelTop: Math.round(host.getBoundingClientRect().top + scrollY), panelHeight: Math.round(host.getBoundingClientRect().height), firstRowBottom: Math.round(host.querySelector('.a9-row[data-chain="now"]').getBoundingClientRect().bottom + scrollY), secondRowBottom: Math.round(host.querySelector('.a9-row[data-chain="full"]').getBoundingClientRect().bottom + scrollY), scrollW: document.scrollingElement.scrollWidth, innerW: innerWidth, minFont: Math.min(...leaves.map((e) => parseFloat(getComputedStyle(e).fontSize))), svgMinFont: Math.min(...[...host.querySelectorAll("svg text")].map((e) => parseFloat(e.getAttribute("font-size")))), note: [...document.querySelectorAll(".a9-note")].map((e) => (e.hidden ? "(hidden) " : "") + e.textContent) }; });
    /* 4 · every assumption, the fold opened */
    await page.evaluate(() => { const d = document.querySelector("#ds1money-host details.asm"); if (d) d.open = true; }); await page.waitForTimeout(200); await shot("4-the-assumptions-opened", "#ds1money-host details.asm");
    await page.evaluate(() => { const d = document.querySelector("#ds1money-host details.asm"); if (d) d.open = false; for (const e of document.querySelectorAll("#ds1money-host details[data-a9-fold]")) e.open = true; }); await page.waitForTimeout(200); await shot("5-page-specs-and-the-dips-opened", '#a9-root [data-sec="more"]');
    await page.evaluate(() => { for (const e of document.querySelectorAll("#ds1money-host details[data-a9-fold]")) e.open = false; }); await page.waitForTimeout(150);
    /* 6 · a day picked on the chart: the April 2025 low, and the first row of pies as they would have been */
    await page.locator('#ds1money-host [data-a9-range="low25"]').click(); await page.waitForTimeout(250);
    const at = await page.evaluate(() => { const g = document.querySelector('#a9-chart [data-mark="2025-04-08"] line'), b = document.getElementById("a9-chart").getBoundingClientRect(); return g ? { x: b.left + +g.getAttribute("x1"), y: b.top + b.height * 0.55 } : null; });
    if (at) { await page.evaluate(() => document.getElementById("a9-chart").scrollIntoView({ block: "center" })); await page.waitForTimeout(150); const at2 = await page.evaluate(() => { const g = document.querySelector('#a9-chart [data-mark="2025-04-08"] line'), b = document.getElementById("a9-chart").getBoundingClientRect(); return { x: b.left + +g.getAttribute("x1"), y: b.top + b.height * 0.55 }; }); await page.mouse.move(at2.x, at2.y); await page.mouse.click(at2.x, at2.y); await page.waitForTimeout(300);
      info.picked = await page.evaluate(() => ({ banner: (document.querySelector("#ds1money-host .a9-asof") || {}).innerText, firstRow: (document.querySelector('#ds1money-host .a9-row[data-chain="now"] .a9-rl') || {}).innerText, read: (document.getElementById("a9-read") || {}).innerText }));
      await page.evaluate(() => window.scrollTo(0, 0)); await page.waitForTimeout(250);   /* back to the top, so the sticky section bar sits where it belongs in the picture */
      await shot("6-a-day-picked-the-april-2025-low-number-and-history", "#a9-root .a9-top"); await shot("6-a-day-picked-the-april-2025-low-the-pies", '#a9-root [data-sec="chain"]'); await page.locator("#ds1money-host [data-a9-now]").click(); await page.waitForTimeout(250); }
    /* 7 · the two other ranges of the history */
    await page.locator('#ds1money-host [data-a9-range="all"]').click(); await page.waitForTimeout(250); await shot("7-the-history-since-2018", "#a9-root .a9-hist"); await page.locator('#ds1money-host [data-a9-range="3m"]').click(); await page.waitForTimeout(250); await shot("7-the-history-three-months", "#a9-root .a9-hist");
    /* 8 · the whole panel, and the two places further down that now say which figure is the answer and read in plain words */
    await page.locator(`#ds1money-host [data-a9-range="${w >= 760 ? "low25" : "3m"}"]`).click(); await page.waitForTimeout(250); await shot("8-the-whole-panel", "#ds1money-host", 12);
    await shot("9-the-brief-with-the-note", "#p-brief", 0); await page.evaluate(() => { const p = document.getElementById("ds1live").closest(".panel"); if (p.classList.contains("folded")) { const b = p.querySelector(".pfold"); if (b) b.click(); } }); await page.waitForTimeout(400); await page.evaluate(() => window.scrollTo(0, 0)); await page.waitForTimeout(200);
    { const c = await page.evaluate(() => { const p = document.getElementById("ds1live").closest(".panel").getBoundingClientRect(), g = document.querySelector("#ds1-root .g2").getBoundingClientRect(); return { x: Math.max(0, p.left + scrollX), y: p.top + scrollY, width: Math.min(p.width, innerWidth), height: g.bottom - p.top + 14 }; }); await page.screenshot({ path: path.join(OUT, `al9-tool-9-step-2-the-note-and-the-market-reading-in-plain-words-${w}.png`), fullPage: true, clip: c }); }
    report.push({ page: "index.html", width: w, errors: P.errors, nonGet: P.nonGet.blocked + P.nonGet.allowed, ...info }); } finally { await P.close(); } }
if (WHAT !== "tool") for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h, path: "study/al9/AL9.html" }); try { await P.page.waitForFunction(() => window.AL9_PAGE_READY === true && [...document.querySelectorAll("img")].every((i) => i.complete), null, { timeout: 60000 }); await P.page.waitForTimeout(500); await P.page.screenshot({ path: path.join(OUT, `al9-page-0-first-screen-${w}.png`) });
    report.push({ page: "study/al9/AL9.html", width: w, errors: P.errors, nonGet: P.nonGet.blocked + P.nonGet.allowed, ...(await P.page.evaluate(() => ({ scrollW: document.scrollingElement.scrollWidth, innerW: innerWidth, imgs: [...document.querySelectorAll("img")].map((i) => i.naturalWidth > 0).filter(Boolean).length + " of " + document.querySelectorAll("img").length, minFont: Math.min(...[...document.querySelectorAll("body *")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0).map((e) => parseFloat(getComputedStyle(e).fontSize))) }))) }); } finally { await P.close(); } }
console.log(JSON.stringify(report, null, 1)); console.log("pictures in", OUT, fs.readdirSync(OUT).filter((f) => /\.png$/.test(f)).length);
