/* DB2 — the pictures, headless, every non-GET blocked, ONE page at a time: the tool's first screen at 1680 and 390 as it loads on live
   prices, the card "how it gets to the number" on its own, and the same card with a what-if chip picked (−8% runs past the end of the
   scale, −5% has the VIX adding and the cash put back, −3%, +3%, +5% stops at 0).
     node scripts/db2-shots.mjs
   Drawn at twice the pixels (a MacBook's own density) so the thin marks can be examined; the layout is the 1680 and the 390 one. The
   private account file is never served to a picture run (tests/_harness.mjs). Pictures land in study/db2/pictures; the report printed at
   the end, and kept in study/db2/data/db2-shots.json, says what was on the screen when each was taken. */
import fs from "node:fs"; import path from "node:path"; import { startServer, chromium, ROOT } from "../tests/_harness.mjs";
const OUT = path.join(ROOT, "study/db2/pictures"), DATA = path.join(ROOT, "study/db2/data"); fs.mkdirSync(OUT, { recursive: true }); fs.mkdirSync(DATA, { recursive: true }); for (const f of fs.readdirSync(OUT)) if (f.endsWith(".png")) fs.unlinkSync(path.join(OUT, f));
const ny = () => new Intl.DateTimeFormat("en-GB", { timeZone: "America/New_York", day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date()), report = [];
const name = (m) => (m === 0 ? "now" : (m < 0 ? "minus-" : "plus-") + String(Math.abs(m)).replace(".", "-"));
for (const [w, h] of [[1680, 1050], [390, 844]]) { const srv = await startServer(), browser = await chromium.launch({ headless: true }), ctx = await browser.newContext({ viewport: { width: w, height: h }, deviceScaleFactor: 2 }), page = await ctx.newPage(), errors = [], nonGet = [];
  await page.route("**/*", (r) => { if (r.request().method() !== "GET") { nonGet.push(r.request().method() + " " + r.request().url()); return r.abort(); } r.continue(); }); page.on("pageerror", (e) => errors.push(String(e)));
  const shot = (n, full = false) => page.screenshot({ path: path.join(OUT, `db2-${n}-${w}.png`), fullPage: full }), card = () => page.locator('#db1-root section[aria-label="How it gets to the number"]');
  try { await page.goto(srv.url, { waitUntil: "networkidle", timeout: 180000 }); await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && document.querySelector("#db1-root[data-version]") && document.querySelector("#db1-root [data-how]"), null, { timeout: 150000 }); await page.waitForTimeout(700);
    const info = () => page.evaluate(() => { const d = document.getElementById("db1-root"), hw = d.querySelector("[data-how]"), st = window.DS1_LIVE, box = (e) => e.getBoundingClientRect(), sec = hw.closest("section"), rail = box(hw.querySelector("[data-rail]")), fill = box(hw.querySelector("[data-fill]"));
      return { move: +d.dataset.move, number: +d.dataset.number, reading: +d.dataset.reading, version: +d.dataset.version, session: st.view.session, live: st.view.live, readAt: st.readAt.hms + " New York", heading: sec.querySelector(".lab").textContent, formula: d.querySelector('[data-line="sum"]').textContent, layout: hw.dataset.layout, fillEndsAt: +(((fill.right - rail.left) / rail.width) * 100).toFixed(2), leftOver: +hw.dataset.off,
        rows: [...hw.querySelectorAll("[data-step]")].map((l) => { const L = box(l), b = box(l.querySelector("[data-bar]")); return { step: l.dataset.step, from: +(+l.dataset.from).toFixed(2), to: +(+l.dataset.to).toFixed(2), drawnFrom: +(((b.left - L.left) / L.width) * 100).toFixed(1), drawnTo: +(((b.right - L.left) / L.width) * 100).toFixed(1), caption: hw.querySelector(`[data-line="${l.dataset.step}"]`).textContent }; }),
        cardHeight: Math.round(box(sec).height), cardTop: Math.round(box(sec).top), chipsBottom: Math.round(box(d.querySelector(".chips")).bottom), footBottom: Math.round(box(d.querySelector(".foot")).bottom), longVersionTop: Math.round(box(document.getElementById("longversion")).top), scrollW: document.scrollingElement.scrollWidth }; });
    const R = { width: w, height: h, now: await info(), chips: {} }; await shot("1-first-screen"); await shot("1-first-screen-full", true); await card().screenshot({ path: path.join(OUT, `db2-2-card-now-${w}.png`) });
    for (const m of [-8, -5, -3, 3, 5]) { await page.locator(`#db1-root .chip[data-move="${m}"]`).click(); await page.waitForTimeout(250); R.chips[m] = await info(); await card().screenshot({ path: path.join(OUT, `db2-3-card-at-${name(m)}-${w}.png`) }); if (m === -5) { await card().scrollIntoViewIfNeeded(); await shot("4-first-screen-at-minus-5"); } }
    await page.locator('#db1-root .chip[data-move="0"]').click(); await page.waitForTimeout(200); R.back = await info(); R.errors = errors; R.nonGet = nonGet.length; report.push(R);
  } finally { await browser.close(); srv.server.close(); } }
fs.writeFileSync(path.join(DATA, "db2-shots.json"), JSON.stringify({ stamp: "pictures taken " + ny() + " New York", takenAt: new Date().toISOString(), report }, null, 1));
for (const R of report) { console.log(`\n== ${R.width} × ${R.height} · read ${R.now.readAt} · session ${R.now.session} · live ${R.now.live} · version ${R.now.version} · errors ${R.errors.length} · non-GET ${R.nonGet} · no sideways scroll ${R.now.scrollW <= R.width}`);
  for (const [k, x] of [["now", R.now], ...Object.entries(R.chips)]) { console.log(`  ${k === "now" ? "now" : k + "%"} · ${x.heading} · ${x.formula} · fill ends at ${x.fillEndsAt} · left over ${x.leftOver} · card ${x.cardHeight}px · chips end ${x.chipsBottom} · foot ends ${x.footBottom} · the long version at ${x.longVersionTop} · ${x.layout}`); for (const r of x.rows) console.log(`      ${r.step.padEnd(7)} ${String(r.from).padStart(7)} → ${String(r.to).padStart(7)}   drawn ${String(r.drawnFrom).padStart(5)} to ${String(r.drawnTo).padStart(5)}   ${r.caption}`); } }
console.log("\npictures in", OUT, fs.readdirSync(OUT).filter((f) => /\.png$/.test(f)).length);
