/* DS2 — the pictures, headless, every non-GET blocked, ONE page at a time: the allocation tool with version 2 and the two dials
   (index.html) at 1680 and 390, then the page for Alan (study/ds2/DS2.html) at 1680 and 390.
     node scripts/ds2-shots.mjs [tool|page|all]
   Each picture is one part, cut from the full page. The report printed at the end says what was on the page when they were taken; the
   time of the run is kept in study/ds2/data/ds2-shots.json, and the page for Alan prints it. */
import fs from "node:fs"; import path from "node:path"; import { openPage, ROOT } from "../tests/_harness.mjs";
const OUT = path.join(ROOT, "study/ds2/pictures"), WHAT = process.argv[2] || "all"; fs.mkdirSync(OUT, { recursive: true });
const report = [], ny = () => new Intl.DateTimeFormat("en-GB", { timeZone: "America/New_York", day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date());
const clipOf = (page, sel) => page.evaluate((s) => { const e = document.querySelector(s); if (!e) return null; const r = e.getBoundingClientRect(); return { x: Math.max(0, r.left + scrollX), y: r.top + scrollY, width: Math.min(r.width, innerWidth), height: r.height }; }, sel);
const leavesInfo = (root) => { const host = document.querySelector(root) || document.body, leaves = [...host.querySelectorAll("*")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg")); return { scrollW: document.scrollingElement.scrollWidth, innerW: innerWidth, minFont: Math.min(...leaves.map((e) => parseFloat(getComputedStyle(e).fontSize))), svgMinFont: Math.min(...[...host.querySelectorAll("svg text")].map((e) => parseFloat(e.getAttribute("font-size") || getComputedStyle(e).fontSize))) }; };
if (WHAT !== "page") for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h }); const { page } = P;
  const shot = async (name, sel, pad = 8) => { const clip = await clipOf(page, sel); if (clip && clip.height > 4) await page.screenshot({ path: path.join(OUT, `ds2-tool-${name}-${w}.png`), fullPage: true, clip: { x: Math.max(0, clip.x - pad), y: Math.max(0, clip.y - pad), width: Math.min(w, clip.width + 2 * pad), height: clip.height + 2 * pad } }); return !!clip; };
  try { await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && document.getElementById("a9-root"), null, { timeout: 120000 }); await page.waitForFunction(() => window.DS1_LIVE.history, null, { timeout: 60000 }).catch(() => {}); await page.waitForTimeout(1500);
    await page.evaluate(() => window.scrollTo(0, 0)); await page.waitForTimeout(300); await page.screenshot({ path: path.join(OUT, `ds2-tool-0-first-screen-${w}.png`) });
    await shot("1-the-number", "#a9-root .a9-num"); await shot("1b-the-number-and-its-history", "#a9-root .a9-top"); await shot("2-split-dial-and-pies", '#a9-root [data-sec="chain"]'); await shot("3-room-to-play", '#a9-root [data-sec="room"]');
    const info = await page.evaluate((li) => { const st = window.DS1_LIVE, X = st.explain, v = st.view, host = document.getElementById("ds1money-host"), f = (x, d = 1) => (x == null ? null : +x.toFixed(d)), q = (s) => host.querySelector(s), txt = (s) => (q(s) || {}).innerText || null;
      return { readAt: st.readAt && st.readAt.date + " " + st.readAt.hms + " New York", session: v.session, live: v.live, number: f(X.sm.number), thisMinute: f(X.live.number), reading: f(X.live.reading), version2: v.v2 && { cash: v.v2.cash, since: v.v2.since, fade: f(v.v2.fade, 2), creditFitted: f(v.v2.creditFitted), creditCounted: f(v.v2.creditCounted), before: v.v2.v1 && v.v2.v1.reading, seededTo: v.v2.seededTo }, v2Error: st.v2Error || null,
        kv: [...host.querySelectorAll(".a9-kv > *")].map((e) => e.innerText), dial: txt('[data-a9="split"]'), dialValue: q("#a9-split") && q("#a9-split").value, oracle: txt('[data-room="ORCL"]'), oracleStarter: !!q('[data-room="ORCL"][data-starter="1"]'), roomRows: host.querySelectorAll("[data-room]").length, corePie: [...host.querySelectorAll('.a9-row[data-chain="now"] .a9-pie')].pop() ? [...host.querySelectorAll('.a9-row[data-chain="now"] .a9-pie')].pop().innerText.replace(/\s+/g, " ").slice(0, 200) : null,
        micron: X.today.names.MU && f(X.today.names.MU.pct, 2), nebius: X.today.names.NBIS && f(X.today.names.NBIS.pct, 2), ceilings: Object.fromEntries(Object.values(X.full.names).map((n) => [n.sym, f(n.pct, 1)])), dips: X.dips.map((d) => [d.dipPct, f(d.number)]), named: X.named.map((k) => [k.d, k.kind, f(k.number)]), error: st.error, panelError: st.panelError || null, step2: (document.querySelector('#ds1live [data-v2="1"]') || {}).innerText || null, marks: [...host.querySelectorAll(".hd .warn")].map((e) => e.innerText), ...(new Function("return (" + li + ")")())("#ds1money-host") }; }, leavesInfo.toString());
    /* the dial moved, and put back: the pies and the room follow */
    await page.locator("#a9-split").evaluate((e) => { e.value = "80"; e.dispatchEvent(new Event("change", { bubbles: true })); }); await page.waitForTimeout(350);
    info.dialAt80 = await page.evaluate(() => { const X = window.DS1_LIVE.explain, host = document.getElementById("ds1money-host"); return { micronOfConv: window.DS1_LIVE.A.micronOfConv, micron: +X.today.names.MU.pct.toFixed(2), nebius: +X.today.names.NBIS.pct.toFixed(2), back: !!host.querySelector("[data-a9-split]"), text: (host.querySelector('[data-a9="split"]') || {}).innerText }; });
    await shot("4-the-dial-moved-to-80-20", '#a9-root [data-sec="chain"]'); await page.locator("[data-a9-split]").click(); await page.waitForTimeout(350); info.dialBack = await page.evaluate(() => window.DS1_LIVE.A.micronOfConv);
    /* the assumptions opened: the two switches of version 2 among them */
    await page.evaluate(() => { const d = document.querySelector("#ds1money-host details.asm"); if (d) d.open = true; }); await page.waitForTimeout(200); await shot("5-the-assumptions-opened", "#ds1money-host details.asm"); info.switches = await page.evaluate(() => ["creditRule", "cashRule", "micronOfConv", "w.ORCL"].map((k) => { const e = document.querySelector(`#ds1money-host input[data-in="${k}"][type="number"]`); return [k, e ? e.value : null, e ? e.closest("label").innerText.replace(/\s+/g, " ") : null]; }));
    /* the raise-cash rule switched off, and on again: what today's number would be without it */
    await page.locator('#ds1money-host input[data-in="cashRule"]').fill("0"); await page.locator('#ds1money-host input[data-in="cashRule"]').dispatchEvent("change"); await page.waitForTimeout(350); info.cashRuleOff = await page.evaluate(() => ({ number: +window.DS1_LIVE.explain.live.number.toFixed(1), kv: [...document.querySelectorAll("#ds1money-host .a9-kv > *")].map((e) => e.innerText).filter((t) => /cash raised|switched off|credit/.test(t)) }));
    await page.evaluate(() => { const d = document.querySelector("#ds1money-host details.asm"); if (d) d.open = false; window.scrollTo(0, 0); }); await page.waitForTimeout(200); await shot("6-the-raise-cash-rule-switched-off", "#a9-root .a9-num");
    await page.evaluate(() => { const d = document.querySelector("#ds1money-host details.asm"); if (d) d.open = true; }); await page.locator("#ds1money-host button[data-reset]").click(); await page.waitForTimeout(350); info.afterReset = await page.evaluate(() => ({ number: +window.DS1_LIVE.explain.live.number.toFixed(1), cashRule: window.DS1_LIVE.A.cashRule, micronOfConv: window.DS1_LIVE.A.micronOfConv }));
    await page.evaluate(() => { const d = document.querySelector("#ds1money-host details.asm"); if (d) d.open = false; for (const e of document.querySelectorAll("#ds1money-host details[data-a9-fold]")) e.open = true; }); await page.waitForTimeout(200); await shot("7-page-specs-and-the-dips-opened", '#a9-root [data-sec="more"]');
    await page.evaluate(() => { for (const e of document.querySelectorAll("#ds1money-host details[data-a9-fold]")) e.open = false; const p = document.getElementById("ds1live").closest(".panel"); if (p.classList.contains("folded")) { const b = p.querySelector(".pfold"); if (b) b.click(); } }); await page.waitForTimeout(400); await page.evaluate(() => window.scrollTo(0, 0)); await page.waitForTimeout(200);
    { const c = await page.evaluate(() => { const p = document.getElementById("ds1live").closest(".panel").getBoundingClientRect(), g = document.querySelector("#ds1-root .g2").getBoundingClientRect(); return { x: Math.max(0, p.left + scrollX), y: p.top + scrollY, width: Math.min(p.width, innerWidth), height: g.bottom - p.top + 14 }; }); await page.screenshot({ path: path.join(OUT, `ds2-tool-8-step-2-the-market-reading-${w}.png`), fullPage: true, clip: c }); }
    await shot("9-the-whole-panel", "#ds1money-host", 12);
    report.push({ page: "index.html", width: w, errors: P.errors, nonGet: P.nonGet.blocked + P.nonGet.allowed, ...info }); } finally { await P.close(); } }
if (WHAT !== "tool") for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h, path: "study/ds2/DS2.html" }); const { page } = P;
  const shot = async (name, sel, pad = 0) => { const clip = await clipOf(page, sel); if (clip && clip.height > 4) await page.screenshot({ path: path.join(OUT, `ds2-page-${name}-${w}.png`), fullPage: true, clip: { x: Math.max(0, clip.x - pad), y: Math.max(0, clip.y - pad), width: Math.min(w, clip.width + 2 * pad), height: clip.height + 2 * pad } }); };
  try { await page.waitForFunction(() => window.DS2_PAGE_READY === true && [...document.querySelectorAll("img")].every((i) => i.complete), null, { timeout: 60000 }); await page.waitForTimeout(500); await page.screenshot({ path: path.join(OUT, `ds2-page-0-first-screen-${w}.png`) });
    for (const [name, sel] of [["1-the-answer", "#p-answer"], ["2-before-and-after", "#p-fig"], ["3-his-dates", "#p-diag"], ["4-the-candidates", "#p-cand"], ["5-the-recommended-version", "#p-rec"], ["6-dials-and-the-pane", "#p-pane"], ["7-wrong-not-done-decisions", "#p-dec"]]) await shot(name, sel);
    /* the pointer on a day (the March 2026 low), then the long range */
    const b = await page.evaluate(() => { const s = document.getElementById("svg").getBoundingClientRect(); return { x: s.left, y: s.top + scrollY, w: s.width, h: s.height }; }); await page.evaluate(() => document.getElementById("svg").scrollIntoView({ block: "center" })); await page.waitForTimeout(150);
    const at = await page.evaluate(() => { const D = DATA.series, i = D.d.indexOf("2026-03-30"), s = document.getElementById("svg").getBoundingClientRect(), W = +document.getElementById("svg").getAttribute("width"), narrow = W < 640, x0 = 38, x1 = W - (narrow ? 8 : 92); return { x: s.left + x0 + (i / (D.d.length - 1)) * (x1 - x0), y: s.top + s.height * 0.7 }; }); await page.mouse.move(at.x, at.y); await page.waitForTimeout(200);
    const readOut = await page.evaluate(() => document.getElementById("read").innerText); await shot("2b-the-pointer-on-the-march-2026-low", "#fig", 4);
    await page.locator('#rg button[data-r="long"]').click(); await page.waitForTimeout(250); await shot("2c-since-2018", "#fig", 4); await page.locator('#rg button[data-r="series"]').click(); await page.waitForTimeout(200);
    report.push({ page: "study/ds2/DS2.html", width: w, errors: P.errors, nonGet: P.nonGet.blocked + P.nonGet.allowed, readOut, ...(await page.evaluate((li) => ({ imgs: [...document.querySelectorAll("img")].map((i) => i.naturalWidth > 0).filter(Boolean).length + " of " + document.querySelectorAll("img").length, tiles: [...document.querySelectorAll("#tiles .tile")].map((t) => t.innerText.replace(/\s+/g, " ").slice(0, 110)), dec: document.querySelectorAll("#dec li").length, wrong: document.querySelectorAll("#wrong li").length, tables: document.querySelectorAll("table").length, ...(new Function("return (" + li + ")")())("body") }), leavesInfo.toString())) }); } finally { await P.close(); } }
const stamp = "pictures taken " + ny() + " New York, on the prices of the 7 Oct close"; if (WHAT !== "page") fs.writeFileSync(path.join(ROOT, "study/ds2/data/ds2-shots.json"), JSON.stringify({ stamp, takenAt: new Date().toISOString() }));
console.log(JSON.stringify(report, null, 1)); console.log("pictures in", OUT, fs.readdirSync(OUT).filter((f) => /\.png$/.test(f)).length);
