/* DS3 — the pictures, headless, every non-GET blocked, ONE page at a time: the allocation tool's account row with the made-up example
   marked on it (index.html) at 1680 and 390, then the page for Alan (study/ds3/DS3.html) at 1680 and 390.
     node scripts/ds3-shots.mjs [tool|page|all]
   The private account file is never served to a picture run (tests/_harness.mjs), so the tool's pictures show the example, not the account.
   Each picture is one part, cut from the full page. The report printed at the end says what was on the page when they were taken; the
   time of the run is kept in study/ds3/data/ds3-shots.json, and the page for Alan prints it. */
import fs from "node:fs"; import path from "node:path"; import { openPage, ROOT } from "../tests/_harness.mjs";
const OUT = path.join(ROOT, "study/ds3/pictures"), WHAT = process.argv[2] || "all"; fs.mkdirSync(OUT, { recursive: true });
const report = [], ny = () => new Intl.DateTimeFormat("en-GB", { timeZone: "America/New_York", day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date());
const clipOf = (page, sel) => page.evaluate((s) => { const e = document.querySelector(s); if (!e) return null; const r = e.getBoundingClientRect(); return { x: Math.max(0, r.left + scrollX), y: r.top + scrollY, width: Math.min(r.width, innerWidth), height: r.height }; }, sel);
const leavesInfo = (root) => { const host = document.querySelector(root) || document.body, leaves = [...host.querySelectorAll("*")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg") && !e.closest("script") && !e.closest("style")); return { scrollW: document.scrollingElement.scrollWidth, innerW: innerWidth, minFont: Math.min(...leaves.map((e) => parseFloat(getComputedStyle(e).fontSize))), svgMinFont: Math.min(...[...host.querySelectorAll("svg text")].map((e) => parseFloat(e.getAttribute("font-size") || getComputedStyle(e).fontSize))) }; };
if (WHAT !== "page") for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h }); const { page } = P;
  const shot = async (name, sel, pad = 8) => { const clip = await clipOf(page, sel); if (clip && clip.height > 4) await page.screenshot({ path: path.join(OUT, `ds3-tool-${name}-${w}.png`), fullPage: true, clip: { x: Math.max(0, clip.x - pad), y: Math.max(0, clip.y - pad), width: Math.min(w, clip.width + 2 * pad), height: clip.height + 2 * pad } }); return !!clip; };
  try { await page.waitForFunction(() => window.DS1_LIVE_READY === true && window.DS1_LIVE.view && document.getElementById("a9-root"), null, { timeout: 120000 }); await page.waitForFunction(() => window.DS1_LIVE.history, null, { timeout: 60000 }).catch(() => {}); await page.waitForTimeout(1500);
    /* only the account's own label is pictured: the rest of that table carries the tool's levels and sizes, which this round's page must not show */
    await shot("example-account-mark", '#ds1money-host [data-room="ALL"] .c.nm', 10);
    const info = await page.evaluate(() => { const st = window.DS1_LIVE, host = document.getElementById("ds1money-host"), row = host.querySelector('[data-room="ALL"]'), mark = host.querySelectorAll("[data-example-account]"); return { readAt: st.readAt && st.readAt.date + " " + st.readAt.hms + " New York", session: st.view.session, number: +st.explain.live.number.toFixed(1), accountRow: row ? row.innerText.replace(/\s+/g, " ").slice(0, 200) : null, exampleMarks: mark.length, markText: mark[0] ? mark[0].innerText : null, cash: st.A.cash, shares: st.A.shares, accountFile: st.account || "not asked for", error: st.error, panelError: st.panelError || null, warn: [...host.querySelectorAll(".hd .warn")].map((e) => e.innerText) }; });
    await page.evaluate(() => { const d = document.querySelector("#ds1money-host details.asm"); if (d) d.open = true; }); await page.waitForTimeout(250); await shot("example-account-assumptions", "#ds1money-host details.asm summary", 10); info.summary = await page.evaluate(() => (document.querySelector("#ds1money-host details.asm summary") || {}).innerText || null);
    report.push({ page: "index.html", width: w, errors: P.errors, nonGet: P.nonGet.blocked + P.nonGet.allowed, ...info }); } finally { await P.close(); } }
if (WHAT !== "tool") for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h, path: "study/ds3/DS3.html" }); const { page } = P;
  const shot = async (name, sel, pad = 0) => { const clip = await clipOf(page, sel); if (clip && clip.height > 4) await page.screenshot({ path: path.join(OUT, `ds3-page-${name}-${w}.png`), fullPage: true, clip: { x: Math.max(0, clip.x - pad), y: Math.max(0, clip.y - pad), width: Math.min(w, clip.width + 2 * pad), height: clip.height + 2 * pad } }); };
  try { await page.waitForFunction(() => window.DS3_PAGE_READY === true && [...document.querySelectorAll("img")].every((i) => i.complete), null, { timeout: 60000 }); await page.waitForTimeout(500); await page.screenshot({ path: path.join(OUT, `ds3-page-0-first-screen-${w}.png`) });
    for (const [name, sel] of [["1-the-answer", "#p-answer"], ["2-before-and-after", "#p-chart"], ["3-this-morning", "#p-morning"], ["4-your-dates", "#p-dates"], ["5-the-candidates", "#p-cands"], ["6-the-recommended-version", "#p-rec"], ["7-the-pane", "#p-pane"], ["8-privacy", "#p-privacy"], ["9a-what-could-be-wrong", "#p-wrong"], ["9b-not-done", "#p-notdone"], ["9c-decisions", "#p-decide"]]) await shot(name, sel);
    /* the pointer on a day (the March 2026 low), then the long range */
    await page.evaluate(() => document.getElementById("svg").scrollIntoView({ block: "center" })); await page.waitForTimeout(150);
    const at = await page.evaluate(() => { const D = DATA.series, i = D.d.indexOf("2026-03-30"), s = document.getElementById("svg").getBoundingClientRect(), W = +document.getElementById("svg").getAttribute("width"), narrow = W < 640, x0 = 38, x1 = W - (narrow ? 8 : 96); return { x: s.left + x0 + (i / (D.d.length - 1)) * (x1 - x0), y: s.top + s.height * 0.55 }; }); await page.mouse.move(at.x, at.y); await page.waitForTimeout(200);
    const readOut = await page.evaluate(() => document.getElementById("read").innerText); await shot("2b-the-pointer-on-the-march-2026-low", "#fig", 4);
    await page.locator('#rg button[data-r="long"]').click(); await page.waitForTimeout(250); await shot("2c-since-2018", "#fig", 4); await page.locator('#rg button[data-r="series"]').click(); await page.waitForTimeout(200);
    report.push({ page: "study/ds3/DS3.html", width: w, errors: P.errors, nonGet: P.nonGet.blocked + P.nonGet.allowed, readOut, ...(await page.evaluate((li) => ({ imgs: [...document.querySelectorAll("img")].map((i) => i.naturalWidth > 0).filter(Boolean).length + " of " + document.querySelectorAll("img").length, tiles: [...document.querySelectorAll(".tiles .tile")].map((t) => t.innerText.replace(/\s+/g, " ").slice(0, 120)), decisions: document.querySelectorAll("#p-decide ol > li").length, tables: document.querySelectorAll("table").length, widestTable: Math.max(...[...document.querySelectorAll("table")].map((t) => t.scrollWidth)), ...(new Function("return (" + li + ")")())("body") }), leavesInfo.toString())) }); } finally { await P.close(); } }
/* the time is written by the run that pictures the tool; the page is built with it and pictured straight after */
const stamp = "pictures taken " + ny() + " New York"; if (WHAT !== "page") fs.writeFileSync(path.join(ROOT, "study/ds3/data/ds3-shots.json"), JSON.stringify({ stamp, takenAt: new Date().toISOString() }));
console.log(JSON.stringify(report, null, 1)); console.log("pictures in", OUT, fs.readdirSync(OUT).filter((f) => /\.png$/.test(f)).length);
