/* PN1 — the pictures of the page for Alan (study/pn1/PN1.html), headless, every non-GET blocked and counted, one page at a time, at 1680
   and 390 wide: the first screen, each panel, each drawing, and one drawing with the pointer on a day.   node scripts/pn1-shots.mjs [outdir] */
import fs from "node:fs"; import path from "node:path"; import { openPage, ROOT } from "../tests/_harness.mjs";
const OUT = process.argv[2] || path.join(ROOT, "study/pn1/pictures"); fs.mkdirSync(OUT, { recursive: true }); const report = [];
for (const [w, h] of [[1680, 1050], [390, 844]]) { const P = await openPage({ width: w, height: h, path: "study/pn1/PN1.html" }), { page } = P;
  try { await page.waitForFunction(() => window.PN1_PAGE_READY === true, null, { timeout: 60000 }); await page.waitForTimeout(400);
    await page.screenshot({ path: path.join(OUT, `pn1-page-00-first-screen-${w}.png`) });
    for (const id of await page.evaluate(() => [...document.querySelectorAll("section.panel[id]")].map((p) => p.id))) await page.locator("#" + id).screenshot({ path: path.join(OUT, `pn1-page-${id.replace(/^p-/, "")}-${w}.png`) });
    for (const id of ["fig-recent", "fig-2020", "fig-all", "fig-parts"]) await page.locator("#" + id).screenshot({ path: path.join(OUT, `pn1-${id}-${w}.png`) });
    /* the pointer on a day: the hairline, the dots and the read-out */
    await page.locator("#fig-all").scrollIntoViewIfNeeded(); await page.evaluate(() => document.getElementById("fig-all").scrollIntoView({ block: "center" })); await page.waitForTimeout(150); const box = await page.locator("#fig-all svg").boundingBox(); await page.mouse.move(box.x + box.width * 0.62, box.y + box.height * 0.7); await page.waitForTimeout(200); const tip = await page.evaluate(() => { const t = document.querySelector("#fig-all .tip"); return t && !t.hidden ? t.innerText.replace(/\n+/g, " | ") : null; });
    await page.locator("#fig-all").screenshot({ path: path.join(OUT, `pn1-fig-all-pointer-on-a-day-${w}.png`) }); await page.mouse.move(2, 2);
    /* the keyboard: focus a drawing, step two bars back */
    await page.focus("#fig-recent"); await page.keyboard.press("ArrowLeft"); await page.keyboard.press("ArrowLeft"); const keyTip = await page.evaluate(() => { const t = document.querySelector("#fig-recent .tip"); return t && !t.hidden ? t.innerText.replace(/\n+/g, " | ") : null; }); await page.evaluate(() => document.activeElement.blur());
    const info = await page.evaluate(() => { const leaves = [...document.querySelectorAll("body *")].filter((e) => e.children.length === 0 && e.textContent.trim() && getComputedStyle(e).display !== "none" && e.getBoundingClientRect().width > 0 && !e.closest("svg") && !e.closest("details:not([open])"));
      const svgText = [...document.querySelectorAll(".fig svg text")].map((t) => parseFloat(getComputedStyle(t).fontSize) * (t.ownerSVGElement.getBoundingClientRect().width / t.ownerSVGElement.viewBox.baseVal.width));
      const figs = [...document.querySelectorAll(".fig")].map((f) => { const s = f.querySelector("svg"), r = s.getBoundingClientRect(); return { id: f.id, width: Math.round(r.width), height: Math.round(r.height), paths: s.querySelectorAll("path").length, labels: [...s.querySelectorAll("g text")].map((t) => t.textContent), clipped: [...s.querySelectorAll("text")].filter((t) => { const b = t.getBBox(); return b.x < -0.5 || b.x + b.width > s.viewBox.baseVal.width + 0.5; }).map((t) => t.textContent) }; });
      return { scrollW: document.scrollingElement.scrollWidth, innerW: innerWidth, minFont: Math.min(...leaves.map((e) => parseFloat(getComputedStyle(e).fontSize))), minSvgFontOnScreen: +Math.min(...svgText).toFixed(1), panels: document.querySelectorAll("section.panel[id]").length, tiles: [...document.querySelectorAll(".tile .v")].map((e) => e.textContent), rows: document.querySelectorAll("#p-agree tbody tr").length, figs }; });
    report.push({ page: "study/pn1/PN1.html", width: w, errors: P.errors, nonGet: P.nonGet.blocked + P.nonGet.allowed, pointerReadOut: tip, keyboardReadOut: keyTip, ...info }); } finally { await P.close(); } }
console.log(JSON.stringify(report, null, 1)); console.log("pictures in", OUT, fs.readdirSync(OUT).length);
